### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by Bastien42** [FlareSolverr/FlareSolverr#102]
### Environment

**FlareSolverr Version**: 1.2.3

**Docker**: yes

**OS**: windows 10 pro

**Last Working FlareSolverr Version**: 1.2.3

**Are you using a proxy or VPN?** no

**Using Captcha Solver:** no

**If using captcha solver, which one:** /

### Description

setup YGGtorrent indexer and flaresolver on docker and run a test (i crossed post it on the jackett git as they are related)

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 670
   at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 618
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1321
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 381
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 724
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

```
2021-03-21T16:21:35.208Z INFO REQ-10 Incoming request: POST /v1

2021-03-21T16:21:35.208Z INFO REQ-10 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/user/disabled","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}

2021-03-21T16:21:35.477Z INFO REQ-10 Cloudflare detected

2021-03-21T16:21:39.947Z INFO REQ-10 Successful response in 4.739 s

2021-03-21T16:21:40.074Z INFO REQ-11 Incoming request: POST /v1

2021-03-21T16:21:40.074Z INFO REQ-11 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/error?http_code=403","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}

2021-03-21T16:21:40.338Z INFO REQ-11 Cloudflare detected

2021-03-21T16:21:44.729Z INFO REQ-11 Successful response in 4.655 s
```

**Comment by ngosang** [comment]
@Bastien42 Jackett and FlaresSolverr MUST be in the same network and have the same external IP. I recommend you to run both in the same machine.
Make sure you don't have a Proxy configured in Jackett.
