### ISSUE TITLE
(yggtorrent) FlareSolverr Error - Sonarr and Jackett Integration Issue

### ISSUE THREAD

**Issue by n1nj444** [FlareSolverr/FlareSolverr#1020]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
FlareSolverr version: 3.3.12
    Last working FlareSolverr version: 3.3.12
    Operating system: Synology DSM 7
    Are you using Docker: yes
    FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
    Are you using a VPN: no
    Are you using a Proxy: no
    Are you using Captcha Solver: no
    If using captcha solver, which one: no
    URL to test this issue: https://www3.yggtorrent.qa/torrent/filmvid%C3%A9o/s%C3%A9rie-tv/946412-better+call+saul+s03+multi+custom+2160p+webrip+x264
```

### Description

When attempting to download a season from Sonarr using Jackett with FlareSolverr, an error occurs after a few seconds without downloading the file. The issue seems to arise during the connection to the indexer's server via FlareSolverr, preventing the retrieval of the desired torrent file.

### Logged Error Messages

```text
Error downloading. indexer: yggtorrent path: https://www3.yggtorrent.qa/engine/download_torrent?id=(removed) Remote server returned Forbidden
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String referer, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 521
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 2107
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56

2023-12-19 22:42:44 	Error 	

Failed download response:
    <!DOCTYPE html>
<html>

<head>
	<title>YggTorrent - 1er Tracker BitTorrent Francophone</title>
	<meta name="google-site-verification" content="jDrVJm_dqGUqNrWYcPdAhE3vCpxfcHBwoKN_V0cSV8A" />

	<meta name="description"
		content="Inscrivez-vous et rejoignez gratuitement la plus grande communauté P2P francophone pour profiter de milliers de films, séries et logiciels en libre-service !" />
	
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="interkassa-verification" content="932c353776e6f12b0dac4f654bd3b9bf" />
		<link rel="icon" href="/favicon.ico" />

		<!-- CSS Includes -->
		<link rel="stylesheet"  href="/assets/css/bootstrap.min.css?cachekiller=1549578">
		<link rel="stylesheet"  href="/assets/css/animate.min.css">
		<link rel="stylesheet"  href="/assets/css/fontawesome.css">
		<link rel="stylesheet"  href="/assets/css/custom.css?cachekiller=15495851">
		<link rel="stylesheet"  href="/assets/css/master.css?cachekiller=15497191">
   	    <link rel="stylesheet"  href="/assets/css/jnotifier.css">
   	    <link rel="stylesheet"  href="/assets/css/select2.min.css">
	    <link rel="stylesheet"  href="/assets/css/select2-bootstrap.min.css">
		<!-- Fonts -->	
		<link crossorigin="anonymous" media="all" href="https://fonts.googleapis.com/css?family=EB+Garamond|Montserrat:400,500,550,600,700|Roboto+Condensed:700|Open+Sans:600|Pangolin" rel="stylesheet">

		<!-- Jquery -->
	    <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
	
</head>

<body>

	<div class="text-center text-white promo-container"
	onclick="window.location = 'https://www3.yggtorrent.qa/user/donate'">
	<img src="/assets/img/summer_icon.png" class="promo-img">
	<div class="promo-close">
		<span class="ico_close"></span>
		fermer
	</div>
	<div class="clearfix"></div>
	<div class="promo-content">
		<div class="promo-text">
			<p class="p1">🎅 Noël 2023 : Bonus Go & Freeleech !</p>
			<p class="p2">cliquez-ici pour en profiter !</p>
		</div>
		<ul id="countdown" class="countdown">
			<li>
				<span class="days">00</span>
				<p class="days_text">Jours</p>
			</li>
			<li class="separator">:</li>
			<li>
				<span class="hours">00</span>
				<p class="hours_text">Heures</p>
			</li>
			<li class="separator">:</li>
			<li>
				<span class="minutes">00</span>
				<p class="minutes_text">Minutes</p>
			</li>
			<li class="separator">:</li>
			<li>
				<span class="seconds">00</span>
				<p class="seconds_text">Secondes</p>
			</li>
		</ul>
	</div>
</div>
<style type="text/css">
	.promo-close {
		float: left;
		font-size: 15px;
		font-weight: bold;
		top: 18px;
		left: 50px;
		cursor: pointer;
		z-index: 999999999999999999;
	}

	.promo-img {
		width: 190px;
		position: absolute;
		left: 400px;
		bottom: -55px;
		filter: grayscale(35%);
		opacity: 0.1;
	}

	.promo-content {
		padding: 14px 0px 25px 0px;
	}

	.promo-text {
		padding-bottom: 13px;
	}

	.promo-text .p1 {
		font-weight: bold;
		font-size: 26px;
		color: #fff;
		letter-spacing: -1px;
	}

	.promo-text .p2 {
		font-weight: bold;
		font-size: 21px;
		padding: 4px 26px 4px 26px;
		text-transform: uppercase;
		margin-top: 10px;
		width: max-content;
		margin-left: auto;
		margin-right: auto;
		background: linear-gradient(45deg, #ff3366, #ffb366);
		-webkit-text-fill-color: transparent;
		-webkit-background-clip: text;
		border-radius: 25px;
		color: #4edf68;
	}

	.promo-text>span {
		font-size: 16px;
		color: #68debe;
	}

	.promo-close>span {
		color: #ffffff;
	}

	.promo-container .ico_close {
		color: #d82121;
	}

	.promo-container {
		display: none;
		cursor: pointer;
		bottom: 0;
		width: 100%;
		position: fixed;
		z-index: 9999999999999;
		color: #fff !important;
		cursor: pointer;
		background: #131518f7;
	}

	ul#countdown {
		list-style: none;
		padding: 0;
		display: block;
		margin-top: -2px;
	}

	ul#countdown li {
		display: inline-block;
	}

	ul#countdown li span {
		font-size: 35px;
		line-height: 38px;
		font-weight: 800;
		color: white;
	}

	ul#countdown li.separator {
		margin: 0px 4px;
		font-size: 22px;
		line-height: 38px;
		vertical-align: top;
		color: white;
	}

	ul#countdown li p {
		margin-top: 3px;
		color: #ccd0d8;
		font-size: 11px;
		text-align: center;
	}
</style>
<div id="connect">
	<h3>Se connecter</h3>
	<h5>Veuillez remplir tous les champs </h5>

	<form action="/user/login" method="post" id="user-login">
		<input type="text" name="id" placeholder="Pseudo" required="" />
		<input type="password" name="pass" placeholder="Mot de passe" required="" autocomplete="off" />
						<div id="ban_msg_login" style="display: none;">
			<center style="margin: 10px 10px; color: #ff3f3f; font-weight: bold;">Votre compte a été banni! <br><span
					style="font-weight: bold; font-size: 15px; color: #582a2a;">Fin du ban : <span
						class="ban_duration"></span></span> <a id="ban_reason"
					style="font-weight:bold; font-size: 13px;">Voir le motif</a></center>
		</div>
		<div id="login_msg_pass" style="display: none;">
			<center style="margin: 10px 10px; color: #ff3f3f; font-weight: bold;">Échec de connexion . Vérifiez vos
				identifiants<br></center>
		</div>
		<div id="login_msg_mail" style="display: none;">
			<center style="margin: 10px 10px; color: #ff3f3f; font-weight: bold;">Vous n'avez pas confirmer votre compte
				à l'aide du mail que nous vous avons envoyé<br></center>
		</div>
		<center id="resetpass" style=" margin: 10px 10px;  font-weight: bold;"><a  href="https://www3.yggtorrent.qa/user/reset_password">Mot de passe oublié ?</a>
		</center>
		<input type="hidden" name="ci_csrf_token"
			value="">


		<button type="submit">Connexion <i class="ico_unlock"></i></button>
	</form>
</div>
<div class="fadeconnect"></div>

	<div class="panel" id="top_panel">

		<div class="ct">


			<ul>
				<li><a data-connect="" title="" id="register"><span class="ico_lock"></span> S'identifier</a></li>
				<li><a 						href="https://www3.yggtorrent.qa/user/register" title=""><span class="ico_user-plus"></span>
						<strong>S'inscrire</strong></a></li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>

<script type="text/javascript">
	$(function () {
		$(document).on('click', '#panel-btn', function () {
			if ($('.panel-cache').is(':visible')) {
				$('.panel-cache').slideUp(400);
			} else {
				$('.panel-cache').slideDown(400);
			}
		});
	});
</script>


<header role="header">
	<div class="ct">
		<a class="ico_navicon nav" data-nav="no"></a>
		<a class="ico_user user" data-user="no"></a>
		<a  href="https://yggtorrent.qa/"
			title="YggTorrent" class="logotype">
			<img class="desktop" alt="YggTorrent - La communauté Bittorrent francophone !" src="/assets/img/logo_winter_v4.svg">
			<img class="mobile" alt="YggTorrent - La communauté Bittorrent francophone !" src="/assets/img/logo_winter_v4.svg"
				style="margin-top: -5px">
		</a>
		<form class="search" action="https://www3.yggtorrent.qa/engine/search" method="get">
			<div class="input">
				<input type="text" name="name" placeholder="Rechercher des torrents">
				<button type="submit" name="do" value="search"><span class="ico_search"></span></button>
			</div>
		</form>
		<style type="text/css">
			/*** COUPE DU MONDE 2022 ***/
			@media screen and (min-width:800px) {
				header .logotype img {
					width: 120px !important;
					margin-top: -12px;
					margin-left: 20px;
				}

				header .search {
					width: calc(100% - 430px) !important;
					right: 240px !important;
				}
			}


			.panel {
				background-image: none !important;
				background-color: #25272f !important;
			}

			.pulse {
				cursor: pointer;
				box-shadow: 0 0 0 rgba(94, 194, 218, 0.4);
				animation: pulse 1s infinite;
			}

			.pulse:hover {
				animation: none;
			}

			@-webkit-keyframes pulse {
				0% {
					-webkit-box-shadow: 0 0 0 0 rgba(94, 194, 218, 0.4);
				}

				70% {
					-webkit-box-shadow: 0 0 0 10px rgba(94, 194, 218, 0);
				}

				100% {
					-webkit-box-shadow: 0 0 0 0 rgba(94, 194, 218, 0);
				}
			}

			@keyframes pulse {
				0% {
					-moz-box-shadow: 0 0 0 0 rgba(94, 194, 218, 0.4);
					box-shadow: 0 0 0 0 rgba(94, 194, 218, 0.4);
				}

				70% {
					-moz-box-shadow: 0 0 0 10px rgba(94, 194, 218, 0);
					box-shadow: 0 0 0 10px rgba(94, 194, 218, 0);
				}

				100% {
					-moz-box-shadow: 0 0 0 0 rgba(94, 194, 218, 0);
					box-shadow: 0 0 0 0 rgba(94, 194, 218, 0);
				}
			}
		</style>
		<a  href="https://www3.yggtorrent.qa/user/donate"
			class="donate pulse"><span class="ico_star"></span> Bonus Go & Freeleech </a>
	</div>
</header>

<div id="top">
	<div class="ct">
		<nav role="navigation">
			<ul>

				<li class="color">
					<a  class="title"
						href="https://yggtorrent.qa/" title=""><span class="ico_home"></span>
						Accueil</a>
				</li>
				<li class="color">
					<a class="title" href="#"> Catégories</a>
					<ul>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2145&sub_category=all&do=search">Films
								& Vidéos</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2140&sub_category=all&do=search">Ebook</a>
						</li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2139&sub_category=all&do=search">Audio</a>
						</li>
												<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2142&sub_category=all&do=search">Jeu
								vidéo</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2144&sub_category=all&do=search">Application</a>
						</li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2300&sub_category=all&do=search">Nulled</a>
						</li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2200&sub_category=all&do=search">Imprimante
								3d</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2143&sub_category=all&do=search">GPS</a>
						</li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&description=&file=&uploader=&category=2141&sub_category=all&do=search">Emulation</a>
						</li>
					</ul>
				</li>

				<li class="color">
					<a class="title torrents" href="#"><span class="ico_download"></span> Torrents</a>
					<ul>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?do=search">Rechercher un torrent</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/top/day">Torrents du jour</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/top/week">Torrents de la semaine</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/top/month">Torrents du mois</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/mostseeded">Torrents rapides</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search?name=&do=search">Derniers torrents
								ajoutés</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/user/upload_torrent">Uploader un torrent</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/rss">Flux RSS</a></li>
					</ul>
				</li>

				<li class="color">
					<a  class="title trends"
						href="https://www3.yggtorrent.qa/torrents/exclus"><span class="ico_star"></span>
						Exclusivités</a>
				</li>

				<li class="color">
					<a  class="title"
						href="https://www3.yggtorrent.qa/engine/mostcompleted" title=""><span class="ico_trophy"></span>
						Top 100 </a>
				</li>

				<li class="color">
					<a class="title">Communauté</a>
					<ul>
						<li><a 								href="https://www3.yggtorrent.qa/engine/search_users">Rechercher un utilisateur</a></li>
						<li><a 								href="https://www3.yggtorrent.qa/forum/index.php?forums/proposer-un-fichier-%C3%A0-lupload.135/">Proposition
								d'upload</a></li>

					</ul>
				</li>

				<li class="color">
					<a class="title" href="https://yggland.fr/FAQ-Tutos/" target="_blank">FAQ & Tuto</a>
				</li>
									<li class="color">
						<a class="title" 							href="https://www3.yggtorrent.qa/rss">Flux RSS</a>
						<ul>
							<li><a 									href="https://www3.yggtorrent.qa/rss">Comment ça fonctionne ?</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2145">Film/Vidéo</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2140">eBook</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2139">Audio</a></li>
														<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2142">Jeu vidéo</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2144">Application</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2300">Nulled</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2200">Imprimante 3D</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2143">GPS</a></li>
							<li><a 									href="https://www3.yggtorrent.qa/rss?parent_category=2141">Emulation</a></li>
						</ul>
					</li>
								<li class="color">
					<a  class="title"
						href="https://www3.yggtorrent.qa/forum">Forum</a>
				</li>
			</ul>
```

**Comment by ilike2burnthing** [comment]
Working ok here.

Are you using YGGtorrent or YGGcookie? If the latter, use the former.

**Comment by n1nj444** [comment]
Hi I'm using YGGTorrent with this config : 

![image](https://github.com/FlareSolverr/FlareSolverr/assets/39305378/130e4148-c26d-4a68-8e54-f3e6c53fbccc)

**Comment by ilike2burnthing** [comment]
Remove the indexer, restart Jackett, re-add the indexer, try searching and downloading again. If it still fails, provide an enhanced Jackett log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Is there any activity in FlareSolverr when trying to download?
