### ISSUE TITLE
[torrentqq] (testing) Exception (torrentqq): The operation was canceled.: The operation was canceled

### ISSUE THREAD

**Issue by KatyPurry** [FlareSolverr/FlareSolverr#1025]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.12
- Last working FlareSolverr version: 3.3.12
- Operating system: unRAID
- Are you using Docker: yes
- FlareSolverr User-Agent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: Yes
- Are you using a Proxy: no
```

### Description

Hello,

I can't use FlareSolver with VPN.

I'm using UnRAID with Flaresolverr/Jackett throutgh a OpenVPN container with ProtonPVN. Jackett and Flaresolver use the same network/container.

Jackett without Flaresolver : ✅
Jackett with Flaresolver and no VPN : ✅
Jackett with Flaresolver and VPN : ❌
Firefox with VPN : ✅

I tried :
- increase timeout to 100s
- disable ipv6

Tried with TorrentQQ, YGGtorrent, iDope with the same result.

Any idea ?

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (torrentqq): The operation was canceled.

[v0.21.1446.0] Jackett.Common.IndexerException: Exception (torrentqq): The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 569
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 340
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 358
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 744
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 320
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Do TorrentQQ, YGGtorrent, and iDope work when Jackett and FlareSolverr aren't behind the VPN?

**Comment by KatyPurry** [comment]
> Do TorrentQQ, YGGtorrent, and iDope work when Jackett and FlareSolverr aren't behind the VPN?

It takes some time but yes.

**Comment by ilike2burnthing** [comment]
Provide debug FlareSolverr logs of TorrentQQ failing when behind the VPN.

**Comment by KatyPurry** [comment]
Nothing is added on log when testing on TorrentQQ (with VPN) : 

```
2023-12-26 22:07:41 INFO     ReqId 22941779498816 FlareSolverr 3.3.12
2023-12-26 22:07:41 DEBUG    ReqId 22941779498816 Debug log enabled
2023-12-26 22:07:41 INFO     ReqId 22941779498816 Testing web browser installation...
2023-12-26 22:07:41 INFO     ReqId 22941779498816 Platform: Linux-6.1.49-Unraid-x86_64-with-glibc2.31
2023-12-26 22:07:41 INFO     ReqId 22941779498816 Chrome / Chromium path: /usr/bin/chromium
2023-12-26 22:07:41 INFO     ReqId 22941779498816 Chrome / Chromium major version: 120
2023-12-26 22:07:41 INFO     ReqId 22941779498816 Launching web browser...
2023-12-26 22:07:41 DEBUG    ReqId 22941779498816 Launching web browser...
version_main cannot be converted to an integer
2023-12-26 22:07:42 DEBUG    ReqId 22941779498816 Started executable: `/app/chromedriver` in a child process with pid: 32
2023-12-26 22:07:43 INFO     ReqId 22941779498816 FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2023-12-26 22:07:43 INFO     ReqId 22941779498816 Test successful!
2023-12-26 22:07:43 INFO     ReqId 22941779498816 Serving on http://0.0.0.0:8191
```

**Comment by ilike2burnthing** [comment]
Ok, so the issue then is that the container is unreachable when using the VPN. What is the FlareSolverr API URL that you've entered in Jackett?

**Comment by KatyPurry** [comment]
Thank you for your answer, urls : 

FlareSolverr:
![image](https://github.com/FlareSolverr/FlareSolverr/assets/89610869/850b5354-5fe6-433f-8a34-dbaa140b6872)

Jackett : 
![image](https://github.com/FlareSolverr/FlareSolverr/assets/89610869/8d403615-d5f7-4c6f-b33a-4345aec6a68c)

**Comment by ilike2burnthing** [comment]
Switch to internal Docker container IP or name, e.g.:
`http://172.17.0.2:8191` or `http://flaresolverr:8191`

**Comment by KatyPurry** [comment]
It's working ! Thank you very much ! 
For information, I set : `http://127.0.0.1:8191`
