### ISSUE TITLE
[1337x] (testing) Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 10.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 10.0 seconds.

### ISSUE THREAD

**Issue by GazzaBL** [FlareSolverr/FlareSolverr#1045]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one: N.A
- URL to test this issue:
https://1337x.to/
```

### Description

Jackett Indexer Failing

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 10.0 seconds.

[v0.21.1588.0] Jackett.Common.IndexerException: Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 10.0 seconds.
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 10.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 360
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 360
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 747
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 331
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2024-01-23 11:38:17	Error	
Error checking for updates.
System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://garrettl.dscloud.me/:56510' failed with status code '400'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in ./Jackett.Common/Services/UpdateService.cs:line 109
```

**Comment by JustinGrote** [comment]
```
flaresolverr  | version_main cannot be converted to an integer
flaresolverr  | 2024-01-22 15:00:28 INFO     Challenge detected. Title found: Just a moment...
flaresolverr  | 2024-01-22 15:01:02 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
flaresolverr  | 2024-01-22 15:01:02 INFO     Response in 60.853 s
flaresolverr  | 2024-01-22 15:01:02 INFO     100.0.0.6 POST http://flaresolverr:8191/v1 500 Internal Server Error
flaresolverr  | 2024-01-22 20:17:25 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
flaresolverr  | version_main cannot be converted to an integer
flaresolverr  | 2024-01-22 20:17:28 INFO     Challenge not detected!
flaresolverr  | 2024-01-22 20:17:28 INFO     Response in 2.544 s
flaresolverr  | 2024-01-22 20:17:28 INFO     100.0.0.6 POST http://flaresolverr:8191/v1 200 OK
flaresolverr  | 2024-01-22 21:01:34 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/', 'proxy': {}}
flaresolverr  | version_main cannot be converted to an integer
flaresolverr  | 2024-01-22 21:01:37 INFO     Challenge detected. Title found: Just a moment...
flaresolverr  | 2024-01-22 21:02:34 INFO     Challenge solved!
flaresolverr  | 2024-01-22 21:02:34 INFO     Response in 59.925 s
flaresolverr  | 2024-01-22 21:02:34 INFO     100.0.0.6 POST http://flaresolverr:8191/v1 200 OK
flaresolverr  | 2024-01-22 22:18:24 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
flaresolverr  | version_main cannot be converted to an integer
flaresolverr  | 2024-01-22 22:18:26 INFO     Challenge not detected!
flaresolverr  | 2024-01-22 22:18:26 INFO     Response in 1.978 s
flaresolverr  | 2024-01-22 22:18:26 INFO     100.0.0.6 POST http://flaresolverr:8191/v1 200 OK
flaresolverr  | 2024-01-22 22:21:19 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
flaresolverr  | version_main cannot be converted to an integer
flaresolverr  | 2024-01-22 22:21:20 INFO     Challenge not detected!
flaresolverr  | 2024-01-22 22:21:20 INFO     Response in 1.145 s
flaresolverr  | 2024-01-22 22:21:20 INFO     100.0.0.6 POST http://flaresolverr:8191/v1 200 OK
flaresolverr  | 2024-01-22 22:22:18 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
flaresolverr  | version_main cannot be converted to an integer
```

**Comment by ilike2burnthing** [comment]
@GazzaBL don't post a link to your server. Also, don't expose FlareSolverr's port to the internet.

Increase your timeout, default is 60s not 10s, but you may need longer.

As for 1337x, they've been experiencing issues for the last few days (apparently due to DDoS attacks), and this latest one seems to now be resolved.

**Comment by GazzaBL** [comment]
Thankyou, do you know if the post gets deleted from github or would U recommend resetting up ddns

Thanks
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
