### ISSUE TITLE
Flaresolverr fails test as non-root user

### ISSUE THREAD

**Issue by mobtactics** [FlareSolverr/FlareSolverr#1052]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.13
- Last working FlareSolverr version: N/A
- Operating system: Ubuntu 22.04.3
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): N/A
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Installed on a freshly setup Ubuntu 22.04 server as a systemd service. Created flaresolverr user for it. Unfortunately crashes after like a minute or so which I expect is the browser test failing. 

When I started the flaresolverr executable as root it will get past the browser test and it starts serving normally.

### Logged Error Messages

```text
2024-02-02 18:24:28 INFO     ReqId 140308059291648 FlareSolverr 3.3.13
2024-02-02 18:24:28 DEBUG    ReqId 140308059291648 Debug log enabled
2024-02-02 18:24:28 INFO     ReqId 140308059291648 Testing web browser installation...
2024-02-02 18:24:28 INFO     ReqId 140308059291648 Platform: Linux-5.15.0-92-generic-x86_64-with-glibc2.35
2024-02-02 18:24:28 INFO     ReqId 140308059291648 Chrome / Chromium path: /opt/flaresolverr/chrome/chrome
2024-02-02 18:24:28 INFO     ReqId 140308059291648 Chrome / Chromium major version: 115
2024-02-02 18:24:28 INFO     ReqId 140308059291648 Launching web browser...
2024-02-02 18:24:28 DEBUG    ReqId 140308059291648 Launching web browser...
2024-02-02 18:24:29 DEBUG    ReqId 140308059291648 Started executable: `/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver` in a child process with pid: 39988
Traceback (most recent call last):
  File "utils.py", line 302, in get_user_agent
  File "utils.py", line 183, in get_webdriver
  File "undetected_chromedriver/__init__.py", line 472, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 45, in __init__
  File "selenium/webdriver/chromium/webdriver.py", line 56, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 208, in __init__
  File "undetected_chromedriver/__init__.py", line 730, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 292, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 347, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 229, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60619
from chrome not reachable
Stacktrace:
#0 0x55a65012f613 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x6a7612)
#1 0x55a64fe5b386 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x3d3385)
#2 0x55a64fe4628a (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x3be289)
#3 0x55a64fe8a70d (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x40270c)
#4 0x55a64fe827da (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x3fa7d9)
#5 0x55a64fec3643 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x43b642)
#6 0x55a64fec2d8f (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x43ad8e)
#7 0x55a64feba803 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x432802)
#8 0x55a64fe8e68b (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x40668a)
#9 0x55a64fe8f42e (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x40742d)
#10 0x55a6500f0c28 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x668c27)
#11 0x55a6500f4af7 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x66caf6)
#12 0x55a6500ff01c (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x67701b)
#13 0x55a6500f5723 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x66d722)
#14 0x55a6500c4457 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x63c456)
#15 0x55a650119628 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x691627)
#16 0x55a6501197b7 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x6917b6)
#17 0x55a650128483 (/home/flaresolverr/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x6a0482)
#18 0x7f38a53b1ac3 <unknown>
```

**Comment by mobtactics** [comment]
Seems to be fixed after updating the kernel to 6.5.0-15-generic.
