### ISSUE TITLE
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by pokemaster974** [FlareSolverr/FlareSolverr#1069]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.13
- Last working FlareSolverr version: 3.3.13
- Operating system: W10
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue: None
```

### Description

Since today, launching FlareSolverr results in a 404 error.
It seems that this error was normally fixed in [v3.3.0](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0) but I don't know why it suddenly appear again.

### Logged Error Messages

```text
python src\flaresolverr.py
2024-02-16 23:43:52 INFO     ReqId 5968 FlareSolverr 3.3.13
2024-02-16 23:43:52 DEBUG    ReqId 5968 Debug log enabled
2024-02-16 23:43:52 INFO     ReqId 5968 Testing web browser installation...
2024-02-16 23:43:52 INFO     ReqId 5968 Platform: Windows-10-10.0.19045-SP0
2024-02-16 23:43:52 INFO     ReqId 5968 Chrome / Chromium path: C:\Program Files\Google\Chrome\Application\chrome.exe
2024-02-16 23:43:52 INFO     ReqId 5968 Chrome / Chromium major version: 121
2024-02-16 23:43:52 INFO     ReqId 5968 Launching web browser...
2024-02-16 23:43:52 DEBUG    ReqId 5968 Launching web browser...
Traceback (most recent call last):
  File "C:\Users\XXX\FlareSolverr\src\utils.py", line 302, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\FlareSolverr\src\utils.py", line 183, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\FlareSolverr\src\undetected_chromedriver\__init__.py", line 259, in __init__
    self.patcher.auto()
  File "C:\Users\XXX\FlareSolverr\src\undetected_chromedriver\patcher.py", line 188, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\FlareSolverr\src\undetected_chromedriver\patcher.py", line 297, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\FlareSolverr\src\flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "C:\Users\XXX\FlareSolverr\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\FlareSolverr\src\utils.py", line 308, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

**Comment by ilike2burnthing** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1745

Looking into it.

**Comment by ilike2burnthing** [comment]
[v3.3.14-hotfix](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.14-hotfix)

**Comment by ilike2burnthing** [comment]
[v3.3.14-hotfix2](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.14-hotfix2)

**Comment by pokemaster974** [comment]
Thanks for the fix
