### ISSUE TITLE
[yggcookie] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. 

### ISSUE THREAD

**Issue by braseb33** [FlareSolverr/FlareSolverr#1102]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.15
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

It's not enable to connect YggTorrent with jackett through flaresolverr since v3
Using yggtorrent or yggcookies.

### Logged Error Messages

```text
FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: invalid session id\nStacktrace:\n#0 0x55965dabdf83 <unknown>\n#1 0x55965d776b2b <unknown>\n#2 0x55965d7b73ba <unknown>\n#3 0x55965d7eff94 <unknown>\n#4 0x55965d7e85bb <unknown>\n#5 0x55965d7e7e0f <unknown>\n#6 0x55965d73f2f8 <unknown>\n#7 0x55965da82531 <unknown>\n#8 0x55965da86455 <unknown>\n#9 0x55965da6ef55 <unknown>\n#10 0x55965da870ef <unknown>\n#11 0x55965da5299f <unknown>\n#12 0x55965d73d54f <unknown>\n#13 0x7f030fa64d0a __libc_start_main\n

[v0.21.1861.0] FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: invalid session id\nStacktrace:\n#0 0x55965dabdf83 <unknown>\n#1 0x55965d776b2b <unknown>\n#2 0x55965d7b73ba <unknown>\n#3 0x55965d7eff94 <unknown>\n#4 0x55965d7e85bb <unknown>\n#5 0x55965d7e7e0f <unknown>\n#6 0x55965d73f2f8 <unknown>\n#7 0x55965da82531 <unknown>\n#8 0x55965da86455 <unknown>\n#9 0x55965da6ef55 <unknown>\n#10 0x55965da870ef <unknown>\n#11 0x55965da5299f <unknown>\n#12 0x55965d73d54f <unknown>\n#13 0x7f030fa64d0a __libc_start_main\n
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 850
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by JKelloggs** [comment]
I'm also getting failures.

**Comment by ilike2burnthing** [comment]
I see you've changed the title to a different error. Please provide the correct FlareSolverr logs.

**Comment by braseb33** [comment]
Hi,
I have just truncated the title.
The error is the same as the first title.

**Comment by ilike2burnthing** [comment]
Provide the FlareSolverr logs, rather than Jackett.

`v3.3.16` is now out, update first.

**Comment by braseb33** [comment]
Flaresolverr logs : 
`2024-02-29 02:29:31 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/'}
2024-02-29 02:29:38 ERROR    Error: Error solving the challenge. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-29 02:29:38 INFO     Response in 6.837 s
2024-02-29 02:29:38 INFO     172.x.x.x POST https://flaresolverr/v1 500 Internal Server Error
`

**Comment by braseb33** [comment]
And now : 
`2024-02-29 02:32:03 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/'}
2024-02-29 02:32:04 INFO     Challenge detected. Title found: Just a moment...
2024-02-29 02:32:16 ERROR    Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=120.0.6099.224)\nStacktrace:\n#0 0x5640b2a19f83 <unknown>\n#1 0x5640b26d2b2b <unknown>\n#2 0x5640b26ba16d <unknown>\n#3 0x5640b26b9882 <unknown>\n#4 0x5640b26b8586 <unknown>\n#5 0x5640b26b844a <unknown>\n#6 0x5640b26b67e1 <unknown>\n#7 0x5640b26b718a <unknown>\n#8 0x5640b26c807c <unknown>\n#9 0x5640b26e07c1 <unknown>\n#10 0x5640b26e66bb <unknown>\n#11 0x5640b26b792d <unknown>\n#12 0x5640b26e0459 <unknown>\n#13 0x5640b276af1a <unknown>\n#14 0x5640b274be53 <unknown>\n#15 0x5640b2713dd4 <unknown>\n#16 0x5640b27151de <unknown>\n#17 0x5640b29de531 <unknown>\n#18 0x5640b29e2455 <unknown>\n#19 0x5640b29caf55 <unknown>\n#20 0x5640b29e30ef <unknown>\n#21 0x5640b29ae99f <unknown>\n#22 0x5640b2a07008 <unknown>\n#23 0x5640b2a071d7 <unknown>\n#24 0x5640b2a19124 <unknown>\n#25 0x7f8f4715dea7 start_thread\n
2024-02-29 02:32:16 INFO     Response in 13.704 s
2024-02-29 02:32:16 INFO     172.x.x.x POST https://flaresolverr/v1 500 Internal Server Error
`

**Comment by ilike2burnthing** [comment]
Restart the FlareSolverr container and provide the startup output.

**Comment by braseb33** [comment]
`2024-02-29 02:39:35 INFO     FlareSolverr 3.3.15
2024-02-29 02:39:35 INFO     Testing web browser installation...
2024-02-29 02:39:35 INFO     Platform: Linux-5.15.0-92-generic-x86_64-with-glibc2.31
2024-02-29 02:39:35 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-02-29 02:39:35 INFO     Chrome / Chromium major version: 120
2024-02-29 02:39:35 INFO     Launching web browser...
2024-02-29 02:39:37 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-02-29 02:39:37 INFO     Test successful!
2024-02-29 02:39:37 INFO     Serving on http://0.0.0.0:7000
`

**Comment by ilike2burnthing** [comment]
> `v3.3.16` is now out, update first.

**Comment by braseb33** [comment]
2024-02-29 03:20:55 INFO     FlareSolverr 3.3.16
2024-02-29 03:20:55 INFO     Testing web browser installation...
2024-02-29 03:20:55 INFO     Platform: Linux-5.15.0-92-generic-x86_64-with-glibc2.36
2024-02-29 03:20:55 INFO     Chrome / Chromium path: /xxxxxxxxxx
2024-02-29 03:20:55 INFO     Chrome / Chromium major version: 123
2024-02-29 03:20:55 INFO     Launching web browser...
2024-02-29 03:21:01 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
2024-02-29 03:21:01 INFO     Test successful!
2024-02-29 03:21:01 INFO     Serving on http://0.0.0.0:34752
2024-02-29 03:21:46 INFO     X.X.X.X GET http://flaresolverr:34752/ 200 OK
2024-02-29 03:22:56 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/'}
2024-02-29 03:22:59 INFO     Challenge detected. Selector found: #challenge-spinner
2024-02-29 03:24:38 ERROR    Error: Error solving the challenge. Timeout after 100.0 seconds.
2024-02-29 03:24:38 INFO     Response in 101.458 s
2024-02-29 03:24:38 INFO     172.X.X.X POST http://flaresolverr:34752/v1 500 Internal Server Error

**Comment by ilike2burnthing** [comment]
If your system language isn't English then set the ENV `LANG` to and English language code, as per the example - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by braseb33** [comment]
Works fine with LANG=en_US.UTF-8 and Version 3.3.16
