### ISSUE TITLE
FlareSolverr Breaks with VPN

### ISSUE THREAD

**Issue by tylort69** [FlareSolverr/FlareSolverr#1115]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.16
- Last working FlareSolverr version: NA
- Operating system: Windows Server 2022
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): NA
- Are you using a VPN: yes
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one: NA
- URL to test this issue: NA
```

### Description

[This](https://github.com/FlareSolverr/FlareSolverr/discussions/293) is a related discussion because it asks about using a VPN with FlareSolverr how ever that is where the relevancy ends. 

Running into some issues with flaresolverr when running VPN .
I'm running expressvpn in split tunnel mode and just using it for the torrent client.
When i turn off the VPN  flaresolverr works fine, However when i turn on the VPN (split tunnelling or full vpn ) flaresolver breaks.
I have tried setting the environment host to 127.0.0.1 as well as 192.168.1.xxx and flaresolverr doesn't even start, this is the following error.

```
2024-03-08 21:30:46 INFO     FlareSolverr 3.3.16
2024-03-08 21:30:46 INFO     Testing web browser installation...
2024-03-08 21:30:46 INFO     Platform: Windows-10-10.0.20348-SP0
2024-03-08 21:30:46 INFO     Chrome / Chromium path: Z:\flaresolverr\chrome\chrome.exe
2024-03-08 21:30:46 INFO     Chrome / Chromium major version: 123
2024-03-08 21:30:46 INFO     Launching web browser...
2024-03-08 21:31:50 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:62375
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00604D43+225091]
        (No symbol) [0x00534E91]
        (No symbol) [0x003D9944]
        (No symbol) [0x003CD444]
        (No symbol) [0x0040477C]
        (No symbol) [0x003FD005]
        (No symbol) [0x003FCE47]
        (No symbol) [0x00437C71]
        (No symbol) [0x0043790A]
        (No symbol) [0x0042F2F6]
        (No symbol) [0x004079B9]
        (No symbol) [0x0040879D]
        sqlite3_dbdata_init [0x00A79B23+4064611]
        sqlite3_dbdata_init [0x00A8112A+4094826]
        sqlite3_dbdata_init [0x00A7BA28+4072552]
        sqlite3_dbdata_init [0x0077CA49+930953]
        (No symbol) [0x00540864]
        (No symbol) [0x0053AD88]
        (No symbol) [0x0053AEB1]
        (No symbol) [0x0052CB20]
        BaseThreadInitThunk [0x75D867F9+25]
        RtlGetFullPathName_UEx [0x771C7EBD+173]
        RtlGetFullPathName_UEx [0x771C7E8B+123]

Traceback (most recent call last):
  File "utils.py", line 308, in get_user_agent
  File "utils.py", line 195, in get_webdriver
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flaresolverr.py", line 105, in <module>
  File "flaresolverr_service.py", line 72, in test_browser_installation
  File "utils.py", line 314, in get_user_agent
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
[5832] Failed to execute script 'flaresolverr' due to unhandled exception!
```

If I set the environment HOST=localhost by making start.bat and running it as admin
```
@echo off
set HOST=localhost
flaresolverr.exe
pause
```

 this happens.
```
2024-03-08 21:48:07 INFO     FlareSolverr 3.3.16
2024-03-08 21:48:07 INFO     Testing web browser installation...
2024-03-08 21:48:07 INFO     Platform: Windows-10-10.0.20348-SP0
2024-03-08 21:48:07 INFO     Chrome / Chromium path: Z:\flaresolverr\chrome\chrome.exe
2024-03-08 21:48:07 INFO     Chrome / Chromium major version: 123
2024-03-08 21:48:07 INFO     Launching web browser...
2024-03-08 21:48:19 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
2024-03-08 21:48:19 INFO     Test successful!
2024-03-08 21:48:19 INFO     Serving on http://[::1]:8191
2024-03-08 21:48:19 INFO     Serving on http://192.168.1.188:8191
```

All looks good, However on doing a test in Jackett I run into the follow issues.
```
2024-03-08 21:49:37 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/'}
2024-03-08 21:50:41 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:59505
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00504D43+225091]
        (No symbol) [0x00434E91]
        (No symbol) [0x002D9944]
        (No symbol) [0x002CD444]
        (No symbol) [0x0030477C]
        (No symbol) [0x002FD005]
        (No symbol) [0x002FCE47]
        (No symbol) [0x00337C71]
        (No symbol) [0x0033790A]
        (No symbol) [0x0032F2F6]
        (No symbol) [0x003079B9]
        (No symbol) [0x0030879D]
        sqlite3_dbdata_init [0x00979B23+4064611]
        sqlite3_dbdata_init [0x0098112A+4094826]
        sqlite3_dbdata_init [0x0097BA28+4072552]
        sqlite3_dbdata_init [0x0067CA49+930953]
        (No symbol) [0x00440864]
        (No symbol) [0x0043AD88]
        (No symbol) [0x0043AEB1]
        (No symbol) [0x0042CB20]
        BaseThreadInitThunk [0x75D867F9+25]
        RtlGetFullPathName_UEx [0x771C7EBD+173]
        RtlGetFullPathName_UEx [0x771C7E8B+123]

2024-03-08 21:50:41 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
2024-03-08 21:50:41 INFO     Response in 63.336 s
2024-03-08 21:50:41 INFO     ::1 POST http://localhost:8191/v1 500 Internal Server Error
```

I have tried setting the timeout time higher and still does nothing.
If i turn off the VPN I get the following
```
2024-03-08 21:54:47 INFO     FlareSolverr 3.3.16
2024-03-08 21:54:47 INFO     Testing web browser installation...
2024-03-08 21:54:47 INFO     Platform: Windows-10-10.0.20348-SP0
2024-03-08 21:54:47 INFO     Chrome / Chromium path: Z:\flaresolverr\chrome\chrome.exe
2024-03-08 21:54:47 INFO     Chrome / Chromium major version: 123
2024-03-08 21:54:47 INFO     Launching web browser...
2024-03-08 21:54:58 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
2024-03-08 21:54:58 INFO     Test successful!
2024-03-08 21:54:58 INFO     Serving on http://[::1]:8191
2024-03-08 21:54:58 INFO     Serving on http://127.0.0.1:8191
2024-03-08 21:55:08 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://ext.to/latest/'}
2024-03-08 21:55:26 INFO     Challenge detected. Title found: Just a moment...
2024-03-08 21:56:01 INFO     Challenge solved!
2024-03-08 21:56:02 INFO     Response in 53.944 s
```

Everything works fine.

### Logged Error Messages

```text
All information that I think could assist in solving this issue has been provided with explanations in the description portion however if I have missed anything please ask and I will be happy to attempt to provide more.
```

**Comment by ilike2burnthing** [comment]
Install the OpenVPN client, run with a config file from ExpressVPN, see if that works instead. If not, try one from vpnbook.com instead.

**Comment by ShinyHobo** [comment]
I wrote .bat script for this exact use case. It just keeps retrying indefinitely:
`@echo off
:repeat
start /wait /B "" "[your install location]\flaresolverr\flaresolverr.exe"
goto repeat
`

Dropped a shortcut to the .bat file into my startup folder, works fine.

**Comment by OisinHick** [comment]
starts for me but it still doesnt work. Unsure why
