### ISSUE TITLE
Cannot add Indexer Proxy on prowlarr: ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by carloshenriquefbf** [FlareSolverr/FlareSolverr#1117]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.16
- Last working FlareSolverr version: -
- Operating system: Raspberry Pi OS Lite (Debian 12)
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one: NA
- URL to test this issue: NA
```

### Description

I can't seem to add the indexer proxy on prowlarr. They are both running on docker under the same network with ipv6 disabled.

prowlarr:

```
[Error] FlareSolverr: Proxy Health Check failed 
[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.183.13:8191/v1]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.Test() in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 188
Error: Error solving the challenge. Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED\n  (Session info: chrome=120.0.6099.224)\nStacktrace:\n#0 0x0055804a4850 <unknown>\n#1 0x0055801ab3e0 <unknown>\n#2 0x0055801a5314 <unknown>\n#3 0x00558019819c <unknown>\n#4 0x0055801997b0 <unknown>\n#5 0x005580198570 <unknown>\n#6 0x005580197668 <unknown>\n#7 0x005580197548 <unknown>\n#8 0x005580196274 <unknown>\n#9 0x00558019661c <unknown>\n#10 0x0055801ae61c <unknown>\n#11 0x005580232958 <unknown>\n#12 0x005580232400 <unknown>\n#13 0x0055801e0904 <unknown>\n#14 0x0055801e1d80 <unknown>\n#15 0x005580479618 <unknown>\n#16 0x00558047c5f0 <unknown>\n#17 0x00558047c1d8 <unknown>\n#18 0x00558046c304 <unknown>\n#19 0x00558047ccb0 <unknown>\n#20 0x005580457858 <unknown>\n#21 0x0055804954c8 <unknown>\n#22 0x0055804956cc <unknown>\n#23 0x0055804a3db4 <unknown>\n#24 0x007f88f7b648 start_thread\n#25 0x007f887b701c <unknown>\n | status=error startTimestamp=1710073717370 endTimestamp=1710073722119 version=3.3.16
[Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
 -- Host: Failed to test proxy: 192.168.183.13 
 ```
 
 flaresolverr:
 
 ```
 2024-03-10 12:28:37 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {'url': 'http://192.168.183.13:8191'}}
version_main cannot be converted to an integer
2024-03-10 12:28:42 ERROR    Error: Error solving the challenge. Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED\n  (Session info: chrome=120.0.6099.224)\nStacktrace:\n#0 0x0055804a4850 <unknown>\n#1 0x0055801ab3e0 <unknown>\n#2 0x0055801a5314 <unknown>\n#3 0x00558019819c <unknown>\n#4 0x0055801997b0 <unknown>\n#5 0x005580198570 <unknown>\n#6 0x005580197668 <unknown>\n#7 0x005580197548 <unknown>\n#8 0x005580196274 <unknown>\n#9 0x00558019661c <unknown>\n#10 0x0055801ae61c <unknown>\n#11 0x005580232958 <unknown>\n#12 0x005580232400 <unknown>\n#13 0x0055801e0904 <unknown>\n#14 0x0055801e1d80 <unknown>\n#15 0x005580479618 <unknown>\n#16 0x00558047c5f0 <unknown>\n#17 0x00558047c1d8 <unknown>\n#18 0x00558046c304 <unknown>\n#19 0x00558047ccb0 <unknown>\n#20 0x005580457858 <unknown>\n#21 0x0055804954c8 <unknown>\n#22 0x0055804956cc <unknown>\n#23 0x0055804a3db4 <unknown>\n#24 0x007f88f7b648 start_thread\n#25 0x007f887b701c <unknown>\n
2024-03-10 12:28:42 INFO     Response in 4.749 s
2024-03-10 12:28:42 INFO     172.23.0.1 POST http://192.168.183.13:8191/v1 500 Internal Server Error
``` 

### Logged Error Messages

```text
2024-03-10 12:28:37 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {'url': 'http://192.168.183.13:8191'}}
version_main cannot be converted to an integer
2024-03-10 12:28:42 ERROR    Error: Error solving the challenge. Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED\n  (Session info: chrome=120.0.6099.224)\nStacktrace:\n#0 0x0055804a4850 <unknown>\n#1 0x0055801ab3e0 <unknown>\n#2 0x0055801a5314 <unknown>\n#3 0x00558019819c <unknown>\n#4 0x0055801997b0 <unknown>\n#5 0x005580198570 <unknown>\n#6 0x005580197668 <unknown>\n#7 0x005580197548 <unknown>\n#8 0x005580196274 <unknown>\n#9 0x00558019661c <unknown>\n#10 0x0055801ae61c <unknown>\n#11 0x005580232958 <unknown>\n#12 0x005580232400 <unknown>\n#13 0x0055801e0904 <unknown>\n#14 0x0055801e1d80 <unknown>\n#15 0x005580479618 <unknown>\n#16 0x00558047c5f0 <unknown>\n#17 0x00558047c1d8 <unknown>\n#18 0x00558046c304 <unknown>\n#19 0x00558047ccb0 <unknown>\n#20 0x005580457858 <unknown>\n#21 0x0055804954c8 <unknown>\n#22 0x0055804956cc <unknown>\n#23 0x0055804a3db4 <unknown>\n#24 0x007f88f7b648 start_thread\n#25 0x007f887b701c <unknown>\n
2024-03-10 12:28:42 INFO     Response in 4.749 s
2024-03-10 12:28:42 INFO     172.23.0.1 POST http://192.168.183.13:8191/v1 500 Internal Server Error
```

**Comment by carloshenriquefbf** [comment]
I must add that it works fine with jackett under the same configurations 🤷‍♂️

**Comment by ilike2burnthing** [comment]
> 'proxy': {'url': 'http://192.168.183.13:8191/'}

It looks like you've configured FlareSolverr as an HTTP proxy rather than as FlareSolverr under `Prowlarr > Settings > Indexers > FlareSolverr`

**Comment by carloshenriquefbf** [comment]
Thank you for the help. It seems like the "use proxy" checkbox under "General settings" was checked. Unchecking it solved my issue. Sorry for the noise.

**Comment by OriginalFlavor** [comment]
When I changed Firefox to use DNS over HTTPS (a/k/a DOH), Prowlarr and Flaresolverr stopped working.
When I returned Firefox's DNS settings to their original form, Prowlarr and Flaresolverr returned to working.

The instructions that i used for implementing DOT using Quad9 can be found at: https://quad9.net/news/blog/doh-with-quad9-dns-servers/

The redacted log file of Flaresolverr during the error, included the following message.

> 2024-10-20 19:43:14,062 DEBG 'flaresolverr' stdout output:
> 2024-10-20 19:43:14 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {'url': 'http://192.168.1.XXX:8118', 'username': 'XXX', 'password': 'XXX'}}
> 
> 2024-10-20 19:43:15,522 DEBG 'flaresolverr' stdout output:
> 2024-10-20 19:43:15 ERROR    Error: Error solving the challenge. Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED\n  (Session info: chrome=123.0.6300.0)\nStacktrace:\n#0 0x55a39d1be863 <unknown>\n#1 0x55a39ceb48c6 <unknown>\n#2 0x55a39ceac9f3 <unknown>\n#3 0x55a39ce9cb2b <unknown>\n#4 0x55a39ce9e0c2 <unknown>\n#5 0x55a39ce9ce4c <unknown>\n#6 0x55a39ce9c638 <unknown>\n#7 0x55a39ce9c485 <unknown>\n#8 0x55a39ce9a516 <unknown>\n#9 0x55a39ce9aa2a <unknown>\n#10 0x55a39ceb724e <unknown>\n#11 0x55a39cf407c5 <unknown>\n#12 0x55a39cf215a2 <unknown>\n#13 0x55a39cf3fc19 <unknown>\n#14 0x55a39cf21343 <unknown>\n#15 0x55a39cef2593 <unknown>\n#16 0x55a39cef2f5e <unknown>\n#17 0x55a39d18284b <unknown>\n#18 0x55a39d1867a5 <unknown>\n#19 0x55a39d170571 <unknown>\n#20 0x55a39d187332 <unknown>\n#21 0x55a39d15587f <unknown>\n#22 0x55a39d1ad728 <unknown>\n#23 0x55a39d1ad8fb <unknown>\n#24 0x55a39d1bd9b4 <unknown>\n#25 0x148b767ab39d <unknown>\n#26 0x148b768302a4 __clone\n
> 
> 2024-10-20 19:43:15,524 DEBG 'flaresolverr' stdout output:
> 2024-10-20 19:43:15 INFO     Response in 1.46 s
> 2024-10-20 19:43:15 INFO     192.168.1.XXX POST http://192.168.1.XXX:8191/v1 500 Internal Server Error
