### ISSUE TITLE
[chdbits] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 75.0 seconds.

### ISSUE THREAD

**Issue by PN62323424** [FlareSolverr/FlareSolverr#1133]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.16
- Last working FlareSolverr version:3.3.16
- Operating system:synology
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [yes]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

FlareSolverr logs :
```
2024-03-25 19:16:08 INFO     FlareSolverr 3.3.16
2024-03-25 19:16:08 INFO     Testing web browser installation...
2024-03-25 19:16:08 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.31
2024-03-25 19:16:08 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-03-25 19:16:10 INFO     Chrome / Chromium major version: 120
2024-03-25 19:16:10 INFO     Launching web browser...
version_main cannot be converted to an integer
2024-03-25 19:16:24 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-03-25 19:16:24 INFO     Test successful!
2024-03-25 19:16:24 INFO     Serving on http://0.0.0.0:8191
2024-03-25 19:16:41 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-25 19:16:49 INFO     Challenge not detected!
2024-03-25 19:16:49 INFO     Response in 7.883 s
2024-03-25 19:16:49 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-25 19:32:31 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-25 19:33:32 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-03-25 19:33:32 INFO     Response in 60.969 s
2024-03-25 19:33:32 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 500 Internal Server Error
2024-03-25 20:10:59 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-25 20:11:01 INFO     Challenge not detected!
2024-03-25 20:11:01 INFO     Response in 2.072 s
2024-03-25 20:11:01 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-26 02:11:33 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-26 02:11:34 INFO     Challenge not detected!
2024-03-26 02:11:34 INFO     Response in 1.939 s
2024-03-26 02:11:34 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-26 08:12:06 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-26 08:12:07 INFO     Challenge not detected!
2024-03-26 08:12:08 INFO     Response in 1.977 s
2024-03-26 08:12:08 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-26 14:12:37 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-26 14:12:39 INFO     Challenge not detected!
2024-03-26 14:12:39 INFO     Response in 1.849 s
2024-03-26 14:12:39 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-26 20:13:10 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-26 20:13:12 INFO     Challenge not detected!
2024-03-26 20:13:12 INFO     Response in 2.042 s
2024-03-26 20:13:12 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-27 02:13:43 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-27 02:13:45 INFO     Challenge not detected!
2024-03-27 02:13:45 INFO     Response in 2.08 s
2024-03-27 02:13:45 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-27 08:14:15 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-27 08:14:17 INFO     Challenge not detected!
2024-03-27 08:14:17 INFO     Response in 2.236 s
2024-03-27 08:14:17 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-27 14:14:47 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-27 14:14:49 INFO     Challenge not detected!
2024-03-27 14:14:49 INFO     Response in 2.278 s
2024-03-27 14:14:49 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-27 17:55:43 INFO     FlareSolverr 3.3.16
2024-03-27 17:55:43 INFO     Testing web browser installation...
2024-03-27 17:55:43 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.31
2024-03-27 17:55:43 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-03-27 17:55:45 INFO     Chrome / Chromium major version: 120
2024-03-27 17:55:45 INFO     Launching web browser...
version_main cannot be converted to an integer
2024-03-27 17:56:00 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-03-27 17:56:00 INFO     Test successful!
2024-03-27 17:56:00 INFO     Serving on http://0.0.0.0:8191
2024-03-27 17:56:11 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-27 17:56:18 INFO     Challenge not detected!
2024-03-27 17:56:18 INFO     Response in 7.138 s
2024-03-27 17:56:18 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-27 18:13:04 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
version_main cannot be converted to an integer
2024-03-27 18:13:06 INFO     Challenge not detected!
2024-03-27 18:13:06 INFO     Response in 2.172 s
2024-03-27 18:13:06 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
2024-03-27 18:39:54 INFO     Incoming request => POST /v1 body: {'maxTimeout': 75000, 'cmd': 'request.get', 'url': 'https://ptchdbits.co/login.php'}
version_main cannot be converted to an integer
2024-03-27 18:40:03 INFO     Challenge detected. Title found: Just a moment...
2024-03-27 18:41:13 ERROR    Error: Error solving the challenge. Timeout after 75.0 seconds.
2024-03-27 18:41:13 INFO     Response in 79.345 s
2024-03-27 18:41:13 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 500 Internal Server Error
2024-03-27 18:41:13 INFO     Incoming request => POST /v1 body: {'maxTimeout': 75000, 'cmd': 'request.get', 'url': 'https://ptchdbits.co/login.php'}
version_main cannot be converted to an integer
2024-03-27 18:41:18 INFO     Challenge detected. Title found: Just a moment...
2024-03-27 18:42:30 ERROR    Error: Error solving the challenge. Timeout after 75.0 seconds.
2024-03-27 18:42:30 INFO     Response in 76.365 s
2024-03-27 18:42:30 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 500 Internal Server Error
2024-03-27 18:42:30 INFO     Incoming request => POST /v1 body: {'maxTimeout': 75000, 'cmd': 'request.get', 'url': 'https://ptchdbits.co/login.php'}
version_main cannot be converted to an integer
2024-03-27 18:42:33 INFO     Challenge detected. Title found: Just a moment...
2024-03-27 18:43:45 ERROR    Error: Error solving the challenge. Timeout after 75.0 seconds.
2024-03-27 18:43:45 INFO     Response in 75.848 s
2024-03-27 18:43:45 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 500 Internal Server Error
2024-03-27 18:45:25 INFO     Incoming request => POST /v1 body: {'maxTimeout': 75000, 'cmd': 'request.get', 'url': 'https://ptchdbits.co/login.php', 'proxy': {'url': 'http://172.17.0.1:7890'}}
version_main cannot be converted to an integer
2024-03-27 18:45:31 INFO     Challenge detected. Title found: Just a moment...
2024-03-27 18:46:42 ERROR    Error: Error solving the challenge. Timeout after 75.0 seconds.
2024-03-27 18:46:42 INFO     Response in 77.004 s
2024-03-27 18:46:42 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 500 Internal Server Error
```

jackett logs:
```
[custom-init] No custom files found, skipping...
03-27 18:39:35 Info Starting Jackett v0.21.2163
03-27 18:39:36 Info Environment version: 6.0.28 (/app/Jackett/)
03-27 18:39:36 Info OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
03-27 18:39:36 Info Jackett variant: CoreLinuxMuslAmdx64
03-27 18:39:36 Info File /etc/issue: Welcome to Alpine Linux 3.19
03-27 18:39:36 Info Running in Docker: Yes (image build: v0.21.2090-ls342)
03-27 18:39:36 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
03-27 18:39:36 Info App config/log directory: /config/Jackett
03-27 18:39:36 Info Using proxy: Disabled
03-27 18:39:36 Info Using FlareSolverr: http://172.17.0.1:8191/
03-27 18:39:36 Info Using HTTP Client: HttpWebClient2
03-27 18:39:36 Info Loading Native indexers ...
03-27 18:39:37 Info Loaded 75 Native indexers.
03-27 18:39:37 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
03-27 18:39:39 Info Loaded 537 Cardigann indexers.
03-27 18:39:39 Info Loaded 612 indexers in total
03-27 18:39:39 Info Adding aggregate indexer ('all' indexer) ...
03-27 18:39:39 Info Adding filter indexer ('type:public' indexer) ...
03-27 18:39:39 Info Adding filter indexer ('type:private' indexer) ...
03-27 18:39:39 Info Adding filter indexer ('type:semi-public' indexer) ...
03-27 18:39:39 Info Jackett startup finished in 4.188 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
Connection to localhost (::1) 9117 port [tcp/*] succeeded!
[ls.io-init] done.
03-27 18:39:59 Info Test search in M-Team - TP => Found 100 releases [1821ms]
03-27 18:41:13 Error Exception in GetConfigurationForSetup (chdbits): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 75.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 943
03-27 18:42:30 Error Exception in GetConfigurationForSetup (chdbits): System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 943
03-27 18:43:45 Error System.OperationCanceledException: The operation was canceled.

[v0.21.2163.0] System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 593
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

03-27 18:45:14 Info Restarting webhost due to configuration change
03-27 18:45:14 Info Restart of the web application host (not process) initiated
03-27 18:45:14 Info Jackett stopped
03-27 18:45:14 Info Environment version: 6.0.28 (/app/Jackett/)
03-27 18:45:14 Info OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
03-27 18:45:14 Info Jackett variant: CoreLinuxMuslAmdx64
03-27 18:45:14 Info File /etc/issue: Welcome to Alpine Linux 3.19
03-27 18:45:14 Info Running in Docker: Yes (image build: v0.21.2090-ls342)
03-27 18:45:14 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
03-27 18:45:14 Info App config/log directory: /config/Jackett
03-27 18:45:14 Info Using proxy: Http
03-27 18:45:14 Info Using FlareSolverr: http://172.17.0.1:8191/
03-27 18:45:14 Info Using HTTP Client: HttpWebClient2
03-27 18:45:14 Info Loading Native indexers ...
03-27 18:45:14 Info Loaded 75 Native indexers.
03-27 18:45:14 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
03-27 18:45:16 Info Loaded 537 Cardigann indexers.
03-27 18:45:16 Info Loaded 612 indexers in total
03-27 18:45:16 Info Adding aggregate indexer ('all' indexer) ...
03-27 18:45:16 Info Adding filter indexer ('type:public' indexer) ...
03-27 18:45:16 Info Adding filter indexer ('type:private' indexer) ...
03-27 18:45:16 Info Adding filter indexer ('type:semi-public' indexer) ...
03-27 18:45:17 Info Jackett startup finished in 341.581 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
03-27 18:46:42 Error FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 75.0 seconds.

[v0.21.2163.0] FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 75.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 593
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Logged Error Messages

```text
none
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1036
