### ISSUE TITLE
[1337x] Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: socket hang up: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: socket hang up (Test)

### ISSUE THREAD

**Issue by Chiggy-Playz** [FlareSolverr/FlareSolverr#114]
### Environment

* **FlareSolverr version**: v1.2.5
* **Last working FlareSolverr version**: v1.2.5
* **Operating system**: Debian 10
* **Are you using Docker**: [yes/no] no (npm + pm2 to handle )
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:** nope

### Description

Till yesterday, the indexer was working. Today, its giving this error. Please Help

[List steps to reproduce the error and details on what happens and what you expected to happen]

I setup flaresolverr in jackett, clicked on test, and got this error. Nothing else is new.

### Logged Error Messages

```
ErrorEvent {
  target:
   WebSocket {
     _events:
      [Object: null prototype] { open: [Function], error: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _binaryType: 'nodebuffer',
     _closeCode: 1006,
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _extensions: {},
     _protocol: '',
     _readyState: 3,
     _receiver: null,
     _sender: null,
     _socket: null,
     _bufferedAmount: 0,
     _isServer: false,
     _redirects: 0,
     _url:
      'ws://127.0.0.1:40487/devtools/browser/bae4761c-90ff-4f20-bf87-feeb7b0cc09d',
     _req: null },
  type: 'error',
  message: 'socket hang up',
  error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:332:15)
       at Socket.socketOnEnd (_http_client.js:435:23)
       at Socket.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } }
2021-04-25T16:57:45.636Z ERROR REQ-30 socket hang up
```

**Comment by Chiggy-Playz** [comment]
Restarting the whole machine seemed to fix it
