### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by Jojont54** [FlareSolverr/FlareSolverr#1169]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.17
- Last working FlareSolverr version: 3.3.17
- Operating system: Linux (Debian) / Ultra.cc
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint): {"msg": "FlareSolverr is ready!", "version": "3.3.17", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://yggtorrent.cool/
```

### Description

I guess the new YggTorrent domain isn't well consider. 

### Logged Error Messages

```text
Tested with : 

curl -L -X POST 'http://MYIPSERVER/v1' -H 'Content-Type: application/json' --data-raw '{
  "cmd": "request.get",
  "url": "http://www3.yggtorrent.cool/",
  "maxTimeout": 60000
}'
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1714391824469, "endTimestamp": 1714391885795, "version": "3.3.17"}
```

**Comment by Razor648** [comment]
I have the same error :

```shell
024-04-29 14:11:19 INFO     Response in 6.446 s
2024-04-29 14:11:19 INFO     172.18.0.1 POST http://192.168.0.112:8191/v1 200 OK
2024-04-29 14:12:11 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-29 14:12:19 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-29 14:12:21 INFO     Challenge detected. Title found: Just a moment...
2024-04-29 14:12:22 INFO     Challenge detected. Title found: Just a moment...
2024-04-29 14:12:55 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-29 14:12:57 INFO     Challenge detected. Title found: Just a moment...
2024-04-29 14:15:12 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024-04-29 14:15:12 INFO     Response in 181.106 s
2024-04-29 14:15:12 INFO     172.18.0.1 POST http://192.168.0.112:8191/v1 500 Internal Server Error
2024-04-29 14:15:21 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024-04-29 14:15:21 INFO     Response in 181.386 s
2024-04-29 14:15:21 INFO     172.18.0.1 POST http://192.168.0.112:8191/v1 500 Internal Server Error
2024-04-29 14:15:57 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024-04-29 14:15:57 INFO     Response in 182.062 s
2024-04-29 14:15:57 INFO     172.18.0.1 POST http://192.168.0.112:8191/v1 500 Internal Server Error
```

**Comment by sovajri7** [comment]
Same error here, timeout error solving challenge.

**Comment by SadE54** [comment]
Same here, timeout error

**Comment by alanstrok** [comment]
Same here as well

**Comment by TH0MVS** [comment]
Same error !

**Comment by Kitchigo** [comment]
Me too, same error :'(

**Comment by behead974** [comment]
same error...

```
HTTP Error - Res: HTTP/1.1 [POST] http://192.168.1.66:8191/v1: 500.InternalServerError (183 bytes)
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 180.0 seconds.", "startTimestamp": 1714420566632, "endTimestamp": 1714420748211, "version": "3.3.17"}
```

**Comment by ilike2burnthing** [comment]
Increase the timeout and follow the steps in the [troubleshooting wiki](https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting). For YGG specifically, and if your system language isn't English, set the ENV LANG to an English language code as per the example - https://github.com/FlareSolverr/FlareSolverr#environment-variables.

Otherwise - https://github.com/FlareSolverr/FlareSolverr/issues/1036

**Comment by Jojont54** [comment]
> @ilike2burnthing A lot of us are using app website with no control over the docker itself 😖

![FlareSolverr_YggTorrent new domain](https://github.com/FlareSolverr/FlareSolverr/assets/64749837/7c0b76f8-edad-46ac-b504-1fe0a87b0b67)

I took a screenshot if it can help, done using Putty with SSH protocol.

**Comment by Kitchigo** [comment]
And is doesnt work only in Yggtorrent, in other like iDope is working well...
`2024-04-30T08:24:49.620679000Z 2024-04-30 10:24:49 DEBUG    ReqId 140715845728000 Try to find the Cloudflare 'Verify you are human' button...
2024-04-30T08:24:49.634801000Z 2024-04-30 10:24:49 DEBUG    ReqId 140715845728000 The Cloudflare 'Verify you are human' button not found on the page.
2024-04-30T08:24:49.875720000Z 2024-04-30 10:24:49 DEBUG    ReqId 140715960121088 A used instance of webdriver has been destroyed
2024-04-30T08:24:49.875917000Z 2024-04-30 10:24:49 ERROR    ReqId 140715960121088 Error: Error solving the challenge. Timeout after 90.0 seconds.
2024-04-30T08:24:49.876281000Z 2024-04-30 10:24:49 DEBUG    ReqId 140715960121088 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 90.0 seconds.', 'startTimestamp': 1714465398920, 'endTimestamp': 1714465489875, 'version': '3.3.17'}
2024-04-30T08:24:49.876384000Z 2024-04-30 10:24:49 INFO     ReqId 140715960121088 Response in 90.955 s
2024-04-30T08:24:49.876440000Z 2024-04-30 10:24:49 INFO     ReqId 140715960121088 127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error`

**Comment by Symness** [comment]
Same problem here...
`2024-04-30 10:26:55 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?category=2145&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-30 10:26:56 INFO     Challenge detected. Title found: Just a moment...
2024-04-30 10:27:55 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-04-30 10:27:55 INFO     Response in 60.792 s
2024-04-30 10:27:55 INFO     XX.XX.XX.XX POST http://XX.XX.XX.XX:8191/v1 500 Internal Server Error`

**Comment by Flameeeeee** [comment]
Same here as well : 
`2024-04-30 10:36:47 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-04-30 10:36:50 INFO     Challenge detected. Title found: Just a moment...
2024-04-30 10:37:48 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-04-30 10:37:48 INFO     Response in 60.783 s
2024-04-30 10:37:48 INFO     XX.XX.XX.XX POST http://XX.XX.XX.XX:8191/v1 500 Internal Server Error
`
I am getting this error since 28th Apr 8:30pm and I am using Flaresolverr v3.3.17

**Comment by DAMIOSKIDEV** [comment]
Same error on FlareSolveer v3.3.17 / Chrome v126

`2024-04-30 10:50:54 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?name=&description=&file=&uploader=&category=2145&sub_category=all&do=search', 'maxTimeout': 60000}
2024-04-30 10:50:56 INFO     Challenge detected. Title found: Just a moment...
2024-04-30 10:51:57 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-04-30 10:51:57 INFO     Response in 62.794 s
2024-04-30 10:51:57 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
`

Re-open this issue

**Comment by ilike2burnthing** [comment]
I've already linked to the open issue for this problem.

**Comment by DAMIOSKIDEV** [comment]
> I've already linked to the open issue for this problem.

My bad

**Comment by Flameeeeee** [comment]
> I've already linked to the open issue for this problem.

Are you 100% sure it is related ? Because everything was working fine on my setup 2 days ago. My system `LANG` variable is already set to an english code (en_US) so I never needed to add the `LANG` env variable in order to make flaresolverr work with ygg. 

I am afraid it may be a different issue.

**Comment by behead974** [comment]
> > > I've already linked to the open issue for this problem.
> > 
> > 
> > Are you 100% sure it is related ? Because everything was working fine on my setup 2 days ago. My system `LANG` variable is already set to an english code (en_US) so I never needed to add the `LANG` env variable in order to make flaresolverr work with ygg.
> > I am afraid it may be a different issue.
> 
> For me it's when Ygg domain went from ".aq" to ".cool"

same for me ! it's when Ygg domain went from ".qa" to ".cool

**Comment by SadE54** [comment]
This error came several time over the last year. It was always solved with a new flaresolverr version 😁

**Comment by DAMIOSKIDEV** [comment]
> > > I've already linked to the open issue for this problem.
> > 
> > 
> > Are you 100% sure it is related ? Because everything was working fine on my setup 2 days ago. My system `LANG` variable is already set to an english code (en_US) so I never needed to add the `LANG` env variable in order to make flaresolverr work with ygg.
> > I am afraid it may be a different issue.
> 
> For me it's when Ygg domain went from ".aq" to ".cool"

omg, same

**Comment by ilike2burnthing** [comment]
Enable debug logging, bump the timeout to 100s, does FlareSolverr show that the challenge is just looping (it's found, clicked, not found a bunch, found again, and the pattern repeats)? If you're on Windows, set `HEADLESS` to `false`, do you see the challenge looping?

If so, yes it's the same problem.

**Comment by Jojont54** [comment]
> > > > I've already linked to the open issue for this problem.
> > > 
> > > 
> > > Are you 100% sure it is related ? Because everything was working fine on my setup 2 days ago. My system `LANG` variable is already set to an english code (en_US) so I never needed to add the `LANG` env variable in order to make flaresolverr work with ygg.
> > > I am afraid it may be a different issue.
> > 
> > 
> > For me it's when Ygg domain went from ".aq" to ".cool"
> 
> omg, same

Look at the description of this issue ticket.

**Comment by alanstrok** [comment]
> Enable debug logging, bump the timeout to 100s, does FlareSolverr show that the challenge is just looping (it's found, clicked, not found a bunch, found again, and the pattern repeats)? If you're on Windows, set `HEADLESS` to `false`, do you see the challenge looping?
> 
> If so, yes it's the same problem.

I think it's the same issue. I set the log to debug and its looping.

**Comment by averagePedestrian** [comment]
I set `LANG=en_US` as suggested here https://github.com/FlareSolverr/FlareSolverr/issues/1036#issuecomment-1888369930. I also increased the timeout to 100 seconds, but this still didn’t resolve the issue for me.

Here are the debug logs:
[flaresolverr.txt](https://github.com/FlareSolverr/FlareSolverr/files/15169316/flaresolverr.txt)

**Comment by Razor648** [comment]
> Enable debug logging, bump the timeout to 100s, does FlareSolverr show that the challenge is just looping (it's found, clicked, not found a bunch, found again, and the pattern repeats)? If you're on Windows, set `HEADLESS` to `false`, do you see the challenge looping?
> 
> If so, yes it's the same problem.

Here is the result in debug mode:

```shell
2024-04-30 21:36:15 INFO     ReqId 140555669042944 Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.cool/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-04-30 21:36:15 DEBUG    ReqId 140555669042944 Launching web browser...
version_main cannot be converted to an integer
2024-04-30 21:36:15 DEBUG    ReqId 140555669042944 Started executable: `/app/chromedriver` in a child process with pid: 168
2024-04-30 21:36:16 DEBUG    ReqId 140555669042944 New instance of webdriver has been created to perform the request
2024-04-30 21:36:16 DEBUG    ReqId 140555635472128 Navigating to... https://www3.yggtorrent.cool/engine/search?category=all&do=search&order=desc&sort=publish_date
2024-04-30 21:36:21 INFO     ReqId 140555635472128 Challenge detected. Title found: Just a moment...
2024-04-30 21:39:02 DEBUG    ReqId 140555635472128 Waiting for title (attempt 45): Just a moment...
2024-04-30 21:39:03 DEBUG    ReqId 140555635472128 Timeout waiting for selector
2024-04-30 21:39:03 DEBUG    ReqId 140555635472128 Try to find the Cloudflare verify checkbox...
2024-04-30 21:39:03 DEBUG    ReqId 140555635472128 Cloudflare verify checkbox not found on the page.
2024-04-30 21:39:03 DEBUG    ReqId 140555635472128 Try to find the Cloudflare 'Verify you are human' button...
2024-04-30 21:39:03 DEBUG    ReqId 140555635472128 The Cloudflare 'Verify you are human' button not found on the page.
2024-04-30 21:39:06 DEBUG    ReqId 140555635472128 Waiting for title (attempt 46): Just a moment...
2024-04-30 21:39:07 DEBUG    ReqId 140555635472128 Timeout waiting for selector
2024-04-30 21:39:07 DEBUG    ReqId 140555635472128 Try to find the Cloudflare verify checkbox...
2024-04-30 21:39:07 DEBUG    ReqId 140555635472128 Cloudflare verify checkbox not found on the page.
2024-04-30 21:39:07 DEBUG    ReqId 140555635472128 Try to find the Cloudflare 'Verify you are human' button...
2024-04-30 21:39:07 DEBUG    ReqId 140555635472128 The Cloudflare 'Verify you are human' button not found on the page.
2024-04-30 21:39:09 DEBUG    ReqId 140555635472128 Waiting for title (attempt 47): Just a moment...
2024-04-30 21:39:10 DEBUG    ReqId 140555635472128 Timeout waiting for selector
2024-04-30 21:39:10 DEBUG    ReqId 140555635472128 Try to find the Cloudflare verify checkbox...
2024-04-30 21:39:10 DEBUG    ReqId 140555635472128 Cloudflare verify checkbox not found on the page.
2024-04-30 21:39:10 DEBUG    ReqId 140555635472128 Try to find the Cloudflare 'Verify you are human' button...
2024-04-30 21:39:10 DEBUG    ReqId 140555635472128 The Cloudflare 'Verify you are human' button not found on the page.
2024-04-30 21:39:12 DEBUG    ReqId 140555635472128 Waiting for title (attempt 48): Just a moment...
2024-04-30 21:39:13 DEBUG    ReqId 140555635472128 Timeout waiting for selector
2024-04-30 21:39:13 DEBUG    ReqId 140555635472128 Try to find the Cloudflare verify checkbox...
2024-04-30 21:39:14 DEBUG    ReqId 140555635472128 Cloudflare verify checkbox not found on the page.
2024-04-30 21:39:14 DEBUG    ReqId 140555635472128 Try to find the Cloudflare 'Verify you are human' button...
2024-04-30 21:39:14 DEBUG    ReqId 140555635472128 The Cloudflare 'Verify you are human' button not found on the page.
2024-04-30 21:39:16 DEBUG    ReqId 140555669042944 A used instance of webdriver has been destroyed
2024-04-30 21:39:16 ERROR    ReqId 140555669042944 Error: Error solving the challenge. Timeout after 180.0 seconds.
2024-04-30 21:39:16 DEBUG    ReqId 140555669042944 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 180.0 seconds.', 'startTimestamp': 1714505775405, 'endTimestamp': 1714505956995, 'version': '3.3.17'}
2024-04-30 21:39:16 INFO     ReqId 140555669042944 Response in 181.59 s
2024-04-30 21:39:16 INFO     ReqId 140555669042944 172.18.0.1 POST http://192.168.0.112:8191/v1 500 Internal Server Error
```

**Comment by Reivilo85k** [comment]
Same problem here since the domain name change.

```Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 597
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 943```
   
   and another error :
   
   
  ```FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

[v0.21.2516.0] FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 597
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 593
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26```
   
   
   And finally
   

 ```Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.  [v0.21.2516.0] Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.  ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext() --- End of stack trace from previous location ---    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 597    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1521    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 365    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 386    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 772    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322    at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26```
