### ISSUE TITLE
Lots of tracebacks on launch in Docker on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by captainkev76** [FlareSolverr/FlareSolverr#1170]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.17 
- Last working FlareSolverr version: unknown
- Operating system: Ubuntu Server 24.04 LTS
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): 
- Are you using a VPN: no
- Are you using a Proxy: no 
- Are you using Captcha Solver: no
- If using captcha solve, which one:
- URL to test this issue: Not getting that far
```

### Description

I've built a new VM (in Proxmox) running Ubuntu 24.04 LTS. When Flaresolvrr is started in docker, there are lots of traceback messages when it tries to launch Chrome. It looks like there was a similar issue in 3.3.7 last year that was resolved in 3.3.8, but it's back in 3.3.17.

Docker version is 26.1.0 

### Logged Error Messages

```text
2024-04-29 18:29:46 INFO     FlareSolverr 3.3.17
2024-04-29 18:29:46 INFO     Testing web browser installation...
2024-04-29 18:29:46 INFO     Platform: Linux-6.8.0-31-generic-x86_64-with-glibc2.31
2024-04-29 18:29:46 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-04-29 18:29:46 INFO     Chrome / Chromium major version: 120
2024-04-29 18:29:46 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 308, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 164, in get_webdriver
    start_xvfb_display()
  File "/app/utils.py", line 324, in start_xvfb_display
    XVFB_DISPLAY = Xvfb()
                   ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/xvfbwrapper.py", line 37, in __init__
    self._tempdir = tempdir or tempfile.gettempdir()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 316, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 309, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 224, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 314, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
2024-04-29 18:30:47 INFO     FlareSolverr 3.3.17
2024-04-29 18:30:47 INFO     Testing web browser installation...
2024-04-29 18:30:47 INFO     Platform: Linux-6.8.0-31-generic-x86_64-with-glibc2.31
2024-04-29 18:30:47 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-04-29 18:30:47 INFO     Chrome / Chromium major version: 120
2024-04-29 18:30:47 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 308, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 164, in get_webdriver
    start_xvfb_display()
  File "/app/utils.py", line 324, in start_xvfb_display
    XVFB_DISPLAY = Xvfb()
                   ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/xvfbwrapper.py", line 37, in __init__
    self._tempdir = tempdir or tempfile.gettempdir()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 316, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 309, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 224, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 314, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
```

**Comment by captainkev76** [comment]
Purging volumes and images seems to have fixed everything now...
