### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by toverux** [FlareSolverr/FlareSolverr#1206]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.19
- Last working FlareSolverr version: v3.3.17 (I think)
- Operating system: Ubuntu 24.04
- Are you using Docker: no
```

### Description

Hello !
This is after I updated to the latest version. I have no real experience with Python so I have no idea why distutil is missing and how to fix it.

This is my update script:

```sh
#!/bin/bash
set -euxo pipefail

git pull
python3 -m venv .venv
source .venv/bin/activate
.venv/bin/pip install -r requirements.txt
sudo systemctl restart flaresolverr.service
```

### Logged Error Messages

```text
May 17 16:00:41 saphir flaresolverr[1506]: Traceback (most recent call last):
May 17 16:00:41 saphir flaresolverr[1506]:   File "/home/morgan/flaresolverr/src/flaresolverr.py", line 13, in <module>
May 17 16:00:41 saphir flaresolverr[1506]:     import flaresolverr_service
May 17 16:00:41 saphir flaresolverr[1506]:   File "/home/morgan/flaresolverr/src/flaresolverr_service.py", line 17, in <module>
May 17 16:00:41 saphir flaresolverr[1506]:     import utils
May 17 16:00:41 saphir flaresolverr[1506]:   File "/home/morgan/flaresolverr/src/utils.py", line 11, in <module>
May 17 16:00:41 saphir flaresolverr[1506]:     import undetected_chromedriver as uc
May 17 16:00:41 saphir flaresolverr[1506]:   File "/home/morgan/flaresolverr/src/undetected_chromedriver/__init__.py", line 44, in <module>
May 17 16:00:41 saphir flaresolverr[1506]:     from .patcher import IS_POSIX
May 17 16:00:41 saphir flaresolverr[1506]:   File "/home/morgan/flaresolverr/src/undetected_chromedriver/patcher.py", line 4, in <module>
May 17 16:00:41 saphir flaresolverr[1506]:     from distutils.version import LooseVersion
May 17 16:00:41 saphir flaresolverr[1506]: ModuleNotFoundError: No module named 'distutils'
```

**Comment by 21hsmw** [comment]
Ubuntu 24.04 uses python 3.12, which removed distutils.
You can use something like [pyenv](https://github.com/pyenv/pyenv) to install the latest 3.11 version and run flaresolverr with it until it is supported.
