### ISSUE TITLE
Infinite load - http://localhost:8191/ works with VPN (windscribe) off but how can i get it working with vpn

### ISSUE THREAD

**Issue by Ensnare2** [FlareSolverr/FlareSolverr#1207]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.19
- Last working FlareSolverr version:
- Operating system:Linux Mint 21.3 (release 21.3)
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: yes
- Are you using a Proxy: no
- Are you using Captcha Solver: no(?)
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

http://localhost:8191/ just infintelty loads.

When i was using podman docker it would load (just not on startup). now im using actual docker and getting it unable to load.

### Logged Error Messages

```text
george@george-HP-Pavilion-Laptop-15-eh0xxx:~$ docker run -d \

  -e LOG_LEVEL=debug \

  -e LOG_HTML=true \

  ... # other options and flags

  flaresolverr/flaresolverr
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
-e: command not found
-e: command not found
...: command not found
2024-05-31 14:45:19 INFO     FlareSolverr 3.3.19
2024-05-31 14:45:19 INFO     Testing web browser installation...
2024-05-31 14:45:19 INFO     Platform: Linux-5.15.0-107-generic-x86_64-with-glibc2.35
2024-05-31 14:45:19 INFO     Chrome / Chromium path: /home/george/flaresolverr/chrome/chrome
2024-05-31 14:45:19 INFO     Chrome / Chromium major version: 123
2024-05-31 14:45:19 INFO     Launching web browser...
2024-05-31 14:45:24 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
2024-05-31 14:45:24 INFO     Test successful!
Traceback (most recent call last):
  File "flaresolverr.py", line 125, in <module>
  File "bottle.py", line 3175, in run
  File "flaresolverr.py", line 124, in run
  File "waitress/__init__.py", line 13, in serve
  File "waitress/server.py", line 78, in create_server
  File "waitress/server.py", line 244, in __init__
  File "waitress/server.py", line 361, in bind_server_socket
  File "waitress/wasyncore.py", line 396, in bind
OSError: [Errno 98] Address already in use
[9478] Failed to execute script 'flaresolverr' due to unhandled exception!
george@george-HP-Pavilion-Laptop-15-eh0xxx:~$
```

**Comment by 21hsmw** [comment]
```
-e: command not found
-e: command not found
```
```
OSError: [Errno 98] Address already in use
```

What are your exact steps? There are a lot of errors in what you shared and it says you are already using the address.
Try using `docker compose` instead of running the container with `docker run` and make sure you don't have another flaresolverr container running at the same time.
