### ISSUE TITLE
The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by disquaw** [FlareSolverr/FlareSolverr#1230]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.19
- Last working FlareSolverr version: N/A
- Operating system: Debian 12
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hello There,

First of all, thank you to the developers! :)

I have been using FlareSolverr on Windows without any problems for a long time. I want to migrate to Debian. I installed Jackett and FlareSolverr under docker. The capcha is well solved but I encounter a cookie problem.
In the Troubleshooting it is indicated that the two containers must be on the same network, I took care to put them in network_mode: host
I also disabled IPV6 on the host.
I specify that I modified the ENV LANG=fr-FR and the TZ=Europe/Paris.
I encounter the problem on iDope, Torrent[CORE] and Ygg

Thanks for your help

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (idope): The cookies provided by FlareSolverr are not valid

[v0.22.188.0] Jackett.Common.IndexerException: Exception (idope): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 598
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1532
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 366
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 387
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 323
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
v3.3.20 just came out. That won't resolve anything, but just a heads up.

Remove the `LANG` and `TZ` ENVs, see if it makes a difference.

Neither Jackett nor FlareSolverr (or the host device for that matter) are using a proxy or VPN?

What have you used as your FlareSolverr API URL in Jackett?

**Comment by cherjr** [comment]
_(not a topic starter, but experiencing the same problem):_

> v3.3.20 just came out. That won't resolve anything, but just a heads up.
> 
> Remove the `LANG` and `TZ` ENVs, see if it makes a difference.
not for me

> Neither Jackett nor FlareSolverr (or the host device for that matter) are using a proxy or VPN?
not for me

> What have you used as your FlareSolverr API URL in Jackett?
in my case - local address: http://10.1.1.8:8191

**Comment by disquaw** [comment]
If I delete TZ and LANG I get a 500 error.

2024-06-22 07:04:40 INFO     192.168.1.56 POST http://192.168.1.56:8191/v1 500 Internal Server Error

No VPN or Proxy.

FlareSolverr API URL : http://192.168.1.56:8191/ 

The address is the same for Flarevolerr and Jackett.

Thanks for help !

**Comment by ilike2burnthing** [comment]
@cherjr see the troubleshooting wiki (namely, don't use a proxy or VPN on just one container).

**Comment by cherjr** [comment]
> @cherjr see the troubleshooting wiki (namely, don't use a proxy or VPN on just one container).

Silly me! Thanks, all is fine.
