### ISSUE TITLE
FreeBSD / Incorrect ChromiumDriver Version

### ISSUE THREAD

**Issue by FroggMaster** [FlareSolverr/FlareSolverr#1251]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: Don't Recall
- Operating system: FreeBSD 13.2
- Are you using Docker: [yes/no] No
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] No
- Are you using a Proxy: [yes/no] No
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue: N/A
```

### Description

Unable to launch Flaresolvver on FreeBSD 13.2. I get errors indicating that the ChromiumDriver is unsupported and only supports older versions of Chromium. However the chromiumdriver is bundled with the Chromium package on FreeBSD. 

I've also tried installing the ChromiumDriver from: https://developer.chrome.com/docs/chromedriver/downloads

### Logged Error Messages

```text
root@prowlarr:/home/frog/FlareSolverr # python3.9 src/flaresolverr.py
2024-07-07 05:49:52 INFO     FlareSolverr 3.3.21
2024-07-07 05:49:52 INFO     Testing web browser installation...
2024-07-07 05:49:52 INFO     Platform: FreeBSD-13.1-RELEASE-p9-amd64-64bit-ELF
2024-07-07 05:49:52 INFO     Chrome / Chromium path: /usr/local/bin/chrome
2024-07-07 05:49:52 INFO     Chrome / Chromium major version: 126
2024-07-07 05:49:52 INFO     Launching web browser...
2024-07-07 05:50:43 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:59882
from session not created: This version of ChromeDriver only supports Chrome version 120
Current browser version is 126.0.6478.126

Traceback (most recent call last):
  File "/home/frog/FlareSolverr/src/utils.py", line 316, in get_user_agent
    driver = get_webdriver()
  File "/home/frog/FlareSolverr/src/utils.py", line 219, in get_webdriver
    return driver
UnboundLocalError: local variable 'driver' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frog/FlareSolverr/src/flaresolverr.py", line 108, in <module>
    flaresolverr_service.test_browser_installation()
  File "/home/frog/FlareSolverr/src/flaresolverr_service.py", line 73, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "/home/frog/FlareSolverr/src/utils.py", line 322, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. local variable 'driver' referenced before assignment
```

**Comment by ilike2burnthing** [comment]
Please test earlier builds, see where the issue began. I don't have a FreeBSD machine to test this.

**Comment by Asthowen** [comment]
Hello @FroggMaster, in my opinion, it has not updated the version of chromedriver patched in `~/.undetected_chromedriver/`, would it be possible to send the contents of the file: `~/.undetected_chromedriver/version.txt`, and the return of `~/.undetected_chromedriver/chromedriver --version`. As well as the return of: `/usr/local/bin/chrome --version` and `/usr/local/bin/chromedriver --version`.

**Comment by FroggMaster** [comment]
It doesn't appear that undetected_chromdriver directory has anything within it for either my user, or root user home directory. Nor am I able to run the command you mention to check the undetected chromium driver version. 
```
root@prowlarr:~/.undetected_chromedriver # ls -l
total 0
root@prowlarr:~/.undetected_chromedriver # ls -l /home/frog/.undetected_chromedriver/
total 0
root@prowlarr:~/.undetected_chromedriver # ~/.undetected_chromedriver/chromedriver --version
/root/.undetected_chromedriver/chromedriver: Command not found.
root@prowlarr:~/.undetected_chromedriver # /home/frog/.undetected_chromedriver/chromedriver -- version
/home/frog/.undetected_chromedriver/chromedriver: Command not found.
```


```
The version of Chromium and the Chromium driver is as follows: 
root@prowlarr:~/.undetected_chromedriver # /usr/local/bin/chrome --version
Chromium 126.0.6478.126
root@prowlarr:~/.undetected_chromedriver # /usr/local/bin/chromedriver --version
ChromeDriver 126.0.6478.126 (d36ace6122e0a59570e258d82441395206d60e1c-refs/branch-heads/6478@{#1591})
```

**Comment by FroggMaster** [comment]
> Please test earlier builds, see where the issue began. I don't have a FreeBSD machine to test this.
Seems to have occurred when I updated my packages on my FreeBSD machine. I would downgrade the chromium port but it's easier said than done and requires rebuilding the entire old chromium package.

**Comment by FroggMaster** [comment]
@ilike2burnthing 

It would appear that the undetected_chromium version that is built into FlareSolverr may not have been updated to the latest version: https://github.com/FlareSolverr/FlareSolverr/commit/96fcd21174cf09086b85f3869326a8c45792680f Indicates that the version is: 3.4.6. However the latest version is 3.5.5. 

If I remove the ~/FlareSolverr/src/undetected_chromedriver folder, the application indicates that Chromium isn't installed at all, rather than tossing the error indicating that the browser is out of date. 

```
frog@prowlarr:~/FlareSolverr $ python3.9 src/flaresolverr.py
2024-07-14 00:25:04 INFO     FlareSolverr 3.3.21
2024-07-14 00:25:04 INFO     Testing web browser installation...
2024-07-14 00:25:04 INFO     Platform: FreeBSD-13.1-RELEASE-p9-amd64-64bit-ELF
2024-07-14 00:25:04 ERROR    Chrome / Chromium web browser not installed!
frog@prowlarr:~/FlareSolverr $
```

**Comment by ilike2burnthing** [comment]
That commit is from over a year ago. Current version:

https://github.com/FlareSolverr/FlareSolverr/blob/dd7eaee2e3bfa529fbc8d88434cec468eac2958c/src/undetected_chromedriver/__init__.py#L20

**Comment by FroggMaster** [comment]
> That commit is from over a year ago. Current version:
> 
> https://github.com/FlareSolverr/FlareSolverr/blob/dd7eaee2e3bfa529fbc8d88434cec468eac2958c/src/undetected_chromedriver/__init__.py#L20

My mistake, I was looking at the other files which mention the chromedriver being updated, but they link back to older commits.

**Comment by FroggMaster** [comment]
The same issue is presented when FlareSolverr is freshly installed as per the instructions in the ReadMe for FreeBSD/TrueNAS. One thing I noted was that *py39-pip* was not found as a PKG but previously omitting this package didn't prevent Flaresolverr from running. 

Here's the output from a fresh install 
```
FreeBSD 13.1-RELEASE-p9 n245429-296d095698e TRUENAS

frog@prowlarr:~ $ pip uninstall undetected_chromedriver
Found existing installation: undetected-chromedriver 3.5.5
Uninstalling undetected-chromedriver-3.5.5:
  Would remove:
    /home/frog/.local/lib/python3.9/site-packages/undetected_chromedriver-3.5.5.dist-info/*
    /home/frog/.local/lib/python3.9/site-packages/undetected_chromedriver/*
Proceed (Y/n)? y
  Successfully uninstalled undetected-chromedriver-3.5.5
frog@prowlarr:~ $ rm -rf FlareSolverr/
frog@prowlarr:~ $ su -
root@prowlarr:~ # pkg install chromium python39 py39-pip xorg-vfbserver
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'py39-pip' have been found in the repositories
root@prowlarr:~ # pkg install chromium python39  xorg-vfbserver
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed
root@prowlarr:~ # exit
logout
frog@prowlarr:~ $ git clone https://github.com/FlareSolverr/FlareSolverr.git
Cloning into 'FlareSolverr'...
remote: Enumerating objects: 1815, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1815 (delta 0), reused 3 (delta 0), pack-reused 1812
Receiving objects: 100% (1815/1815), 1.09 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (1125/1125), done.
frog@prowlarr:~ $ cd FlareSolverr/
frog@prowlarr:~/FlareSolverr $ python3.9 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Ignoring pefile: markers 'platform_system == "Windows"' don't match your environment
Requirement already satisfied: bottle==0.12.25 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.12.25)
Requirement already satisfied: waitress==2.1.2 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: selenium==4.15.2 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (4.15.2)
Requirement already satisfied: func-timeout==4.3.5 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.3.5)
Requirement already satisfied: prometheus-client==0.17.1 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.17.1)
Requirement already satisfied: requests==2.32.0 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.32.0)
Requirement already satisfied: certifi==2024.07.04 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (2024.7.4)
Requirement already satisfied: websockets==11.0.3 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (11.0.3)
Requirement already satisfied: xvfbwrapper==0.2.9 in /home/frog/.local/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (0.2.9)
Requirement already satisfied: urllib3<3,>=1.26 in /home/frog/.local/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.15.2->-r requirements.txt (line 3)) (2.2.1)
Requirement already satisfied: trio~=0.17 in /home/frog/.local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in /home/frog/.local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (0.11.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/frog/.local/lib/python3.9/site-packages (from requests==2.32.0->-r requirements.txt (line 7)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/frog/.local/lib/python3.9/site-packages (from requests==2.32.0->-r requirements.txt (line 7)) (3.6)
Requirement already satisfied: attrs>=20.1.0 in /home/frog/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (23.2.0)
Requirement already satisfied: sortedcontainers in /home/frog/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: outcome in /home/frog/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /home/frog/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: exceptiongroup in /home/frog/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /home/frog/.local/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium==4.15.2->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /home/frog/.local/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.15.2->-r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /home/frog/.local/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.15.2->-r requirements.txt (line 3)) (0.14.0)
frog@prowlarr:~/FlareSolverr $ python3.9 src/flaresolverr.py
2024-07-15 21:59:00 INFO     FlareSolverr 3.3.21
2024-07-15 21:59:00 INFO     Testing web browser installation...
2024-07-15 21:59:00 INFO     Platform: FreeBSD-13.1-RELEASE-p9-amd64-64bit-ELF
2024-07-15 21:59:00 INFO     Chrome / Chromium path: /usr/local/bin/chrome
2024-07-15 21:59:00 INFO     Chrome / Chromium major version: 126
2024-07-15 21:59:00 INFO     Launching web browser...
2024-07-15 21:59:21 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:64329
from session not created: This version of ChromeDriver only supports Chrome version 120
Current browser version is 126.0.6478.126

Traceback (most recent call last):
  File "/home/frog/FlareSolverr/src/utils.py", line 316, in get_user_agent
    driver = get_webdriver()
  File "/home/frog/FlareSolverr/src/utils.py", line 219, in get_webdriver
    return driver
UnboundLocalError: local variable 'driver' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frog/FlareSolverr/src/flaresolverr.py", line 108, in <module>
    flaresolverr_service.test_browser_installation()
  File "/home/frog/FlareSolverr/src/flaresolverr_service.py", line 73, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "/home/frog/FlareSolverr/src/utils.py", line 322, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. local variable 'driver' referenced before assignment
```

**Comment by FroggMaster** [comment]
Fixed the issue by performing the following actions: 

```
mkdir /home/flaresolverr
chmod 777 /home/flaresolverr
mkdir /app
chmod 777 /app
mkdir /.undetected_chromedriver
chmod 755 /.undetected_chromedriver
mkdir /root/.undetected_chromedriver
chmod 755 /root/.undetected_chromedriver
cp /usr/local/bin/chromedriver /app/chromedriver
chmod 777 /app/chromedriver
cp /usr/local/bin/chromedriver /app/chromedriver.exe
chmod 777 /app/chromedriver.exe
```

**Comment by FroggMaster** [comment]
Tested, and confirmed functional. That error message would have saved me a fair bit of time troubleshooting that's for sure. :)
