### ISSUE TITLE
Flaresolverr crashes as soon as you run it Windows

### ISSUE THREAD

**Issue by Digital619** [FlareSolverr/FlareSolverr#1257]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.21
- Last working FlareSolverr version: v3.3.21
- Operating system: Windows
- Are you using Docker: No
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: No
- Are you using a Proxy: No
- Are you using Captcha Solver: No
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Launching flaresolverr.exe launches a command terminal that flashes a second then exits immediately. I was able to screenshot the message that shows up but I can't find any other issues with a similar error and I can't figure out how to run the environment variables.

### Logged Error Messages

```text
I wasn't able to copy the error message as the window crashes immediately but I was able to screenshot it
```

### Screenshots

![Screenshot 2024-07-13 163124](https://github.com/user-attachments/assets/2d961e15-7e0d-48fb-a19d-bdf758abe76c)

**Comment by ilike2burnthing** [comment]
Check your AV, firewall, or other security software aren't blocking FlareSolverr.

With the FlareSolverr folder open in Windows Explorer, click the address bar, delete the path there, type `cmd` and press enter. Command Prompt will open at that directory, and you can now type `flaresolverr` and press enter. This should fail again, but you'll be able to see the error.

You can now set environment variables - https://github.com/FlareSolverr/FlareSolverr#environment-variables

Try changing `TEST_URL` to a site you can access from that device without a proxy or VPN, e.g. `https://github.com` and then run `flaresolverr` again.

If you still have issues, set `LOG_LEVEL` to `debug` and `HEADLESS` to `false`, see if that gives us any better idea of the cause of the issue.

**Comment by Digital619** [comment]
I've checked my firewall and AV and flaresolverr is allowed there. And thanks for letting me know how to change the EV. I tried setting test url to another site an setting log_level to debug and headless to false but whenever I try to run flaresolverrr I still get the same error as shown in the first post.

```
2024-07-14 22:59:47 INFO     ReqId 9208 FlareSolverr 3.3.21
2024-07-14 22:59:47 DEBUG    ReqId 9208 Debug log enabled
2024-07-14 22:59:47 INFO     ReqId 9208 Testing web browser installation...
2024-07-14 22:59:47 INFO     ReqId 9208 Platform: Windows-10-10.0.22631-SP0
2024-07-14 22:59:47 INFO     ReqId 9208 Chrome / Chromium path: C:\Users\Jayson\Documents\flaresolverr\chrome\chrome.exe
2024-07-14 22:59:47 INFO     ReqId 9208 Chrome / Chromium major version: 123
2024-07-14 22:59:47 INFO     ReqId 9208 Launching web browser...
2024-07-14 22:59:47 DEBUG    ReqId 9208 Launching web browser...
2024-07-14 22:59:47 ERROR    ReqId 9208 Error starting Chrome: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
Traceback (most recent call last):
  File "utils.py", line 316, in get_user_agent
  File "utils.py", line 203, in get_webdriver
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flaresolverr.py", line 108, in <module>
  File "flaresolverr_service.py", line 73, in test_browser_installation
  File "utils.py", line 322, in get_user_agent
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
[21884] Failed to execute script 'flaresolverr' due to unhandled exception!
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1119
