### ISSUE TITLE
FlareSolverr gets stuck with Chromium 127

### ISSUE THREAD

**Issue by paveloom** [FlareSolverr/FlareSolverr#1318]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: 3.3.21
- Operating system: NixOS
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): None
- Are you using a VPN: [yes/no] yes
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: https://github.com/paveloom/FlareSolverr/tree/chromium-127
```

### Description

FlareSolverr gets stuck at launching Chromium 127. This is most likely not an issue with FlareSolverr, but rather with [Selenium](https://github.com/SeleniumHQ/selenium) or Chromium. Still, reporting it here so that users can find it. Also, see https://github.com/NixOS/nixpkgs/issues/332776.

You can test this on commit https://github.com/paveloom/FlareSolverr/tree/fa65fcb1deed9b555a815e4812406b92cae5d0a3:

```bash
$ podman build -t flaresolverr .
$ podman run --name=flaresolverr -p 8191:8191 -e LOG_LEVEL=DEBUG --rm flaresolverr
2024-08-10 09:45:03 INFO     ReqId 139687882656640 FlareSolverr 3.3.21
2024-08-10 09:45:03 DEBUG    ReqId 139687882656640 Debug log enabled
2024-08-10 09:45:03 INFO     ReqId 139687882656640 Testing web browser installation...
2024-08-10 09:45:03 INFO     ReqId 139687882656640 Platform: Linux-6.10.2-x86_64-with-glibc2.39
2024-08-10 09:45:03 INFO     ReqId 139687882656640 Chrome / Chromium path: /bin/chromium
2024-08-10 09:45:03 INFO     ReqId 139687882656640 Chrome / Chromium major version: 127
2024-08-10 09:45:03 INFO     ReqId 139687882656640 Launching web browser...
2024-08-10 09:45:03 DEBUG    ReqId 139687882656640 Launching web browser...
2024-08-10 09:45:03 DEBUG    ReqId 139687882656640 Started executable: `/app/chromedriver` in a child process with pid: 25
```

You can reveal the error by switching to the nightly version of Selenium (with https://github.com/SeleniumHQ/selenium/pull/14354 incorporated), which is done in the latest commit on the https://github.com/paveloom/FlareSolverr/tree/chromium-127 branch:

```bash
$ podman build -t flaresolverr .
$ podman run --name=flaresolverr -p 8191:8191 -e LOG_LEVEL=DEBUG -e GLOBAL_DEFAULT_TIMEOUT=2 --rm flaresolverr
2024-08-10 09:49:28 INFO     ReqId 139832726322048 FlareSolverr 3.3.21
2024-08-10 09:49:28 DEBUG    ReqId 139832726322048 Debug log enabled
2024-08-10 09:49:28 INFO     ReqId 139832726322048 Testing web browser installation...
2024-08-10 09:49:28 INFO     ReqId 139832726322048 Platform: Linux-6.10.2-x86_64-with-glibc2.39
2024-08-10 09:49:28 INFO     ReqId 139832726322048 Chrome / Chromium path: /bin/chromium
2024-08-10 09:49:28 INFO     ReqId 139832726322048 Chrome / Chromium major version: 127
2024-08-10 09:49:28 INFO     ReqId 139832726322048 Launching web browser...
2024-08-10 09:49:28 DEBUG    ReqId 139832726322048 Launching web browser...
2024-08-10 09:49:28 DEBUG    ReqId 139832726322048 Skipping Selenium Manager; path to chrome driver specified in Service class: /app/chromedriver
2024-08-10 09:49:28 DEBUG    ReqId 139832726322048 Started executable: `/app/chromedriver` in a child process with pid: 25 using 0 to output -3
2024-08-10 09:49:41 ERROR    ReqId 139832726322048 Error starting Chrome: HTTPConnectionPool(host='localhost', port=49947): Read timed out. (read timeout=2.0)
Traceback (most recent call last):
  File "/app/utils.py", line 316, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 219, in get_webdriver
    return driver
           ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 108, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 73, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 322, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
```

### Logged Error Messages

```text
Error starting Chrome: HTTPConnectionPool(host='localhost', port=49947): Read timed out. (read timeout=2.0)
```

**Comment by Gankachi** [comment]
Running from source on win11, I had the same issue. It seemed to be fixed by disabling HEADLESS. No idea if it is a windows-only issue tho...

**Comment by paveloom** [comment]
@Gankachi Unfortunately, can't confirm that using a Podman container.

**Comment by HDoujinDownloader** [comment]
> This is most likely not an issue with FlareSolverr, but rather with [Selenium](https://github.com/SeleniumHQ/selenium)

It doesn't seem to be isolated to Selenium, because the same thing happens with Drission Page (#1300):

```
2024-08-20 22:08:29 INFO     FlareSolverr 3.3.21
2024-08-20 22:08:29 INFO     Testing web browser installation...
2024-08-20 22:08:29 INFO     Platform: Windows-10-10.0.19045-SP0
2024-08-20 22:08:29 INFO     Chrome / Chromium path: C:\Program Files\Google\Chrome\Application\chrome.exe
2024-08-20 22:08:29 INFO     Chrome / Chromium major version: 127
2024-08-20 22:08:29 INFO     Launching web browser...
Traceback (most recent call last):
  File "utils.py", line 400, in get_user_agent
  File "utils.py", line 254, in get_webdriver
  File "DrissionPage\_pages\chromium_page.py", line 65, in __init__
  File "DrissionPage\_pages\chromium_base.py", line 73, in __init__
  File "DrissionPage\_pages\chromium_base.py", line 116, in _connect_browser
  File "DrissionPage\_pages\chromium_base.py", line 137, in _driver_init
  File "DrissionPage\_pages\chromium_base.py", line 424, in run_cdp
  File "DrissionPage\_functions\tools.py", line 241, in raise_error
TimeoutError:
错误：timeout
方法：Page.getFrameTree
参数：{'_timeout': 30}
版本：4.0.5.6
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\flaresolverr.py", line 108, in <module>
    flaresolverr_service.test_browser_installation()
  File "flaresolverr_service.py", line 68, in test_browser_installation
  File "utils.py", line 406, in get_user_agent
Exception: Error getting browser User-Agent.
错误：timeout
方法：Page.getFrameTree
参数：{'_timeout': 30}
版本：4.0.5.6
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues
[38244] Failed to execute script 'flaresolverr' due to unhandled exception!
```

**Comment by ferhatcandas** [comment]
I have a temporary solution, if the base image you use in your Dockerfile automatically installs chromium 127, it would be useful to try different image versions, I was using debian:trixie-slim, when I switched to debian:bullseye-slim(stable) my chromium version went to an older version and now I have no problems.

bullseye-slim : chromium (120.0.6099.224-1~deb11u1) works
trixie-slim: chromium (127.0.6533.119-1~deb13u1) does not work

Solves the problem of Chromium 127 getting stuck on startup.
resource : https://packages.debian.org/bullseye/chromium

**Comment by FroggMaster** [comment]
I can confirm I'm running into the same issues on FreeBSD 13.1 with Chromium 127.

**Comment by FroggMaster** [comment]
I've temporarily worked around the issue on my FreeBSD system by downgrading the installed Chromium package to Chromium version 125.0.6422.141_1. I believe Chromium 126 will work as well, but I haven't had the opportunity to test it. 


Here's the instructions on how to build an older Chromium version for FreeBSD should anyone else need them. 

1. Uninstall Chromium
```
pkg remove chromium
```
2. Fetch Chromium version 125.0.6422.141_1
```
fetch https://cgit.freebsd.org/ports/snapshot/ports-21476ca8a9b5feb3485a3fa29299c0b447c90350.zip
```
3. Create a directory for the build files, extract the ZIP and navigate to the chromium directory. 
```
mkdir ChromeBuild
unzip ports-21476ca8a9b5feb3485a3fa29299c0b447c90350.zip -d ChromeBuild
cd ChromeBuild/ports-21476ca8a9b5feb3485a3fa29299c0b447c90350/www/chromium
```
4. Build Chromium and install it
```
env BATCH=yes DISABLE_VULNERABILITIES=yes MAKE_JOBS_UNSAFE=yes VERBOSE=1 make install clean
```
5. Lock the package until this is resolved to avoid accidentally updating it again. 
```
pkg lock chromium
```

**Comment by bfourgeaud** [comment]
wow building chromium 125 takes foreeeeever.
I hope that will solve the problem, it's been 2h now ^^

**Comment by hponcet** [comment]
On debian, simply do that did the trick

```
wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_\126.0.6478.182-1_amd64.deb;
sudo dpkg -i --force-all /tmp/chrome.deb;
rm /tmp/chrome.deb;
apt-mark hold google-chrome-stable;
```

**Comment by eliosh** [comment]
I have this problem:

```
2024-10-14 11:52:47 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:54086
from chrome not reachable
Stacktrace:
#0 0x0c273ad76863 <unknown>
#1 0x0c273aa6c717 <unknown>
#2 0x0c273aa577c3 <unknown>
#3 0x0c273aaa5c91 <unknown>
#4 0x0c273aa9c7bb <unknown>
#5 0x0c273aae5aed <unknown>
#6 0x0c273aad9343 <unknown>
#7 0x0c273aaaa593 <unknown>
#8 0x0c273aaaaf5e <unknown>
#9 0x0c273ad3a84b <unknown>
#10 0x0c273ad3e7a5 <unknown>
#11 0x0c273ad28571 <unknown>
#12 0x0c273ad3f332 <unknown>
#13 0x0c273ad0d87f <unknown>
#14 0x0c273ad65728 <unknown>
#15 0x0c273ad658fb <unknown>
#16 0x0c273ad759b4 <unknown>
#17 0x7979154aaac3 <unknown>

2024-10-14 11:52:47 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value

```

I am using the standalone latest version on Ubuntu 22.04

```
2024-10-14 11:54:47 INFO     FlareSolverr 3.3.21
2024-10-14 11:54:47 INFO     Testing web browser installation...
2024-10-14 11:54:47 INFO     Platform: Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-glibc2.35
2024-10-14 11:54:47 INFO     Chrome / Chromium path: /root/flaresolverr/chrome/chrome
2024-10-14 11:54:47 INFO     Chrome / Chromium major version: 123
2024-10-14 11:54:47 INFO     Launching web browser...
```

**Comment by eliosh** [comment]
My problem is easy solved: there were no more space on disk.

**Comment by Tanvir1337x** [comment]
There's a NUR package that works: https://github.com/nix-community/nur-combined/blob/master/repos/xddxdd/pkgs/uncategorized/flaresolverr-21hsmw/default.nix#L63.

`flaresolverr.package = pkgs.nur.repos.xddxdd.flaresolverr-21hsmw;`

**Comment by paveloom** [comment]
I believe the issue was fixed with https://github.com/FlareSolverr/FlareSolverr/commit/8b1851eeb16cd88063394205ba2b893090a69db9. You can test it with Docker at commit https://github.com/paveloom/FlareSolverr/commit/e36265c3047fa48a6cab159aab39e9ae9d732db3:

```console
$ git log --oneline HEAD~3..HEAD
e36265c (HEAD -> chromium-127, origin/chromium-127) Use Selenium 4.28.0.
dd801d5 Update Dockerfile to install Chromium from `unstable`.
8b1851e Fix headless=false stalling
$ docker build --progress plain -t flaresolverr .
$ docker run --rm --name flaresolverr -p 8191:8191 flaresolverr
2025-03-08 14:00:10 INFO     FlareSolverr 3.3.21
2025-03-08 14:00:10 INFO     Testing web browser installation...
2025-03-08 14:00:10 INFO     Platform: Linux-6.13.5-x86_64-with-glibc2.41
2025-03-08 14:00:10 INFO     Chrome / Chromium path: /usr/bin/chromium
2025-03-08 14:00:10 INFO     Chrome / Chromium major version: 134
2025-03-08 14:00:10 INFO     Launching web browser...
2025-03-08 14:00:11 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
2025-03-08 14:00:11 INFO     Test successful!
2025-03-08 14:00:11 INFO     Serving on http://0.0.0.0:8191
```
