### ISSUE TITLE
Test successful, but no requests get a reply. "cannot access local variable 'driver' where it is not associated with a value" (Linux AMD64 - Not Docker)

### ISSUE THREAD

**Issue by prmbittencourt** [FlareSolverr/FlareSolverr#1328]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: None
- Operating system: EndeavourOS Linux
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one: N/A
- URL to test this issue: http://www.google.com/
```

### Description

Yesterday evening I installed FlareSolverr from source by following the instructions in the README, then attempted to add it as an indexer in Prowlarr, but the test in Prowlarr's webGUI failed. I noted that FlareSolverr's own internal test had apparently succeeded, as per the terminal output. I then tried running the example bash request from the README, which also failed. Note that neither FlareSolverr nor Prowlarr are installed via Docker.

This morning I tried again and it still didn't work. After reading the issues and discussions here and Googling unsuccessfully for a solution, I ran the example code again, but this time lowering the timeout to 60 seconds, just so that I could copy the terminal output for this bug report. I decided to do this a second time, and ended up leaving FlareSolverr on for several minutes before exiting with Ctrl+C. This resulted in a different error message, even though both times it was left running for over the specified timeout duration of 60 seconds (as can be seen in the logs below by the timestamps before and after '^C').

The first time, the only output I got upon exiting was that there was still a thread running. The second time, the information I got was more useful. I have pasted both logs below, separated by a double line. Below them is the relevant bit of the Prowlarr log from running the test yesterday.

Note that while the logs below show a timeout of only 60 seconds, **the example code also failed with the timeout set to 60000 seconds as provided in the README file.** The 60-second test was only done to get the logs since I had not saved them previously.

### Logged Error Messages

```text
❯ python /opt/flaresolverr/src/flaresolverr.py
2024-08-19 10:28:32 INFO     FlareSolverr 3.3.21
2024-08-19 10:28:32 INFO     Testing web browser installation...
2024-08-19 10:28:32 INFO     Platform: Linux-6.10.5-zen1-1-zen-x86_64-with-glibc2.40
2024-08-19 10:28:32 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-08-19 10:28:32 INFO     Chrome / Chromium major version: 128
2024-08-19 10:28:32 INFO     Launching web browser...
2024-08-19 10:28:32 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
2024-08-19 10:28:32 INFO     Test successful!
2024-08-19 10:28:32 INFO     Serving on http://0.0.0.0:8191
2024-08-19 10:28:41 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'http://www.google.com/', 'maxTimeout': 60}
^C2024-08-19 10:33:44 WARNING  1 thread(s) still running

=================================================================================================

❯ python /opt/flaresolverr/src/flaresolverr.py
2024-08-19 10:38:41 INFO     FlareSolverr 3.3.21
2024-08-19 10:38:41 INFO     Testing web browser installation...
2024-08-19 10:38:41 INFO     Platform: Linux-6.10.5-zen1-1-zen-x86_64-with-glibc2.40
2024-08-19 10:38:41 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-08-19 10:38:41 INFO     Chrome / Chromium major version: 128
2024-08-19 10:38:41 INFO     Launching web browser...
2024-08-19 10:38:42 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
2024-08-19 10:38:42 INFO     Test successful!
2024-08-19 10:38:42 INFO     Serving on http://0.0.0.0:8191
2024-08-19 10:38:46 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'http://www.google.com/', 'maxTimeout': 60}
^C2024-08-19 10:46:42 ERROR    Error starting Chrome: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-08-19 10:46:42 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
2024-08-19 10:46:42 INFO     Response in 476.696 s
2024-08-19 10:46:42 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error

=================================================================================================

2024-08-18 22:22:03.8|Error|FlareSolverr|Proxy validation failed

[v1.21.2.4649] System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 170
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.Test() in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 189


2024-08-18 22:22:03.8|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to proxy: Http request timed out. Check the log surrounding this error for details
```

**Comment by FFYzz** [comment]
+1, so wired!

**Comment by ilike2burnthing** [comment]
Timeout is in ms, so the default of `60000` is 60s, whereas your `60` is 0.06s, likely breaking things.

Check out some of the PR builds, see if they resolve anything.

**Comment by ilike2burnthing** [comment]
Try the PR builds anyway, as they change a lot, and the current release is largely non-functional.

**Comment by brad-charboneau** [comment]
has anyone found a solution to this? im on the latest release and getting this same issue. If I need a PR release, can someone suggest one that solves this issue?
