### ISSUE TITLE
no module named  "charset_normalizer.md

### ISSUE THREAD

**Issue by tsg040** [FlareSolverr/FlareSolverr#1330]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.21
- Last working FlareSolverr version: none
- Operating system: win 11
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

C:\Users\Admin\Downloads\flare>flaresolverr
Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flaresolverr.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "flaresolverr_service.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "undetected_chromedriver\__init__.py", line 41, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "undetected_chromedriver\cdp.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "charset_normalizer\cd.py", line 14, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'
[21260] Failed to execute script 'flaresolverr' due to unhandled exception!

### Logged Error Messages

```text
C:\Users\Admin\Downloads\flare>flaresolverr
Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flaresolverr.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "flaresolverr_service.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "undetected_chromedriver\__init__.py", line 41, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "undetected_chromedriver\cdp.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "charset_normalizer\cd.py", line 14, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'
[21260] Failed to execute script 'flaresolverr' due to unhandled exception!
```

**Comment by ilike2burnthing** [comment]
You followed these instructions, in particular installing the requirements? https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by tsg040** [comment]
Thank you for the response.
Something went wrong with the RAR file, it did not unpack all of the files.
Now it is working !!!

Thanks again....
