### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 95 seconds elapsing. 

### ISSUE THREAD

**Issue by DaGreenX** [FlareSolverr/FlareSolverr#1371]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version:3.3.21
- Last working FlareSolverr version: 1 week ago
- Operating system: DSM 7.2.1
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] Yes
- Are you using a Proxy: [yes/no] No
- Are you using Captcha Solver: [yes/no] Yes
- If using captcha solver, which one: Harvester
- URL to test this issue:
```

### Description

unable to reactivate indexer

### Logged Error Messages

```text
Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
Challenge detected. Title found: Just a moment...
Error: Error solving the challenge. Timeout after 90.0 seconds.
Response in 96.512 s
192.168.1.44 POST http://192.168.1.44:8191/v1 500 Internal Server Error





Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 95 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException (125): Operation canceled --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async) at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of
```

**Comment by dj41ph4** [comment]
I just compiled the solution, you can find it on Docker.io:

dj41ph4/flaresolverrfix:ygg (not dj41ph4/flaresolverrfix:yggfix).

**Comment by Xav-Pe** [comment]
> I just compiled the solution, you can find it on Docker.io:
> 
> dj41ph4/flaresolverrfix:ygg .

Any diff ? Without PR we don't know what you edited in the code, it could be malicious.

**Comment by iPAL45-80** [comment]
cette solution ne fonctionne pas de toute manière (ou plus actuellement)

**Comment by 21hsmw** [comment]
> > > I just compiled the solution, you can find it on Docker.io:
> > > dj41ph4/flaresolverrfix:ygg .
> > 
> > 
> > Any diff ? Without PR we don't know what you edited in the code, it could be malicious.
> 
> I want to clarify that I didn’t make a Pull Request because I’m not really into GitHub. Usually, I just make modifications for myself, to fix things for my own use. This time, I shared my modification to help others, nothing more. I understand it might seem suspicious to some, but that wasn’t my intention. #1370 Honestly, I have better things to do than justify myself. If you’re not interested in my solution, feel free to look for another one elsewhere.
> 
> Best of luck.

You are using my branch for your image, no changes have been made by yourself.
People should stay away from it, it might contain malicious code. The user claiming the code is his own could lead to that conclusion.

For anyone looking for the code, check out my message here: https://github.com/FlareSolverr/FlareSolverr/pull/1163#issuecomment-2308926030

**Comment by DaGreenX** [comment]
thx @21hsmw. did you identified the issue yet ?

**Comment by 21hsmw** [comment]
> thx @21hsmw. did you identified the issue yet ?

The main branch has been a hit and miss for a few months now.
Have you tried my image? If it doesn't work, can you provide debug logs and your compose file in this PR? https://github.com/FlareSolverr/FlareSolverr/pull/1163

**Comment by DaGreenX** [comment]
@21hsmw : No, I haven’t tried yet, I’ve stayed on the main branch. Indeed, it hasn’t moved for several months.
I will try using your version and get back to you.

**Comment by DaGreenX** [comment]
ok @21hsmw . Okay, I chose ‘FixLoopping’. Is that correct? The test fails with the following logs :

**Jackett :** 
Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.

[v0.22.688.0] Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1550
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26


**FlareSolver :** 

024/09/29 19:08:11 | stdout | 2024-09-29 17:08:11 INFO     192.168.1.44 POST http://192.168.1.44:8191/v1 500 Internal Server Error
-- | -- | --
2024/09/29 19:08:11 | stdout | 2024-09-29 17:08:11 INFO     Response in 92.167 s
2024/09/29 19:08:11 | stdout | 2024-09-29 17:08:11 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
2024/09/29 19:06:49 | stdout | 2024-09-29 17:06:49 INFO     Challenge detected. Title found: Just a moment...
2024/09/29 19:06:39 | stdout | 2024-09-29 17:06:39 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
2024/09/29 19:06:13 | stdout | 2024-09-29 17:06:13 INFO     Serving on http://0.0.0.0:8191
2024/09/29 19:06:12 | stdout | 2024-09-29 17:06:12 INFO     Test successful!
2024/09/29 19:06:12 | stdout | 2024-09-29 17:06:12 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
2024/09/29 19:06:02 | stdout | 2024-09-29 17:06:02 INFO     Launching web browser...
2024/09/29 19:06:02 | stdout | 2024-09-29 17:06:02 INFO     Chrome / Chromium major version: 126
2024/09/29 19:05:58 | stdout | 2024-09-29 17:05:58 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/09/29 19:05:58 | stdout | 2024-09-29 17:05:58 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.36
2024/09/29 19:05:58 | stdout | 2024-09-29 17:05:57 INFO     Testing web browser installation...
2024/09/29 19:05:57 | stdout | 2024-09-29 17:05:57 INFO     FlareSolverr 3.3.19

**Comment by 21hsmw** [comment]
> Okay, I chose ‘FixLoopping’. Is that correct?

It was my previous fix, which is no longer maintained. The one you need to try is `21hsmw/flaresolverr:nodriver`

**Comment by DaGreenX** [comment]
@21hsmw : My god, it works! You’re a rock star, mate!

**Comment by PandeoF1** [comment]
> It was my previous fix, which is no longer maintained. The one you need to try is `21hsmw/flaresolverr:nodriver`

Work for me, thx you @21hsmw

**Comment by DaGreenX** [comment]
@21hsmw : Does this mean that the main branch is abandoned?

**Comment by 21hsmw** [comment]
> @21hsmw : Does this mean that the main branch is abandoned?

I would say it's stale at the moment. A proper solution needs to be found, but the main developer behind the project is not around to make the decision. So for now we have to stay as we are and hope that something will happen soon.

**Comment by imadhy** [comment]
> It was my previous fix, which is no longer maintained. The one you need to try is 21hsmw/flaresolverr:nodriver

@21hsmw does it need the variable DRIVER:nodriver ?

**Comment by DaGreenX** [comment]
Anyway, thank you very much for your help :)

**Comment by 21hsmw** [comment]
> > It was my previous fix, which is no longer maintained. The one you need to try is 21hsmw/flaresolverr:nodriver
> 
> @21hsmw does it need the variable DRIVER:nodriver ?

It was needed before, but it's not necessary now. I recently switched to nodriver by default.

**Comment by imadhy** [comment]
@DaGreenX did it work for you ? I'm having challenge not detected :

```
2024-09-29 18:17:26 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login', 'proxy': {}}

2024-09-29 18:17:38 INFO     Challenge not detected!

2024-09-29 18:17:38 INFO     Response in 11.75 s

2024-09-29 18:17:38 INFO     172.17.0.1 POST http://192.168.1.76:8191/v1 200 OK
```

**Comment by PonyWarrior** [comment]
Is there any working fix?

**Comment by DaGreenX** [comment]
@imadhy yep. did you set the parameters ?

**Comment by LinSN** [comment]
Thanks @21hsmw for the docker image
I use your image (21hsmw/flaresolverr:nodriver) but I have this weird error that I don't understand

`2024-09-29 20:27:08 ERROR    Error creating Chrome Browser: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
2024-09-29 20:27:08 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value`

I don't have that issue on the main branch of flaresolver (but it doesn't work with yggtorrent of course)
