### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs.

### ISSUE THREAD

**Issue by DaGreenX** [FlareSolverr/FlareSolverr#1375]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

@21hsmw : hey it's me again ;) - #1371 - Down again Timeout and Error 500. I put the log below

### Logged Error Messages

```text
Jackett :
ackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.

[v0.22.694.0] Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1550
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26




Flare :
2024/09/30 17:16:17	stdout	2024-09-30 15:16:17 INFO     192.168.1.44 POST http://192.168.1.44:8191/v1 500 Internal Server Error
2024/09/30 17:16:17	stdout	2024-09-30 15:16:17 INFO     Response in 93.508 s
2024/09/30 17:16:17	stdout	2024-09-30 15:16:17 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
2024/09/30 17:14:56	stdout	2024-09-30 15:14:56 INFO     Challenge detected. Title found: Just a moment...
2024/09/30 17:14:44	stdout	2024-09-30 15:14:44 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
```

**Comment by DaGreenX** [comment]
works now with DRIVER:nodriver

**Comment by PonyWarrior** [comment]
> works now with DRIVER:nodriver

What do you mean? How do you use that?

**Comment by DaGreenX** [comment]
@PonyWarrior : Here are the parameters in my Docker.

<img width="487" alt="image" src="https://github.com/user-attachments/assets/012640d0-3cec-4d55-9274-becfb9f6d78f">

**Comment by bibiwan** [comment]
> But i don't know why sometime you can have the error : ` Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value` And when that happens the container can have lots of child processes which are never closed. It crashed my NAS 😭

I have the same error, on a Synology, using the nodriver environment parameter. I stopped using flaresolverr for now until a solution appears.

**Comment by PonyWarrior** [comment]
> > But i don't know why sometime you can have the error : ` Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value` And when that happens the container can have lots of child processes which are never closed. It crashed my NAS 😭
> 
> I have the same error, on a Synology, using the nodriver environment parameter. I stopped using flaresolverr for now until a solution appears.

Do you have a working alternative?

**Comment by n1nj444** [comment]
Same problem for me

From prowlarr & jackett : 
```

2024/10/04 19:24:15	stdout	2024-10-04 17:24:15 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024/10/04 19:23:25	stdout	2024-10-04 17:23:25 INFO     Challenge detected. Title found: Just a moment...
2024/10/04 19:23:14	stdout	2024-10-04 17:23:14 INFO     192.168.1.18 POST http://192.168.1.18:8191/v1 500 Internal Server Error
2024/10/04 19:23:14	stdout	2024-10-04 17:23:14 INFO     Response in 68.862 s
2024/10/04 19:23:14	stdout	2024-10-04 17:23:14 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024/10/04 19:23:09	stdout	2024-10-04 17:23:09 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024/10/04 19:23:06	stdout	2024-10-04 17:23:06 INFO     192.168.1.18 POST http://192.168.1.18:8191/v1 500 Internal Server Error
2024/10/04 19:23:06	stdout	2024-10-04 17:23:06 INFO     Response in 63.112 s
2024/10/04 19:23:06	stdout	2024-10-04 17:23:06 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds. 
```
