### ISSUE TITLE
Server is not running and INFO doesn't progress past "Launching web browser..." 

### ISSUE THREAD

**Issue by 101Dude** [FlareSolverr/FlareSolverr#1384]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version:
- Operating system:  macOS-15.0.1-x86_64-i386-64bit
- Are you using Docker:  no
- FlareSolverr User-Agent (see log traces or / endpoint): 
- Are you using a VPN: no
- Are you using a Proxy:  no
- Are you using Captcha Solver:
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

FlareSolverr is launching Chrome processes but they are running at 100% cpu (fans are at top speed) and I "can't connect to the FlareSolverr server" web page.

Terminal shows this only until I kill the command...
```
08:10:04.533 localhost ~/GitHub/FlareSolverr  master 
➜ python src/flaresolverr.py
2024-10-08 08:10:07 INFO     FlareSolverr 3.3.21
2024-10-08 08:10:07 INFO     Testing web browser installation...
2024-10-08 08:10:07 INFO     Platform: macOS-15.0.1-x86_64-i386-64bit
2024-10-08 08:10:07 INFO     Chrome / Chromium path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
2024-10-08 08:10:07 INFO     Chrome / Chromium major version: 129
2024-10-08 08:10:07 INFO     Launching web browser...
```
from Activity Monitor.app
```
15783	 Google Chrome Helper (Renderer)	100.0
15782	 Google Chrome Helper (Renderer)	100.0
15786	 Google Chrome Helper (GPU)	17.8	
```

python requirements
```
08:22:32.032 localhost ~/GitHub/FlareSolverr  master 1m 56.7s 
➜ pip list
Package            Version
------------------ -----------
attrs              24.2.0
bottle             0.12.25
certifi            2024.7.4
charset-normalizer 3.3.2
func_timeout       4.3.5
h11                0.14.0
idna               3.10
outcome            1.3.0.post0
pip                24.0
prometheus-client  0.17.1
PySocks            1.7.1
requests           2.32.3
selenium           4.15.2
setuptools         65.5.0
sniffio            1.3.1
sortedcontainers   2.4.0
trio               0.26.2
trio-websocket     0.11.1
urllib3            2.2.3
waitress           2.1.2
websockets         11.0.3
wsproto            1.2.0
xvfbwrapper        0.2.9
```

### Logged Error Messages

```text
No Logs in logfiles

Terminal output Once I kill the process...

08:10:04.533 localhost ~/GitHub/FlareSolverr  master 
➜ python src/flaresolverr.py
2024-10-08 08:10:07 INFO     FlareSolverr 3.3.21
2024-10-08 08:10:07 INFO     Testing web browser installation...
2024-10-08 08:10:07 INFO     Platform: macOS-15.0.1-x86_64-i386-64bit
2024-10-08 08:10:07 INFO     Chrome / Chromium path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
2024-10-08 08:10:07 INFO     Chrome / Chromium major version: 129
2024-10-08 08:10:07 INFO     Launching web browser...
^CTraceback (most recent call last):
  File "/Users/john/GitHub/FlareSolverr/src/flaresolverr.py", line 108, in <module>
    flaresolverr_service.test_browser_installation()
  File "/Users/john/GitHub/FlareSolverr/src/flaresolverr_service.py", line 73, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/GitHub/FlareSolverr/src/utils.py", line 316, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/Users/john/GitHub/FlareSolverr/src/utils.py", line 195, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/GitHub/FlareSolverr/src/undetected_chromedriver/__init__.py", line 474, in __init__
    super(Chrome, self).__init__(
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/Users/john/GitHub/FlareSolverr/src/undetected_chromedriver/__init__.py", line 732, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 300, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 321, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/.pyenv/versions/3.11.10/lib/python3.11/socket.py", line 718, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```
```


### Screenshots

![Screenshot 2024-10-08 at 8 18 18 AM](https://github.com/user-attachments/assets/d5a37a42-2d0e-4ade-8838-a2c65244b129)

**Comment by ilike2burnthing** [comment]
Try this fork instead - https://github.com/21hsmw/FlareSolverr/tree/nodriver-support

**Comment by 101Dude** [comment]
I assumed I should choose the `DRIVER=nodriver` option?

Upon attempting to add my private tracker, before even entering my credentials, a Chrome window opened for the tracker page asking to solve a cloudflare question. I completed the puzzle, the window disappeared, and I was able to fill in my credentials in jackett for the tracker. Seems to be working now. EXCEPT the tracker webpage windows are opening in the foreground as they did earlier this year/late last year... _at least one of them did and not the one I had just added_. I am assuming FlareSolverr is caching.

This is promising...
```
{"msg": "FlareSolverr is ready!", "version": "3.4.0", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"}
```

I noticed this exact warning on the normal Flaresolverr install as well:
```
/Users/john/GitHub/FlareSolverr/src/utils.py:434: SyntaxWarning: invalid escape sequence '\d'
  pattern = '\d+\.\d+\.\d+\.\d+'
```

Terminal  output while flaresolverr is starting up and running.
```
07:24:18.168 localhost ~/GitHub/FlareSolverr  nodriver-support 2.9s 
➜ python src/flaresolverr.py
/Users/john/GitHub/FlareSolverr/src/utils.py:434: SyntaxWarning: invalid escape sequence '\d'
  pattern = '\d+\.\d+\.\d+\.\d+'
2024-10-09 07:24:33 INFO     FlareSolverr 3.4.0
2024-10-09 07:24:33 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-10-09 07:24:33 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-10-09 07:24:33 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-10-09 07:24:33 INFO     Testing web browser installation...
2024-10-09 07:24:33 INFO     Platform: macOS-15.0.1-x86_64-i386-64bit
2024-10-09 07:24:33 INFO     Chrome / Chromium path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
2024-10-09 07:24:33 INFO     Chrome / Chromium major version: 129
2024-10-09 07:24:33 INFO     Launching web browser...
2024-10-09 07:24:33 INFO     Launching web browser...
2024-10-09 07:24:40 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
2024-10-09 07:24:40 INFO     Test successful!
2024-10-09 07:24:40 INFO     Serving on http://0.0.0.0:8191
2024-10-09 07:24:40 WARNING  Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 60846 is closed
2024-10-09 07:25:09 INFO     127.0.0.1 GET http://localhost:8191/ 200 OK
2024-10-09 07:25:09 WARNING  unhandled incoming priority event
2024-10-09 07:25:09 WARNING  unhandled incoming priority event
2024-10-09 07:26:46 INFO     127.0.0.1 GET http://localhost:8191/ 200 OK
2024-10-09 07:26:46 WARNING  unhandled incoming priority event
```

FYI jackett doesn't like `0.0.0.0`
[log.log](https://github.com/user-attachments/files/17308217/log.log)

```
07:37:54.628 localhost ~/GitHub/FlareSolverr  nodriver-support 13m 21.9s 
➜ HOST=127.0.0.1

07:38:07.851 127.0.0.1 ~/GitHub/FlareSolverr  nodriver-support 
➜ python src/flaresolverr.py
2024-10-09 07:38:12 INFO     FlareSolverr 3.4.0
2024-10-09 07:38:12 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-10-09 07:38:12 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-10-09 07:38:12 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-10-09 07:38:12 INFO     Testing web browser installation...
2024-10-09 07:38:12 INFO     Platform: macOS-15.0.1-x86_64-i386-64bit
2024-10-09 07:38:12 INFO     Chrome / Chromium path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
2024-10-09 07:38:12 INFO     Chrome / Chromium major version: 129
2024-10-09 07:38:12 INFO     Launching web browser...
2024-10-09 07:38:12 INFO     Launching web browser...
2024-10-09 07:38:18 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
2024-10-09 07:38:18 INFO     Test successful!
2024-10-09 07:38:18 WARNING  Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 63263 is closed
2024-10-09 07:38:18 INFO     Serving on http://0.0.0.0:8191
```
changing to  `HOST=127.0.0.1` didn't seem to make it use `127.0.0.1` but changing the address in the browser afterwards to `127.0.0.1` did.

In case anyone reads this be aware not to use `https://127.0.0.1` but `http://127.0.0.1` in jackett for FlareSolverr API URL

FYI when I refresh the webpage for the server or even open one up I get a warning.
```
2024-10-09 07:29:04 INFO     127.0.0.1 GET http://localhost:8191/ 200 OK
2024-10-09 07:29:04 WARNING  unhandled incoming priority event
```

**Comment by jmsprsns** [comment]
Im having the exact same issue with the Windows binary. Worked fine for months, suddenly broken. most likely a Cloudflare update and the devs need to update the binary. I'm assuming it's quite a bit behind on the regular updates that the Docker folks get.

**Comment by 101Dude** [comment]
@jmsprsns 

Actually it's running fine for me now on macOS.

**Comment by ilike2burnthing** [comment]
@101Dude use 127.0.0.1 in Jackett, seeing 0.0.0.0 in the logs is fine.

@jmsprsns use the fork linked above.
