### ISSUE TITLE
[yggtorrent] (updating) The operation was canceled.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 70.0 seconds.

### ISSUE THREAD

**Issue by Rurtzane** [FlareSolverr/FlareSolverr#1388]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

yes

### Environment

```markdown
- FlareSolverr version: v3.3.21
- Last working FlareSolverr version: v3.3.21
- Operating system: linux/arm64/v8
- Are you using Docker: yes with docker compose
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no 
- If using captcha solver, which one:
- URL to test this issue: https://www.ygg.re/auth/login
```

### Description

I use Sonarr with Jackett and Flaresolver to download from this site, but it hasn't been working for the past two days.

### Logged Error Messages

```text
2024-10-14 22:10:20 INFO     Launching web browser...
2024-10-14 22:10:48 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-10-14 22:10:48 INFO     Test successful!
2024-10-14 22:10:49 INFO     Serving on http://0.0.0.0:8191
2024-10-14 22:12:12 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
2024-10-14 22:12:25 INFO     Challenge detected. Title found: Just a moment...
2024-10-14 22:13:27 ERROR    Error: Error solving the challenge. Timeout after 70.0 seconds.
2024-10-14 22:13:27 INFO     Response in 75.15 s
```

**Comment by groot-stuff** [comment]
Same issue using binhex/arch-flaresolverr container on Unraid

- FlareSolverr version: v3.3.21
- Last working FlareSolverr version: v3.3.21
- Operating system: linux
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no 
- If using captcha solver, which one:
- URL to test this issue:

**Comment by Rurtzane** [comment]
I'm using the architecture linux/arm64/v8, which is not compatible. Still, thank you very much for your help!

**Comment by Telkaoss** [comment]
`image: 21hsmw/flaresolverr:nodriver
`

work

**Comment by cuebit** [comment]
Duplicate #1253

**Comment by Rurtzane** [comment]
the "21hsmw/flaresolverr:nodriver"  not work for me :/ 

```
2024-10-17 16:47:21 INFO     FlareSolverr 3.4.0
2024-10-17 16:47:21 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-10-17 16:47:21 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-10-17 16:47:21 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-10-17 16:47:21 INFO     Testing web browser installation...
2024-10-17 16:47:21 INFO     Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.36
2024-10-17 16:47:21 INFO     Chrome / Chromium path: /bin/chromium
2024-10-17 16:47:22 INFO     Chrome / Chromium major version: 129
2024-10-17 16:47:22 INFO     Launching web browser...
2024-10-17 16:47:22 INFO     Launching web browser...
2024-10-17 16:47:25 ERROR    Error creating Chrome Browser: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 125, in <module>
    asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
    user_agent = await utils.get_user_agent_nd()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 456, in get_user_agent_nd
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
Traceback (most recent call last):
  File "/app/utils.py", line 450, in get_user_agent_nd
    driver = await get_webdriver_nd()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 252, in get_webdriver_nd
    return driver
           ^^^^^^
2024-10-17 16:47:38 INFO     FlareSolverr 3.4.0
2024-10-17 16:47:38 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-10-17 16:47:38 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-10-17 16:47:38 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-10-17 16:47:38 INFO     Testing web browser installation...
2024-10-17 16:47:38 INFO     Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.36
2024-10-17 16:47:38 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-10-17 16:47:38 INFO     Chrome / Chromium major version: 129
2024-10-17 16:47:38 INFO     Launching web browser...
2024-10-17 16:47:38 INFO     Launching web browser...
2024-10-17 16:47:40 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
2024-10-17 16:47:40 INFO     Test successful!
2024-10-17 16:47:40 INFO     Serving on http://0.0.0.0:8191
2024-10-17 16:48:19 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
2024-10-17 16:48:22 ERROR    Error creating Chrome Browser: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
2024-10-17 16:48:22 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
2024-10-17 16:48:22 INFO     Response in 2.851 s
2024-10-17 16:48:22 INFO     172.19.0.6 POST http://flaresolverr:8191/v1 500 Internal Server Error
2024-10-17 16:48:47 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
2024-10-17 16:48:50 ERROR    Error creating Chrome Browser: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
2024-10-17 16:48:50 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
2024-10-17 16:48:50 INFO     Response in 2.855 s
2024-10-17 16:48:50 INFO     172.19.0.6 POST http://flaresolverr:8191/v1 500 Internal Server Error
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 125, in <module>
    asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
    user_agent = await utils.get_user_agent_nd()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 456, in get_user_agent_nd
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
```

**Comment by danny66900** [comment]
> Thank you for this response. The "21hsmw/flaresolverr:nodriver" not work for me :/
> 
> ```
> 2024-10-17 16:47:21 INFO     FlareSolverr 3.4.0
> 2024-10-17 16:47:21 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
> 2024-10-17 16:47:21 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
> 2024-10-17 16:47:21 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
> 2024-10-17 16:47:21 INFO     Testing web browser installation...
> 2024-10-17 16:47:21 INFO     Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.36
> 2024-10-17 16:47:21 INFO     Chrome / Chromium path: /bin/chromium
> 2024-10-17 16:47:22 INFO     Chrome / Chromium major version: 129
> 2024-10-17 16:47:22 INFO     Launching web browser...
> 2024-10-17 16:47:22 INFO     Launching web browser...
> 2024-10-17 16:47:25 ERROR    Error creating Chrome Browser: 
>                 ---------------------
>                 Failed to connect to browser
>                 ---------------------
>                 One of the causes could be when you are running as root.
>                 In that case you need to pass no_sandbox=True 
>                 
> 
> Traceback (most recent call last):
>   File "/app/flaresolverr.py", line 125, in <module>
>     asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
>   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
>     user_agent = await utils.get_user_agent_nd()
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/utils.py", line 456, in get_user_agent_nd
>     raise Exception("Error getting browser User-Agent. " + str(e))
> Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
> Traceback (most recent call last):
>   File "/app/utils.py", line 450, in get_user_agent_nd
>     driver = await get_webdriver_nd()
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/utils.py", line 252, in get_webdriver_nd
>     return driver
>            ^^^^^^
> 2024-10-17 16:47:38 INFO     FlareSolverr 3.4.0
> 2024-10-17 16:47:38 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
> 2024-10-17 16:47:38 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
> 2024-10-17 16:47:38 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
> 2024-10-17 16:47:38 INFO     Testing web browser installation...
> 2024-10-17 16:47:38 INFO     Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.36
> 2024-10-17 16:47:38 INFO     Chrome / Chromium path: /usr/bin/chromium
> 2024-10-17 16:47:38 INFO     Chrome / Chromium major version: 129
> 2024-10-17 16:47:38 INFO     Launching web browser...
> 2024-10-17 16:47:38 INFO     Launching web browser...
> 2024-10-17 16:47:40 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
> 2024-10-17 16:47:40 INFO     Test successful!
> 2024-10-17 16:47:40 INFO     Serving on http://0.0.0.0:8191
> 2024-10-17 16:48:19 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
> 2024-10-17 16:48:22 ERROR    Error creating Chrome Browser: 
>                 ---------------------
>                 Failed to connect to browser
>                 ---------------------
>                 One of the causes could be when you are running as root.
>                 In that case you need to pass no_sandbox=True 
>                 
> 2024-10-17 16:48:22 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
> 2024-10-17 16:48:22 INFO     Response in 2.851 s
> 2024-10-17 16:48:22 INFO     172.19.0.6 POST http://flaresolverr:8191/v1 500 Internal Server Error
> 2024-10-17 16:48:47 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
> 2024-10-17 16:48:50 ERROR    Error creating Chrome Browser: 
>                 ---------------------
>                 Failed to connect to browser
>                 ---------------------
>                 One of the causes could be when you are running as root.
>                 In that case you need to pass no_sandbox=True 
>                 
> 2024-10-17 16:48:50 ERROR    Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value
> 2024-10-17 16:48:50 INFO     Response in 2.855 s
> 2024-10-17 16:48:50 INFO     172.19.0.6 POST http://flaresolverr:8191/v1 500 Internal Server Error
> UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/flaresolverr.py", line 125, in <module>
>     asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
>   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
>     user_agent = await utils.get_user_agent_nd()
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/utils.py", line 456, in get_user_agent_nd
>     raise Exception("Error getting browser User-Agent. " + str(e))
> Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
> ```

By reading the error message 

One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Try to add a variable named no_sandbox with the value True and see what happen

**Comment by Rurtzane** [comment]
It works, thank you !!

```
  flaresolverr:
    container_name: flaresolverr
    restart: unless-stopped
    image: 21hsmw/flaresolverr:nodriver
    environment:
      - TZ=Europe/Paris
      - no_sandbox=true
    ports:
      - 8191:8191
```

**Comment by Guesh1337** [comment]
Thanks @danny66900 it worked for me too.

**Comment by Brainwasher06** [comment]
21hsmw/flaresolverr:nodriver works for me as well on uraid

Let see how long it will stay that way

**Comment by vgelly** [comment]
Hi everyone,

I've tried the solution on my side too, but it doesn't seems to help.

Here is what i got : 
2024-10-22 13:14:30 INFO     FlareSolverr 3.4.0
2024-10-22 13:14:30 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-10-22 13:14:30 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-10-22 13:14:30 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-10-22 13:14:30 INFO     Testing web browser installation...
2024-10-22 13:14:31 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.36
2024-10-22 13:14:31 INFO     Chrome / Chromium path: /bin/chromium
2024-10-22 13:15:00 INFO     Chrome / Chromium major version: 129
2024-10-22 13:15:00 INFO     Launching web browser...
2024-10-22 13:15:00 INFO     Launching web browser...
2024-10-22 13:15:05 ERROR    Error creating Chrome Browser:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Traceback (most recent call last):
  File "/app/utils.py", line 450, in get_user_agent_nd
    driver = await get_webdriver_nd()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 252, in get_webdriver_nd
    return driver
           ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 125, in <module>
    asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
    user_agent = await utils.get_user_agent_nd()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 456, in get_user_agent_nd
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
2024-10-22 13:15:05 WARNING  Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 24 is closed


The strange thing is related to the env' variable. I've added those one in the Synology part (yes, i'm not on a direct Docker, i hope it's not related to that).
Thanks in advance if you have an idea !
![2024-10-22_13h27_35](https://github.com/user-attachments/assets/2978b2be-70e3-4477-874b-2dad160a331d)

**Comment by PTD-PREY** [comment]
> Hi everyone,
> 
> I've tried the solution on my side too, but it doesn't seems to help.
> 
> Here is what i got : 2024-10-22 13:14:30 INFO FlareSolverr 3.4.0 2024-10-22 13:14:30 INFO WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS. 2024-10-22 13:14:30 INFO WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK: 2024-10-22 13:14:30 INFO WARNING: #1163 2024-10-22 13:14:30 INFO Testing web browser installation... 2024-10-22 13:14:31 INFO Platform: Linux-4.4.302+-x86_64-with-glibc2.36 2024-10-22 13:14:31 INFO Chrome / Chromium path: /bin/chromium 2024-10-22 13:15:00 INFO Chrome / Chromium major version: 129 2024-10-22 13:15:00 INFO Launching web browser... 2024-10-22 13:15:00 INFO Launching web browser... 2024-10-22 13:15:05 ERROR Error creating Chrome Browser: --------------------- Failed to connect to browser --------------------- One of the causes could be when you are running as root. In that case you need to pass no_sandbox=True
> 
> Traceback (most recent call last): File "/app/utils.py", line 450, in get_user_agent_nd driver = await get_webdriver_nd() ^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/utils.py", line 252, in get_webdriver_nd return driver ^^^^^^ UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/app/flaresolverr.py", line 125, in asyncio.run(flaresolverr_service_nd.test_browser_installation_nd()) File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd user_agent = await utils.get_user_agent_nd() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/utils.py", line 456, in get_user_agent_nd raise Exception("Error getting browser User-Agent. " + str(e)) Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value 2024-10-22 13:15:05 WARNING Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 24 is closed
> 
> The strange thing is related to the env' variable. I've added those one in the Synology part (yes, i'm not on a direct Docker, i hope it's not related to that). Thanks in advance if you have an idea ! ![2024-10-22_13h27_35](https://private-user-images.githubusercontent.com/6535019/378818761-2978b2be-70e3-4477-874b-2dad160a331d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Nzk3NDMsIm5iZiI6MTcyOTY3OTQ0MywicGF0aCI6Ii82NTM1MDE5LzM3ODgxODc2MS0yOTc4YjJiZS03MGUzLTQ0NzctODc0Yi0yZGFkMTYwYTMzMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTAzMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFhYWY2N2I1NDRmOWIxZDUzOTU2MmNhOGUwZTllMTgyNTNlNWNlZmI4ODc1MjU3ZDQxYmI2MjlkYmMxM2VmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SuaZhgL_Lgz3i8Ha78OVV1GLzjqMqwIHA8IALL1NV68)

You need DRIVER = nodriver as an env variable too.

(sadly it is quite buggy running the python file as I can't run it on Docker)

**Comment by vgelly** [comment]
> > Hi everyone,
> > I've tried the solution on my side too, but it doesn't seems to help.
> > Here is what i got : 2024-10-22 13:14:30 INFO FlareSolverr 3.4.0 2024-10-22 13:14:30 INFO WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS. 2024-10-22 13:14:30 INFO WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK: 2024-10-22 13:14:30 INFO WARNING: #1163 2024-10-22 13:14:30 INFO Testing web browser installation... 2024-10-22 13:14:31 INFO Platform: Linux-4.4.302+-x86_64-with-glibc2.36 2024-10-22 13:14:31 INFO Chrome / Chromium path: /bin/chromium 2024-10-22 13:15:00 INFO Chrome / Chromium major version: 129 2024-10-22 13:15:00 INFO Launching web browser... 2024-10-22 13:15:00 INFO Launching web browser... 2024-10-22 13:15:05 ERROR Error creating Chrome Browser: --------------------- Failed to connect to browser --------------------- One of the causes could be when you are running as root. In that case you need to pass no_sandbox=True
> > Traceback (most recent call last): File "/app/utils.py", line 450, in get_user_agent_nd driver = await get_webdriver_nd() ^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/utils.py", line 252, in get_webdriver_nd return driver ^^^^^^ UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/app/flaresolverr.py", line 125, in asyncio.run(flaresolverr_service_nd.test_browser_installation_nd()) File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd user_agent = await utils.get_user_agent_nd() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/utils.py", line 456, in get_user_agent_nd raise Exception("Error getting browser User-Agent. " + str(e)) Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value 2024-10-22 13:15:05 WARNING Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 24 is closed
> > The strange thing is related to the env' variable. I've added those one in the Synology part (yes, i'm not on a direct Docker, i hope it's not related to that). Thanks in advance if you have an idea ! ![2024-10-22_13h27_35](https://private-user-images.githubusercontent.com/6535019/378818761-2978b2be-70e3-4477-874b-2dad160a331d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Nzk3NDMsIm5iZiI6MTcyOTY3OTQ0MywicGF0aCI6Ii82NTM1MDE5LzM3ODgxODc2MS0yOTc4YjJiZS03MGUzLTQ0NzctODc0Yi0yZGFkMTYwYTMzMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTAzMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFhYWY2N2I1NDRmOWIxZDUzOTU2MmNhOGUwZTllMTgyNTNlNWNlZmI4ODc1MjU3ZDQxYmI2MjlkYmMxM2VmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SuaZhgL_Lgz3i8Ha78OVV1GLzjqMqwIHA8IALL1NV68)
> 
> You need DRIVER = nodriver as an env variable too.
> 
> (sadly it is quite buggy running the python file as I can't run it on Docker)

Seems to be the same :/

2024-10-23 17:05:16 INFO     FlareSolverr 3.4.0
2024-10-23 17:05:16 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-10-23 17:05:16 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-10-23 17:05:16 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-10-23 17:05:16 INFO     Testing web browser installation...
2024-10-23 17:05:16 INFO     Platform: Linux-4.4.302+-x86_64-with-glibc2.36
2024-10-23 17:05:16 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-10-23 17:05:22 INFO     Chrome / Chromium major version: 129
2024-10-23 17:05:22 INFO     Launching web browser...
2024-10-23 17:05:22 INFO     Launching web browser...
2024-10-23 17:05:26 ERROR    Error creating Chrome Browser:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Traceback (most recent call last):
  File "/app/utils.py", line 450, in get_user_agent_nd
    driver = await get_webdriver_nd()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 252, in get_webdriver_nd
    return driver
           ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 125, in <module>
    asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
    user_agent = await utils.get_user_agent_nd()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 456, in get_user_agent_nd
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value



Is that possible that the variable set (in the capture) are not applied ?

**Comment by overthetop78** [comment]
I have an issue with this image ( 21hsmw/flaresolverr:nodriver ) and Prowlarr. I have to 'test the indexers' every time to unlock Cloudflare with FlareSolverr for a short period.

Does anyone know what’s going wrong? I’m using the image with Docker (I haven’t used docker-compose).

**Comment by MaskDD** [comment]
Hello, Same problem here. Have added no_sandbox=true and the path of chrome but it only work for 3-4 hours and i get the same error 500.

**Comment by cuebit** [comment]
Could you please take issues, comments, etc, regarding another repository, to that repository please?
