### ISSUE TITLE
issue with new version 1.2.6

### ISSUE THREAD

**Issue by xcybermanx** [FlareSolverr/FlareSolverr#141]
hello i install new version but i see this error message with old Version 1.2. Work Great

2021-05-31T16:34:49+02:00 INFO FlareSolverr v1.2.6
2021-05-31T16:34:49+02:00 ERROR Error starting Chrome browser. Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/home2/software/FlareSolverr/node_modules/puppeteer/lib/Launcher.js:59:23)
    at async PuppeteerExtra.launch (/home2//software/FlareSolverr/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)
    at async Object.create (/home2/software/FlareSolverr/dist/session.js:49:27)
    at async testChromeInstallation (/home2/software/FlareSolverr/dist/index.js:43:21)
gxvood@server1773:~/software/FlareSolverr$

FlareSolverr 1.2.5 Work

FlareSolverr0$ npm start

> flaresolverr@1.2.5 start
> node ./dist/index.js

2021-05-31T14:33:59.680Z INFO FlareSolverr v1.2.5
2021-05-31T14:34:02.786Z INFO Listening on http://0.0.0.0:8191

******************************************************************

* **FlareSolverr version**: 12.6
* **Last working FlareSolverr version**: 1.2.5
* **Operating system**: linux Ubuntu
* **Are you using Docker**: [yes/no] : No
* **Are you using a proxy or VPN?** [yes/no] : No
* **Are you using Captcha Solver:** [yes/no] : No
* **If using captcha solver, which one:** No
* **URL to test this issue:**

**Comment by ngosang** [comment]
Please follow the instructions. You need to run more commands before `npm start`
https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by ngosang** [comment]
In fact, the documentation was wrong. It's updated now => https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by xcybermanx** [comment]
Fixed with ( node node_modules/puppeteer/install.js ) 

Thank You
