### ISSUE TITLE
Connection refuse 192.168.1.69:8191 and Serving on http://0.0.0.0:8191

### ISSUE THREAD

**Issue by ERASER-QC** [FlareSolverr/FlareSolverr#1413]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

yes

### Environment

```markdown
- FlareSolverr version:FlareSolverr 3.4.0
- Last working FlareSolverr version:
- Operating system:TOS 5.1
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no]no
- Are you using Captcha Solver: [yes/no]no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I apologize for my English
I installed this version, yesterday everything was working fine and today I can't connect to it and the logs give me 0.0.0.0:8191, I don't understand my error. 

Linux NAS-Julien 5.10.107 #313 SMP PREEMPT Wed Jul 26 09:35:47 UTC 2023 aarch64                            GNU/Linux

### Logged Error Messages

```text
[Julien@NAS-Julien ~]# docker logs flaresolverr
2024-11-23 08:31:43 INFO     FlareSolverr 3.4.0
2024-11-23 08:31:43 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-11-23 08:31:43 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-11-23 08:31:43 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-11-23 08:31:43 INFO     Testing web browser installation...
2024-11-23 08:31:44 INFO     Platform: Linux-5.10.107-aarch64-with-glibc2.36
2024-11-23 08:31:44 INFO     Chrome / Chromium path: /bin/chromium
2024-11-23 08:31:50 INFO     Chrome / Chromium major version: 130
2024-11-23 08:31:50 INFO     Launching web browser...
2024-11-23 08:31:50 INFO     Launching web browser...
2024-11-23 08:32:12 ERROR    Error creating Chrome Browser:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Traceback (most recent call last):
  File "/app/utils.py", line 450, in get_user_agent_nd
    driver = await get_webdriver_nd()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 252, in get_webdriver_nd
    return driver
           ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 125, in <module>
    asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
    user_agent = await utils.get_user_agent_nd()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 456, in get_user_agent_nd
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
2024-11-23 08:32:35 INFO     FlareSolverr 3.4.0
2024-11-23 08:32:35 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-11-23 08:32:35 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-11-23 08:32:35 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-11-23 08:32:35 INFO     Testing web browser installation...
2024-11-23 08:32:35 INFO     Platform: Linux-5.10.107-aarch64-with-glibc2.36
2024-11-23 08:32:35 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-11-23 08:32:38 INFO     Chrome / Chromium major version: 130
2024-11-23 08:32:38 INFO     Launching web browser...
2024-11-23 08:32:38 INFO     Launching web browser...
2024-11-23 08:33:00 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
2024-11-23 08:33:00 INFO     Test successful!
2024-11-23 08:33:01 INFO     Serving on http://0.0.0.0:8191
2024-11-23 08:46:25 INFO     FlareSolverr 3.4.0
2024-11-23 08:46:25 INFO     WARNING: YOU ARE RUNNING AN UNOFFICIAL EXPERIMENTAL BRANCH OF FLARESOLVER WHICH MAY CONTAIN BUGS.
2024-11-23 08:46:25 INFO     WARNING: IF YOU ENCOUNTER ANY, PLEASE REPORT THEM ON GITHUB AT THE FOLLOWING LINK:
2024-11-23 08:46:25 INFO     WARNING: https://github.com/FlareSolverr/FlareSolverr/pull/1163
2024-11-23 08:46:25 INFO     Testing web browser installation...
2024-11-23 08:46:25 INFO     Platform: Linux-5.10.107-aarch64-with-glibc2.36
2024-11-23 08:46:25 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-11-23 08:46:29 INFO     Chrome / Chromium major version: 130
2024-11-23 08:46:29 INFO     Launching web browser...
2024-11-23 08:46:29 INFO     Launching web browser...
2024-11-23 08:46:58 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
2024-11-23 08:46:59 INFO     Test successful!
2024-11-23 08:47:01 INFO     Serving on http://0.0.0.0:8191
```

**Comment by ERASER-QC** [comment]
ok that's it, I just understood that I'm a big root noob on my nas... you can close it, sorry for the inconvenience.

**Comment by nabjit** [comment]
same happened to me on truenas  scale but i fixed it by using the port as 18191 instead of 8191 in prowlarr

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1371
https://github.com/FlareSolverr/FlareSolverr/issues/1388
