### ISSUE TITLE
Error launching FlareSolverr using chromium-browser

### ISSUE THREAD

**Issue by JulesLePrince** [FlareSolverr/FlareSolverr#142]
### Environment

* **FlareSolverr version**: 1.2.6
* **Last working FlareSolverr version**: No
* **Operating system**: Ubuntu 20.04 LTS armv7l
* **Are you using Docker**: no
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no

### Description
Due to a problem with my OS, I decided to do a fresh reinstall. Everything works great except FlareSolverr which no doesn't start. I use an armhf board (Odroid XU4) running Ubuntu 20.04. As I know, integrated chrome simulation in nodejs isn't compatible with the following architecture so I followed [these instructions](https://github.com/FlareSolverr/FlareSolverr/issues/88#issuecomment-806227185) which worked fine on my first installation

### Logged Error Messages

```
root@odroid:/opt/FlareSolverr-1.2.6# npm start

> flaresolverr@1.2.6 start
> node ./dist/index.js

2021-05-31T17:06:21+00:00 INFO FlareSolverr v1.2.6
2021-05-31T17:06:24+00:00 ERROR Error starting Chrome browser. Error: net::ERR_FILE_NOT_FOUND at file:///tmp/flaresolverr_860f6000-c232-11eb-8c3a-ef5e98a0d546.txt
    at navigate (/opt/FlareSolverr-1.2.6/node_modules/puppeteer/lib/FrameManager.js:95:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/opt/FlareSolverr-1.2.6/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/opt/FlareSolverr-1.2.6/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/opt/FlareSolverr-1.2.6/node_modules/puppeteer/lib/helper.js:95:27)
    at testChromeInstallation (/opt/FlareSolverr-1.2.6/dist/index.js:48:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ngosang** [comment]
Take a look at the `/tmp/` folder. FlareSolverr is creating a temporary file to test chrome. Maybe you need to grant permissions to do the operation.

**Comment by JulesLePrince** [comment]
Thanks a lot for this fast answer,
I'm already running npm as root. What do you mean by "grant permission" ?

**Comment by ngosang** [comment]
You don't need to run npm as root.
Check if there are "flaresolverr_*.txt" files in `/tmp` folder.

**Comment by JulesLePrince** [comment]
yep, it creates a flaresolverr_*.txt that matches, but there is only one line inside : 

`flaresolverr_v1.2.6`

**Comment by ngosang** [comment]
I see the issue is Chrome can not read the .txt file but I don't know why.
I recommend you to try Docker image. It's available for armv7l and you will have less issues since already contains a tested Chrome.
