### ISSUE TITLE
Flaresolverr behind proxy

### ISSUE THREAD

**Issue by i3laze** [FlareSolverr/FlareSolverr#175]
### Environment

* **FlareSolverr version**: 1.2.8
* **Last working FlareSolverr version**: -
* **Operating system**: Windows Server 2019 Standard
* **Are you using Docker**: [yes/no] no
* **Are you using a proxy or VPN?** **yes**
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www.lostfilm.run/new

### Description

I'm trying to solve CloudFlare on Lostfilm.run, however this website is banned in Russia and is accessible only via VPN, proxy or Tor.
How can I forward Flaresolverr requests through my Tor Socks5 proxy 127.0.0.1:9050 or utilize Chrome proxy extensions?

Opened without VPN the website is either redirected to ISP's block webpage with wrong SSL certificate, or just get ERR_CONNECTION_RESET.

### Logged Error Messages
2021-07-29T11:07:05+03:00 INFO FlareSolverr v1.2.8
2021-07-29T11:07:06+03:00 INFO Listening on http://0.0.0.0:8191
2021-07-29T11:07:36+03:00 INFO REQ-1 Incoming request: POST /v1
2021-07-29T11:07:36+03:00 INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.lostfilm.run/new","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-07-29T11:07:37+03:00 ERROR REQ-1 Error: net::ERR_CONNECTION_RESET at https://www.lostfilm.run/new
    at navigate (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:95:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:70:21)
    at async Frame.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:295:16)
    at async Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:16)
    at async resolveChallenge (C:\snapshot\FlareSolverr\dist\routes.js:44:20)
    at async resolveChallengeWithTimeout (C:\snapshot\FlareSolverr\dist\routes.js:26:16)
    at async browserRequest (C:\snapshot\FlareSolverr\dist\routes.js:149:22)
    at async request.get (C:\snapshot\FlareSolverr\dist\routes.js:189:9)
    at async Object.Router [as default] (C:\snapshot\FlareSolverr\dist\routes.js:202:16)
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at resolveChallenge (C:\snapshot\FlareSolverr\dist\routes.js:44:31)
    at resolveChallengeWithTimeout (C:\snapshot\FlareSolverr\dist\routes.js:25:25)
    at browserRequest (C:\snapshot\FlareSolverr\dist\routes.js:149:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async request.get (C:\snapshot\FlareSolverr\dist\routes.js:189:9)
    at async Object.Router [as default] (C:\snapshot\FlareSolverr\dist\routes.js:202:16)
2021-07-29T11:07:37+03:00 ERROR REQ-1 Unable to process browser request. Error: Error: net::ERR_CONNECTION_RESET at https://www.lostfilm.run/new

**Comment by ngosang** [comment]
Proxy is not supported yet. There is an issue for that #26
For now you can use a VPN instead.

**Comment by DRSDavidSoft** [comment]
Since OP mentioned running on Windows Server, I think it's important to note that Chrome honors the system proxy settings, so if set globally through Internet Options → LAN Settings, Flaresolverr will work beautifully with it.

Another option (besides VPN'ing the entire OS) is to use solutions such as [Proxifier](https://www.proxifier.com/).  Personally, I'd like to use Fiddler + Squid + Privoxy + Tor, so I can proxy the entire system over Tor and see each request as it's being made in real-time.
