### ISSUE TITLE
Unable to use in Windows 10

### ISSUE THREAD

**Issue by Plus-xu** [FlareSolverr/FlareSolverr#178]
### Environment

* **FlareSolverr version**:1.2.9
* **Last working FlareSolverr version**: first  time using
* **Operating system**: Windows 10
* **Are you using Docker**: no
* **Are you using a proxy or VPN?** yes
* **Are you using Captcha Solver:** no

### Description
I use the windows version of flaresolverr，I change the FlareSolverr API URL to http://localhost:8191/ in Jackett.
When I enter the http://localhost:8191/  the errors showed in the Screenshots.
When I search something in Jackett, nothing changed and no data showed in the FlareSolverr.exe window

### Screenshots

![image](https://user-images.githubusercontent.com/52371609/128223287-d9504309-55eb-4a41-a376-c7cc33b415e4.png)

**Comment by ilike2burnthing** [comment]
Try `http://127.0.0.1:8191/` instead.

Try without the VPN.

**Comment by ngosang** [comment]
> When I search something in Jackett, nothing changed and no data showed in the FlareSolverr.exe window

Jackett only calls FlareSolverr when it detects Cloudflare in some page. Try with 1337x site

**Comment by Plus-xu** [comment]
> Try `http://127.0.0.1:8191/` instead.
> 
> Try without the VPN.

Thanks，It works with http://127.0.0.1:8191/, but Nothing changed. No page can bypass the Cloudflare in Jackett

**Comment by ilike2burnthing** [comment]
What indexers (and what site links) are you using and what errors are you getting?

**Comment by Plus-xu** [comment]
### **Indexer: https://www.anirena.com/**
### Errors：
  2021-08-14T09:14:24+08:00 INFO REQ-8 Incoming request: POST /v1
  2021-08-14T09:14:24+08:00 INFO REQ-8 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.anirena.com/?s=new","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
  2021-08-14T09:14:26+08:00 INFO REQ-8 Cloudflare detected
  2021-08-14T09:15:25+08:00 ERROR REQ-8 Error: Maximum timeout reached. maxTimeout=60000 (ms)
      at C:\snapshot\FlareSolverr\node_modules\await-timeout\src\utils.js:20:38
      at Timeout.<anonymous> (C:\snapshot\FlareSolverr\node_modules\await-timeout\src\index.js:32:46)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
  2021-08-14T09:15:25+08:00 ERROR REQ-8 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)


### **Indexer: https://idope.se/**
### Errors: 
    2021-08-14T09:20:44+08:00 INFO REQ-10 Incoming request: POST /v1
    2021-08-14T09:20:44+08:00 INFO REQ-10 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://idope.se/browse.html","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
    2021-08-14T09:20:45+08:00 INFO REQ-10 Cloudflare detected
    2021-08-14T09:21:44+08:00 ERROR REQ-10 Error: Maximum timeout reached. maxTimeout=60000 (ms)
        at C:\snapshot\FlareSolverr\node_modules\await-timeout\src\utils.js:20:38
        at Timeout.<anonymous> (C:\snapshot\FlareSolverr\node_modules\await-timeout\src\index.js:32:46)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
    2021-08-14T09:21:44+08:00 ERROR REQ-10 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)
    2021-08-14T09:21:45+08:00 INFO REQ-11 Incoming request: POST /v1
    2021-08-14T09:21:45+08:00 INFO REQ-11 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://idope.se/torrent-list/1?o=-3&c=","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}

I can open these website in Chrome，but can't search it by FlareSolverr on Jackett
