### ISSUE TITLE
Unable to run versions later than 1.2.9

### ISSUE THREAD

**Issue by Sc0th** [FlareSolverr/FlareSolverr#211]
Running docker version, in kubernetes

`
> flaresolverr@2.0.0 start
> node ./dist/server.js

2021-10-25T19:22:07+08:00 INFO FlareSolverr v2.0.0
2021-10-25T19:22:07+08:00 DEBUG Debug log enabled
2021-10-25T19:22:07+08:00 INFO Testing web browser installation...
2021-10-25T19:22:07+08:00 DEBUG Launching web browser...
/home/node/flaresolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
*** You are running in headless mode.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/node/flaresolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at ChildProcess.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:150:76)
    at ChildProcess.emit (node:events:402:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm notice
npm notice New minor version of npm available! 8.0.0 -> 8.1.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.1>
npm notice Run `npm install -g npm@8.1.1` to update!
npm notice
`

**Comment by ngosang** [comment]
I'm not sure what could be the issue. I'm running the Docker container in several machines without issues. I'm using Docker daemon instead of Kubernetes but it should be the same.
I just released v2.0.2, you can try just in case.

**Comment by Sc0th** [comment]
Getting a different error now, if this helps at all? 

Pod name is downloader-9bb45f67c-shf8h.
2021-11-01T10:00:04+08:00 INFO FlareSolverr v2.0.2
2021-11-01T10:00:04+08:00 DEBUG Debug log enabled
2021-11-01T10:00:04+08:00 INFO Testing web browser installation...
2021-11-01T10:00:04+08:00 DEBUG FlareSolverr user home directory is OK: /home/node
2021-11-01T10:00:04+08:00 DEBUG Launching web browser...
2021-11-01T10:00:33+08:00 ERROR Error: Navigation failed because browser has disconnected!
    at CDPSession.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:45:131)
    at CDPSession.emit (node:events:390:28)
    at CDPSession._onClosed (/home/node/flaresolverr/node_modules/puppeteer/lib/Connection.js:181:14)
    at Connection._onClose (/home/node/flaresolverr/node_modules/puppeteer/lib/Connection.js:110:21)
    at WebSocket.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/WebSocketTransport.js:29:30)
    at WebSocket.onClose (/home/node/flaresolverr/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/home/node/flaresolverr/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/home/node/flaresolverr/node_modules/ws/lib/websocket.js:1063:15)
    at Socket.emit (node:events:390:28)
  -- ASYNC --
    at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:56:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Sc0th** [comment]
ok, I check the release notes and doubled BROWSER_TIMEOUT to 60000 all appears well now :) - perhaps the complexities of k8s require a little longer grace

great work, thank you :)

--

Pod name is downloader-69dcfc6856-x64p9.
2021-11-01T10:16:01+08:00 INFO FlareSolverr v2.0.2
2021-11-01T10:16:01+08:00 DEBUG Debug log enabled
2021-11-01T10:16:01+08:00 INFO Testing web browser installation...
2021-11-01T10:16:01+08:00 DEBUG FlareSolverr user home directory is OK: /home/node
2021-11-01T10:16:01+08:00 DEBUG Launching web browser...
2021-11-01T10:16:29+08:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
2021-11-01T10:16:29+08:00 INFO Test successful
2021-11-01T10:16:29+08:00 INFO Listening on http://0.0.0.0:8191

**Comment by HommeOursPorc** [comment]
I'm unable to run any v2.x.x docker image on raspberry Pi 4 (raspbian?? buster).

Flaresolverr v2.0.2 docker image won't even start.

docker logs flaresolverr returns :

# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: some hex code that is different after each restart.

**Comment by ngosang** [comment]
I have a Raspberry Pi 4B running FlareSolverr without issues. Remove the Docker image and make sure you download the  `linux/arm/v7` image.

**Comment by HommeOursPorc** [comment]
Hi,

I stopped flaresolverr and run `docker system prune`

Then I tried:
`docker pull ghcr.io/flaresolverr/flaresolverr:latest@sha256:359c2eabe49a2524b84e15d8668c4bb42da86f4465b0ed837016a84ecce419c5`

Also used the same lastest@... In my docker compose file.

Still no go. Fatal error in line 0, unreachable code

What I'm I doing wrong?

Thanks 😊

**Comment by HommeOursPorc** [comment]
@ngosang could it be related to alpine??

Other project seem to have similar issues

https://github.com/svrooij/sonos2mqtt/issues/152#issuecomment-924873254

https://github.com/Koenkk/zigbee2mqtt/issues/7662#issuecomment-853146458

**Comment by HommeOursPorc** [comment]
@ngosang I can confirm it's the same problem.

I updated the libseccomp2 package and it now works.

https://github.com/xirixiz/dsmr-reader-docker/issues/203#issuecomment-817354261

https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-812287338

```
wget https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.2-2_armhf.deb
sudo dpkg -i libseccomp2_2.5.2-2_armhf.deb
rm libseccomp2_2.5.2-2_armhf.deb
```

**Comment by 2fst4u** [comment]
@Sc0th are you able to share your kubernetes manifest yaml? I'm struggling to get flaresolverr working even though all my other apps can communicate fine.

When I try to send a test to flaresolver it looks like my pod isn't even receiving the request to start with.
