### ISSUE TITLE
Docker "Error tried to use PUPPETEER"

### ISSUE THREAD

**Issue by mushuthecat** [FlareSolverr/FlareSolverr#216]
### Environment

* **FlareSolverr version**: flaresolverr@2.0.2
* **Last working FlareSolverr version**: 1.x
* **Operating system**:Linux raspberrypi 5.10.63-v7+ #1457 SMP Tue Sep 28 11:25:31 BST 2021 armv7l GNU/Linux
* **Are you using Docker**: YES
* **FlareSolverr User-Agent (see log traces or / endpoint)**:YES
* **Are you using a proxy or VPN?** NO
* **Are you using Captcha Solver:** YES
* **If using captcha solver, which one:**harvester
* **URL to test this issue:**

### Description

Since YGG is not working with my docker flaresolverr, i decided to update my container to 2.0.2 but now i have this error message:

### Logged Error Messages

```
flaresolverr@2.0.2 start


> node ./dist/server.js



2021-11-01T14:24:45+00:00 INFO FlareSolverr v2.0.2


2021-11-01T14:24:45+00:00 INFO Testing web browser installation...


2021-11-01T14:24:45+00:00 ERROR Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/chromium-browser


    at FirefoxLauncher.launch (/home/node/flaresolverr/node_modules/puppeteer/lib/Launcher.js:189:23)


    at async create (/home/node/flaresolverr/dist/services/sessions.js:80:19)


    at async testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:52:21)
```

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/83928911/139687795-60a2a896-91a4-486a-a323-93acbd7350b8.png)

**Comment by ngosang** [comment]
Remove the `PUPPETEER_*` env vars

**Comment by mushuthecat** [comment]
> 
> 
> Remove the `PUPPETEER_*` env vars. Or even better, remove the container and start from scratch following the instructions. I don't know why are those env vars set.

ONE-SHOT Thanks 👯‍♂️
