### ISSUE TITLE
Flaresolverr win64 - 2.1.0 - stuck on web browser installation testing

### ISSUE THREAD

**Issue by Chico0008** [FlareSolverr/FlareSolverr#251]
### Environment

* **FlareSolverr version** : 2.1.0
* **Last working FlareSolverr version**: 1.2.
* **Operating system**: Win10 64
* **Are you using Docker**: [no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**: ????
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description
juste installed new version of flaresolverr because was not working anymore with yggtorrent cloudfare
but, when i start flaresolverr.exe, in admin mode, it juste stay on testing web browser installation, and nothing works
what do i miss ?

last vers was a 1.2., with Chrome included

### Logged Error Messages
2021-12-12T21:09:12+01:00 INFO FlareSolverr v2.0.2
2021-12-12T21:09:12+01:00 INFO Testing web browser installation...

and nothing more

**Comment by ngosang** [comment]
You have to reinstall from scratch following the instructions in the readme.

**Comment by Chico0008** [comment]
This is what i already did
for windows you only have the precompiled lib, and it's juste a zip to unzip containing the necessary
the readme only tell to execute the flaresolverr bin
but it get stuck

tryes laucnhing on debug, got this

D:\Torrent\flaresolverr>set LOG_LEVEL=debug
D:\Torrent\flaresolverr>set LOG_HTML=true
D:\Torrent\flaresolverr>flaresolverr.exe
2021-12-13T09:08:35+01:00 INFO FlareSolverr v2.1.0
2021-12-13T09:08:35+01:00 DEBUG Debug log enabled
2021-12-13T09:08:35+01:00 INFO Testing web browser installation...
2021-12-13T09:08:35+01:00 DEBUG FlareSolverr user home directory is OK: C:\Users\Chico
2021-12-13T09:08:35+01:00 DEBUG Test URL: https://www.google.com
2021-12-13T09:08:35+01:00 DEBUG Launching web browser...

then nothing more
(flaresolverr is not launched from the user directory, dk how to tell flaresolverr to change it)

if i try on chrome localhost:8191, nothing respond (on old version i got a reponse telling flaresolverr was ready)

my default browser on this computer is Chrome, do i have to chanage to the firefox provided with the binaries ?

**Comment by ngosang** [comment]
It should work with out-the-box. Just extract and run. Can you try to execute as Administrator? Maybe you have some firewall or antivirus causing issues in your system.

**Comment by nafeasonto** [comment]
I have the same issue with 2.1.0

**Comment by nafeasonto** [comment]
This is the error:

2022-01-28T21:26:05-05:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:56:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by ngosang** [comment]
FlareSolverr 2.2.0 is released. That version includes important changes related to this issue.

**Comment by varoOP** [comment]
> FlareSolverr 2.2.0 is released. That version includes important changes related to this issue.

It seems that the issue still exists. On my system Flaresolverr v2.0.2 starts perfectly but v2.1.0 and latest v2.2.0 get this error:
```2022-01-31T11:41:09+01:00 INFO FlareSolverr v2.2.0
2022-01-31T11:41:09+01:00 INFO Testing web browser installation...
2022-01-31T11:41:49+01:00 ERROR TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.    at Timeout.onTimeout (/snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:240:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-01-31T11:41:49+01:00 ERROR It seems that the system is too slow to run FlareSolverr. 
    If you are running with Docker, try to remove CPU limits in the container. 
    If not, try setting the 'BROWSER_TIMEOUT' environment variable and the 'maxTimeout' parameter to higher values.```

**Comment by ngosang** [comment]
Did you use Proxy?

**Comment by thegrunge36** [comment]
Same problem whit version 2.2.1.0

jonathan@Jonathan:/opt/flaresolverr$ sudo chmod +x flaresolverr
[sudo] Mot de passe de jonathan : 
jonathan@Jonathan:/opt/flaresolverr$ ./flaresolverr
2023-02-21T08:10:07-05:00 INFO FlareSolverr v2.2.10
2023-02-21T08:10:07-05:00 INFO Testing web browser installation...
2023-02-21T08:10:48-05:00 ERROR TimeoutError: Navigation timeout of 40000 ms exceeded
    at /snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
jonathan@Jonathan:/opt/flaresolverr$
