### ISSUE TITLE
Flaresolverr linux- 2.1.0 - stuck on web browser installation testing

### ISSUE THREAD

**Issue by o0larrylurex0o** [FlareSolverr/FlareSolverr#252]
### Environment

* **FlareSolverr version :** 2.1.0
* **Last working FlareSolverr version :** 1.2.5
* **Operating system**:  Debian GNU/Linux 10 \n \l  | Linux version 5.10.0-0.bpo.8-amd64  | cloud server
* **Are you using Docker**: no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: N/A
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:** N/A
* **URL to test this issue:** N/A

### Description

just installed new version of flaresolverr because was not working anymore with yggtorrent cloudfare
but, when i start flaresolverr.exe, in USER mode, it juste stay on testing web browser installation, and nothing works

Installation from binary

### Logged Error Messages
2021-12-13T11:06:47+01:00 INFO FlareSolverr v2.1.0
2021-12-13T11:06:47+01:00 DEBUG Debug log enabled
2021-12-13T11:06:47+01:00 INFO Testing web browser installation...
2021-12-13T11:06:47+01:00 DEBUG FlareSolverr user home directory is OK: /home/MyUserName
2021-12-13T11:06:47+01:00 DEBUG Test URL: https://www.google.com
2021-12-13T11:06:47+01:00 DEBUG Launching web browser...
2021-12-13T11:07:48+01:00 ERROR TimeoutError: Timed out after 60000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
    at Timeout.onTimeout (/snapshot/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:170:20)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
2021-12-13T11:07:48+01:00 ERROR It seems that the system is too slow to run FlareSolverr.
    If you are running with Docker, try to remove CPU limits in the container.
    If not, try setting the 'BROWSER_TIMEOUT' environment variable and the 'maxTimeout' parameter to higher values.

Browser Timeout has been set to 60000

Why is the error message stating that only Chrome is guaranteed to work since Flaresolverr moved to firefox ?

Thx a lot

**Comment by o0larrylurex0o** [comment]
Version 2.0.2 seems to be working.
I could launch it with no problem.

But when i tested it with jackett or Prowlar on Yggtorrent
the challenge was detected repeatedly

2021-12-13T11:25:05+01:00 DEBUG REQ-9 Javascript challenge element '#trk_jschal_js' detected.
2021-12-13T11:25:05+01:00 DEBUG REQ-9 Waiting for Cloudflare challenge...
2021-12-13T11:25:05+01:00 DEBUG REQ-9 Javascript challenge element '#trk_jschal_js' detected.
2021-12-13T11:25:05+01:00 DEBUG REQ-9 Challenge element is visible
2021-12-13T11:25:05+01:00 DEBUG REQ-9 Found challenge element again
2021-12-13T11:25:05+01:00 DEBUG REQ-9 Waiting for Cloudflare challenge...
2021-12-13T11:25:06+01:00 DEBUG REQ-9 Javascript challenge element '#trk_jschal_js' detected.
2021-12-13T11:25:06+01:00 DEBUG REQ-9 Challenge element is visible
2021-12-13T11:25:06+01:00 DEBUG REQ-9 Found challenge element again

etc ...

And now i seem to be banned by Cloudflare xD

But still version 2.1.0 seems to have an issue

Thx

**Comment by o0larrylurex0o** [comment]
Can anyone give us a hand on this ?
fyi i'm using an ultraseedbox instance, so i don't have root acces and cannot run a docker image

thx a lot

**Comment by XxAcielxX** [comment]
I'm trying FlareSolverr for the first time and I'm having the same problem with both latest & v2.0.2

arm64 version here.

**Comment by ngosang** [comment]
Related to #275

**Comment by ngosang** [comment]
Closing as it's similar to #276 

For Ubuntu/Debian users: try to download the ZIP package from the releases page instead of compiling from the source code.
