### ISSUE TITLE
Cannot run with node from source on rasbian

### ISSUE THREAD

**Issue by yahay505** [FlareSolverr/FlareSolverr#270]
### Environment

* **FlareSolverr version**: latest
* **Last working FlareSolverr version**: none
* **Operating system**: raspbian
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: N/A
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:** N/A
* **URL to test this issue:** N/A

### Description
When trying to run from source Doesn't run and throws a puppeteer error. 

### Logged Error Messages

```
pi@yahaypi:/opt/flaresolverr $ git clone https://github.com/FlareSolverr/FlareSolverr
Cloning into 'FlareSolverr'...
remote: Enumerating objects: 717, done.
remote: Counting objects: 100% (389/389), done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 717 (delta 252), reused 307 (delta 192), pack-reused 328
Receiving objects: 100% (717/717), 601.55 KiB | 2.13 MiB/s, done.
Resolving deltas: 100% (418/418), done.
pi@yahaypi:/opt/flaresolverr $ cd FlareSolverr/
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ export PUPPETEER_PRODUCT=firefox
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ npm install

⸨##################⸩ ⠼ reify:typescript: http fetch GET 200 https://registry.npmjs.org/typescript/-/typescript-4.4.4.tgz 258523ms (cache miss)

added 706 packages, and audited 707 packages in 11m

51 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0
npm notice Run npm install -g npm@8.3.0 to update!
npm notice 
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ 
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ node node_modules/puppeteer/install.js
Requesting latest Firefox Nightly version from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central
Firefox Nightly is already in /opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1; skipping download.
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ export PUPPETEER_PRODUCT=firefox^C
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ npm run build

> flaresolverr@2.1.0 build
> tsc

pi@yahaypi:/opt/flaresolverr/FlareSolverr $ npm start

> flaresolverr@2.1.0 start
> node ./dist/server.js

2021-12-25T12:11:51+00:00 INFO FlareSolverr v2.1.0
2021-12-25T12:11:51+00:00 INFO Testing web browser installation...
2021-12-25T12:11:51+00:00 ERROR Error: Failed to launch the browser process!
/opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: 1: /opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: @: not found
/opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: 1: /opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: cannot open ?!�d�GNU: No such file
/opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: 1: /opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: ELF: not found
/opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: 2: /opt/flaresolverr/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/firefox: Syntax error: word unexpected (expecting ")")


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/opt/flaresolverr/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/opt/flaresolverr/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
pi@yahaypi:/opt/flaresolverr/FlareSolverr $ 

```

when running as root 
```

pi@yahaypi:/opt/flaresolverr/FlareSolverr $ sudo npm start

> flaresolverr@2.1.0 start
> node ./dist/server.js

2021-12-25T12:27:44+00:00 INFO FlareSolverr v2.1.0
2021-12-25T12:27:44+00:00 INFO Testing web browser installation...
2021-12-25T12:27:44+00:00 ERROR Error: EACCES: permission denied, access '/root'
    at Object.accessSync (node:fs:250:3)
    at testWebBrowserInstallation (/opt/flaresolverr/FlareSolverr/dist/services/sessions.js:67:8)
    at Object.<anonymous> (/opt/flaresolverr/FlareSolverr/dist/server.js:30:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -13,
  syscall: 'access',
  code: 'EACCES',
  path: '/root'
}
```

**Comment by SmartBoy84** [comment]
#88

**Comment by yahay505** [comment]
docker images refused to start thats why I went for running from source. what package should I get for it to work with puppeteer?

**Comment by yahay505** [comment]
```
ENV PUPPETEER_PRODUCT=chrome \
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
```
setting these environment variables fixed it thanks!

**Comment by SmartBoy84** [comment]
> docker images refused to start thats why I went for running from source. what package should I get for it to work with puppeteer?

I've been able to solve the issue of the containers not starting by using the `--privileged` flag, look at #273 for more info. @yahay505
