### ISSUE TITLE
Can't get install working in Ubuntu 20.04

### ISSUE THREAD

**Issue by lgwapnitsky** [FlareSolverr/FlareSolverr#276]
\### Environment

* **FlareSolverr version**: git pull on 2022-01-04
* **Last working FlareSolverr version**: N/A
* **Operating system**: Ubuntu 20.04
* **Are you using Docker**: [yes/no] No
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] No
* **Are you using Captcha Solver:** [yes/no] No
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

Unable to run FS at all without errors. Have tried installing libraries to no avail.

See log of installation:

```
root@flaresolverr:/opt/FlareSolverr# node node_modules/puppeteer/install.js 
Requesting latest Firefox Nightly version from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central
Firefox Nightly is already in /opt/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1; skipping download.
root@flaresolverr:/opt/FlareSolverr# npm run build

> flaresolverr@2.1.0 build
> tsc

root@flaresolverr:/opt/FlareSolverr# npm start

> flaresolverr@2.1.0 start
> node ./dist/server.js

2022-01-05T20:37:29-05:00 INFO FlareSolverr v2.1.0
2022-01-05T20:37:29-05:00 INFO Testing web browser installation...
2022-01-05T20:37:29-05:00 ERROR Error: Failed to launch the browser process!
XPCOMGlueLoad error for file /opt/FlareSolverr/node_modules/puppeteer/.local-firefox/linux-97.0a1/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/opt/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/opt/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:internal/readline/interface:496:10)
    at Socket.onend (node:internal/readline/interface:229:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
root@flaresolverr:/opt/FlareSolverr# 
```

**Comment by lgwapnitsky** [comment]
downgraded libdbus-glib library. Now receiving the following:

`2022-01-05T20:40:40-05:00 INFO FlareSolverr v2.1.0
2022-01-05T20:40:40-05:00 INFO Testing web browser installation...
2022-01-05T20:40:44-05:00 ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:45919/devtools/browser/b02bb378-f989-497c-8b79-ffe3493ce1ee',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED ::1:45919',
  error: Error: connect ECONNREFUSED ::1:45919
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 45919
  }
}
`

**Comment by lgwapnitsky** [comment]
downgraded libdbus-glib library.  now receiving this:

```
2022-01-05T20:40:40-05:00 INFO FlareSolverr v2.1.0
2022-01-05T20:40:40-05:00 INFO Testing web browser installation...
2022-01-05T20:40:44-05:00 ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:45919/devtools/browser/b02bb378-f989-497c-8b79-ffe3493ce1ee',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED ::1:45919',
  error: Error: connect ECONNREFUSED ::1:45919
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 45919
  }
}

```

**Comment by ericocallaghan** [comment]
I'm seeing similar behaviour with the v2.1.0 binary on Debian 5.10.46-4 running libdbus version 1.12.20-0+deb10u1.
Unfortunately its a shared system without root so testing a earlier version of libdbus-glib is not an option.

2022-01-06T21:25:26+00:00 INFO FlareSolverr v2.1.0
2022-01-06T21:25:26+00:00 DEBUG Debug log enabled
2022-01-06T21:25:26+00:00 INFO Testing web browser installation...
2022-01-06T21:25:26+00:00 DEBUG FlareSolverr user home directory is OK: /home/<user>
2022-01-06T21:25:26+00:00 DEBUG Test URL: https://www.google.com
2022-01-06T21:25:26+00:00 DEBUG Launching web browser...
2022-01-06T21:25:26+00:00 ERROR Error: Failed to launch the browser process!
XPCOMGlueLoad error for file /home/<user>/flaresolverr/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/snapshot/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/snapshot/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by widgetfonda** [comment]
Same error here. Clean install, Ubuntu 20.04 Server, FlareSolverr v2.1.0. It was working on my previous server with the same specs.

libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

**Comment by ngosang** [comment]
There is some missing package in your OS. You can try 2 things:
* Install Firefox package in Ubuntu. Maybe it install all required dependencies for you.
* Use Docker image. It's well tested and it contains all you need.

**Comment by ngosang** [comment]
Instead of installing from source code, just download the ZIP for linux, extract and execute.
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.1.0

**Comment by lordyod** [comment]
> Install Firefox package in the system. It will install most dependencies.

Is this different from the package installed with `node node_modules/puppeteer/install.js`?

> Make sure you have NodeJS version 16 installed. The version in official repositories is really old.

I encountered #265 with NodeJS v17 installed [from nodesource](https://github.com/nodesource/distributions/blob/master/README.md).

**Comment by ngosang** [comment]
> Is this different from the package installed with node node_modules/puppeteer/install.js?

`node node_modules/puppeteer/install.js` just download Firefox executable but it does not install the dependencies required by Firefox.

**Comment by ngosang** [comment]
I'm closing this issue since it's possible to install in Ubuntu. Make sure you install the `firefox` package.
