### ISSUE TITLE
ERROR Error: NS_ERROR_UNKNOWN_HOST at https://www.google.com

### ISSUE THREAD

**Issue by rconstant** [FlareSolverr/FlareSolverr#280]
### Environment

* **FlareSolverr version**: 2.1.0
* **Last working FlareSolverr version**:
* **Operating system**: Debian 10
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

Hello,

It's the first time I use Flaresolverr, I created a docker-compose yaml file with configuration from README, but when I run it, I have an error `NS_ERROR_UNKNOWN_HOST` in my container log.

Do you have any idea where this issue could come from? I couldn't find any related issue.

Thank you 

docker-compose.yaml file
```
version: "2.1"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Paris
    ports:
      - "8191:8191"
    restart: unless-stopped
```

### Logged Error Messages

```
root@xxx:/home/docker/flaresolverr$ docker-compose up
Creating network "flaresolverr_default" with the default driver
Creating flaresolverr ... done
Attaching to flaresolverr
flaresolverr    | 2022-01-17T18:19:12+01:00 INFO FlareSolverr v2.1.0
flaresolverr    | 2022-01-17T18:19:12+01:00 DEBUG Debug log enabled
flaresolverr    | 2022-01-17T18:19:12+01:00 INFO Testing web browser installation...
flaresolverr    | 2022-01-17T18:19:12+01:00 DEBUG FlareSolverr user home directory is OK: /home/node
flaresolverr    | 2022-01-17T18:19:12+01:00 DEBUG Test URL: https://www.google.com
flaresolverr    | 2022-01-17T18:19:12+01:00 DEBUG Launching web browser...
flaresolverr    | 2022-01-17T18:19:21+01:00 ERROR Error: NS_ERROR_UNKNOWN_HOST at https://www.google.com
flaresolverr    |     at navigate (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:95:23)
flaresolverr    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
flaresolverr    |     at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:70:21)
flaresolverr    |     at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:295:16)
flaresolverr    |     at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:16)
flaresolverr    |     at async testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:75:5)
flaresolverr    |   -- ASYNC --
flaresolverr    |     at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
flaresolverr    |     at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
flaresolverr    |     at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
flaresolverr    |     at testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:75:16)
flaresolverr    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jamesmacwhite** [comment]
NS_ERROR_UNKNOWN_HOST suggests a DNS issue with resolving www.google.com. Check you network/DNS setup.

**Comment by rconstant** [comment]
Thank you for your help, I fixed the issue with adding `network_mode: "host"`Not a perfect solution but will be enough for now.

**Comment by BBshinya** [comment]
or You can set the environment variable TEST_URL=https://www.bing.com

**Comment by volker-fr** [comment]
Ran into the same problem with kubernetes. `nslookup google.com` worked, but `ping google.com` fails with a DNS lookup issue.

One cause of the issue was `options ndots:5` in `/etc/resolv.conf`. As soon as I updated it to `options ndots:1` it worked for me.

Didn't see this issue in any other pod, only with flaresolverr.
