### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by heroku-miraheze** [FlareSolverr/FlareSolverr#282]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

2022-01-25T10:27:51+01:00 INFO FlareSolverr v2.1.0
2022-01-25T10:27:51+01:00 INFO Testing web browser installation...
2022-01-25T10:27:54+01:00 ERROR Error: SEC_ERROR_UNKNOWN_ISSUER at https://www.google.com
    at navigate (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:95:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:70:21)
    at async Frame.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:295:16)
    at async Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:16)
    at async testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

### Environment

* **FlareSolverr version**: Last version
* **Last working FlareSolverr version**: Last version
* **Operating system**: Windows 11
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] i thinks that no.
* **If using captcha solver, which one:**
* **URL to test this issue:** Running google.com and see certificate error.

### Description

2022-01-25T10:27:51+01:00 INFO FlareSolverr v2.1.0
2022-01-25T10:27:51+01:00 INFO Testing web browser installation...
2022-01-25T10:27:54+01:00 ERROR Error: SEC_ERROR_UNKNOWN_ISSUER at https://www.google.com
    at navigate (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:95:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:70:21)
    at async Frame.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:295:16)
    at async Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:16)
    at async testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

### Logged Error Messages

2022-01-25T10:27:51+01:00 INFO FlareSolverr v2.1.0
2022-01-25T10:27:51+01:00 INFO Testing web browser installation...
2022-01-25T10:27:54+01:00 ERROR Error: SEC_ERROR_UNKNOWN_ISSUER at https://www.google.com
    at navigate (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:95:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:70:21)
    at async Frame.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\FrameManager.js:295:16)
    at async Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:16)
    at async testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by 3xploitzer0** [comment]
![image](https://user-images.githubusercontent.com/56762704/151710030-5edce1bb-5e51-4e25-9812-8327bc38b986.png)

**Comment by ngosang** [comment]
Make sure you can access https://www.google.com in your web browser. If that URL is block in your country you can change it with the environment variable `TEST_URL`

https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/151749460-f86b0ccc-1763-4f2d-a4f2-332c8d99d54d.png)
![image](https://user-images.githubusercontent.com/19517680/151749471-1e1dc1bf-aa0b-4ed6-a8bb-9753efa6817b.png)

version 2.2.0 still error

**Comment by ngosang** [comment]
It looks like it's related to wrong folder permissions in Windows => https://github.com/FlareSolverr/FlareSolverr/issues/286#issuecomment-1025330739
Try that workaround, I will try to improve this in the next version.

**Comment by ngosang** [comment]
Related #295

**Comment by ngosang** [comment]
Others users reported the same error but I can't reproduce it. #297

**Comment by DenysTsi** [comment]
@ngosang Hey, had this issue as I had Fiddler running, I think you can reproduce with it directly.
