### ISSUE TITLE
Can't Run FlareSolverr, error in CMD prompt

### ISSUE THREAD

**Issue by nafeasonto** [FlareSolverr/FlareSolverr#283]
I downloaded the latest release, 2.1.0.  When I try to run it, I get this error messge in the CLI window:

2022-01-28T21:26:05-05:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:56:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by nafeasonto** [comment]
It looks like PIA (Private Internet Access) VPN is blocking it.  I didn't have this issue with the older versions.  What would be causing this?

**Comment by ngosang** [comment]
FlareSolverr 2.2.0 is released. Try with that version.

**Comment by nafeasonto** [comment]
> FlareSolverr 2.2.0 is released. Try with that version.

Same issue, only when the VPN is active.  It just timesout.  Without the VPN, it instantly connects.  Then I can activate it. Unless there is something being blocked with my VPN?

**Comment by ngosang** [comment]
Sorry but I do not use VPN and I can't help you. I'm closing because it's a network issue not related to FlareSolverr.
