### ISSUE TITLE
flaresolverr 2.2.0 win10 does not startup with  ERROR ProtocolError: Protocol error

### ISSUE THREAD

**Issue by garfield69** [FlareSolverr/FlareSolverr#286]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.0
* **Last working FlareSolverr version**: 2.1.0
* **Operating system**: windows 10 x64
* **Are you using Docker**: [yes/no] NO
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

does not startup. error `@chrome://remote/content/cdp/targets/TabTarget.jsm:108:5` implies its looking for a chrome header but are'nt we supposed to be using firefox?

### Logged Error Messages

```
C:\ProgramData\Jackett>flaresolverr
2022-01-31T14:15:19+13:00 INFO FlareSolverr v2.2.0
2022-01-31T14:15:19+13:00 INFO Testing web browser installation...
2022-01-31T14:15:21+13:00 ERROR ProtocolError: Protocol error (Target.setDiscoverTargets): can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null get title@chrome://remote/content/cdp/targets/TabTarget.jsm:108:5
_getTargetInfo@chrome://remote/content/cdp/domains/parent/Target.jsm:178:7
_onTargetCreated@chrome://remote/content/cdp/domains/parent/Target.jsm:187:29
setDiscoverTargets@chrome://remote/content/cdp/domains/parent/Target.jsm:82:12
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14

    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:75:24
    at new Promise (<anonymous>)
    at Connection.send (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:16)
    at Function.create (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:121:26)
    at FirefoxLauncher.launch (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:275:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async create (C:\snapshot\FlareSolverr\dist\services\sessions.js:99:19)
    at async testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:71:21) {
  originalMessage: `can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null`
}

C:\ProgramData\Jackett>
```

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Do you get the same error if you run a freshly extracted copy in your Downloads folder?

ProgramData permissions issues are on my mind since https://github.com/Jackett/Jackett/issues/12864. Have you manually reinstalled Jackett since then (rather than just auto-updated)?

**Comment by garfield69** [comment]
yes, you are correct. If I run 2.2.0 from the `%programdata%/Jackett` folder it fails, but if I run it from its own folder elsewhere it startup ok.
Odd that 2.1.0 runs from the Jackett folder ok.
Anyway, so I have an resolution and that's fine by me.
Thanks.

**Comment by garfield69** [comment]
>Have you manually reinstalled Jackett since then (rather than just auto-updated)?

both. I run the check-for-updates from the dashboard, and I also regularly run the installer when testing PR over the top.

**Comment by taravasya** [comment]
Looks like on Win Server 2016 Standart I have the same issue:
```
R:\Temp\flaresolverr-v2.2.4-windows-x64\flaresolverr>flaresolverr.exe
2022-06-13T18:05:44+03:00 INFO FlareSolverr v2.2.4
2022-06-13T18:05:44+03:00 INFO Testing web browser installation...
2022-06-13T18:05:48+03:00 ERROR ProtocolError: Protocol error (Target.setDiscoverTargets): can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null get title@chrome://remote/content/cdp/targets/TabTarget.jsm:115:5
_getTargetInfo@chrome://remote/content/cdp/domains/parent/Target.jsm:184:7
_onTargetCreated@chrome://remote/content/cdp/domains/parent/Target.jsm:193:29
setDiscoverTargets@chrome://remote/content/cdp/domains/parent/Target.jsm:84:12
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:103:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:66:25
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:273:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:91:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:73:14

    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:75:24
    at new Promise (<anonymous>)
    at Connection.send (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:16)
    at Function.create (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:121:26)
    at FirefoxLauncher.launch (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:276:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async create (C:\snapshot\FlareSolverr\dist\services\sessions.js:105:19)
    at async testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:21) {
  originalMessage: `can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null`
}
```

I was trying old verisions: 2.1.0 and 2.0.0 with the same result...
Can somebody provide some workaround here?
Thanks.

**Comment by taravasya** [comment]
Hmm...  I don't think this is permissions problem.
I use local drive.
Permissions for folder, for USERS and for EVERYONE is "full control"
![ ](http://photomir.dn.ua/pastenupload/2022.06/z0rleh.png)
Anyway... I was try another locations but with no luck.

**Comment by taravasya** [comment]
And yet it's some kind of problem with user permissions. But .. there is one oddity.
I almost always use Total Commander as a file manager, which I run with administrator rights. And it turns out that when I run the flaresolverr from Total Commander(with admin rights), the flaresolverr does not work. However, when I launched the flaresolverr simply from the win explorer, the flaresolverr started without errors.
It turns out that the flaresolverr does not work if it is started with elevated permissions?

**Comment by ilike2burnthing** [comment]
Possibly, I'm not sure.

If that is the issue, it's very niche and easily solved - don't run as admin if your username is Administrator.

As you said earlier, it does appear to be a permissions issue, but one which only occurs when running as admin, which is odd. I'm not sure why that would be the case.

If you think they is a bigger issue here and want the actual dev to take a look at it (when they're free), open a new issue with the information requested and link to this thread.
