### ISSUE TITLE
FlareSolverr crashes on image request

### ISSUE THREAD

**Issue by JimmXinu** [FlareSolverr/FlareSolverr#290]
### Environment

* **FlareSolverr version**: 2.2.0
* **Last working FlareSolverr version**: 2.1.0
* **Operating system**: Win10
* **Are you using Docker**: no
* **FlareSolverr User-Agent (see log traces or / endpoint)**:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

### Description

Version 2.2.0 crashes when an image is requested.  Log suggests it's a bug in error handling.

### Logged Error Messages
Called with:
```
curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{
  "cmd": "request.get",
  "url":"https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
  "maxTimeout": 60000
}'
```
FlareSolverr v2.2.0 shows:
```
2022-01-31T12:30:26-06:00 INFO FlareSolverr v2.2.0
2022-01-31T12:30:26-06:00 INFO Testing web browser installation...
2022-01-31T12:30:28-06:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
2022-01-31T12:30:29-06:00 INFO Test successful
2022-01-31T12:30:29-06:00 INFO Listening on http://0.0.0.0:8191
2022-01-31T12:30:31-06:00 INFO REQ-1 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png","maxTimeout":60000}
C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26
        throw new Error(message);
              ^

Error: Execution Context has already been set.
    at assert (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld._setContext (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:62:36)
    at FrameManager._onExecutionContextCreated (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:337:19)
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:76:18
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:249:18)
    at Connection._onMessage (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:117:25)
```
...and returns to command prompt.

**Comment by ngosang** [comment]
Downloading binary files is not supported but I fixed the crash issue.
Fixed on [v2.2.1](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.1)
