### ISSUE TITLE
CentOS does not startup with ERROR ProtocolError: Protocol error #286

### ISSUE THREAD

**Issue by Wolftein** [FlareSolverr/FlareSolverr#295]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.0
* **Last working FlareSolverr version**:
* **Operating system**: CentOS 8
* **Are you using Docker**: [yes/no] NO
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] NO
* **Are you using Captcha Solver:** [yes/no] NO
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

does not startup. error @chrome://remote/content/cdp/targets/TabTarget.jsm:108:5

### Logged Error Messages

```
[root@CentOS-85-64-minimal flaresolverr]# sudo ./flaresolverr

2022-02-06T02:41:47+01:00 INFO FlareSolverr v2.2.0
2022-02-06T02:41:47+01:00 INFO Testing web browser installation...
2022-02-06T02:41:48+01:00 ERROR ProtocolError: Protocol error (Target.setDiscoverTargets): can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null get title@chrome://remote/content/cdp/targets/TabTarget.jsm:108:5
_getTargetInfo@chrome://remote/content/cdp/domains/parent/Target.jsm:178:7
_onTargetCreated@chrome://remote/content/cdp/domains/parent/Target.jsm:187:29
setDiscoverTargets@chrome://remote/content/cdp/domains/parent/Target.jsm:82:12
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
      at /snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24
      at new Promise (<anonymous>)
      at Connection.send (/snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:16)
      at Function.create (/snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:121:26)
      at FirefoxLauncher.launch (/snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:275:50)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async create (/snapshot/FlareSolverr/dist/services/sessions.js:99:19)
      at async testWebBrowserInstallation (/snapshot/FlareSolverr/dist/services/sessions.js:71:21) {
        originalMessage: can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null
}
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
Other users reported the same issue in Windows but I can not reproduce. #297
