### ISSUE TITLE
Flaresolver 2.2.2 does not start anymore

### ISSUE THREAD

**Issue by Tsuna77** [FlareSolverr/FlareSolverr#341]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.2
* **Last working FlareSolverr version**: 2.2.1
* **Operating system**: Fedora server 35
* **Are you using Docker**: yes 
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** internal flaresolver deployement

### Description

I simply upgrade flaresolver from 2.2.1 to 2.2.2 to fix yggtorrent errors. Work 1 hours and no more after.

### Logged Error Messages

```
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2022-03-20T18:11:25+01:00 INFO FlareSolverr v2.2.2
2022-03-20T18:11:25+01:00 INFO Testing web browser installation...
2022-03-20T18:11:25+01:00 ERROR Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (node:events:538:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by ilike2burnthing** [comment]
Does reverting to v2.2.1 work?

Nothing changed which would affect Puppeteer.

**Comment by Tsuna77** [comment]
I go back to v2.2.1 tag and it's working without any problem. just not working with ygg

**Comment by ilike2burnthing** [comment]
Try removing the v2.2.2 image and pulling a fresh one, see if that resolves the issue.

If not, there may be some breaking change between Firefox Nightly v98 and v100.

**Comment by Tsuna77** [comment]
O.o after cleaning image and pull it again, it's working again. I hope it will continue working.

thanks you. I'll wait some hours before closing, to be sure it is not going down again.

**Comment by Obegg** [comment]
I don't know if I have the same issue, but it's probably is the same:
I'm on Windows and after a restart, there are a few times where the program closes itself, without logs or errors, before it reaches the "Test successful" stage. So I guess it's a firefox problem?

**Comment by ilike2burnthing** [comment]
If the program is closing without logs or error, that doesn't seem like a Firefox issue (also, I can't recreate it).

Check your security software isn't causing these crashes by either closing it completely or creating exclusions for flaresolverr.exe and firefox.exe (or just the whole folder).

**Comment by Tsuna77** [comment]
Everythings works fin today. I'm closing this issus :) thanks for your help @ilike2burnthing
