### ISSUE TITLE
Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191.

### ISSUE THREAD

**Issue by Romangelo** [FlareSolverr/FlareSolverr#402]
21:33:25    flaresolverr[i] Waiting for response from http://localhost:8191/v1
21:33:25    flaresolverr[x] Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191.
21:33:25    cloudflare  [x] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it [::1]:8191
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ‪⁮⁯⁭⁫​⁬​‪‫⁬‪‍⁭⁫⁭‪⁮‫⁭‭⁫‮‪‭‏‎‏‍⁭‌‮‍⁯‏​‪‎‌⁬‮.​⁪⁫‪‌⁬‭⁬⁪⁭‪⁬⁭‮‎⁪‌⁫‬‫⁫⁬‏‍‎⁬⁯⁬‏⁫⁬⁫⁬‭‪⁬⁪‭⁯⁮‮(Uri )
   at ‫‭⁮‬‎⁬⁫‭‬‫⁬‫⁭​‪⁭‎‫‪‫‍‏‮‫⁪‏⁭​‭‎‎⁯‭‭⁫⁭‭‎⁯‎‮.‌‏⁮‬​‍⁮‍​‮⁫‫‭‪‫⁪⁪⁬⁯⁯‮⁬‫⁭‍‏‫⁯‍‫​⁪⁪⁪⁪‬⁯‮⁯‍‮(String , IWebProxy )

**Comment by Romangelo** [comment]
I'm so silly... the problem was that I extracted the plugin's zipped file.
