### ISSUE TITLE
Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by Cattleyan** [FlareSolverr/FlareSolverr#420]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version:2.2.4
* **Are you using Docker: yes

### Logged Error Messages
INFO FlareSolverr v2.2.4

 INFO Testing web browser installation...

 ERROR TimeoutError: Navigation timeout of 40000 ms exceeded

    at /home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111

    at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)

    at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)

    at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)

**Comment by ChestnutHeng** [comment]
did you solve this?
