### ISSUE TITLE
Crash on Install - Failed to launch the browser process! (opensuse leap 15.4)

### ISSUE THREAD

**Issue by MetaStazz** [FlareSolverr/FlareSolverr#426]
As I can see, this is a common issue !! But I didn't find a way to make it work !

### Environment

* **FlareSolverr version**: 2.2.4
* **Last working FlareSolverr version**: Never
* **Operating system**: Opensuse Leap 15.4 64bits - KDE Plasma.
* **Are you using Docker**: NO
* **FlareSolverr User-Agent (see log traces or / endpoint)**: ??
* **Are you using a proxy or VPN?** NO
* **Are you using Captcha Solver:** NO

### Description

I follow the manual install with precompiled source but at the step 3, when I execute flareSolverr, I get a crash reporter saying:
> The application had a problem and crashed
> Unfortunately, the crash reporter is unable to submit a report for this crash
> Details: The application didn't leave an application data file

Just in case, I have `nodeJS16`, `puppeteer-core` and `libdbus-1-3`

When I manually install the service, the status block on "activating"!
```shell
systemctl status flaresolverr
● flaresolverr.service - FlareSolverr
     Loaded: loaded (/etc/systemd/system/flaresolverr.service; disabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2022-07-14 20:25:10 CEST; 41ms ago
    Process: 31527 ExecStart=~/.system/bin/flaresolverr (code=exited, status=203/EXEC)
   Main PID: 31527 (code=exited, status=203/EXEC)
```

### Logged Error Messages with FlareSolverr 2.2.4
```shell
export LOG_LEVEL=debug
.......
2022-07-14T13:25:41+02:00 INFO FlareSolverr v2.2.4
2022-07-14T13:25:41+02:00 DEBUG Debug log enabled
2022-07-14T13:25:41+02:00 INFO Testing web browser installation...
2022-07-14T13:25:41+02:00 DEBUG FlareSolverr user home directory is OK: /home/loky
2022-07-14T13:25:41+02:00 DEBUG Test URL: https://www.google.com
2022-07-14T13:25:41+02:00 DEBUG Creating new session...
2022-07-14T13:25:41+02:00 DEBUG Launching web browser...
2022-07-14T13:25:41+02:00 ERROR Error: Failed to launch the browser process!
*** You are running in headless mode.
ExceptionHandler::GenerateDump cloned child 18883
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:232:79)
    at ChildProcess.emit (node:events:538:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

## Edit :
I try with FlareSolverr 2.2.0 with no luck but another error !!

### Logged Error Messages with FlareSolverr 2.2.0
```shell
export LOG_LEVEL=debug
.........
2022-07-14T20:20:30+02:00 INFO FlareSolverr v2.2.0
2022-07-14T20:20:30+02:00 DEBUG Debug log enabled
2022-07-14T20:20:30+02:00 INFO Testing web browser installation...
2022-07-14T20:20:30+02:00 DEBUG FlareSolverr user home directory is OK: /home/loky
2022-07-14T20:20:30+02:00 DEBUG Test URL: https://www.google.com
2022-07-14T20:20:30+02:00 DEBUG Launching web browser...
2022-07-14T20:20:35+02:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0
2022-07-14T20:20:36+02:00 INFO Test successful
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND stellaris
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1517:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stellaris'
}

```

**Thanks**

**Comment by ngosang** [comment]
I don't know much about Opensuse. Try to follow the installation instructions:
1. Docker is the recommended way
2. Install from source code
3. Download the binary attached in the release page

FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496
