### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed.

### ISSUE THREAD

**Issue by SulliL** [FlareSolverr/FlareSolverr#441]
### Environment

* **FlareSolverr version**: 2.2.4
* **Last working FlareSolverr version**:
* **Operating system**: debian
* **Are you using Docker**: [yes]
* **FlareSolverr User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0**
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Logged Error Messages

Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 909
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 888

**Comment by resuarez** [comment]
I am having the same problem

**Comment by tcrevel** [comment]
Do you have checked if your YGG account is still active?

**Comment by resuarez** [comment]
In my case, my account is still active

**Comment by SulliL** [comment]
> Do you have checked if your YGG account is still active?

My account is still active

**Comment by ngosang** [comment]
Fixed in:
FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496

**Comment by SulliL** [comment]
The problem is still present in 2.2.6 jackett v0.20.1529

**Comment by ngosang** [comment]
Provide FlareSolverr traces

**Comment by resuarez** [comment]
Not sure @ngosang if you are asking for this:  But, in my case, I am using Jackett v0.20.1539 and FlareSolverr v2.2.6

I've tested the indexer several times with the same result that it couldn't find challengers.  I am behind of proxy, but I can open the site in the browser and the rest of the indexers work without problem.

=== log from FlareSolverr ===

2022-08-01T18:56:22+00:00 INFO REQ-5 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www5.yggtorrent.fi/","proxy":{"url":"192.168.2.204:8118"}}
2022-08-01T18:56:22+00:00 DEBUG REQ-5 Creating new session...
2022-08-01T18:56:22+00:00 DEBUG REQ-5 Using proxy: 192.168.2.204:8118
2022-08-01T18:56:22+00:00 DEBUG REQ-5 Launching web browser...
2022-08-01T18:56:24+00:00 DEBUG REQ-5 Using proxy: 192.168.2.204:8118
2022-08-01T18:56:24+00:00 DEBUG REQ-5 Navigating to... https://www5.yggtorrent.fi/
2022-08-01T18:56:25+00:00 INFO REQ-5 Cloudflare detected
2022-08-01T18:56:25+00:00 DEBUG REQ-5 No challenge element detected.
2022-08-01T18:56:25+00:00 INFO REQ-5 Cloudflare Error: No challenge selectors found, unable to proceed.
2022-08-01T18:56:25+00:00 INFO REQ-5 Response in 3.223 s
2022-08-01T18:56:33+00:00 INFO REQ-6 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www5.yggtorrent.fi/","proxy":{"url":"192.168.2.204:8118"}}
2022-08-01T18:56:33+00:00 DEBUG REQ-6 Creating new session...
2022-08-01T18:56:33+00:00 DEBUG REQ-6 Using proxy: 192.168.2.204:8118
2022-08-01T18:56:33+00:00 DEBUG REQ-6 Launching web browser...
2022-08-01T18:56:36+00:00 DEBUG REQ-6 Using proxy: 192.168.2.204:8118
2022-08-01T18:56:36+00:00 DEBUG REQ-6 Navigating to... https://www5.yggtorrent.fi/
2022-08-01T18:56:37+00:00 INFO REQ-6 Cloudflare detected
2022-08-01T18:56:37+00:00 DEBUG REQ-6 No challenge element detected.
2022-08-01T18:56:38+00:00 INFO REQ-6 Cloudflare Error: No challenge selectors found, unable to proceed.
2022-08-01T18:56:38+00:00 INFO REQ-6 Response in 4.148 s


=== Log from Jackett == 

<html>
<body>


2022-08-01 14:56:38 | Error | FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed.    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext() --- End of stack trace from previous location ---    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
-- | -- | --



</body>
</html>

**Comment by ilike2burnthing** [comment]
Do you get the same issue if you remove the proxy?

**Comment by resuarez** [comment]
yes.. I did same..  but I am not who opened this issue. Then, we are two with the same problem.

**Comment by SulliL** [comment]
> 

Yes

**Comment by ilike2burnthing** [comment]
To either of you, please post the debug log with HTML enabled.

**Comment by resuarez** [comment]
Ok.. I will try to do it tonight

**Comment by resuarez** [comment]
Ok.. I couldn't wait, I've connected to my server remotely.  I didn't know about the HTML enabled option.  It is really helpful.  For some reason:  I am getting this: 
`        <div class="main-wrapper" role="main">
         <div class="header section">
            <h1>
               <span class="error-description">Access denied</span>
               <span class="code-label">Error code <span>1020</span></span>
            </h1>
            <div class="large-font">
               <p>You do not have access to www5.yggtorrent.fi.</p><p>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.</p>
            </div>
         </div>
      </div>`
I am connecting directly to internet and I can open the site in my browser.  Then, the IP is not blocked.

I hope this help. 
I think that it is the problem.

**Comment by ilike2burnthing** [comment]
FlareSolverr, Jackett, and your browser are all on the same device?

You're not using a VPN or proxy?

If the answer to both of those is yes, I'm not sure what would be causing the issue, and it may be worth talking to YGG staff.

**Comment by resuarez** [comment]
the answer is yes.  I understand, btw, thank you a lot for your help.  I will try to do some testing this weekend if I get something new.  I will post it.
