### ISSUE TITLE
Number of selector found: 0, total selector: 3

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#48]
I'm getting the message `Number of selector found: 0, total selector: 3` in the following links:
* https://www.divxtotal.one/page/1/?s=
* https://wwv.epizod.tv/mon-cirque-a-moi-french-webrip-720p-2020/,
* https://pirateiro.com/torrents/?search=&orderby=enviado

**Comment by adamwinn** [comment]
I'm seeing the same error trying to download a torrent file in Jackett from PrivateHD.

I use FlareSolverr in docker on my Synology nas so exporting the logs was weird and I'm sorry for the format they're in (and you have to read them bottom-to-top instead of top-to-bottom).  Does FlareSolverr write logs anywhere besides stdout so I can get to the logs easier?

[flaresolverr-flaresolverr.html.zip](https://github.com/FlareSolverr/FlareSolverr/files/5749779/flaresolverr-flaresolverr.html.zip)

**Comment by adamwinn** [comment]
```
2020-12-29 03:52:29.3757 Error On attempt 3 downloading from PrivateHD: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: No challenge selectors found, unable to proceed FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: No challenge selectors found, unable to proceed
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 496
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
```

**Comment by xfouloux** [comment]
as @abeloin said on another issue : https://github.com/scaredos/cfresearch

**Comment by ngosang** [comment]
FlareSolverr v1.2.2
