### ISSUE TITLE
[btschool] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by ghwjp** [FlareSolverr/FlareSolverr#485]
Please help with troubleshooting, great thanks!

### Environment

* **FlareSolverr version**: v2.2.6
* **Last working FlareSolverr version**: v2.2.6
* **Operating system**: Linux DS218 4.4.180+ (Synology DSM 7.0-41890)
* **Are you using Docker**: [yes/no] Yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** [yes/no]  No
* **Are you using Captcha Solver:** [yes/no] yes
* **If using captcha solver, which one:** FlareSolverr
* **URL to test this issue:** 

### Description

Add private index BTSchool to jackett with flaresolverr, got the error msg and failed

An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid
[Click here to open an issue on GitHub for FlareSolverr.]

### Logged Error Messages

Log from flaresolverr
=====================================
some tail lines of logs from my flarewolverr container using command 
sudo docker logs <thenameofflarewolverrcontainer>

2022-08-28T03:17:17+00:00 INFO REQ-6 Cloudflare detected
2022-08-28T03:17:17+00:00 DEBUG REQ-6 Javascript challenge element '#trk_jschal_js' detected.
2022-08-28T03:17:17+00:00 DEBUG REQ-6 Waiting for Cloudflare challenge...
2022-08-28T03:17:17+00:00 DEBUG REQ-6 Javascript challenge element '#trk_jschal_js' detected.
2022-08-28T03:17:20+00:00 DEBUG REQ-6 Challenge element is hidden
2022-08-28T03:17:21+00:00 DEBUG REQ-6 Validating HTML code...
2022-08-28T03:17:21+00:00 INFO REQ-6 Challenge solved
2022-08-28T03:17:21+00:00 DEBUG REQ-6 Reloading the page
2022-08-28T03:17:22+00:00 INFO REQ-6 Response in 15.132 s

Logged Error Messages from jackett (view logs)
=====================================
Exception in GetConfigurationForSetup (btschool): FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889

FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 581
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/481

**Comment by ghwjp** [comment]
@ilike2burnthing 
Is this comment under issue #481 the solution to my case?
https://github.com/FlareSolverr/FlareSolverr/issues/481#issuecomment-1228189653
Could you help explain a little bit more about how to apply it? Great thanks！

**Comment by ilike2burnthing** [comment]
No, to my knowledge there would be no way to do that with Jackett.

**Comment by ghwjp** [comment]
@ilike2burnthing 
You mean, BTSchool is not able to be added to Jackett?

**Comment by ilike2burnthing** [comment]
The workaround you linked to, as currently written, is not able to be used with Jackett.

**Comment by ghwjp** [comment]
So, you mean, when I got "The cookies provided by FlareSolverr are not valid", this error message, nothing can do to try to fix it.  Will the next update fix it?

**Comment by ilike2burnthing** [comment]
Wait for the next FlareSolverr release. Not sure when that will be.
