### ISSUE TITLE
FlareSolverr and Windows 7

### ISSUE THREAD

**Issue by shindante** [FlareSolverr/FlareSolverr#539]
### Discussed in https://github.com/FlareSolverr/FlareSolverr/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **shindante** September 28, 2022</sup>
I wasn't sure where exactly to post this and if this is the wrong place I'd appreciate being pointed in the right direction.

After updating Flaresolverr to v 2.2.9 and trying to download from Nhentai, I got the message that the captcha was blocking Hdoujin Downloader. I've pasted the log below and noticed one of the lines saying Node.js is only supported on windows 8.1, Windows Server 2012 R2, or higher along with another entry saying unsupported problems will not be fixed. Is it safe to say I'm SoL on this one?

22:26:48 hdoujin dow [i] CLR Version: 4.0.30319.42000
22:26:48 hdoujin dow [i] Framework Version: 4.8.4069.0
22:26:48 hdoujin dow [i] OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64-bit)
22:26:48 hdoujin dow [i] Locale: en-US
22:26:48 hdoujin dow [i] Path: %USERNAME%\Desktop\HDoujin Downloader\HDoujin Downloader.exe
22:26:48 hdoujin dow [i] Working Directory: %USERNAMEPROFILE%\Desktop\HDoujin Downloader
22:26:48 hdoujin dow [i] Timestamp: 9/18/2022 10:24:42 PM
22:26:48 hdoujin dow [i] Product Version: 2022.1.3
22:26:48 hdoujin dow [i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3
22:26:48 hdoujin dow [i] Standalone: False
22:26:48 hdoujin dow [i] Repositories: Official Lua Repository, Internal
22:26:48 hdoujin dow [i] Theme: Default
22:26:48 queue       [i] Attempting to enqueue https://nhentai.net/g/420811/
22:26:48 hdoujinchal [i] Using FlareSolverrChallengeHandler
22:26:48 flaresolver [i] Starting FlareSolverr service
22:26:48 flaresolver [i] Starting FlareSolverr process
22:26:48 flaresolver [x] Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
22:26:48 flaresolver [x] Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
22:26:48 flaresolver [x] check, but Node.js might not execute correctly. Any issues encountered on
22:26:48 flaresolver [x] unsupported platforms will not be fixed.
22:26:48 flaresolver [x] Failed to start FlareSolverr process
22:26:48 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> afHjInmTsQxoiLqMAiJMENuahgnaA: Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8191
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at geaWYoSJClStyLEisGZqBlTeCAHT.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   at MFKEaMZjkLMutBNFBXdrIvmiGQSt.MwEeLqDJeNlfEStnMlqHbNJoYdrSA(TZNgPAKdlPnVdOLXQTXLlHChlAnaA , Boolean )
   at AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   --- End of inner exception stack trace ---
   at AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   at DIyBwRXrbgAcRcGdAnWEKsAhyyFv.opCRWpkqwPduNzNaFGXTcgvKNOxg()
   at fXvQSqEcFwfaRGnRXEdLwQWDzZks.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   --- End of inner exception stack trace ---
   at PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at uuoaNorlsetLwkNGECqbbdEahRArA.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
22:26:48 http        [x] Exception was thrown when accessing https://nhentai.net/g/420811/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> afHjInmTsQxoiLqMAiJMENuahgnaA: Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8191
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at geaWYoSJClStyLEisGZqBlTeCAHT.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   at MFKEaMZjkLMutBNFBXdrIvmiGQSt.MwEeLqDJeNlfEStnMlqHbNJoYdrSA(TZNgPAKdlPnVdOLXQTXLlHChlAnaA , Boolean )
   at AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   --- End of inner exception stack trace ---
   at AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   at DIyBwRXrbgAcRcGdAnWEKsAhyyFv.opCRWpkqwPduNzNaFGXTcgvKNOxg()
   at fXvQSqEcFwfaRGnRXEdLwQWDzZks.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   --- End of inner exception stack trace ---
   at PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at uuoaNorlsetLwkNGECqbbdEahRArA.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   at DIyBwRXrbgAcRcGdAnWEKsAhyyFv.opCRWpkqwPduNzNaFGXTcgvKNOxg()
   at fXvQSqEcFwfaRGnRXEdLwQWDzZks.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at EDvCRNwEFITnqfPJWdCsdHryLZAX.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at qnYYRkMoIaAMXwNQSriSnITgTYWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at DDQIzAFVmHzQuaJVvZhBGyhnACdJ.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   --- End of inner exception stack trace ---
   at PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at SVlelqdAVtHOBKzMwEFXGHelfkwG.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   at APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   at ANkQshBKCTJBLlAYVGxknznGGiFd.wwjGYLdpLXvZBBXeZEBQozkDwQSoA(String , CookieContainer , String[] , String , wJhZKjMhUlAAOrHmtApKIGEADPnVA , String[] )
22:26:48 queue       [!] Skipped https://nhentai.net/g/420811/ (Invalid response or missing/outdated module)
</div>

**Comment by HDoujinDownloader** [comment]
> 22:26:48 flaresolver [x] Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
> 22:26:48 flaresolver [x] Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
> 22:26:48 flaresolver [x] check, but Node.js might not execute correctly. Any issues encountered on
> 22:26:48 flaresolver [x] unsupported platforms will not be fixed.

This is the important part. In my experience it will actually run just fine on Windows 7 so long as that environmental variable is set. Try using the [latest pre-release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/v2022.6.9.0-rc.5) of HDoujin Downloader, which sets this variable automatically.

**Comment by shindante** [comment]
> > 22:26:48 flaresolver [x] Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
> > 22:26:48 flaresolver [x] Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
> > 22:26:48 flaresolver [x] check, but Node.js might not execute correctly. Any issues encountered on
> > 22:26:48 flaresolver [x] unsupported platforms will not be fixed.
> 
> This is the important part. In my experience it will actually run just fine on Windows 7 so long as that environmental variable is set. Try using the [latest pre-release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/v2022.6.9.0-rc.5) of HDoujin Downloader, which sets this variable automatically.

Thank you! I tried looking for about an hour for where I could change that setting myself, but had to give up and redo my user settings after confirming my account information. Thanks again!

**Comment by ngosang** [comment]
FlareSolverr 3.0.0 is out and it has different install instructions. Checkout the readme.
