### ISSUE TITLE
ERROR Error: EACCES: permission denied, access '/home/node'

### ISSUE THREAD

**Issue by philou669** [FlareSolverr/FlareSolverr#590]
### Environment

* **FlareSolverr version**: v2.2.10
* **Last working FlareSolverr version**: ?
* **Operating system**: TOS5 (NAS terramaster)
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** /no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

2022-11-18T16:29:48-05:00 INFO FlareSolverr v2.2.10
2022-11-18T16:29:48-05:00 INFO Testing web browser installation...
2022-11-18T16:29:48-05:00 ERROR Error: EACCES: permission denied, access '/home/node'
    at Object.accessSync (node:fs:254:3)
    at testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:71:8)
    at Object.<anonymous> (/home/node/flaresolverr/dist/server.js:33:43)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -13,
  syscall: 'access',
  code: 'EACCES',
  path: '/home/node'
}

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
This issue is fixed in FlareSolverr 3.0.0
