### ISSUE TITLE
SSL_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by samuelds** [FlareSolverr/FlareSolverr#597]
### Environment

* **FlareSolverr version**: v2.2.10
* **Last working FlareSolverr version**: no
* **Operating system**: debian 10
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: no change
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:** no
* **URL to test this issue:** no

### Description

On start :
```
docker run -d \
  --name=flaresolverr \
  -e LOG_LEVEL=debug \
  -e LOG_HTML=true \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest
```

### Logged Error Messages

```
2022-08-14T06:58:04+00:00 INFO FlareSolverr v2.2.10
2022-08-14T06:58:05+00:00 DEBUG Debug log enabled
2022-08-14T06:58:05+00:00 INFO Testing web browser installation...
2022-08-14T06:58:05+00:00 DEBUG FlareSolverr user home directory is OK: /home/node
2022-08-14T06:58:05+00:00 DEBUG Test URL: https://www.google.com
2022-08-14T06:58:05+00:00 DEBUG Creating new session...
2022-08-14T06:58:05+00:00 DEBUG Launching web browser...
2022-08-14T06:58:07+00:00 ERROR Error: SSL_ERROR_UNKNOWN at https://www.google.com
    at navigate (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:80:5)
```

**Comment by ilike2burnthing** [comment]
If you're unable to access google.com then change the `TEST_URL` env - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by samuelds** [comment]
I trying : 
````
docker run -d \
  --name=flaresolverr \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  -e TEST_URL=https://github.com \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest
````

```
2022-08-14T15:18:58+00:00 INFO FlareSolverr v2.2.10
2022-08-14T15:18:58+00:00 INFO Testing web browser installation...
2022-08-14T15:19:02+00:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
2022-08-14T15:19:02+00:00 INFO Test successful
2022-08-14T15:19:02+00:00 INFO Listening on http://0.0.0.0:8191
```

Is ok 

Retry google
````
docker run -d \
  --name=flaresolverr \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  -e TEST_URL=https://www.google.com \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest
```

```
2022-08-14T15:20:37+00:00 INFO FlareSolverr v2.2.10
2022-08-14T15:20:37+00:00 INFO Testing web browser installation...
2022-08-14T15:20:40+00:00 ERROR Error: SSL_ERROR_UNKNOWN at https://www.google.com
    at navigate (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:80:5)
````

**Comment by samuelds** [comment]
```
INFO REQ-6 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.instagram.com/p/Cj3JdhWsm7q","maxTimeout":60000}
ERROR REQ-6 Unexpected error: Error: SSL_ERROR_UNKNOWN at https://www.instagram.com/p/Cj3JdhWsm7q
ERROR REQ-6 Error: Unable to process browser request. Error: SSL_ERROR_UNKNOWN at https://www.instagram.com/p/Cj3JdhWsm7q
INFO REQ-6 Response in 3.445 s
INFO REQ-7 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.youtube.com/watch?v=xykaLzgr1Gk","maxTimeout":60000}
ERROR REQ-7 Unexpected error: Error: SSL_ERROR_UNKNOWN at https://www.youtube.com/watch?v=xykaLzgr1Gk
INFO REQ-7 Response in 3.123 s
ERROR REQ-7 Error: Unable to process browser request. Error: SSL_ERROR_UNKNOWN at https://www.youtube.com/watch?v=xykaLzgr1Gk
```

Google, Youtube, Instagram not work "SSL_ERROR_UNKNOWN"

**Comment by samuelds** [comment]
Need "no-check-certificate"
