### ISSUE TITLE
The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by CyberRim** [FlareSolverr/FlareSolverr#656]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [x] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.0.0
- Last working FlareSolverr version:
- Operating system:Debian 10
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
- Are you using a proxy or VPN: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:https://kp.m-team.cc/takelogin.php
```

### In my Jackett web ui toast:
An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid

### Logged Error Messages

```text
flareSolverr log:
2023-01-06 05:28:17 INFO     ReqId 139740566226688 192.168.2.3 POST http://192.168.2.3:8191/v1 200 OK
2023-01-06 05:28:17 INFO     ReqId 139740541048576 Challenge not detected!
2023-01-06 05:28:14 INFO     ReqId 139740566226688 Incoming request => POST /v1 body: {'postData': 'username=myusername&password=mypassword', 'maxTimeout': 100000, 'cmd': 'request.post', 'url': 'https://kp.m-team.cc/takelogin.php'}
2023-01-06 05:28:14 DEBUG    ReqId 139740566226688 Launching web browser...
2023-01-06 05:28:15 DEBUG    ReqId 139740541048576 Navigating to... https://kp.m-team.cc/takelogin.php
2023-01-06 05:28:17 DEBUG    ReqId 139740566226688 Response => POST /v1 body: {'status': 'ok', 'message': 'Challenge not detected!', 'solution': {'url': 'data:text/html;charset=utf-8,%0A        <!DOCTYPE html>%0A        <html>%0A        <body>%0A            <form id="hackForm" action="https://kp.m-team.cc/takelogin.php" method="POST"><input type="text" name="username" value="myusername"><br><input type="text" name="password" value="mypassword%22%3E%3Cbr%3E%3C/form%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cscript%3Edocument.getElementById(\'hackForm\').submit();%3C/script%3E%0A%20%20%20%20%20%20%20%20%3C/body%3E%0A%20%20%20%20%20%20%20%20%3C/html%3E', 'status': 200, 'cookies': [], 'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36', 'headers': {}, 'response': '<html><head></head><body>\n            <form id="hackForm" action="https://kp.m-team.cc/takelogin.php" method="POST"><input type="text" name="username" value="myusername"><br></form></body></html>'}, 'startTimestamp': 1672982894308, 'endTimestamp': 1672982897788, 'version': '3.0.0'}
2023-01-06 05:28:17 INFO     ReqId 139740566226688 Response in 3.48 s


jackett log:
2023-01-06T05:28:19.617823066Z 01-06 13:28:19 Error FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
2023-01-06T05:28:19.620792071Z    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2023-01-06T05:28:19.620819367Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2023-01-06T05:28:19.620828053Z    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
2023-01-06T05:28:19.621176034Z    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
2023-01-06T05:28:19.621206213Z    at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 540
2023-01-06T05:28:19.621213153Z    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 562
2023-01-06T05:28:19.621219076Z    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
2023-01-06T05:28:19.621225180Z    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
2023-01-06T05:28:19.621231143Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-01-06T05:28:19.621237251Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2023-01-06T05:28:19.621249259Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-01-06T05:28:19.621255731Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-01-06T05:28:19.621262420Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-01-06T05:28:19.621268680Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-01-06T05:28:19.621274977Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-01-06T05:28:19.621281234Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-01-06T05:28:19.621287170Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-01-06T05:28:19.621293041Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-01-06T05:28:19.621298859Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-01-06T05:28:19.621323847Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
2023-01-06T05:28:19.621336693Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2023-01-06T05:28:19.621330901Z    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2023-01-06T05:28:19.621357128Z    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
2023-01-06T05:28:19.621366142Z    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
2023-01-06T05:28:19.621372168Z    at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 540
2023-01-06T05:28:19.621378922Z    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 562
2023-01-06T05:28:19.621384672Z    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
2023-01-06T05:28:19.621390659Z    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
2023-01-06T05:28:19.621396664Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-01-06T05:28:19.621402738Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2023-01-06T05:28:19.621408795Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-01-06T05:28:19.621418179Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-01-06T05:28:19.621423850Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-01-06T05:28:19.621431126Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-01-06T05:28:19.621438020Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-01-06T05:28:19.621450193Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-01-06T05:28:19.621456601Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-01-06T05:28:19.621468388Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-01-06T05:28:19.621462528Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-01-06T05:28:19.621473951Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ngosang** [comment]
Make sure you are using the latest release of Jackett
https://github.com/Jackett/Jackett/releases/tag/v0.20.2495

**Comment by CyberRim** [comment]
> Make sure you are using the latest release of Jackett https://github.com/Jackett/Jackett/releases/tag/v0.20.2495

jackett version is v0.20.2495

```
01-06 19:54:53 Info Starting Jackett v0.20.2495 
01-06 19:54:55 Info Environment version: 6.0.12 (/app/Jackett/) 
01-06 19:54:55 Info OS version: Unix 5.10.0.0 (64bit OS) (64bit process) 
01-06 19:54:55 Info Jackett variant: CoreLinuxAmdx64 
01-06 19:54:55 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
01-06 19:54:55 Info Running in Docker: Yes (image build: v0.20.2495-ls87) 
01-06 19:54:55 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
01-06 19:54:55 Info App config/log directory: /config/Jackett 
01-06 19:54:55 Info Using proxy: Disabled 
01-06 19:54:55 Info Using FlareSolverr: http://192.168.2.3:8191 
01-06 19:54:55 Info Using HTTP Client: HttpWebClient2 
```

**Comment by ngosang** [comment]
M-Team is working fine for me with FlareSolverr 3.0.1 and Jackett v0.20.2495

**Comment by CyberRim** [comment]
> M-Team is working fine for me with FlareSolverr 3.0.1 and Jackett v0.20.2495

I found out where the problem was.
Previously my password contained the character ‘#’ like "ABCDE123#4".Then Jackett will occur “The cookies provided by FlareSolverr are not valid”.And in Flaresolverr log, the value of Form will show some HTML/JavaScript code following password string “ABCDE123#4” whthout closing double quote：
`<input type="text" name="password" value="ABCDE123#4%22%3E%3Cbr%3E%3C/form%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cscript%3Edocument.getElementById(\'hackForm\').submit();`

Now I remove the character ‘#’ and change the password to “ABCDE1234”.Then it works.
