### ISSUE TITLE
Flaresolverr fails to work

### ISSUE THREAD

**Issue by ghostklart** [FlareSolverr/FlareSolverr#662]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a proxy or VPN: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

version v.3.0.0 / v.3.0.1 does not work

using docker on ubuntu 22.04.1 (docker.io from default repo)

vars as follows:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-true}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - HEADLESS=true
      - TZ=Europe/Moscow
      - HTTP_PROXY=http://vpnproxy:8118

### Logged Error Messages

```text
2023-01-07 01:46:14 INFO     ReqId 139829441849152 FlareSolverr 3.0.1
2023-01-07 01:46:14 DEBUG    ReqId 139829441849152 Debug log enabled
2023-01-07 01:46:14 INFO     ReqId 139829441849152 Testing web browser installation...
2023-01-07 01:46:14 DEBUG    ReqId 139829441849152 Launching web browser...
2023-01-07 01:46:14 DEBUG    ReqId 139829441849152 Started executable: `/app/chromedriver` in a child process with pid: 15
Traceback (most recent call last):
  File "/app/utils.py", line 155, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 72, in get_webdriver
    driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 436, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 698, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 213, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <html>
<head>
 <title>500 Internal Privoxy Error</title>
 <link rel="shortcut icon" href="http://config.privoxy.org/error-favicon.ico" type="image/x-icon"></head>
<body>
<h1>500 Internal Privoxy Error</h1>
<p>Privoxy encountered an error while processing your request:</p>
<p><b>Could not load template file <code>connect-failed</code> or one of its included components.</b></p>
<p>Please contact your proxy administrator.</p>
<p>If you are the proxy administrator, please put the required file(s)in the <code><i>(confdir)</i>/templates</code> directory.  The location of the <code><i>(confdir)</i></code> directory is specified in the main Privoxy <code>config</code> file.  (It's typically the Privoxy install directory, or <code>/etc/privoxy/</code>).</p>
</body>
</html>



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 91, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 39, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 159, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: <html>
<head>
 <title>500 Internal Privoxy Error</title>
 <link rel="shortcut icon" href="http://config.privoxy.org/error-favicon.ico" type="image/x-icon"></head>
<body>
<h1>500 Internal Privoxy Error</h1>
<p>Privoxy encountered an error while processing your request:</p>
<p><b>Could not load template file <code>connect-failed</code> or one of its included components.</b></p>
<p>Please contact your proxy administrator.</p>
<p>If you are the proxy administrator, please put the required file(s)in the <code><i>(confdir)</i>/templates</code> directory.  The location of the <code><i>(confdir)</i></code> directory is specified in the main Privoxy <code>config</code> file.  (It's typically the Privoxy install directory, or <code>/etc/privoxy/</code>).</p>
</body>
</html>
```

### Screenshots

![image](https://user-images.githubusercontent.com/6444884/211112689-8f2d1c4c-514a-4fa7-a736-c1780cc7281a.png)

**Comment by ghostklart** [comment]
latest version in 2.2.10 works fine

**Comment by ngosang** [comment]
Proxy is not supported yet in FlareSolverr 3
It looks like the proxy is mandatory in your network.
Follow this issue => #657
