### ISSUE TITLE
[yggtorrent] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by hutigh** [FlareSolverr/FlareSolverr#664]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.0.1
- Last working FlareSolverr version:idk
- Operating system:Ubuntu
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint): "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
- Are you using a proxy or VPN: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: yggtorrent.lol
```

### Description

Hello, 

I see a lot of people having Flaresoverr working with jackett and yggtorrent but i still cant manage to make it work.
It seems with version 3.0.1 Flaresolverr now resolve easly the challenge but once it is solved jackett tells me The cookies provided by FlareSolverr are not valid.

I've read to disable ipv6 but it seems my provider dont activate ipv6 anyway so i dont know what to do can you guys help me ?

Only errors i got is from jackett not flare 
Jackett version : v0.20.2509

### Logged Error Messages

```text
FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 221
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 581
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-01-07 11:12:23	Error	
Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 221
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
```

**Comment by ngosang** [comment]
Make sure you are using latest version of Jackett

**Comment by hutigh** [comment]
v0.20.2509 still the same

**Comment by rp1989** [comment]
Also getting the same issue for BT4g. Jackett Version 'v0.20.2509' & Flaresolverr version '3.0.1' IPV6 is disabled. 

Jackett.Common.IndexerException: Exception (bt4g): The cookies provided by FlareSolverr are not valid  ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 221    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 526    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 695    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 317    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 147    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
--

**Comment by Ray-P** [comment]
Hello guys,

First of all thank you @ngosang & all 
contributors for this new version. It's looking very promising (Selenium & Python <3)

```
FlareSolverr Version  v3.0.1 (latest)
Jackett Version v0.20.2509 (latest)
```
Jackett & FlareSolverr are not running on the same server.

Jackett is running on my seedbox.
FlareSolverr is running on my Raspberry Pi.

I have the same error too, here the logs:
**FlareSolverr logs:**
![image](https://user-images.githubusercontent.com/6727063/211155321-ce9eb00e-16b6-44f0-8540-a58ad3222678.png)

**Jackett logs:**
![image](https://user-images.githubusercontent.com/6727063/211155108-4f52ef54-0a7b-40f0-a299-48e7ec945c97.png)


Thank you for your help !

**Comment by hutigh** [comment]
> Hello guys,
> 
> First of all thank you @ngosang & all contributors for this new version. It's looking very promising (Selenium & Python <3)
> 
> ```
> FlareSolverr Version  v3.0.1 (latest)
> Jackett Version v0.20.2509 (latest)
> ```
> 
> Jackett & FlareSolverr are not running on the same server.
> 
> Jackett is running on my seedbox. FlareSolverr is running on my Raspberry Pi.
> 
> I have the same error too, here the logs: **FlareSolverr logs:** ![image](https://user-images.githubusercontent.com/6727063/211155321-ce9eb00e-16b6-44f0-8540-a58ad3222678.png)
> 
> **Jackett logs:** ![image](https://user-images.githubusercontent.com/6727063/211155108-4f52ef54-0a7b-40f0-a299-48e7ec945c97.png)
> 
> Thank you for your help !

Same as him i'm not running flaresolverr on the same server i'm running it on ionos and jackett on my seedbox server

**Comment by ngosang** [comment]
They MUST run in the same machine. Cloudflare cookie is only valid for the same User-Agent and IP.

**Comment by rp1989** [comment]
> They MUST run in the same machine. Cloudflare cookie is only valid for the same User-Agent and IP.

Both flaresolverr and jackett containers are setup on the same qnap nas for me but still get that message.

**Comment by hutigh** [comment]
Okay thx for the info i'll try it i though we could do it with separate server

**Comment by hutigh** [comment]
Okay for me it is now working witg flare and jackett on the same machine it was my mistake i can let it open maybe for the other people asking for help instead of opening another thread

**Comment by rp1989** [comment]
> Okay for me it is now working with flare and jackett on the same machine it was my mistake i can let it open maybe for the other people asking for help instead of opening another thread

Glad its working for you now. Are you able to explain a bit more about your setup please? I am using container station on a Qnap nas and have both the Flaresolverr and Jackett docker containers on the same machine and same network adapter but still get this error.

**Comment by rp1989** [comment]
Seems to have started working for me now without doing anything.

**Comment by rp1989** [comment]
Updated Jackett to Version v0.20.2593 still experiencing the same issue.

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.0.2 but I don't think it will solve this issue.

**Comment by Machou** [comment]
> https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.0.2 but I don't think it will solve this issue.

Nop, not solve.

**FlareSolverr** 3.0.2
**Jackett** 0.20.2593 

```text

2023-01-08 22:16:20	Error	
FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
2023-01-08 22:15:47	Error	
Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 522
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
```

**Comment by fred-gb** [comment]
Hi,

Docker
Flaresolverr 3.0.2
Prowlarr: 1.0.1.2220
Jackett: v0.20.2593

```
2023-01-09 18:34:37 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-09 18:34:37 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-01-09 18:35:04 INFO     Challenge detected. Title found: Just a moment...
2023-01-09 18:36:40 ERROR    Error: Error solving the challenge. Timeout after 120.0 seconds.
2023-01-09 18:36:40 INFO     Response in 123.649 s
2023-01-09 18:36:40 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

With ou without cookie method.

Somestimes, In logs:
```
2023-01-09 18:40:21 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-09 18:40:21 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-01-09 18:40:53 ERROR    Error: Error solving the challenge. Message: session not created
from tab crashed
  (Session info: chrome=108.0.5359.124)
Stacktrace:
#0 0x55b4dbb4b133 <unknown>
#1 0x55b4db8ea09c <unknown>
#2 0x55b4db8d7a94 <unknown>
#3 0x55b4db8d6ee9 <unknown>
#4 0x55b4db8d61df <unknown>
#5 0x55b4db8d6090 <unknown>
#6 0x55b4db8d49dd <unknown>
#7 0x55b4db8d5044 <unknown>
#8 0x55b4db8f8248 <unknown>
#9 0x55b4db8ee3a3 <unknown>
#10 0x55b4db8ede14 <unknown>
#11 0x55b4db8ee99e <unknown>
#12 0x55b4db8eede4 <unknown>
#13 0x55b4db95954d <unknown>
#14 0x55b4db957de0 <unknown>
#15 0x55b4db950903 <unknown>
#16 0x55b4db91a6b6 <unknown>
#17 0x55b4db91b8f5 <unknown>
#18 0x55b4dbb8ce2d <unknown>
#19 0x55b4dbb8eaf7 <unknown>
#20 0x55b4dbb8e520 <unknown>
#21 0x55b4dbb8f205 <unknown>
#22 0x55b4dbb7b8eb <unknown>
#23 0x55b4dbb8f536 <unknown>
#24 0x55b4dbb6e27e <unknown>
#25 0x55b4dbba79f5 <unknown>
#26 0x55b4dbba7b9a <unknown>
#27 0x55b4dbbc13d0 <unknown>
#28 0x7fce90cedea7 start_thread

2023-01-09 18:40:53 INFO     Response in 69.757 s
2023-01-09 18:40:53 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
2023-01-09 18:40:55 ERROR    Error: Error solving the challenge. Message: unknown error: unable to discover open window in chrome
  (Session info: chrome=108.0.5359.124)
Stacktrace:
#0 0x55ed0c7e4133 <unknown>
#1 0x55ed0c583358 <unknown>
#2 0x55ed0c55cc74 <unknown>
#3 0x55ed0c5f1426 <unknown>
#4 0x55ed0c5f0de0 <unknown>
#5 0x55ed0c5e9903 <unknown>
#6 0x55ed0c5b36b6 <unknown>
#7 0x55ed0c5b48f5 <unknown>
#8 0x55ed0c825e2d <unknown>
#9 0x55ed0c827af7 <unknown>
#10 0x55ed0c827520 <unknown>
#11 0x55ed0c828205 <unknown>
#12 0x55ed0c8148eb <unknown>
#13 0x55ed0c828536 <unknown>
#14 0x55ed0c80727e <unknown>
#15 0x55ed0c8409f5 <unknown>
#16 0x55ed0c840b9a <unknown>
#17 0x55ed0c85a3d0 <unknown>
#18 0x7fe737ac1ea7 start_thread

2023-01-09 18:40:55 INFO     Response in 69.76 s
2023-01-09 18:40:55 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

Thanks

**Comment by rp1989** [comment]
> https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.0.2 but I don't think it will solve this issue.

Hi, still the same with this release unfortunately.

**Comment by ngosang** [comment]
@fred-gb what is your hardware?

**Comment by fred-gb** [comment]
VPS

**Comment by ngosang** [comment]
Run `uname -a` and `cat /etc/issue`

**Comment by fred-gb** [comment]
`uname -a`

```
Linux vps 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

`cat /etc/issue`

```
Ubuntu 20.04.5 LTS \n \l
```

**Comment by rp1989** [comment]
uname -a
Linux RajanNAS 5.10.60-qnap #1 SMP Thu Dec 15 01:02:36 CST 2022 x86_64 GNU/Linux

cat /etc/issue
Welcome to TBS-464, QNAP Systems, Inc.

**Comment by gumballwat** [comment]
hi all,

same issue here :'(,

Linux plex-web 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
Debian GNU/Linux 11 \n \l


01-10 18:45:02 Error Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 695
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 440

Thank you for your help

**Comment by arashtotti88** [comment]
hi

I still have this problem

any solution?

thanks for the hard work

**Comment by ilike2burnthing** [comment]
Disable IPv6 for Jackett/Prowlarr and FlareSolverr, make sure they're using the same IP on the same device, disable any proxies or VPNs.

Other than that, no, just wait for the DDoS attacks against YGG to stop so they can  drop their Cloudflare protection.

**Comment by angarod** [comment]
When using docker for flaresolverr execution, it works for me only with 
`--network host` in the docker arguments.
This allow the container to share the host IP and not using the usual nat.

**Comment by grogniakss** [comment]
Thanks Angarod! I followed your step and it solved the problem. You're a true GitHub ninja !

**Comment by eleanorcuallado** [comment]
> When using docker for flaresolverr execution, it works for me only with `--network host` in the docker arguments. This allow the container to share the host IP and not using the usual nat.

Welp, I guess I discovered that host network mode is, in fact, only available for Linux. I do believe this means the only option left for Windows would be having binaries for 3.0.2...

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by eleanorcuallado** [comment]
I have just tested and it indeed works when I run it from source for Windows! Thanks a lot :D

**Comment by ngosang** [comment]
> The cookies provided by FlareSolverr are not valid

This error could be caused by several reasons:
* Jackett and FlareSolverr are in different networks (for example, one uses VPN and the other does not. another example, one is running in your computer and the other in a server)
* FlareSolverr Docker container is running with IPv6. You have to disable IPv6 (read previous messages in this issue)
* Cloudflare changed something important in the challenge and I have to update FlareSolverr.
