### ISSUE TITLE
I am getting 500 Internal Server Error In Response

### ISSUE THREAD

**Issue by bbbvcrain** [FlareSolverr/FlareSolverr#667]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.0.2
- Last working FlareSolverr version: None
- Operating system: Windows 10
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a proxy or VPN: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one: no
- URL to test this issue: https://torn.com
```

### Description

Hey, While i did a get request to https://torn.com I am getting 500 internal error response with no cookies

### Logged Error Messages

```text
2023-01-10 09:45:05 DEBUG    ReqId 4432 Navigating to... http://www.torn.com
2023-01-10 09:45:05 INFO     ReqId 4432 Challenge detected. Selector found: #trk_jschal_js
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for title: Just a moment...
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for title: DDOS-GUARD
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for selector: #cf-challenge-running
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for selector: .ray_id
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for selector: .attack-box
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for selector: #cf-please-wait
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for selector: #challenge-spinner
2023-01-10 09:45:05 DEBUG    ReqId 4432 Waiting for selector: #trk_jschal_js
2023-01-10 09:45:16 DEBUG    ReqId 4432 Timeout waiting for selector
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for title: Just a moment...
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for title: DDOS-GUARD
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for selector: #cf-challenge-running
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for selector: .ray_id
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for selector: .attack-box
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for selector: #cf-please-wait
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for selector: #challenge-spinner
2023-01-10 09:45:16 DEBUG    ReqId 4432 Waiting for selector: #trk_jschal_js
```

**Comment by bbbvcrain** [comment]
Hey actually the flare doesn't works with my target which is torn.com can i do something about it? other target works

**Comment by GravuTrad** [comment]
Same problem 500 internal server error even if my server ports are ok for my personal ip.

**Comment by Jamy50** [comment]
Exactly same problem :(

**Comment by MrAuronTV** [comment]
same for me

**Comment by elin1023** [comment]
Same problem for me. Using Docker for Windows, version FlareSolverr 3.0.2
My logs are:
```
2023-02-18 16:18:25 2023-02-18 08:18:25 INFO     FlareSolverr 3.0.2
2023-02-18 16:18:25 2023-02-18 08:18:25 INFO     Testing web browser installation...
2023-02-18 16:18:25 2023-02-18 08:18:25 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-02-18 16:18:25 2023-02-18 08:18:25 INFO     Chrome / Chromium major version: 108
2023-02-18 16:18:26 2023-02-18 08:18:26 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
2023-02-18 16:18:26 2023-02-18 08:18:26 INFO     Test successful
2023-02-18 16:18:26 2023-02-18 08:18:26 INFO     Serving on http://0.0.0.0:8191
2023-02-18 16:18:31 2023-02-18 08:18:31 INFO     172.17.0.1 GET http://localhost:8191/ 200 OK
2023-02-18 16:18:42 2023-02-18 08:18:42 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': '<WEBSITE>', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-18 16:18:43 2023-02-18 08:18:43 INFO     Challenge detected. Title found: Just a moment...
2023-02-18 16:19:42 2023-02-18 08:19:42 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': '<WEBSITE>', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-18 16:19:43 2023-02-18 08:19:43 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-18 16:19:43 2023-02-18 08:19:43 INFO     Response in 60.901 s
2023-02-18 16:19:43 2023-02-18 08:19:43 INFO     172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
2023-02-18 16:19:43 2023-02-18 08:19:43 INFO     Challenge detected. Title found: Just a moment...
2023-02-18 16:18:25 find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
2023-02-18 16:20:42 2023-02-18 08:20:42 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-18 16:20:42 2023-02-18 08:20:42 INFO     Response in 60.705 s
2023-02-18 16:20:42 2023-02-18 08:20:42 INFO     172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
2023-02-18 16:20:46 2023-02-18 08:20:46 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': '<WEBSITE>', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-18 16:20:47 2023-02-18 08:20:47 INFO     Challenge detected. Title found: Just a moment...
2023-02-18 16:21:47 2023-02-18 08:21:47 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-18 16:21:47 2023-02-18 08:21:47 INFO     Response in 60.831 s
2023-02-18 16:21:47 2023-02-18 08:21:47 INFO     172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

and it goes on and on.

**Comment by MrTyton** [comment]
+1. Issue started on Thursday. Running 3.0.2 in Docker, image was working fine for the last month.

```
02/18/2023 10:05:01 AM
2023-02-18 15:05:01 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14043289/1/Raise', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
02/18/2023 10:05:02 AM
2023-02-18 15:05:02 INFO     Challenge detected. Title found: Just a moment...
02/18/2023 10:05:06 AM
2023-02-18 15:05:06 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
02/18/2023 10:05:06 AM
2023-02-18 15:05:06 INFO     Response in 65.735 s
02/18/2023 10:05:06 AM
2023-02-18 15:05:06 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
```

**Comment by malambert35** [comment]
Same issue, in docker on Unraid.

**Comment by ekirchman** [comment]
Started for me as well this week on docker. Was working just fine the other day

```
flaresolverr    | 2023-02-18 16:29:30 INFO     FlareSolverr 3.0.2
flaresolverr    | 2023-02-18 16:29:30 INFO     Testing web browser installation...
flaresolverr    | 2023-02-18 16:29:30 INFO     Chrome / Chromium path: /usr/bin/chromium
flaresolverr    | find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
flaresolverr    | 2023-02-18 16:29:30 INFO     Chrome / Chromium major version: 108
flaresolverr    | 2023-02-18 16:29:33 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
flaresolverr    | 2023-02-18 16:29:33 INFO     Test successful
flaresolverr    | 2023-02-18 16:29:33 INFO     Serving on http://0.0.0.0:8191
flaresolverr    | 2023-02-18 16:29:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/'}
flaresolverr    | 2023-02-18 16:29:44 INFO     Challenge detected. Title found: Just a moment...
flaresolverr    | 2023-02-18 16:30:36 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
flaresolverr    | 2023-02-18 16:30:36 INFO     Response in 56.525 s
flaresolverr    | 2023-02-18 16:30:36 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by estikf** [comment]
I am having the same issue, started on thursday.

**Comment by bensamou** [comment]
Same here since last week in Unraid Docker. Tried through Prowlarr and Jackett.

**Comment by MrTyton** [comment]
It's also been constantly crashing with error code 1

Logs don't seem to give a reason why


```
2023-02-21 10:34:28 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
2023-02-21 10:35:32 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
2023-02-21 10:35:32 INFO     Response in 65.737 s
2023-02-21 10:35:32 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
2023-02-21 10:35:35 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14066102/1/Arc-Corp', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
2023-02-21 10:35:36 INFO     Challenge detected. Title found: Just a moment...
2023-02-21 10:36:40 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
2023-02-21 10:36:40 INFO     Response in 65.629 s
2023-02-21 10:36:40 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
2023-02-21 10:36:51 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14066102/1/Arc-Corp', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
2023-02-21 10:36:52 INFO     Challenge detected. Title found: Just a moment...

** Press ANY KEY to close this window ** 
```

**Comment by albyofdoom** [comment]
Was experiencing the same issue using the unraid docker container (with 3.0.2), so installed fresh on a Win10 box. At first it looked like it was going to do the same thing, but after the first timeout, it was able to successfully solve the challenge. I can draw no conclusions from this, just adding more data for someone smarter than me to work with. :)

Win10 Results:
```
2023-02-22 08:07:27 INFO     FlareSolverr 3.0.2
2023-02-22 08:07:27 INFO     Testing web browser installation...
2023-02-22 08:07:27 INFO     Chrome / Chromium path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
2023-02-22 08:07:27 INFO     Chrome / Chromium major version: 110
2023-02-22 08:07:33 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
2023-02-22 08:07:33 INFO     Test successful
2023-02-22 08:07:34 INFO     Serving on http://0.0.0.0:8191
2023-02-22 08:08:37 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 08:08:39 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 08:09:37 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 08:09:41 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-22 08:09:41 INFO     Response in 64.051 s
2023-02-22 08:09:41 INFO     192.168.1.120 POST http://192.168.1.120:8191/v1 500 Internal Server Error
2023-02-22 08:09:43 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 08:10:29 INFO     Challenge solved!
2023-02-22 08:10:30 INFO     Response in 52.982 s
2023-02-22 08:10:30 INFO     192.168.1.120 POST http://192.168.1.120:8191/v1 200 OK
```

From Unraid Docker:
```2023-02-22 16:43:57 INFO     FlareSolverr 3.0.2
2023-02-22 16:43:57 INFO     Testing web browser installation...
2023-02-22 16:43:57 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-02-22 16:44:00 INFO     Chrome / Chromium major version: 108
2023-02-22 16:44:02 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
2023-02-22 16:44:02 INFO     Test successful
2023-02-22 16:44:02 INFO     Serving on http://0.0.0.0:8191
2023-02-22 16:49:11 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 16:49:18 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 16:50:11 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 16:50:12 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-22 16:50:12 INFO     Response in 61.197 s
2023-02-22 16:50:12 INFO     192.168.1.120 POST http://192.168.1.125:8191/v1 500 Internal Server Error
2023-02-22 16:50:19 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 16:51:12 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-22 16:51:12 INFO     Response in 61.077 s
2023-02-22 16:51:12 INFO     192.168.1.120 POST http://192.168.1.125:8191/v1 500 Internal Server Error
2023-02-22 16:51:15 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 16:51:22 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 16:52:16 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-22 16:52:16 INFO     Response in 60.958 s
2023-02-22 16:52:16 INFO     192.168.1.120 POST http://192.168.1.125:8191/v1 500 Internal Server Error
2023-02-22 16:52:23 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 16:52:31 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 16:53:24 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-22 16:53:24 INFO     Response in 60.963 s
2023-02-22 16:53:24 INFO     192.168.1.120 POST http://192.168.1.125:8191/v1 500 Internal Server Error
2023-02-22 16:53:39 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fictionpress.com/s/3213420/1/Tales-of-the-Union', 'maxTimeout': 60000, 'cookies': [], 'postData': None}
2023-02-22 16:53:47 INFO     Challenge detected. Title found: Just a moment...
2023-02-22 16:54:41 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-22 16:54:41 INFO     Response in 61.513 s
2023-02-22 16:54:41 INFO     192.168.1.120 POST http://192.168.1.125:8191/v1 500 Internal Server Error
```

edit: I noticed after the fact that Win10 is running Chrome 110, and the Docker is running 108. I attempted to updated the docker to 110, but that failed with an error that the undetected-chromedriver only supports build 108. Not sure how to update that component, as it wasn't something listed when I used apt to upgrade chrome.

**Comment by GravuTrad** [comment]
another one

https://github.com/FlareSolverr/FlareSolverr/issues/667

**Comment by Zxurian** [comment]
getting similar error when trying to use with 1337x.to. This is on Unraid with container for `flaresolverr/flaresolverr` & `lscr.io/linuxserver/prowlarr`

flaresolverr logs when prowlarr tries a request
```
2023-02-24 22:50:53 INFO     ReqId 22802995177216 Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-02-24 22:50:53 WARNING  ReqId 22802995177216 Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-02-24 22:50:53 DEBUG    ReqId 22802995177216 Launching web browser...
2023-02-24 22:50:53 DEBUG    ReqId 22802995177216 Started executable: `/app/chromedriver` in a child process with pid: 857
2023-02-24 22:50:54 DEBUG    ReqId 22802781427456 Navigating to... https://1337x.to/cat/Movies/time/desc/1/
2023-02-24 22:50:55 INFO     ReqId 22802781427456 Challenge detected. Title found: Just a moment...
2023-02-24 22:50:55 DEBUG    ReqId 22802781427456 Waiting for title: Just a moment...
2023-02-24 22:51:06 DEBUG    ReqId 22802781427456 Timeout waiting for selector
2023-02-24 22:51:06 DEBUG    ReqId 22802781427456 Waiting for title: Just a moment...
2023-02-24 22:51:16 DEBUG    ReqId 22802781427456 Timeout waiting for selector
2023-02-24 22:51:16 DEBUG    ReqId 22802781427456 Waiting for title: Just a moment...
2023-02-24 22:51:26 DEBUG    ReqId 22802781427456 Timeout waiting for selector
2023-02-24 22:51:26 DEBUG    ReqId 22802781427456 Waiting for title: Just a moment...
2023-02-24 22:51:36 DEBUG    ReqId 22802781427456 Timeout waiting for selector
2023-02-24 22:51:36 DEBUG    ReqId 22802781427456 Waiting for title: Just a moment...
2023-02-24 22:51:46 DEBUG    ReqId 22802781427456 Timeout waiting for selector
2023-02-24 22:51:46 DEBUG    ReqId 22802781427456 Waiting for title: Just a moment...
2023-02-24 22:51:54 ERROR    ReqId 22802995177216 Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-02-24 22:51:54 DEBUG    ReqId 22802995177216 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 60.0 seconds.', 'startTimestamp': 1677297053348, 'endTimestamp': 1677297114387, 'version': '3.0.2'}
2023-02-24 22:51:54 INFO     ReqId 22802995177216 Response in 61.039 s
2023-02-24 22:51:54 INFO     ReqId 22802995177216 172.31.200.203 POST http://172.31.200.205:8191/v1 500 Internal Server Error
```

**Comment by GravuTrad** [comment]
seems since the start of version 3:

https://github.com/FlareSolverr/FlareSolverr/issues/522

**Comment by Zxurian** [comment]
Just fired up my firefox container on the same `wg0` network, went to the same address as requested in the flaresolverr logs, and got no cloudflare challenge. Also confirmed no ip6 (saw that mentioned elsewhere). Is the useragent / chromium that flaresolverr is using arbitrarily triggering a cloudflare challenge?

**Comment by Crosus97** [comment]
same here with dontorrent

**Comment by rix1337** [comment]
#715 solves the issue described in this thread. Seems like an easy merge / simple fix.

For those eager to test this fix, I have built and made available the fixed version:
```
docker run -d \
  --name=flaresolverr \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  --restart unless-stopped \
  rix1337/docker-flaresolverr:pull-request-715
```

**Comment by ilike2burnthing** [comment]
v3.0.3 should resolve the issue. Retry a few times if it continues after updating.

**Comment by MrTyton** [comment]
I still think that something isn't working properly.

```
03/06/2023 4:30:14 PM
2023-03-06 21:30:14 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:31:41 PM
2023-03-06 21:31:41 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14004904/1/The-Eternal-Crown', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:31:42 PM
2023-03-06 21:31:42 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:32:08 PM
2023-03-06 21:32:08 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
03/06/2023 4:32:08 PM
2023-03-06 21:32:08 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
03/06/2023 4:32:09 PM
2023-03-06 21:32:09 INFO     Challenge not detected!
03/06/2023 4:32:09 PM
2023-03-06 21:32:09 INFO     Response in 0.821 s
03/06/2023 4:32:09 PM
2023-03-06 21:32:09 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 200 OK
03/06/2023 4:32:41 PM
2023-03-06 21:32:41 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14004904/1/The-Eternal-Crown', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:32:42 PM
2023-03-06 21:32:42 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:32:47 PM
2023-03-06 21:32:47 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:32:47 PM
2023-03-06 21:32:47 INFO     Response in 65.748 s
03/06/2023 4:32:47 PM
2023-03-06 21:32:47 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:33:45 PM
2023-03-06 21:33:45 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14004904/1/The-Eternal-Crown', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:33:46 PM
2023-03-06 21:33:46 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:33:47 PM
2023-03-06 21:33:47 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:33:47 PM
2023-03-06 21:33:47 INFO     Response in 65.628 s
03/06/2023 4:33:47 PM
2023-03-06 21:33:47 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:34:51 PM
2023-03-06 21:34:51 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:34:51 PM
2023-03-06 21:34:51 INFO     Response in 65.729 s
03/06/2023 4:34:51 PM
2023-03-06 21:34:51 INFO     172.17.0.1 POST http:///v1 500 Internal Server Error
03/06/2023 4:34:53 PM
2023-03-06 21:34:53 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14004904/1/The-Eternal-Crown', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:34:54 PM
2023-03-06 21:34:54 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:35:59 PM
2023-03-06 21:35:59 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:35:59 PM
2023-03-06 21:35:59 INFO     Response in 65.729 s
03/06/2023 4:35:59 PM
2023-03-06 21:35:59 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:36:09 PM
2023-03-06 21:36:09 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14004904/1/The-Eternal-Crown', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:36:10 PM
2023-03-06 21:36:10 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:37:10 PM
2023-03-06 21:37:10 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14147353/1/Remnant-Invicta', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:37:11 PM
2023-03-06 21:37:11 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:37:15 PM
2023-03-06 21:37:15 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:37:15 PM
2023-03-06 21:37:15 INFO     Response in 65.715 s
03/06/2023 4:37:15 PM
2023-03-06 21:37:15 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:38:10 PM
2023-03-06 21:38:10 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14147353/1/Remnant-Invicta', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:38:11 PM
2023-03-06 21:38:11 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:38:16 PM
2023-03-06 21:38:16 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:38:16 PM
2023-03-06 21:38:16 INFO     Response in 65.702 s
03/06/2023 4:38:16 PM
2023-03-06 21:38:16 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:39:14 PM
2023-03-06 21:39:14 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14147353/1/Remnant-Invicta', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:39:15 PM
2023-03-06 21:39:15 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:39:16 PM
2023-03-06 21:39:16 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:39:16 PM
2023-03-06 21:39:16 INFO     Response in 65.728 s
03/06/2023 4:39:16 PM
2023-03-06 21:39:16 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:40:20 PM
2023-03-06 21:40:20 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:40:20 PM
2023-03-06 21:40:20 INFO     Response in 65.628 s
03/06/2023 4:40:20 PM
2023-03-06 21:40:20 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:40:22 PM
2023-03-06 21:40:22 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14147353/1/Remnant-Invicta', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:40:23 PM
2023-03-06 21:40:23 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:41:28 PM
2023-03-06 21:41:28 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:41:28 PM
2023-03-06 21:41:28 INFO     Response in 65.63 s
03/06/2023 4:41:28 PM
2023-03-06 21:41:28 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:41:38 PM
2023-03-06 21:41:38 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/14147353/1/Remnant-Invicta', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:41:39 PM
2023-03-06 21:41:39 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:42:44 PM
2023-03-06 21:42:44 ERROR    Error: Error solving the challenge. Timeout after 65.0 seconds.
03/06/2023 4:42:44 PM
2023-03-06 21:42:44 INFO     Response in 65.728 s
03/06/2023 4:42:44 PM
2023-03-06 21:42:44 INFO     172.17.0.1 POST http://xxx.xxx.x.xxx:xxxx/v1 500 Internal Server Error
03/06/2023 4:42:45 PM
2023-03-06 21:42:45 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.fanfiction.net/s/13931794/1/Legendarily-Popular', 'maxTimeout': 65000, 'cookies': [], 'postData': None}
03/06/2023 4:42:46 PM
2023-03-06 21:42:46 INFO     Challenge detected. Title found: Just a moment...
03/06/2023 4:43:45 PM
Traceback (most recent call last):
03/06/2023 4:43:45 PM
  File "/app/flaresolverr.py", line 95, in <module>
03/06/2023 4:43:45 PM
    run(app, host=server_host, port=server_port, quiet=True, server='waitress')
03/06/2023 4:43:45 PM
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 3172, in run
03/06/2023 4:43:45 PM
    server.run(app)
03/06/2023 4:43:45 PM
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 2853, in run
03/06/2023 4:43:45 PM
    serve(handler, host=self.host, port=self.port)
03/06/2023 4:43:45 PM
  File "/usr/local/lib/python3.11/site-packages/waitress/__init__.py", line 19, in serve
03/06/2023 4:43:45 PM
    server.run()
03/06/2023 4:43:45 PM
  File "/usr/local/lib/python3.11/site-packages/waitress/server.py", line 322, in run
03/06/2023 4:43:45 PM
    self.asyncore.loop(
03/06/2023 4:43:45 PM
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 245, in loop
03/06/2023 4:43:45 PM
    poll_fun(timeout, map)
03/06/2023 4:43:45 PM
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 172, in poll
03/06/2023 4:43:45 PM
    r, w, e = select.select(r, w, e, timeout)
03/06/2023 4:43:45 PM
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
03/06/2023 4:43:45 PM
ValueError: filedescriptor out of range in select()
03/06/2023 4:47:02 PM
2023-03-06 21:47:02 INFO     FlareSolverr 3.0.3
03/06/2023 4:47:02 PM
2023-03-06 21:47:02 INFO     Testing web browser installation...
03/06/2023 4:47:02 PM
2023-03-06 21:47:02 INFO     Chrome / Chromium path: /usr/bin/chromium
```

Been failing like this for at least a few hours, even after restarts of the container.

**Comment by GravuTrad** [comment]
Not solved by 3.0.3, always the same problem

**Comment by ilike2burnthing** [comment]
Try v3.0.4

**Comment by MrTyton** [comment]
v3.0.4 seems to work. It's being challenged each time, so I guess it's not storing the session/cookies, but it is working (23 seconds  a page though lol). I'll put it through some more stress tests, but hopefully this resolves it for a long while.

Thanks for the effort!

**Comment by GravuTrad** [comment]
solved so. thanks.

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.0

**Comment by Baltimorepc** [comment]
Have they fixed this yet. AS its been happening to me and i cant get passed any checks. i cant add any of the indexers as none will enable as they keep timing out  this shows for everyone i try (different url of course)

Incoming request => POST /v1 body: {'maxTimeout': 80000, 'cmd': 'request.get', 'url': 'https://idope.se/browse.html', 'proxy': {}}
2025-02-09T16:50:10.351385890Z 2025-02-09 11:50:10 INFO     Challenge detected. Title found: Just a moment...
2025-02-09T16:50:55.540987205Z 2025-02-09 11:50:55 INFO     REDACTED GET http://REDACTED:****/ 200 OK
2025-02-09T16:51:26.819196900Z 2025-02-09 11:51:26 ERROR    Error: Error solving the challenge. Timeout after 80.0 seconds.

**Comment by ilike2burnthing** [comment]
See pinned issues and open PRs.
