### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceled

### ISSUE THREAD

**Issue by eejag** [FlareSolverr/FlareSolverr#670]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: 2.2.10
- Operating system: Debian 11
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a proxy or VPN: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Since end of Nov 2022, yggtorrent indexer has been non functional for several people. I opened another issue previously about it (#596 ) which was closed upon release of FlareSolverr 3.0.0 .

Unfortunately the issue remains despite improvements for some. Installing a fork and/or docker in my case (thinking about aeonlucid's fork) is not possible.

I'm using FlareSolverr with Jackett (v0.20.2660). Tried with Prowlarr as well without success.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 75 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```

**Comment by Write** [comment]
Same here. I can add YGGCookie but not YGGTorrent. When adding it just show nothing and after 60 sec the exception in the console.

**Comment by ilike2burnthing** [comment]
Add and test the indexer TorrentQQ. Does it work and trigger FlareSolverr?

**Comment by eejag** [comment]
> Add and test the indexer TorrentQQ. Does it work and trigger FlareSolverr?

Looks like I face the same issue when testing TorrentQQ:

```
Jackett.Common.IndexerException: Exception (torrentqq): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 75 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```

**Comment by Write** [comment]
Never mind it works for me after I’ve updated flaresolverr IP in Jackett’s config at the bottom,Really sorry.Le 17 janv. 2023 à 04:13, ilike2burnthing - notifications(a)github.com ***@***.***> a écrit :﻿
Add and test the indexer TorrentQQ. Does it work and trigger FlareSolverr?

**Comment by ilike2burnthing** [comment]
If you access the FlareSolverr API URL (that you've used in Jackett) in your browser on the same device, what is returned?

**Comment by eejag** [comment]
> If you access the FlareSolverr API URL (that you've used in Jackett) in your browser on the same device, what is returned?

This is what the browser (Firefox in this case) returns:
![image](https://user-images.githubusercontent.com/2801276/212878821-4296afc8-c475-4ec5-9a89-dfad5ecca732.png)

Would the log file from Prowlarr helps? It seems to contain more information

**Comment by ilike2burnthing** [comment]
Ok, that looks fine. Any reason you changed the port from default?

Sure, provide the log.

**Comment by eejag** [comment]
> Ok, that looks fine. Any reason you changed the port from default?
> 
> Sure, provide the log.

Given i don't know shit about linux (or the bare minimum), i'm using the service quickbox.io which helps setting up a media server. Flaresolverr is installed with a random port around 8191.

Here are the relevant logs for an attempt to add yggtorrent to prowlar a bit earlier:
[prowlarr_logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/10434708/prowlarr_logs.txt)

**Comment by ilike2burnthing** [comment]
Try Jackett instead, see if that makes a difference.

**Comment by eejag** [comment]
> Try Jackett instead, see if that makes a difference.

I normally use Jackett. I've just tried Prowlarr to see if I would have better luck.

Here's the log from Jackett from the latest "test" on yggtorrent:
[log.txt](https://github.com/FlareSolverr/FlareSolverr/files/10436150/log.txt)

**Comment by ilike2burnthing** [comment]
The FlareSolverr log is going to be of more use here.

**Comment by eejag** [comment]
I can't seem to find any of the logs. Any place i should be checking in particular? Is there a command maybe to view them or to ensure logging is on?

**Comment by ilike2burnthing** [comment]
Run FlareSolverr from command line and you'll get the logged output in that window.

**Comment by eejag** [comment]
So... remember when I said I didn't know shit about Linux?


While in /opt/<user>/FlareSolverr, I tried to execute with:
`python3 src/flaresolverr.py`

It returned the following:
```
Traceback (most recent call last):
  File "/opt/<user>/FlareSolverr/src/flaresolverr.py", line 6, in <module>
    from bottle import run, response, Bottle, request
ModuleNotFoundError: No module named 'bottle'
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by eejag** [comment]
> https://github.com/FlareSolverr/FlareSolverr#from-source-code

Ok. Installed the requirements and executed again. It shows this, and doesn't go back to the prompt:
```
2023-01-18 11:40:26 INFO     FlareSolverr 3.0.2
2023-01-18 11:40:26 INFO     Testing web browser installation...
2023-01-18 11:40:26 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-01-18 11:40:26 INFO     Chrome / Chromium major version: 109
2023-01-18 11:40:27 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
2023-01-18 11:40:27 INFO     Test successful
```

**Comment by ilike2burnthing** [comment]
Ok, so now run a test with TorrentQQ and provide the returned output.

**Comment by eejag** [comment]
Really sorry to sound like a dumbass but how do i do that from the command line? or you mean the output from jackett?

If from jackett:
```
Jackett.Common.IndexerException: Exception (torrentqq): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```

**Comment by ilike2burnthing** [comment]
Run the test in Jackett and provide the output in the FlareSolverr window, not from Jackett's logs.

**Comment by eejag** [comment]
> Run the test in Jackett and provide the output in the FlareSolverr window, not from Jackett's logs.

Nothing changed on the FlareSolverr window, last line remains "Test successful"

For clarity:
- I ssh onto my server
- I ran python3 src/flaresolverr.py in the terminal
- I opened the jackett web page
- Tested TorrentQQ
=> output in jackett similar as the one posted above, and no change in the terminal with flaresolverr

**Comment by ilike2burnthing** [comment]
K, then something is blocking Jackett and FlareSolverr from communicating. If it's not an AV, firewall, or some other security software, then I'm not really sure where else to look.

**Comment by eejag** [comment]
Thanks for having taken the time to check. I'll keep investigating on my side.
I've just noticed i'm using Python 3.9.2 while the recommandation is 3.10. I'll look into this

Please feel free too close the issue if there's no further leads on your side

**Comment by eejag** [comment]
**Quick update on my side:**

- I've uninstalled and reinstalled FlareSolverr - as mentioned above, the service I use (quickbox) assigns a random port to FlareSolverr, it's 8237 now
- Executing the script flaresolver returns an additional line this time:

> ❯ python3 src/flaresolverr.py
> 2023-01-24 17:57:43 INFO     FlareSolverr 3.0.2
> 2023-01-24 17:57:43 INFO     Testing web browser installation...
> 2023-01-24 17:57:43 INFO     Chrome / Chromium path: /bin/chromium
> 2023-01-24 17:57:43 INFO     Chrome / Chromium major version: 109
> 2023-01-24 17:57:44 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> 2023-01-24 17:57:44 INFO     Test successful
> 2023-01-24 17:57:44 INFO     Serving on http://0.0.0.0:8191

- In Jackett, setting Flaresolver API URL url to: http://myserverIP:8191
- Testing TorrentQQ, returns the following in the script window:

> ❯ python3 src/flaresolverr.py
> 2023-01-24 18:04:11 INFO     FlareSolverr 3.0.2
> 2023-01-24 18:04:11 INFO     Testing web browser installation...
> 2023-01-24 18:04:11 INFO     Chrome / Chromium path: /bin/chromium
> 2023-01-24 18:04:11 INFO     Chrome / Chromium major version: 109
> 2023-01-24 18:04:12 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> 2023-01-24 18:04:12 INFO     Test successful
> 2023-01-24 18:04:12 INFO     Serving on http://0.0.0.0:8191
> 2023-01-24 18:05:16 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://torrentqq240.com/torrent/newest.html'}
> 2023-01-24 18:05:17 INFO     Challenge detected. Title found: Just a moment...
> 2023-01-24 18:05:19 INFO     Challenge solved!
> 2023-01-24 18:05:19 INFO     Response in 3.538 s
> 2023-01-24 18:05:19 INFO     176.9.19.180 POST http://myserverIP:8191/v1 200 OK

**Comments:**

- my whole server and all apps are only accessible via https, if i try to put the API URL as https, I get the errors mentioned previously
- if i try to put the local ip or the installation port (8237), same errors
- if i try export PORT=8237 before executing the script, it won't run (see errors below) and i have to change the port back to 8191 in the script:

> ❯ python3 src/flaresolverr.py
> 2023-01-24 18:11:40 INFO     FlareSolverr 3.0.2
> 2023-01-24 18:11:40 INFO     Testing web browser installation...
> 2023-01-24 18:11:40 INFO     Chrome / Chromium path: /usr/bin/chromium
> 2023-01-24 18:11:40 INFO     Chrome / Chromium major version: 109
> 2023-01-24 18:11:41 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
> 2023-01-24 18:11:41 INFO     Test successful
> Traceback (most recent call last):
>   File "/opt/cehem/FlareSolverr/src/flaresolverr.py", line 95, in <module>
>     run(app, host=server_host, port=server_port, quiet=True, server='waitress')
>   File "/usr/local/lib/python3.9/dist-packages/bottle.py", line 3172, in run
>     server.run(app)
>   File "/usr/local/lib/python3.9/dist-packages/bottle.py", line 2853, in run
>     serve(handler, host=self.host, port=self.port)
>   File "/usr/local/lib/python3.9/dist-packages/waitress/__init__.py", line 13, in serve
>     server = _server(app, **kw)
>   File "/usr/local/lib/python3.9/dist-packages/waitress/server.py", line 78, in create_server
>     last_serv = TcpWSGIServer(
>   File "/usr/local/lib/python3.9/dist-packages/waitress/server.py", line 244, in __init__
>     self.bind_server_socket()
>   File "/usr/local/lib/python3.9/dist-packages/waitress/server.py", line 361, in bind_server_socket
>     self.bind(sockaddr)
>   File "/usr/local/lib/python3.9/dist-packages/waitress/wasyncore.py", line 396, in bind
>     return self.socket.bind(addr)
> OSError: [Errno 98] Address already in use

- if i close the script, Jackett reverts to throwing errors at me

I'm not sure anything of this can help :)

**Comment by ngosang** [comment]
I think this is a miss configuration issue.
You have to run Jackett + FlareSolverr in the same machine.

> INFO Challenge solved!

That means Jackett and FlareSolverr are working.

>  OSError: [Errno 98] Address already in use

That is because you are running `python3 src/flaresolverr.py` two times. You only need to start FlareSolverr once.

**Comment by eejag** [comment]
Thanks for your input @ngosang 

About the first part: both are running on the same machine, a remote server
About the second part: indeed, i just understood that afterwards :/

Nonetheless, i'll close this issue. The problem seemt to be resolved as of today, either with the update to the latest jackett version v0.20.2732 or by the tracker changing something on their side.

Thank you all for your input, support and continuous work on flaresolverr
