### ISSUE TITLE
[rutracker] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by ServPol** [FlareSolverr/FlareSolverr#676]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: idk
- Jackett version: v0.20.2687
- Operating system: 
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
- Are you using a proxy or VPN: yes
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://rutracker.org/forum/login.php
```

### Description

While trying to add Rutracker.org indexer, I'm getting error about invalid cookies even it says challenge not detected. But at same time running 'curl https://rutracker.org/forum/login.php' from container with FlareSolverr shows CloudFlare page.

### Logged Error Messages

```text
2023-01-22 17:31:00 INFO     FlareSolverr 3.0.2
2023-01-22 17:31:00 INFO     Testing web browser installation...
2023-01-22 17:31:00 INFO     Chrome / Chromium path: /usr/bin/chromium
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
2023-01-22 17:31:07 INFO     Chrome / Chromium major version: 108
2023-01-22 17:31:13 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
2023-01-22 17:31:13 INFO     Test successful
2023-01-22 17:31:14 INFO     Serving on http://0.0.0.0:8191
2023-01-22 18:03:37 INFO     127.0.0.1 GET http://localhost:8191/ 200 OK
2023-01-22 18:04:42 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://rutracker.org/forum/login.php'}
2023-01-22 18:04:51 INFO     Challenge not detected!
2023-01-22 18:04:53 INFO     Response in 10.636 s
2023-01-22 18:04:53 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
2023-01-22 18:05:02 INFO     Incoming request => POST /v1 body: {'postData': 'login_username=xxx&login_password=xxx&login=Login', 'maxTimeout': 120000, 'cmd': 'request.post', 'url': 'https://rutracker.org/forum/login.php'}
2023-01-22 18:05:13 INFO     Challenge not detected!
2023-01-22 18:05:13 INFO     Response in 10.643 s
2023-01-22 18:05:13 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK


Jackett:

FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
```

**Comment by ilike2burnthing** [comment]
Are Jackett and FlareSolverr running on the same device and using the same IP?

Try dropping the proxy/VPN.

Disable IPv6 for both containers or the host.

**Comment by ServPol** [comment]
> Are Jackett and FlareSolverr running on the same device and using the same IP?
Yes they are running inside Docker on my NAS, and traffic goes through VPN because of ISP torrents policy.
> Try dropping the proxy/VPN.
In this case Flare will not be able to load indexer.
> Disable IPv6 for both containers or the host.
I've disabled it for all of them, didn't help.

**Comment by ilike2burnthing** [comment]
If you're not already, try using the `host` Docker network (as opposed to `bridge`).

**Comment by ServPol** [comment]
Btw, turned on debug logs and I can clearly see that FlareSolverr fetching correct page after signing in.



**> If you're not already, try using the `host` Docker network (as opposed to `bridge`).**
Is there any guide how to use it with VPN?

**Comment by ilike2burnthing** [comment]
Not something I'm aware of, you'll have to google it.

**Comment by Rumbiz** [comment]
As someone who faced the same issue with rutracker today...
It happens cause your Jackett gets a cloudflare from VPNs IP, and Flaresolverr processes it from your IP, thus cookies missmatch.
I use OpenVPN client docker configured for Antizapret proxy. I will just call it VPN container.
Here and below:
IP=> Your HOST IP. From your router or similar stuff. LAN, not internet! NOT docker bridge IP or stuff. In my case it would be 192.168.31.xxx.

1) Connect Flaresolverr to the same container as Jackett, so your Jackett and FS have the same endpoint IP.
2) For container with VPN, forward -p  9117:9117 AND 8191:8191.
3) For Jackett, configure it like always. Check IP:8191 as your Flaresolverr API link.
After that everything should be fine. Just tested it with Rutor, for example, and challenge got solved.

**Comment by ilike2burnthing** [comment]
@Rumbiz, OP stated that Jackett and FlareSolverr are already using the same IP.

**Comment by ServPol** [comment]
rutracker is offline atm, waiting to come back online to test again

**Comment by Rumbiz** [comment]
You can use rutracker.net as address btw. For some reasons it works, while .org isn't.

**Comment by ServPol** [comment]
Sadly I have same issue.
Jackett and FlareSolverr going to web through OpenVPN network, so they do have same external IP. (checked by attaching to their containers and running ```curl checkip.amazonaws.com```).
FlareSolverr signing in successfully according to debug logs but Jackett keeps saying about invalid cookies. 


```
2023-01-25 21:00:32 INFO     ReqId 139851876747072 FlareSolverr 3.0.2
2023-01-25 21:00:32 DEBUG    ReqId 139851876747072 Debug log enabled
2023-01-25 21:00:32 INFO     ReqId 139851876747072 Testing web browser installation...
2023-01-25 21:00:32 INFO     ReqId 139851876747072 Chrome / Chromium path: /usr/bin/chromium
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
2023-01-25 21:00:37 INFO     ReqId 139851876747072 Chrome / Chromium major version: 108
2023-01-25 21:00:37 DEBUG    ReqId 139851876747072 Launching web browser...
2023-01-25 21:00:37 DEBUG    ReqId 139851876747072 Started executable: `/app/chromedriver` in a child process with pid: 28
2023-01-25 21:00:42 INFO     ReqId 139851876747072 FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
2023-01-25 21:00:42 INFO     ReqId 139851876747072 Test successful
2023-01-25 21:00:42 INFO     ReqId 139851876747072 Serving on http://0.0.0.0:8191
2023-01-26 20:00:45 INFO     ReqId 139851845306112 192.168.144.1 GET http://192.168.1.151:8191/ 200 OK
2023-01-26 20:01:00 INFO     ReqId 139851836913408 Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://rutracker.org/forum/login.php'}
2023-01-26 20:01:00 DEBUG    ReqId 139851836913408 Launching web browser...
2023-01-26 20:01:01 DEBUG    ReqId 139851836913408 Started executable: `/app/chromedriver` in a child process with pid: 160
2023-01-26 20:01:07 DEBUG    ReqId 139851811735296 Navigating to... https://rutracker.org/forum/login.php
2023-01-26 20:01:15 INFO     ReqId 139851811735296 Challenge not detected!
2023-01-26 20:01:16 DEBUG    ReqId 139851836913408 Response => POST /v1 body: {'status': 'ok', 'message': 'Challenge not detected!', 'solution': {'url': 'https://rutracker.org/forum/login.php', 'status': 200, 'cookies': [{'domain': '.rutracker.org', 'expiry': 1674835275, 'httpOnly': False, 'name': '_ym_isad', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '2'}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': '_ym_d', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': ''}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': '_ym_uid', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': ''}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': 'bb_guid', 'path': '/forum/', 'secure': False, 'value': ''}], 'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36', 'headers': {}, 'response': '<html lang="ru">></html>'}, 'startTimestamp': 1674763260840, 'endTimestamp': 1674763276860, 'version': '3.0.2'}
2023-01-26 20:01:16 INFO     ReqId 139851836913408 Response in 16.02 s
2023-01-26 20:01:16 INFO     ReqId 139851836913408 127.0.0.1 POST http://localhost:8191/v1 200 OK
2023-01-26 20:01:39 INFO     ReqId 139851828520704 Incoming request => POST /v1 body: {'postData': 'login_username=xxx&login_password=xxx&login=Login', 'maxTimeout': 55000, 'cmd': 'request.post', 'url': 'https://rutracker.org/forum/login.php'}
2023-01-26 20:01:39 DEBUG    ReqId 139851828520704 Launching web browser...
2023-01-26 20:01:39 DEBUG    ReqId 139851828520704 Started executable: `/app/chromedriver` in a child process with pid: 330
2023-01-26 20:01:41 DEBUG    ReqId 139851811735296 Navigating to... https://rutracker.org/forum/login.php
2023-01-26 20:01:48 INFO     ReqId 139851811735296 Challenge not detected!
2023-01-26 20:01:49 DEBUG    ReqId 139851828520704 Response => POST /v1 body: {'status': 'ok', 'message': 'Challenge not detected!', 'solution': {'url': 'https://rutracker.org/forum/index.php', 'status': 200, 'cookies': [{'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': '_ym_d', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': ''}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': '_ym_uid', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': ''}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': 'bb_guid', 'path': '/forum/', 'secure': False, 'value': ''}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': False, 'name': '_ym_isad', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '2'}, {'domain': '.rutracker.org', 'expiry':, 'httpOnly': True, 'name': 'bb_session', 'path': '/forum/', 'secure': False, 'value': '0-'}], 'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36', 'headers': {}, 'response': '<html lang="ru"></html>'}, 'startTimestamp': 1674763299557, 'endTimestamp': 1674763309206, 'version': '3.0.2'}
2023-01-26 20:01:49 INFO     ReqId 139851828520704 Response in 9.649 s
2023-01-26 20:01:49 INFO     ReqId 139851828520704 127.0.0.1 POST http://localhost:8191/v1 200 OK

```

**Comment by ServPol** [comment]
Jackett with enhanced logging

`01-26 22:17:44 Debug Execution plan of exception filters (in the following order): None 
01-26 22:17:44 Debug Execution plan of result filters (in the following order): None 
01-26 22:17:44 Debug Authorization was successful. 
01-26 22:17:44 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
01-26 22:17:44 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
01-26 22:17:44 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://rutracker.org/forum/login.php) 
01-26 22:17:58 Error Error loading configuration: FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 522
   at Jackett.Common.Indexers.RuTracker.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1389 
01-26 22:17:58 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
01-26 22:17:58 Debug No information found on request to perform content negotiation. 
01-26 22:17:58 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
01-26 22:17:58 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
01-26 22:17:58 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
01-26 22:17:58 Info Executing OkObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'. 
01-26 22:17:58 Debug The response will be compressed with 'gzip'. 
01-26 22:17:58 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 13378.9813ms 
01-26 22:17:58 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
01-26 22:17:58 Debug Connection id "0HMNVR7DTQFQL" completed keep alive response. 
01-26 22:17:58 Info Request finished HTTP/1.1 GET http://192.168.1.151:9117/api/v2.0/indexers/rutracker/config?_=1674764239727 - - - 200 - application/json;+charset=utf-8 13427.9487ms 
01-26 22:18:29 Info Request starting HTTP/1.1 POST http://192.168.1.151:9117/api/v2.0/indexers/rutracker/config application/json 410 
01-26 22:18:29 Debug Request is continuing in applying rules. Current url is http://192.168.1.151:9117/api/v2.0/indexers/rutracker/config 
01-26 22:18:29 Debug Request is continuing in applying rules. Current url is http://192.168.1.151:9117/api/v2.0/indexers/rutracker/config 
01-26 22:18:29 Debug Request is continuing in applying rules. Current url is http://192.168.1.151:9117/api/v2.0/indexers/rutracker/config 
01-26 22:18:29 Debug POST requests are not supported 
01-26 22:18:29 Debug AuthenticationScheme: Cookies was successfully authenticated. 
01-26 22:18:29 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/rutracker/config' 
01-26 22:18:29 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/rutracker/config' 
01-26 22:18:29 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
01-26 22:18:29 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
01-26 22:18:29 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
01-26 22:18:29 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
01-26 22:18:29 Debug Execution plan of resource filters (in the following order): None 
01-26 22:18:29 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
01-26 22:18:29 Debug Execution plan of exception filters (in the following order): None 
01-26 22:18:29 Debug Execution plan of result filters (in the following order): None 
01-26 22:18:29 Debug Authorization was successful. 
01-26 22:18:29 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
01-26 22:18:29 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
01-26 22:18:29 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
01-26 22:18:29 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
01-26 22:18:29 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
01-26 22:18:29 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
01-26 22:18:29 Debug Connection id "0HMNVR7DTQFQL", Request id "0HMNVR7DTQFQL:0000000C": started reading request body. 
01-26 22:18:29 Debug Connection id "0HMNVR7DTQFQL", Request id "0HMNVR7DTQFQL:0000000C": done reading request body. 
01-26 22:18:29 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
01-26 22:18:29 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
01-26 22:18:29 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
01-26 22:18:29 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
01-26 22:18:29 Debug CACHE IsCacheEnabled => false 
01-26 22:18:29 Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://rutracker.org/forum/login.php PostData: {login_username=xxx, login_password=xxx, login=Login} RawBody: ) 
01-26 22:18:39 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 10359.2363ms 
01-26 22:18:39 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
01-26 22:18:39 Error FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 540
   at Jackett.Common.Indexers.RuTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1435
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
01-26 22:18:39 Debug The response will be compressed with 'gzip'. 
01-26 22:18:39 Debug Connection id "0HMNVR7DTQFQL" completed keep alive response. 
01-26 22:18:39 Info Request finished HTTP/1.1 POST http://192.168.1.151:9117/api/v2.0/indexers/rutracker/config application/json 410 - 500 - application/json 10423.9733ms `

**Comment by ilike2burnthing** [comment]
Can you try the other domains as well?

**Comment by ServPol** [comment]
They don't have any alternative working domains afaik

**Comment by ServPol** [comment]
Worked smoothly with https://rutracker.net and https://rutracker.nl

Damn!
