### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by BDDam** [FlareSolverr/FlareSolverr#680]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: 2.x / 3.0.0 (maybe 3.0.1)
- Operating system: Synology DSM 7.1.1 (Linux version 4.4.180+)
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
- Are you using a proxy or VPN: no 
- Are you using Captcha Solver: no
- If using captcha solver, which one: n/a
- URL to test this issue:
```

### Description

Flaresolverr seems to crash randomly, causing the container to stop unexpectedly (using Docker's `restart: unless-stopped` in compose file). It then reboots and start working again until next crash.

I can't list steps to reproduce as I'm not doing anything myself and I don't see a specific pattern but it appears to happen once every 2-3 days on average.
Not a big deal in itself, but it's fairly recent behaviour (I would say since 3.0.2 but can't be sure 100%)

Flaresolverr is used by Prowlarr/Jackett, both containers on the same custom Docker network than Flaresolverr
Logs during last crash occurence below @20:56

### Logged Error Messages

```text
2023-01-25 20:06:09 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date'}
2023-01-25 20:06:11 INFO     Challenge detected. Title found: Just a moment...
2023-01-25 20:06:14 INFO     Challenge solved!
2023-01-25 20:06:14 INFO     Response in 5.491 s
2023-01-25 20:06:14 INFO     172.18.0.6 POST http://flaresolverr:8191/v1 200 OK
2023-01-25 20:06:17 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/'}
2023-01-25 20:06:19 INFO     Challenge detected. Title found: Just a moment...
2023-01-25 20:06:21 INFO     Challenge solved!
2023-01-25 20:06:21 INFO     Response in 4.185 s
2023-01-25 20:06:21 INFO     172.18.0.6 POST http://flaresolverr:8191/v1 200 OK
2023-01-25 20:20:27 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-25 20:20:27 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-01-25 20:20:28 INFO     Challenge detected. Title found: Just a moment...
2023-01-25 20:20:32 INFO     Challenge solved!
2023-01-25 20:20:32 INFO     Response in 5.692 s
2023-01-25 20:20:32 INFO     172.18.0.4 POST http://flaresolverr:8191/v1 200 OK
2023-01-25 20:20:33 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-25 20:20:33 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-01-25 20:20:34 INFO     Challenge detected. Title found: Just a moment...
2023-01-25 20:20:37 INFO     Challenge solved!
2023-01-25 20:20:37 INFO     Response in 4.37 s
2023-01-25 20:20:37 INFO     172.18.0.4 POST http://flaresolverr:8191/v1 200 OK
2023-01-25 20:51:27 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-25 20:51:27 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-01-25 20:51:29 INFO     Challenge detected. Title found: Just a moment...
2023-01-25 20:51:32 INFO     Challenge solved!
2023-01-25 20:51:32 INFO     Response in 5.086 s
2023-01-25 20:51:32 INFO     172.18.0.4 POST http://flaresolverr:8191/v1 200 OK
2023-01-25 20:51:33 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-25 20:51:33 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
2023-01-25 20:51:34 INFO     Challenge detected. Title found: Just a moment...
2023-01-25 20:51:37 INFO     Challenge solved!
2023-01-25 20:51:37 INFO     Response in 4.316 s
2023-01-25 20:51:37 INFO     172.18.0.4 POST http://flaresolverr:8191/v1 200 OK
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 95, in <module>
    run(app, host=server_host, port=server_port, quiet=True, server='waitress')
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 3172, in run
    server.run(app)
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 2853, in run
    serve(handler, host=self.host, port=self.port)
  File "/usr/local/lib/python3.11/site-packages/waitress/__init__.py", line 19, in serve
    server.run()
  File "/usr/local/lib/python3.11/site-packages/waitress/server.py", line 322, in run
    self.asyncore.loop(
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()
2023-01-25 20:56:12 INFO     FlareSolverr 3.0.2
2023-01-25 20:56:12 INFO     Testing web browser installation...
2023-01-25 20:56:12 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-01-25 20:56:12 INFO     Chrome / Chromium major version: 108
2023-01-25 20:56:13 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
2023-01-25 20:56:13 INFO     Test successful
2023-01-25 20:56:13 INFO     Serving on http://0.0.0.0:8191
```

**Comment by ngosang** [comment]
It looks like an issue in `waitress` library. I'm going to close this because I'm not able to reproduce the issue.

**Comment by BDDam** [comment]
It crashed again today. The delay between two crashes seems to be consistent between 3 and 4 days (container running 24/7).

No idea of the exact cause but given it didn’t happen on v3.0.0 and there was apparently no bump in dependency version since then it must probably be induced by a change on 3.0.1 or 3.0.2.

I’ll revert to 3.0.0 for now. Hopefully I won’t need newer versions anytime soon until it gets fixed.

**Comment by BDDam** [comment]
@ngosang
I reverted to 3.0.0 right after my comment above on Jan 29th and got no issue the whole week (would have had 2/3 crashes in that time span on 3.0.2).

Then I switched back to 3.0.1 on Feb 5th, and it's back at crashing after couple days today (so barely after 3 days) with same error log than in my initial post.

> It looks like an issue in `waitress` library. I'm going to close this because I'm not able to reproduce the issue.

So that's been introduced with 3.0.1, although I agree likely as an indirect side-effect from one of the change.
I would assume it's then somehow related to the following commit:
https://github.com/FlareSolverr/FlareSolverr/commit/7d84f1b663d82625bf111d5e9c984a11cabd1504 `(Kill Chromium processes properly to avoid defunct/zombie processes)`


Not familiar with Python ecosystem but it appears to be commonly caused by some mis-managed parallel/multiple process execution using `select()` instead of `poll()` for I-don't-know-what operations. This can apparently be fixed by passing the `asyncore_use_poll` parameter to that `waitress` server.

I see Bottle is used in `flaresolver.py`  and seems to support passing server-specific parameters :
https://github.com/bottlepy/bottle/blob/99341ff3791b2e7e705d7373e71937e9018eb081/bottle.py#L3329

Thanks for looking into it once again.

Ref.
https://github.com/Pylons/waitress/issues/31
https://python-list.python.narkive.com/QmvuCFKJ/valueerror-filedescriptor-out-of-range-in-select
https://docs.pylonsproject.org/projects/waitress/en/stable/arguments.html (at the bottom of the page)

**Comment by jankete** [comment]
The same here with 3.0.2 on docker.

```
2023-02-07T18:17:40.082394140Z 2023-02-07 19:17:40 INFO     Challenge detected. Title found: Just a moment...
2023-02-07T18:18:37.886333143Z Traceback (most recent call last):
2023-02-07T18:18:37.886943438Z   File "/app/flaresolverr.py", line 95, in <module>
2023-02-07T18:18:37.888544352Z     run(app, host=server_host, port=server_port, quiet=True, server='waitress')
2023-02-07T18:18:37.888806868Z   File "/usr/local/lib/python3.11/site-packages/bottle.py", line 3172, in run
2023-02-07T18:18:37.892442769Z     server.run(app)
2023-02-07T18:18:37.892627389Z   File "/usr/local/lib/python3.11/site-packages/bottle.py", line 2853, in run
2023-02-07T18:18:37.893848909Z     serve(handler, host=self.host, port=self.port)
2023-02-07T18:18:37.894176322Z   File "/usr/local/lib/python3.11/site-packages/waitress/__init__.py", line 19, in serve
2023-02-07T18:18:37.895096764Z     server.run()
2023-02-07T18:18:37.895502367Z   File "/usr/local/lib/python3.11/site-packages/waitress/server.py", line 322, in run
2023-02-07T18:18:37.896593016Z     self.asyncore.loop(
2023-02-07T18:18:37.896658942Z   File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 245, in loop
2023-02-07T18:18:37.897538269Z     poll_fun(timeout, map)
2023-02-07T18:18:37.897721470Z   File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 172, in poll
2023-02-07T18:18:37.898054863Z     r, w, e = select.select(r, w, e, timeout)
2023-02-07T18:18:37.898341191Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-07T18:18:37.898512055Z ValueError: filedescriptor out of range in select()
```

**Comment by almico** [comment]
Same issue here.

**Comment by Badn1nja** [comment]
I am also getting this behavior `2023-03-03 18:12:30 INFO     172.23.0.9 POST http://flaresolverr:8191/v1 500 Internal Server Error
2023-03-03 18:12:30 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://badasstorrents.com/torrents/search/wicked.tuna. S08/date/desc'}
2023-03-03 18:12:32 INFO     Challenge detected. Title found: Just a moment...
2023-03-03 18:13:26 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-03-03 18:13:26 INFO     Response in 55.846 s
2023-03-03 18:13:26 INFO     172.23.0.9 POST http://flaresolverr:8191/v1 500 Internal Server Error
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 95, in <module>
    run(app, host=server_host, port=server_port, quiet=True, server='waitress')
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 3172, in run
    server.run(app)
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 2853, in run
    serve(handler, host=self.host, port=self.port)
  File "/usr/local/lib/python3.11/site-packages/waitress/__init__.py", line 19, in serve
    server.run()
  File "/usr/local/lib/python3.11/site-packages/waitress/server.py", line 322, in run
    self.asyncore.loop(
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()`

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.0
