### ISSUE TITLE
Oracle Linux 8.7 - 3.0+ does not work - keeps restarting.  

### ISSUE THREAD

**Issue by gitrosers** [FlareSolverr/FlareSolverr#685]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0+
- Last working FlareSolverr version: 2.0+
- Operating system: Oracle Linux Server 8.7
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint): ???
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

As you can see from the debug log, it fails to start.  Version 2 used to work fine but perhaps after switching to chrome since 3.0, something fails.  

### Logged Error Messages

```text
2023-01-31 19:38:51 INFO     ReqId 281457499139088 FlareSolverr 3.0.2
2023-01-31 19:38:51 DEBUG    ReqId 281457499139088 Debug log enabled
2023-01-31 19:38:51 INFO     ReqId 281457499139088 Testing web browser installation...
2023-01-31 19:38:51 INFO     ReqId 281457499139088 Chrome / Chromium path: /usr/bin/chromium
2023-01-31 19:38:51 INFO     ReqId 281457499139088 Chrome / Chromium major version: 108
2023-01-31 19:38:51 DEBUG    ReqId 281457499139088 Launching web browser...
2023-01-31 19:38:51 DEBUG    ReqId 281457499139088 Started executable: `/app/chromedriver` in a child process with pid: 29
Traceback (most recent call last):
  File "/app/utils.py", line 158, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 72, in get_webdriver
    driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 436, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 698, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: tab crashed
  (Session info: chrome=108.0.5359.124)
Stacktrace:
#0 0xaaacded33d3c <unknown>
#1 0xaaacdeb13e4c <unknown>
#2 0xaaacdeb03788 <unknown>
#3 0xaaacdeb02d50 <unknown>
#4 0xaaacdeb021b0 <unknown>
#5 0xaaacdeb020ac <unknown>
#6 0xaaacdeb00e3c <unknown>
#7 0xaaacdeb01208 <unknown>
#8 0xaaacdeb0d7e8 <unknown>
#9 0xaaacdeaff8c4 <unknown>
#10 0xaaacdeb01e24 <unknown>
#11 0xaaacdeb00e3c <unknown>
#12 0xaaacdeb01208 <unknown>
#13 0xaaacdeb0ac90 <unknown>
#14 0xaaacdeaff8c4 <unknown>
#15 0xaaacdeb01e24 <unknown>
#16 0xaaacdeb00e3c <unknown>
#17 0xaaacdeb01208 <unknown>
#18 0xaaacdeb07d90 <unknown>
#19 0xaaacdeaff8c4 <unknown>
#20 0xaaacdeb01e24 <unknown>
#21 0xaaacdeb00e3c <unknown>
#22 0xaaacdeb01208 <unknown>
#23 0xaaacdeaf9554 <unknown>
#24 0xaaacdeaff8c4 <unknown>
#25 0xaaacdeafeefc <unknown>
#26 0xaaacdeafea04 <unknown>
#27 0xaaacdeaf3250 <unknown>
#28 0xaaacdeaf2170 <unknown>
#29 0xaaacdeb7320c <unknown>
#30 0xaaacdeb72d48 <unknown>
#31 0xaaacdeb3e0f0 <unknown>
#32 0xaaacdeb3f1f4 <unknown>
#33 0xaaacded74c5c <unknown>
#34 0xaaacded76760 <unknown>
#35 0xaaacded762c0 <unknown>
#36 0xaaacded641c0 <unknown>
#37 0xaaacded77028 <unknown>
#38 0xaaacded57aec <unknown>
#39 0xaaacded8f8c4 <unknown>
#40 0xaaacded8fa84 <unknown>
#41 0xaaacdeda87c8 <unknown>
#42 0xfffc4f7b7648 start_thread
#43 0xfffc4eee2c1c <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 91, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 61, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 162, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: tab crashed
  (Session info: chrome=108.0.5359.124)
Stacktrace:
#0 0xaaacded33d3c <unknown>
#1 0xaaacdeb13e4c <unknown>
#2 0xaaacdeb03788 <unknown>
#3 0xaaacdeb02d50 <unknown>
#4 0xaaacdeb021b0 <unknown>
#5 0xaaacdeb020ac <unknown>
#6 0xaaacdeb00e3c <unknown>
#7 0xaaacdeb01208 <unknown>
#8 0xaaacdeb0d7e8 <unknown>
#9 0xaaacdeaff8c4 <unknown>
#10 0xaaacdeb01e24 <unknown>
#11 0xaaacdeb00e3c <unknown>
#12 0xaaacdeb01208 <unknown>
#13 0xaaacdeb0ac90 <unknown>
#14 0xaaacdeaff8c4 <unknown>
#15 0xaaacdeb01e24 <unknown>
#16 0xaaacdeb00e3c <unknown>
#17 0xaaacdeb01208 <unknown>
#18 0xaaacdeb07d90 <unknown>
#19 0xaaacdeaff8c4 <unknown>
#20 0xaaacdeb01e24 <unknown>
#21 0xaaacdeb00e3c <unknown>
#22 0xaaacdeb01208 <unknown>
#23 0xaaacdeaf9554 <unknown>
#24 0xaaacdeaff8c4 <unknown>
#25 0xaaacdeafeefc <unknown>
#26 0xaaacdeafea04 <unknown>
#27 0xaaacdeaf3250 <unknown>
#28 0xaaacdeaf2170 <unknown>
#29 0xaaacdeb7320c <unknown>
#30 0xaaacdeb72d48 <unknown>
#31 0xaaacdeb3e0f0 <unknown>
#32 0xaaacdeb3f1f4 <unknown>
#33 0xaaacded74c5c <unknown>
#34 0xaaacded76760 <unknown>
#35 0xaaacded762c0 <unknown>
#36 0xaaacded641c0 <unknown>
#37 0xaaacded77028 <unknown>
#38 0xaaacded57aec <unknown>
#39 0xaaacded8f8c4 <unknown>
#40 0xaaacded8fa84 <unknown>
#41 0xaaacdeda87c8 <unknown>
#42 0xfffc4f7b7648 start_thread
#43 0xfffc4eee2c1c <unknown>
```

### Screenshots

-

**Comment by ilike2burnthing** [comment]
Is this on an ARM device?

**Comment by gitrosers** [comment]
> Is this on an ARM device?

correct.  arm64.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/687
