### ISSUE TITLE
FlareSolverr won't start.

### ISSUE THREAD

**Issue by so1ar** [FlareSolverr/FlareSolverr#687]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest form git
- Last working FlareSolverr version:
- Operating system: Manjaro Arm64 for RaspberryPi4
- Are you using Docker: [no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I'm installing FlareSolverr from source code and it won't start.

### Logged Error Messages

```text
2023-02-02 14:28:58 INFO     FlareSolverr 3.0.2
2023-02-02 14:28:58 INFO     Testing web browser installation...
2023-02-02 14:28:58 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-02-02 14:29:00 INFO     Chrome / Chromium major version: 109
Traceback (most recent call last):
  File "/home/pi/FlareSolverr/src/utils.py", line 158, in get_user_agent
    driver = get_webdriver()
  File "/home/pi/FlareSolverr/src/utils.py", line 72, in get_webdriver
    driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
  File "/home/pi/FlareSolverr/src/undetected_chromedriver/__init__.py", line 436, in __init__
    super(Chrome, self).__init__(
  File "/home/pi/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/pi/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/home/pi/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 199, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.local/share/undetected_chromedriver/d0c3e87b99700651_chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/FlareSolverr/src/flaresolverr.py", line 91, in <module>
    flaresolverr_service.test_browser_installation()
  File "/home/pi/FlareSolverr/src/flaresolverr_service.py", line 61, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "/home/pi/FlareSolverr/src/utils.py", line 162, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. [Errno 8] Exec format error: '/home/pi/.local/share/undetected_chromedriver/d0c3e87b99700651_chromedriver'
```
```


### Screenshots

_No response_

**Comment by ilike2burnthing** [comment]
@ngosang there are a few open issues (as well as a couple of older closed ones) with similar errors on ARM devices - #688 and #685(?).

**Comment by gitrosers** [comment]
thanks not sure why mine 685 was closed as duplicate either way, mine is not memory issue like 688.  32gb ram here.

**Comment by ilike2burnthing** [comment]
You were a few seconds too quick. See edited comment above for similar issues. May be a wider problem.

**Comment by emald00** [comment]
@ilike2burnthing apparently, it's a chrome/puppeteer issue
https://github.com/puppeteer/puppeteer/issues/7740
and people propose some workarounds here, but unfortunately, i don't have the technical background to understand it (on how to use alpine chrome instead for example, i am new to docker)

**Comment by ilike2burnthing** [comment]
We're using Selenium now, not Puppeteer.

**Comment by lborruto** [comment]
Same issue here trying to install Flaresolverr on my RaspberryPi.

**Comment by jfcabral** [comment]
Hi, I'm currently having a similar issue 😕 

```
2023-02-12 19:23:13 INFO     FlareSolverr 3.0.2
2023-02-12 19:23:13 INFO     Testing web browser installation...
2023-02-12 19:23:13 INFO     Chrome / Chromium path: /usr/bin/chromium
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
2023-02-12 19:23:13 INFO     Chrome / Chromium major version: 108
Traceback (most recent call last):
  File "/app/utils.py", line 158, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 72, in get_webdriver
    driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 242, in __init__
    patcher = Patcher(
              ^^^^^^^^
  File "/app/undetected_chromedriver/patcher.py", line 69, in __init__
    os.makedirs(self.data_path, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/app/.local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 91, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 61, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 162, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. [Errno 13] Permission denied: '/app/.local'
Exception ignored in: <function Patcher.__del__ at 0x7f912253a0>
Traceback (most recent call last):
  File "/app/undetected_chromedriver/patcher.py", line 255, in __del__
    if self._custom_exe_path:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Patcher' object has no attribute '_custom_exe_path'
```

I'm running a very simple docker compose:

```yaml
version: '3.8'
services:
  ...
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
    - LOG_LEVEL=info
    - LOG_HTML=false
    - CAPTCHA_SOLVER=none
    ports:
    - 8191:8191
    restart: unless-stopped 
```

My specs:
* OS: Armbian (22.11.4) aarch64
* Host: Radxa ROCK 5B
* Kernel: 5.10.110-rockchip-rk3588
* Docker version 23.0.1, build a5ee5b1
* FlareSolverr 3.0.2

I've tried to delete the image and re-download it, but the problem still stands.
I guess the problem should be something out of the scope of FlareSolverr, because I got the very same version to work like 2 weeks ago.

**Comment by jfcabral** [comment]
I've cloned the repo and rebuilt the docker image, and it started working again 😄 

@ngosang maybe you could publish a new minor version just to update the container OS dependencies?

Thank you

**Comment by fe80Grau** [comment]
Same error in Ubuntu 22.04 ARM64. Is an free instance Oracle Cloud.
Server spects
```
VM.Standard.A1.Flex
OCPU count: 4
Network bandwidth (Gbps): 4
Memory (GB): 24
Local disk: Block storage only
```

lscpu server output:
```
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           1
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            50.00
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm
                         lrcpc dcpop asimddp ssbs
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Mitigation; CSV2, BHB
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

Error:
```
2023-02-14 19:12:53 INFO     FlareSolverr 3.0.2
2023-02-14 19:12:53 INFO     Testing web browser installation...
2023-02-14 19:12:53 INFO     Chrome / Chromium path: /bin/chromium-browser
2023-02-14 19:12:53 INFO     Chrome / Chromium major version: 110
Traceback (most recent call last):
  File "/opt/FlareSolverr/src/utils.py", line 158, in get_user_agent
    driver = get_webdriver()
  File "/opt/FlareSolverr/src/utils.py", line 72, in get_webdriver
    driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
  File "/opt/FlareSolverr/src/undetected_chromedriver/__init__.py", line 436, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 199, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.local/share/undetected_chromedriver/ce7bf9f0354f7b7b_chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/FlareSolverr/src/flaresolverr.py", line 91, in <module>
    flaresolverr_service.test_browser_installation()
  File "/opt/FlareSolverr/src/flaresolverr_service.py", line 61, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "/opt/FlareSolverr/src/utils.py", line 162, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. [Errno 8] Exec format error: '/root/.local/share/undetected_chromedriver/ce7bf9f0354f7b7b_chromedriver'
```

Tried installing chromium-browser and chromium-chromedriver apt packages, each alone and both toguether, nothing works.

**Comment by ngosang** [comment]
I'm providing images for these architectures:
* x86 | linux/386 => tested by my
* x86-64 | linux/amd64 => tested by my
* ARM32 | linux/arm/v7 => NOT tested
* ARM64 | linux/arm64 => tested by my, Raspberry Pi 4

Some of the issues are related to the ARM 32 version. I did some changes but I can not test them:
* 8de16058d0cf24b90a3f9691f38e0eb107556336
* 24f59a39cbf127bd0915772821140c2e5d3b05c4

The error `Exec format error` is caused because you are running a Docker image for an architecture not supported by your machine. @fe80Grau try running the Docker image for ARM64.

> maybe you could publish a new minor version just to update the container OS dependencies?

Sure.

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.0

**Comment by so1ar** [comment]
> The error `Exec format error` is caused because you are running a Docker image for an architecture not supported by your machine. 

I'm not using docker. Instead I'm running Flaresolverr [from source code](https://github.com/FlareSolverr/FlareSolverr#from-source-code), still get `Exec format error`. Running in Manjaro Arm64, and the [AUR package](https://aur.archlinux.org/packages/flaresolverr-git) also doesn't work.

**Comment by ngosang** [comment]
I will investigate more.
The main problem is FlareSolverr requires Chrome web browser + Chrome webdriver + Selenium and they are not available for all architectures. Windows / Linux x64 works fine. For other architectures I recommend you to use Docker.

**Comment by jfcabral** [comment]
Hey @ngosang, thank you for publishing a new version with updated dependencies! 😄 

I have just tested it and it works perfectly now! ✅💪😎 

For reference, my specs are:

* OS: Armbian (23.02.2) aarch64 (which is based on Ubuntu 22.04.2 LTS Jammy)
* Host: Radxa ROCK 5B
* Kernel: 5.10.110-rockchip-rk3588
* Docker version 23.0.1, build a5ee5b1
* FlareSolverr 3.1.0
   * Platform: Linux-5.10.110-rockchip-rk3588-aarch64-with-glibc2.31
   * Chrome / Chromium major version: 111
   * image id: 90445b7c496e

Thank you once again!

**Comment by so1ar** [comment]
> I will investigate more. The main problem is FlareSolverr requires Chrome web browser + Chrome webdriver + Selenium and they are not available for all architectures. Windows / Linux x64 works fine. For other architectures I recommend you to use Docker.

Thanks For reply. The docker image works fine for me. ;)

**Comment by ngosang** [comment]
I made some clarification in the readme. For ARM you MUST use the Docker images.
7017715e21a0d2d8d2779fb3215b76cdcabb0c0a

**Comment by gitrosers** [comment]
@ngosang still issue with 3.1.1-

Trace/breakpoint trap (core dumped)
2023-03-26 03:11:10 ERROR    ReqId 281461294984416 Chrome / Chromium version not detected!
2023-03-26 03:11:11 INFO     ReqId 281464989838560 FlareSolverr 3.1.1
2023-03-26 03:11:11 DEBUG    ReqId 281464989838560 Debug log enabled
2023-03-26 03:11:11 INFO     ReqId 281464989838560 Testing web browser installation...
2023-03-26 03:11:11 INFO     ReqId 281464989838560 Platform: Linux-5.4.17-2136.317.5.3.el8uek.aarch64-aarch64-with-glibc2.31
2023-03-26 03:11:11 INFO     ReqId 281464989838560 Chrome / Chromium path: /usr/bin/chromium

**Comment by ngosang** [comment]
@gitrosers Sorry to head that. I see you are running ARM64 and Chrome is crashing. I tested in some SBC boards with ARM64 and it's working so there is not much I can do.

**Comment by jfcabral** [comment]
I've just download the newest version (`3.1.1`) to test for an eventual regression, but all seems good over here:
```bash
docker logs flaresolverr  -f
2023-03-26 17:53:49 INFO     FlareSolverr 3.1.1
2023-03-26 17:53:49 INFO     Testing web browser installation...
2023-03-26 17:53:49 INFO     Platform: Linux-5.10.110-rockchip-rk3588-aarch64-with-glibc2.31
2023-03-26 17:53:49 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-03-26 17:53:50 INFO     Chrome / Chromium major version: 111
2023-03-26 17:53:50 INFO     Launching web browser...
2023-03-26 17:53:53 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
2023-03-26 17:53:53 INFO     Test successful!
2023-03-26 17:53:53 INFO     Serving on http://0.0.0.0:8191
```

So I guess @gitrosers's issue is a different one from what motivated this thread...

@gitrosers, when asking for help, you should try to provide the maximum relevant information you can gather, otherwise it's difficult to provide any help/support..

**Comment by gitrosers** [comment]
@jfcabral @ngosang 

Thanks.  Here is the previously posted report with additional information on the system I am running.

https://github.com/FlareSolverr/FlareSolverr/issues/685

Happy to provide any additional information that you'd need to debug the issue.

**Comment by alavaros** [comment]
I am having the same problem, I just pulled the latest docker image (v.3.1.2) to my Asustor Drivestor 2 NAS (ARM64, 2GB DDR4), here is the log:
```
2023-05-03 10:40:16 INFO     FlareSolverr 3.1.2
2023-05-03 10:40:16 INFO     Testing web browser installation...
2023-05-03 10:40:16 INFO     Platform: Linux-4.9.119-aarch64-with-glibc2.31
2023-05-03 10:40:16 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-05-03 10:40:20 INFO     Chrome / Chromium major version: 111
2023-05-03 10:40:20 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 194, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 83, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 447, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 710, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60623
from chrome not reachable
Stacktrace:
#0 0x00556f078890 <unknown>
#1 0x00556ee58600 <unknown>
#2 0x00556ee49fc8 <unknown>
#3 0x00556ee8009c <unknown>
#4 0x00556ee79d3c <unknown>
#5 0x00556eebb5b8 <unknown>
#6 0x00556ee834a4 <unknown>
#7 0x00556ee84730 <unknown>
#8 0x00556f0bfb4c <unknown>
#9 0x00556f0c2324 <unknown>
#10 0x00556f0c1e48 <unknown>
#11 0x00556f0ae1fc <unknown>
#12 0x00556f0c2c74 <unknown>
#13 0x00556f0a0dec <unknown>
#14 0x00556f0dcd94 <unknown>
#15 0x00556f0dcf54 <unknown>
#16 0x00556f0f5760 <unknown>
#17 0x007f80fa2648 start_thread
#18 0x007f8074dc1c <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 198, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:60623
from chrome not reachable
Stacktrace:
#0 0x00556f078890 <unknown>
#1 0x00556ee58600 <unknown>
#2 0x00556ee49fc8 <unknown>
#3 0x00556ee8009c <unknown>
#4 0x00556ee79d3c <unknown>
#5 0x00556eebb5b8 <unknown>
#6 0x00556ee834a4 <unknown>
#7 0x00556ee84730 <unknown>
#8 0x00556f0bfb4c <unknown>
#9 0x00556f0c2324 <unknown>
#10 0x00556f0c1e48 <unknown>
#11 0x00556f0ae1fc <unknown>
#12 0x00556f0c2c74 <unknown>
#13 0x00556f0a0dec <unknown>
#14 0x00556f0dcd94 <unknown>
#15 0x00556f0dcf54 <unknown>
#16 0x00556f0f5760 <unknown>
#17 0x007f80fa2648 start_thread
#18 0x007f8074dc1c <unknown>
```

**Comment by adaragaopt** [comment]
I had this issue on a raspberry 4, using docker swarm. I was limiting the the memory for this container at 200 MB, when I remove the limit it worked, it needs at least 300 MB to start.

Just didn't had enough memory... :)

**Comment by gitrosers** [comment]
my vps has 32gb of memory...

**Comment by ngosang** [comment]
The only hardware with ARM that I have is RaspberryPi 4 and it's working as expected.
Make sure your host OS is up-to-date (Docker, Linux kernel...) and you are using the latest FlareSolverr release. If that isn't working maybe your hardware is not supported by Chrome.

**Comment by nusiloot** [comment]
- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: first time I try this software
- Operating system: Raspbian GNU/Linux 10 (buster) for RaspberryPi2
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
