### ISSUE TITLE
can't get browser user agent in docker

### ISSUE THREAD

**Issue by emald00** [FlareSolverr/FlareSolverr#688]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.0.2
- Last working FlareSolverr version:
- Operating system: NAS asustor as3304T
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): can't access it
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue:
```

### Description

i try to install flaresoverr on my nas (asustor drivestor 4 pro) using portainer, i make the port 8191 for both host and container, and i do not put any other env parameter, and it does not work, with the error: Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:55653
(other containers such as radarr sonarr prowlarr work fine)
can somebody help me please?

### Logged Error Messages

```text
2023-02-02 16:14:24 INFO     FlareSolverr 3.0.2
2023-02-02 16:14:24 INFO     Testing web browser installation...
2023-02-02 16:14:24 INFO     Chrome / Chromium path: /usr/bin/chromium
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
2023-02-02 16:14:26 INFO     Chrome / Chromium major version: 108
Traceback (most recent call last):
  File "/app/utils.py", line 158, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 72, in get_webdriver
    driver = uc.Chrome(options=options, driver_executable_path=driver_exe_path, version_main=version_main,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 436, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/app/undetected_chromedriver/__init__.py", line 698, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55653
from chrome not reachable
Stacktrace:
#0 0x00556dad6d3c <unknown>
#1 0x00556d8b6e4c <unknown>
#2 0x00556d8a8d44 <unknown>
#3 0x00556d8ddde8 <unknown>
#4 0x00556d8d7ab0 <unknown>
#5 0x00556d916148 <unknown>
#6 0x00556d915d48 <unknown>
#7 0x00556d8e10f0 <unknown>
#8 0x00556d8e21f4 <unknown>
#9 0x00556db17c5c <unknown>
#10 0x00556db19760 <unknown>
#11 0x00556db192c0 <unknown>
#12 0x00556db071c0 <unknown>
#13 0x00556db1a028 <unknown>
#14 0x00556dafaaec <unknown>
#15 0x00556db328c4 <unknown>
#16 0x00556db32a84 <unknown>
#17 0x00556db4b7c8 <unknown>
#18 0x007fa0196648 start_thread
#19 0x007f9f941c1c <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 91, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 61, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 162, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:55653
from chrome not reachable
Stacktrace:
#0 0x00556dad6d3c <unknown>
#1 0x00556d8b6e4c <unknown>
#2 0x00556d8a8d44 <unknown>
#3 0x00556d8ddde8 <unknown>
#4 0x00556d8d7ab0 <unknown>
#5 0x00556d916148 <unknown>
#6 0x00556d915d48 <unknown>
#7 0x00556d8e10f0 <unknown>
#8 0x00556d8e21f4 <unknown>
#9 0x00556db17c5c <unknown>
#10 0x00556db19760 <unknown>
#11 0x00556db192c0 <unknown>
#12 0x00556db071c0 <unknown>
#13 0x00556db1a028 <unknown>
#14 0x00556dafaaec <unknown>
#15 0x00556db328c4 <unknown>
#16 0x00556db32a84 <unknown>
#17 0x00556db4b7c8 <unknown>
#18 0x007fa0196648 start_thread
#19 0x007f9f941c1c <unknown>
```

**Comment by ilike2burnthing** [comment]
Provide the Docker run command or compose file for FlareSolverr, or screenshot the Portainer settings if you just used it.

**Comment by ilike2burnthing** [comment]
Provide the Docker run command or compose file for FlareSolverr, or screenshots of the container's settings in Portainer if you just used it.

**Comment by emald00** [comment]
i figured it out, my nas does not have enough RAM, it only has 2 gb, found out that if i stop the other running containers (radarr, prowlarr and transmission) it does not give this error anymore, so it has to be RAM related issue, i hosted FS on a AWS free tier vps and it works fine, thanks anyway

**Comment by ilike2burnthing** [comment]
I'm running FlareSolverr on an Asustor NAS with 2GB RAM, no issues here. The difference is, mine has an x86 CPU, not ARM.

**Comment by emald00** [comment]
i thought it was compatible with arm...

**Comment by emald00** [comment]
i thought it was compatible with arm

**Comment by ilike2burnthing** [comment]
It is.

**Comment by emald00** [comment]
weird then... anyway, i'm looking for a workaround on where to run it (as vps IPs get flagged so it does not work, and i don't want to run the container on my laptop and keep it running 24 7)

**Comment by ilike2burnthing** [comment]
Follow https://github.com/FlareSolverr/FlareSolverr/issues/687

**Comment by LegendAdmin** [comment]
I also encountered the same problem, but I can't solve it by increasing the memory.
I'm running it in the Docker of the NAS.
Even if I don't make any restrictions (I have 8GB of memory, the maximum container is 7.5GB), it still can't run.
It always restarts itself infinitely.

**Comment by ilike2burnthing** [comment]
Nice profile picture ;)

Open a new issues, provide the information requested and reference this closed issue.
