### ISSUE TITLE
Can't run FlareSolverr as non-root user

### ISSUE THREAD

**Issue by DimitriDR** [FlareSolverr/FlareSolverr#718]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: N/A
- Operating system: Linux x86/x64
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): N/A
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one: N/A
- URL to test this issue: N/A
```

### Description

Can't run FlareSolverr as non root user. When I specify, in my Docker compose file, `user: X:Y` where X is not a root user, FlareSolverr can't properly start.

### Logged Error Messages

```text
2023-03-03 10:50:16 INFO     FlareSolverr 3.0.2
flaresolver  | 2023-03-03 10:50:16 INFO     Testing web browser installation...
flaresolver  | 2023-03-03 10:50:16 INFO     Chrome / Chromium path: /usr/bin/chromium
flaresolver  | find: ‘//.config/chromium/Crash Reports/pending/’: No such file or directory
flaresolver  | 2023-03-03 10:50:26 INFO     Chrome / Chromium major version: 108
flaresolver  | Traceback (most recent call last):
flaresolver  |   File "/app/utils.py", line 158, in get_user_agent
flaresolver  |     driver = get_webdriver()
flaresolver  |              ^^^^^^^^^^^^^^^
flaresolver  |   File "/app/utils.py", line 57, in get_webdriver
flaresolver  |     start_xvfb_display()
flaresolver  |   File "/app/utils.py", line 172, in start_xvfb_display
flaresolver  |     XVFB_DISPLAY = Xvfb()
flaresolver  |                    ^^^^^^
flaresolver  |   File "/usr/local/lib/python3.11/site-packages/xvfbwrapper.py", line 37, in __init__
flaresolver  |     self._tempdir = tempdir or tempfile.gettempdir()
flaresolver  |                                ^^^^^^^^^^^^^^^^^^^^^
flaresolver  |   File "/usr/local/lib/python3.11/tempfile.py", line 299, in gettempdir
flaresolver  |     return _os.fsdecode(_gettempdir())
flaresolver  |                         ^^^^^^^^^^^^^
flaresolver  |   File "/usr/local/lib/python3.11/tempfile.py", line 292, in _gettempdir
flaresolver  |     tempdir = _get_default_tempdir()
flaresolver  |               ^^^^^^^^^^^^^^^^^^^^^^
flaresolver  |   File "/usr/local/lib/python3.11/tempfile.py", line 223, in _get_default_tempdir
flaresolver  |     raise FileNotFoundError(_errno.ENOENT,
flaresolver  | FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
flaresolver  | 
flaresolver  | During handling of the above exception, another exception occurred:
flaresolver  | 
flaresolver  | Traceback (most recent call last):
flaresolver  |   File "/app/flaresolverr.py", line 91, in <module>
flaresolver  |     flaresolverr_service.test_browser_installation()
```

**Comment by DimitriDR** [comment]
> Try ~v3.0.3~ v3.0.4

Sadly, it's the same. Thanks anyway. Looking forward this feature but It's certainly not urgent.

**Comment by ngosang** [comment]
FlareSolverr does not run as root inside the container, it has his own user. You can use the "flaresolverr" user or "root". If you want to use another user you have to build your own Docker image, but I don't see a reason to do that.
```shell
flaresolverr@74d7f819d84f:~$ id
uid=1000(flaresolverr) gid=1000(flaresolverr) groups=1000(flaresolverr)

flaresolverr@74d7f819d84f:~$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
flareso+       1  0.0  0.0   2236   896 ?        Ss   14:24   0:00 /usr/bin/dumb-init -- /usr/local/bin/python -u /app/flaresolverr.py
flareso+       7  0.7  0.4 345500 44500 ?        Ssl  14:24   0:00 /usr/local/bin/python -u /app/flaresolverr.py
flareso+      24  0.0  0.1  23020 13056 ?        S    14:24   0:00 Xvfb :534845478 -screen 0 800x680x24
flareso+     179  0.0  0.0   6056  3456 pts/0    Ss   14:25   0:00 bash
flareso+     188  0.0  0.0   8652  3200 pts/0    R+   14:25   0:00 ps aux
```

**Comment by ngosang** [comment]
As I said, it doesn't use root. Set runAsUser=flaresolverr

**Comment by SuperJugy** [comment]
Thanks. Setting runAsUser=1000 worked. I had created a separate user to handle the media center apps and that user was not working. Only root worked.
