### ISSUE TITLE
[dontorrent] (testing) Exception (dontorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by killo3967** [FlareSolverr/FlareSolverr#770]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.1.2
- Last working FlareSolverr version: 3.1.2
- Operating system: Windows 10
- Are you using Docker: [yes/no] No
- FlareSolverr User-Agent (see log traces or / endpoint):FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] No
- Are you using a Proxy: [yes/no] Yes
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

1.- Check DONTORRENT tracker.
After a while i saw a info, who said:

Dontorrent check fail with error:
 An error occurred while testing this indexer
Exception (dontorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### Logged Error Messages

```text
2023-04-28 21:10:10.8563 Error Jackett.Common.IndexerException: Exception (dontorrent): The cookies provided by FlareSolverr are not valid Jackett.Common.IndexerException: Exception (dontorrent): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.DonTorrent.PerformQueryNewest(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DonTorrent.cs:line 195
   at Jackett.Common.Indexers.DonTorrent.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DonTorrent.cs:line 156
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 701
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 315
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

========================================================================================================

And Flaresolverr log:

2023-04-28 20:53:16 INFO     FlareSolverr 3.1.2
2023-04-28 20:53:16 INFO     Testing web browser installation...
2023-04-28 20:53:16 INFO     Platform: Windows-10-10.0.19045-SP0
2023-04-28 20:53:16 INFO     Chrome / Chromium path: C:\flaresolverr\chrome\chrome.exe
2023-04-28 20:53:16 INFO     Chrome / Chromium major version: 111
2023-04-28 20:53:16 INFO     Launching web browser...
2023-04-28 20:53:18 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
2023-04-28 20:53:18 INFO     Test successful!
2023-04-28 20:53:18 INFO     Serving on http://0.0.0.0:8191
2023-04-28 20:53:49 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://dontorrent.observer/ultimos', 'proxy': {'url': '192.168.1.52:8118'}}
2023-04-28 20:53:53 INFO     Challenge not detected!
2023-04-28 20:53:53 INFO     Response in 4.053 s
2023-04-28 20:53:53 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
2023-04-28 21:07:52 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://dontorrent.observer/ultimos', 'proxy': {'url': '192.168.1.52:8118'}}
2023-04-28 21:07:55 INFO     Challenge not detected!
2023-04-28 21:07:56 INFO     Response in 4.053 s
2023-04-28 21:07:56 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
2023-04-28 21:08:12 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://www.divxtotal.wf/page/1/?s=', 'proxy': {'url': '192.168.1.52:8118'}}
2023-04-28 21:08:17 INFO     Challenge not detected!
2023-04-28 21:08:18 INFO     Response in 5.944 s
2023-04-28 21:08:18 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
2023-04-28 21:08:29 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://dontorrent.observer/ultimos', 'proxy': {'url': '192.168.1.52:8118'}}
2023-04-28 21:08:32 INFO     Challenge not detected!
2023-04-28 21:08:33 INFO     Response in 3.401 s
2023-04-28 21:08:33 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
2023-04-28 21:10:07 INFO     Incoming request => POST /v1 body: {'maxTimeout': 100000, 'cmd': 'request.get', 'url': 'https://dontorrent.observer/ultimos', 'proxy': {'url': '192.168.1.52:8118'}}
2023-04-28 21:10:09 INFO     Challenge not detected!
2023-04-28 21:10:09 INFO     Response in 2.506 s
2023-04-28 21:10:09 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
```

### Screenshots

![image](https://user-images.githubusercontent.com/71940871/235234723-b0fd4036-425d-4684-a3cc-25c1f82b198a.png)

**Comment by ilike2burnthing** [comment]
Disable the proxy and try again.

**Comment by killo3967** [comment]
Thi is the problem. It's take a lot lot lot  of time but at final it's ok.

2023-04-28 22:33:11.2019 Info Test search in DonTorrent => Found 306 releases [**156665**ms]

**Comment by ilike2burnthing** [comment]
If you want to use a VPN or proxy, you'll have to use it for both Jackett and FlareSolverr, not just one. However, doing so will not speed anything up, it takes a stupid amount of time - https://github.com/Jackett/Jackett/issues/6214#issuecomment-1404516412.
