### ISSUE TITLE
Tooks very long to solve cf chl

### ISSUE THREAD

**Issue by GariPog** [FlareSolverr/FlareSolverr#776]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: last
- Last working FlareSolverr version: last
- Operating system: Ubuntu 20
- Are you using Docker: [yes/no]yes and no (same situation on both)
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no]no
- Are you using a Proxy: [yes/no]no
- Are you using Captcha Solver: [yes/no]no
- If using captcha solver, which one:
- URL to test this issue:https://vostic.me/
```

### Description

It tooks very long to solve challenge, about 25 seconds. But on windows its like 4-5 seconds like before. I have tried reinstalling everything but nothing changes. It worked fine few days ago so maybe cf changed something. start time: 1683996913387, end time: 1683996937557, here you can see it doesnt even solved it.

### Logged Error Messages

```text
Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://vostic.me/', 'maxTimeout': 30000}
New instance of webdriver has been created to perform the request
Navigating to... https://vostic.me/
Challenge detected. Title found: Just a moment...
Waiting for title (attempt 1): Just a moment...


Timeout waiting for selector
Try to find the Cloudflare verify checkbox
Cloudflare verify checkbox found and clicked
Try to find the Cloudflare 'Verify you are human' button
The Cloudflare 'Verify you are human' button not found on the page
Waiting for title (attempt 2): Just a moment...
Waiting for title (attempt 2): DDoS-Guard
Waiting for title (attempt 2): NexusPIPE | Security Check
Waiting for title (attempt 2): PoW Shield
Waiting for selector (attempt 2): #cf-challenge-running
Waiting for selector (attempt 2): .ray_id
Waiting for selector (attempt 2): .attack-box
Waiting for selector (attempt 2): #cf-please-wait
Waiting for selector (attempt 2): #challenge-spinner
Waiting for selector (attempt 2): #trk_jschal_js
Waiting for selector (attempt 2): td.info #js_info
Waiting for selector (attempt 2): div.vc div.text-box#link-ddg
Waiting for redirect
Timeout waiting for redirect
Challenge solved!
A used instance of webdriver has been destroyed
Response => POST /v1 body: {'status': 'ok', 'message': 'Challenge solved!', 'solution': {'url': 'https://vostic.me/', 'status': 200, 'cookies': [{'domain': '.vostic.me', 'expiry': 1715532925, 'httpOnly': True, 'name': 'cf_clearance', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '9WM4w9zbEt8qs8jT4LbH_QMIZvQmeFdOmYElVjX9eVM-1683996913-0-250'}], 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36', 'headers': {}, 'response': '<html xmlns="http://www.w3.org/1999/xhtml"><!--\n    Modified from the Debian original for Ubuntu\n    Last updated: 2022-03-22\n    See: https://launchpad.net/bugs/1966004\n  --><head>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n    <title>Apache2 Ubuntu Default Page: It works</title>\n    <style type="text/css" media="screen">\n  * {\n    margin: 0px 0px 0px 0px;\n    padding: 0px 0px 0px 0px;\n  }\n\n  body, html {\n    padding: 3px 3px 3px 3px;\n\n    background-color: #D8DBE2;\n\n    font-family: Ubuntu, Verdana, sans-serif;\n    font-size: 11pt;\n    text-align: center;\n  }\n\n  div.main_page {\n    position: relative;\n    display: table;\n\n    width: 800px;\n\n    margin-bottom: 3px;\n    margin-left: auto;\n    margin-right: auto;\n    padding: 0px 0px 0px 0px;\n\n    border-width: 2px;\n    border-color: #212738;\n    border-style: solid;\n\n    background-color: #FFFFFF;\n\n    text-align: center;\n  }\n\n  div.page_header {\n    height: 180px;\n    width: 100%;\n\n    background-color: #F5F6F7;\n  }\n\n  div.page_header span {\n    margin: 15px 0px 0px 50px;\n\n    font-size: 180%;\n    font-weight: bold;\n  }\n\n  div.page_header img {\n    margin: 3px 0px 0px 40px;\n\n    border: 0px 0px 0px;\n  }\n\n  div.banner {\n    padding: 9px 6px 9px 6px;\n    background-color: #E9510E;\n    color: #FFFFFF;\n    font-weight: bold;\n    font-size: 112%;\n    text-align: center;\n    position: absolute;\n    left: 40%;\n    bottom: 30px;\n    width: 20%;\n  }\n\n  div.table_of_contents {\n    clear: left;\n\n    min-width: 200px;\n\n    margin: 3px 3px 3px 3px;\n\n    background-color: #FFFFFF;\n\n    text-align: left;\n  }\n\n  div.table_of_contents_item {\n    clear: left;\n\n    width: 100%;\n\n    margin: 4px 0px 0px 0px;\n\n    background-color: #FFFFFF;\n\n    color: #000000;\n    text-align: left;\n  }\n\n  div.table_of_contents_item a {\n    margin: 6px 0px 0px 6px;\n  }\n\n  div.content_section {\n    margin: 3px 3px 3px 3px;\n\n    background-color: #FFFFFF;\n\n    text-align: left;\n  }\n\n  div.content_section_text {\n    padding: 4px 8px 4px 8px;\n\n    color: #000000;\n    font-size: 100%;\n  }\n\n  div.content_section_text pre {\n    margin: 8px 0px 8px 0px;\n    padding: 8px 8px 8px 8px;\n\n    border-width: 1px;\n    border-style: dotted;\n    border-color: #000000;\n\n    background-color: #F5F6F7;\n\n    font-style: italic;\n  }\n\n  div.content_section_text p {\n    margin-bottom: 6px;\n  }\n\n  div.content_section_text ul, div.content_section_text li {\n    padding: 4px 8px 4px 16px;\n  }\n\n  div.section_header {\n    padding: 3px 6px 3px 6px;\n\n    background-color: #8E9CB2;\n\n    color: #FFFFFF;\n    font-weight: bold;\n    font-size: 112%;\n    text-align: center;\n  }\n\n  div.section_header_grey {\n    background-color: #9F9386;\n  }\n\n  .floating_element {\n    position: relative;\n    float: left;\n  }\n\n  div.table_of_contents_item a,\n  div.content_section_text a {\n    text-decoration: none;\n    font-weight: bold;\n  }\n\n  div.table_of_contents_item a:link,\n  div.table_of_contents_item a:visited,\n  div.table_of_contents_item a:active {\n    color: #000000;\n  }\n\n  div.table_of_contents_item a:hover {\n    background-color: #000000;\n\n    color: #FFFFFF;\n  }\n\n  div.content_section_text a:link,\n  div.content_section_text a:visited,\n   div.content_section_text a:active {\n    background-color: #DCDFE6;\n\n    color: #000000;\n  }\n\n  div.content_section_text a:hover {\n    background-color: #000000;\n\n    color: #DCDFE6;\n  }\n\n  div.validator {\n  }\n    </style>\n  </head>\n  <body>\n    <div class="main_page">\n      <div class="page_header floating_element">\n        <img src="icons/ubuntu-logo.png" alt="Ubuntu Logo" style="width:184px;height:146px;" class="floating_element">\n        <div>\n          <span style="margin-top: 1.5em;" class="floating_element">\n            Apache2 Default Page\n          </span>\n        </div>\n        <div class="banner">\n          <div id="about"></div>\n          It works!\n        </div>\n\n      </div>\n      <div class="content_section floating_element">\n        <div class="content_section_text">\n          <p>\n                This is the default welcome page used to test the correct \n                operation of the Apache2 server after installation on Ubuntu systems.\n                It is based on the equivalent page on Debian, from which the Ubuntu Apache\n                packaging is derived.\n                If you can read this page, it means that the Apache HTTP server installed at\n                this site is working properly. You should <b>replace this file</b> (located at\n                <tt>/var/www/html/index.html</tt>) before continuing to operate your HTTP server.\n          </p>\n\n          <p>\n                If you are a normal user of this web site and don\'t know what this page is\n                about, this probably means that the site is currently unavailable due to\n                maintenance.\n                If the problem persists, please contact the site\'s administrator.\n          </p>\n\n        </div>\n        <div class="section_header">\n          <div id="changes"></div>\n                Configuration Overview\n        </div>\n        <div class="content_section_text">\n          <p>\n                Ubuntu\'s Apache2 default configuration is different from the\n                upstream default configuration, and split into several files optimized for\n                interaction with Ubuntu tools. The configuration system is\n                <b>fully documented in\n                /usr/share/doc/apache2/README.Debian.gz</b>. Refer to this for the full\n                documentation. Documentation for the web server itself can be\n                found by accessing the <a href="/manual">manual</a> if the <tt>apache2-doc</tt>\n                package was installed on this server.\n          </p>\n          <p>\n                The configuration layout for an Apache2 web server installation on Ubuntu systems is as follows:\n          </p>\n          <pre>/etc/apache2/\n|-- apache2.conf\n|       `--  ports.conf\n|-- mods-enabled\n|       |-- *.load\n|       `-- *.conf\n|-- conf-enabled\n|       `-- *.conf\n|-- sites-enabled\n|       `-- *.conf\n          </pre>\n          <ul>\n                        <li>\n                           <tt>apache2.conf</tt> is the main configuration\n                           file. It puts the pieces together by including all remaining configuration\n                           files when starting up the web server.\n                        </li>\n\n                        <li>\n                           <tt>ports.conf</tt> is always included from the\n                           main configuration file. It is used to determine the listening ports for\n                           incoming connections, and this file can be customized anytime.\n                        </li>\n\n                        <li>\n                           Configuration files in the <tt>mods-enabled/</tt>,\n                           <tt>conf-enabled/</tt> and <tt>sites-enabled/</tt> directories contain\n                           particular configuration snippets which manage modules, global configuration\n                           fragments, or virtual host configurations, respectively.\n                        </li>\n\n                        <li>\n                           They are activated by symlinking available\n                           configuration files from their respective\n                           *-available/ counterparts. These should be managed\n                           by using our helpers\n                           <tt>\n                                a2enmod,\n                                a2dismod,\n                           </tt>\n                           <tt>\n                                a2ensite,\n                                a2dissite,\n                            </tt>\n                                and\n                           <tt>\n                                a2enconf,\n                                a2disconf\n                           </tt>. See their respective man pages for detailed information.\n                        </li>\n\n                        <li>\n                           The binary is called apache2 and is managed using systemd, so to\n                           start/stop the service use <tt>systemctl start apache2</tt> and\n                           <tt>systemctl stop apache2</tt>, and use <tt>systemctl status apache2</tt>\n                           and <tt>journalctl -u apache2</tt> to check status.  <tt>system</tt>\n                           and <tt>apache2ctl</tt> can also be used for service management if\n                           desired.\n                           <b>Calling <tt>/usr/bin/apache2</tt> directly will not work</b> with the\n                           default configuration.\n                        </li>\n          </ul>\n        </div>\n\n        <div class="section_header">\n            <div id="docroot"></div>\n                Document Roots\n        </div>\n\n        <div class="content_section_text">\n            <p>\n                By default, Ubuntu does not allow access through the web browser to\n                <em>any</em> file outside of those located in <tt>/var/www</tt>,\n                <a href="http://httpd.apache.org/docs/2.4/mod/mod_userdir.html" rel="nofollow">public_html</a>\n                directories (when enabled) and <tt>/usr/share</tt> (for web\n                applications). If your site is using a web document root\n                located elsewhere (such as in <tt>/srv</tt>) you may need to whitelist your\n                document root directory in <tt>/etc/apache2/apache2.conf</tt>.\n            </p>\n            <p>\n                The default Ubuntu document root is <tt>/var/www/html</tt>. You\n                can make your own virtual hosts under /var/www.\n            </p>\n        </div>\n\n        <div class="section_header">\n          <div id="bugs"></div>\n                Reporting Problems\n        </div>\n        <div class="content_section_text">\n          <p>\n                Please use the <tt>ubuntu-bug</tt> tool to report bugs in the\n                Apache2 package with Ubuntu. However, check <a href="https://bugs.launchpad.net/ubuntu/+source/apache2" rel="nofollow">existing bug reports</a> before reporting a new bug.\n          </p>\n          <p>\n                Please report bugs specific to modules (such as PHP and others)\n                to their respective packages, not to the web server itself.\n          </p>\n        </div>\n\n      </div>\n    </div>\n    <div class="validator">\n    </div>\n  \n\n</body></html>'}, 'startTimestamp': 1683996913387, 'endTimestamp': 1683996937557, 'version': '3.1.2'}
Response in 24.17 s
2023-05-13 16:55:37 INFO     146.70.189.175 POST http://167.235.236.40:8195/v1 200 OK
<LocalRequest: POST http://167.235.236.40:8195/v1>
Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://vostic.me/', 'maxTimeout': 30000}
^CError: Error solving the challenge. Message: Service /root/.local/share/undetected_chromedriver/chromedriver unexpectedly exited. Status code was: -2

Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Message: Service /root/.local/share/undetected_chromedriver/chromedriver unexpectedly exited. Status code was: -2\n', 'startTimestamp': 1683996937927, 'endTimestamp': 1683996938445, 'version': '3.1.2'}

```

EDIT:
I have tried to update version of chromium/chromedriver but unsuccessfully, it only works with standard chromedriver that comes with compiled version of flaresolverr.
```
2023-05-13 19:35:00 INFO     FlareSolverr 3.1.2
Testing web browser installation...
Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Chrome / Chromium path: /root/fs0/src/chrome/chrome
Chrome / Chromium major version: 113
Launching web browser...
*FREEZES HERE*
```

script doesnt work with 3.4.5 version of undetected-chromedriver and 113 version of chromium, but with 115 (Chromium 115.0.5769.0) version i get this error:

```
2023-05-13 19:33:24 INFO     FlareSolverr 3.1.2
Testing web browser installation...
Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Chrome / Chromium path: /root/fs0/src/chrome/chrome
Chrome / Chromium major version: 115
Launching web browser...
Traceback (most recent call last):
  File "/root/fs0/src/utils.py", line 188, in get_user_agent
    driver = get_webdriver("/")
             ^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/utils.py", line 83, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/undetected_chromedriver/__init__.py", line 246, in __init__
    self.patcher.auto()
  File "/root/fs0/src/undetected_chromedriver/patcher.py", line 124, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/undetected_chromedriver/patcher.py", line 145, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/fs0/src/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/root/fs0/src/flaresolverr_service.py", line 78, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/utils.py", line 192, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

Someone knows fixed?

**Comment by ilike2burnthing** [comment]
We're using a modified version of undetected_chromedriver 3.4.6:
https://github.com/FlareSolverr/FlareSolverr/pull/715#issuecomment-1455361970
https://github.com/FlareSolverr/FlareSolverr/commit/a9d1a2de2d3350aa60cd116423fce49d9e261b86

As for the difference in time, are you using different hardware?

**Comment by GariPog** [comment]
No, its same hardware, everything is same, version of chrome, undetected-chromedriver, flaresolverr, everything is same but it takes longer than few days ago.

**Comment by GariPog** [comment]
And, its not some 2 core server, its 16 core, 32gb ram, 1gbit port. so its unusual to take that long.

**Comment by GariPog** [comment]
UPDATE:
its slow and bad only at CF, on ddos guard it works fine and solves in 3-4 seconds like on cf like 5 days ago.
```

2023-05-14 11:18:57 INFO     1.1.1.1 POST http://1.1.1.1:8191/v1 200 OK
2023-05-14 11:19:08 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://anidex.info/', 'maxTimeout': 30000}
2023-05-14 11:19:09 INFO     Challenge detected. Title found: DDoS-Guard

2023-05-14 11:19:12 INFO     Challenge solved!
2023-05-14 11:19:12 INFO     Response in 3.652 s
2023-05-14 11:19:12 INFO     1.1.1.1 POST http://1.1.1.1:8191/v1 200 OK
2023-05-14 11:19:13 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://anidex.info/', 'maxTimeout': 30000}
2023-05-14 11:19:14 INFO     Challenge detected. Title found: DDoS-Guard
2023-05-14 11:19:16 INFO     Challenge solved!
2023-05-14 11:19:16 INFO     Response in 3.604 s
2023-05-14 11:19:16 INFO     1.1.1.1 POST http://1.1.1.1:8191/v1 200 OK
2023-05-14 11:19:17 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://anidex.info/', 'maxTimeout': 30000}
2023-05-14 11:19:18 INFO     Challenge detected. Title found: DDoS-Guard
2023-05-14 11:19:20 INFO     Challenge solved!
2023-05-14 11:19:21 INFO     Response in 3.516 s
2023-05-14 11:19:21 INFO     1.1.1.1POST http://1.1.1.1:8191/v1 200 OK
```

**Comment by ngosang** [comment]
Sorry but there is nothing we can fix in FlareSolverr. I notice in Linux Cloudflare challenge could take more time (also in my personal web browser). I guess most of the DDoS attacks come from Linux machines and they are doing something different.
