### ISSUE TITLE
Can't start Flaresolverr after python-selenium 4.10 update

### ISSUE THREAD

**Issue by DX37** [FlareSolverr/FlareSolverr#801]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.0
- Last working FlareSolverr version: 3.2.0
- Operating system: Arch Linux
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): got none
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: -
```

### Description

Got logs down there. I can't figure which dependency or something doing this error.

### Logged Error Messages

```text
00:08:52 systemd[1]: Started FlareSolverr.
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     FlareSolverr 3.2.0
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Testing web browser installation...
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Platform: Linux-6.3.8-arch1-1-x86_64-with-glibc2.37
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Chrome / Chromium path: /usr/bin/chromium
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Chrome / Chromium major version: 114
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Launching web browser...
00:08:56 flaresolverr[26508]: Traceback (most recent call last):
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/utils.py", line 202, in get_user_agent
00:08:56 flaresolverr[26508]:     driver = get_webdriver()
00:08:56 flaresolverr[26508]:              ^^^^^^^^^^^^^^^
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/utils.py", line 88, in get_webdriver
00:08:56 flaresolverr[26508]:     driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
00:08:56 flaresolverr[26508]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/undetected_chromedriver/__init__.py", line 447, in __init__
00:08:56 flaresolverr[26508]:     super(Chrome, self).__init__(
00:08:56 flaresolverr[26508]: TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
00:08:56 flaresolverr[26508]: During handling of the above exception, another exception occurred:
00:08:56 flaresolverr[26508]: Traceback (most recent call last):
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/flaresolverr.py", line 102, in <module>
00:08:56 flaresolverr[26508]:     flaresolverr_service.test_browser_installation()
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/flaresolverr_service.py", line 72, in test_browser_installation
00:08:56 flaresolverr[26508]:     user_agent = utils.get_user_agent()
00:08:56 flaresolverr[26508]:                  ^^^^^^^^^^^^^^^^^^^^^^
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/utils.py", line 206, in get_user_agent
00:08:56 flaresolverr[26508]:     raise Exception("Error getting browser User-Agent. " + str(e))
00:08:56 flaresolverr[26508]: Exception: Error getting browser User-Agent. WebDriver.__init__() got an unexpected keyword argument 'executable_path'
00:08:56 systemd[1]: flaresolverr.service: Main process exited, code=exited, status=1/FAILURE
00:08:56 systemd[1]: flaresolverr.service: Failed with result 'exit-code'.
00:08:57 systemd[1]: Stopped FlareSolverr.
```

**Comment by DX37** [comment]
Oh, I guess I got it. Flaresolverr shipped with undetected-chromedriver version `3.4.6`, but recently it got updated to `3.5.0` to be compatible with recently updated Selenium `4.10` (which I installed on 8 Jun, but found out about error only now).
