### ISSUE TITLE
HEADLESS=false causes windows flaresolverr.exe to loop

### ISSUE THREAD

**Issue by sunnyd24** [FlareSolverr/FlareSolverr#819]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.2.1
- Last working FlareSolverr version: v2.2.10
- Operating system: Windows 11
- Are you using Docker: no
- FlareSolverr User-Agent (when working without HEADLESS=false): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: N/A
```

### Description

Issue caused when moving to v3.x.x of Flaresolverr, used to work fine with v2.1.10.

1. Open command prompt with admin privileges
2. Point to path where flaresolverr.exe exists
3. Set environment variables to: LOG_HTML=true, LOG_LEVEL=debug, HEADLESS=false
4. Run flaresolverr.exe
5. See Flaresolverr continuously trying to "Launching web browser..."

### Logged Error Messages

```text
**with following set in environment variables, it doesn't work:
set LOG_HTML=true
set LOG_LEVEL=debug
set HEADLESS=false**

D:\FlareSolverr\flaresolverr>flaresolverr.exe
2023-07-15 11:14:52 INFO     ReqId 31100 FlareSolverr 3.2.1
2023-07-15 11:14:52 DEBUG    ReqId 31100 Debug log enabled
2023-07-15 11:14:52 INFO     ReqId 31100 Testing web browser installation...
2023-07-15 11:14:52 INFO     ReqId 31100 Platform: Windows-10-10.0.22621-SP0
2023-07-15 11:14:52 INFO     ReqId 31100 Chrome / Chromium path: D:\FlareSolverr\flaresolverr\chrome\chrome.exe
2023-07-15 11:14:52 INFO     ReqId 31100 Chrome / Chromium major version: 111
2023-07-15 11:14:52 INFO     ReqId 31100 Launching web browser...
2023-07-15 11:14:52 DEBUG    ReqId 31100 Launching web browser...
2023-07-15 11:14:53 INFO     ReqId 13752 FlareSolverr 3.2.1
2023-07-15 11:14:53 DEBUG    ReqId 13752 Debug log enabled
2023-07-15 11:14:53 INFO     ReqId 13752 Testing web browser installation...
2023-07-15 11:14:53 INFO     ReqId 13752 Platform: Windows-10-10.0.22621-SP0
2023-07-15 11:14:53 INFO     ReqId 13752 Chrome / Chromium path: D:\FlareSolverr\flaresolverr\chrome\chrome.exe
2023-07-15 11:14:53 INFO     ReqId 13752 Chrome / Chromium major version: 111
2023-07-15 11:14:53 INFO     ReqId 13752 Launching web browser...
2023-07-15 11:14:53 DEBUG    ReqId 13752 Launching web browser...
2023-07-15 11:14:54 INFO     ReqId 9500 FlareSolverr 3.2.1
2023-07-15 11:14:54 DEBUG    ReqId 9500 Debug log enabled
2023-07-15 11:14:54 INFO     ReqId 9500 Testing web browser installation...
2023-07-15 11:14:54 INFO     ReqId 9500 Platform: Windows-10-10.0.22621-SP0
2023-07-15 11:14:54 INFO     ReqId 9500 Chrome / Chromium path: D:\FlareSolverr\flaresolverr\chrome\chrome.exe
2023-07-15 11:14:54 INFO     ReqId 9500 Chrome / Chromium major version: 111
2023-07-15 11:14:54 INFO     ReqId 9500 Launching web browser...
2023-07-15 11:14:54 DEBUG    ReqId 9500 Launching web browser...

**For Comparison, with following set in environment variables, it works:
set LOG_HTML=true
set LOG_LEVEL=debug
set HEADLESS=true**

D:\FlareSolverr\flaresolverr>flaresolverr.exe
2023-07-15 11:23:59 INFO     ReqId 22996 FlareSolverr 3.2.1
2023-07-15 11:23:59 DEBUG    ReqId 22996 Debug log enabled
2023-07-15 11:23:59 INFO     ReqId 22996 Testing web browser installation...
2023-07-15 11:23:59 INFO     ReqId 22996 Platform: Windows-10-10.0.22621-SP0
2023-07-15 11:23:59 INFO     ReqId 22996 Chrome / Chromium path: D:\FlareSolverr\flaresolverr\chrome\chrome.exe
2023-07-15 11:23:59 INFO     ReqId 22996 Chrome / Chromium major version: 111
2023-07-15 11:23:59 INFO     ReqId 22996 Launching web browser...
2023-07-15 11:23:59 DEBUG    ReqId 22996 Launching web browser...
2023-07-15 11:24:00 DEBUG    ReqId 22996 Started executable: `C:\Users\User\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe` in a child process with pid: 31096
2023-07-15 11:24:01 INFO     ReqId 22996 FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
2023-07-15 11:24:01 INFO     ReqId 22996 Test successful!
2023-07-15 11:24:01 INFO     ReqId 22996 Serving on http://0.0.0.0:8191
```

**Comment by ngosang** [comment]
It should be fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0

**Comment by ilike2burnthing** [comment]
Unfortunately not:

```text
C:\Users\WDAGUtilityAccount\Downloads\flaresolverr>flaresolverr
2023-08-02 21:05:25 INFO     ReqId 5528 FlareSolverr 3.3.0
2023-08-02 21:05:25 DEBUG    ReqId 5528 Debug log enabled
2023-08-02 21:05:25 INFO     ReqId 5528 Testing web browser installation...
2023-08-02 21:05:25 INFO     ReqId 5528 Platform: Windows-10-10.0.19041-SP0
2023-08-02 21:05:25 INFO     ReqId 5528 Chrome / Chromium path: C:\Users\WDAGUtilityAccount\Downloads\flaresolverr\chrome\chrome.exe
2023-08-02 21:05:25 INFO     ReqId 5528 Chrome / Chromium major version: 115
2023-08-02 21:05:25 INFO     ReqId 5528 Launching web browser...
2023-08-02 21:05:25 DEBUG    ReqId 5528 Launching web browser...
2023-08-02 21:05:26 INFO     ReqId 5540 FlareSolverr 3.3.0
2023-08-02 21:05:26 DEBUG    ReqId 5540 Debug log enabled
2023-08-02 21:05:26 INFO     ReqId 5540 Testing web browser installation...
2023-08-02 21:05:26 INFO     ReqId 5540 Platform: Windows-10-10.0.19041-SP0
2023-08-02 21:05:26 INFO     ReqId 5540 Chrome / Chromium path: C:\Users\WDAGUtilityAccount\Downloads\flaresolverr\chrome\chrome.exe
2023-08-02 21:05:26 INFO     ReqId 5540 Chrome / Chromium major version: 115
2023-08-02 21:05:26 INFO     ReqId 5540 Launching web browser...
2023-08-02 21:05:26 DEBUG    ReqId 5540 Launching web browser...
2023-08-02 21:05:27 INFO     ReqId 4080 FlareSolverr 3.3.0

[...]

2023-08-02 21:05:32 DEBUG    ReqId 4060 Launching web browser...
Traceback (most recent call last):
  File "flaresolverr.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "flaresolverr_service.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "undetected_chromedriver\__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "undetected_chromedriver\cdp.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "requests\compat.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "http\cookiejar.py", line 288, in <module>
  File "re\__init__.py", line 227, in compile
  File "re\__init__.py", line 294, in _compile
  File "re\_compiler.py", line 743, in compile
  File "re\_parser.py", line 980, in parse
  File "re\_parser.py", line 455, in _parse_sub
  File "re\_parser.py", line 863, in _parse
  File "re\_parser.py", line 455, in _parse_sub
  File "re\_parser.py", line 863, in _parse
  File "re\_parser.py", line 455, in _parse_sub
  File "re\_parser.py", line 699, in _parse
  File "re\_parser.py", line 166, in __setitem__
KeyboardInterrupt
[4964] Failed to execute script 'flaresolverr' due to unhandled exception!
Traceback (most recent call last):
  File "flaresolverr.py", line 99, in <module>
  File "flaresolverr_service.py", line 72, in test_browser_installation
  File "utils.py", line 296, in get_user_agent
  File "utils.py", line 177, in get_webdriver
  File "undetected_chromedriver\__init__.py", line 437, in __init__
  File "undetected_chromedriver\dprocess.py", line 37, in start_detached
  File "multiprocessing\process.py", line 149, in join
  File "multiprocessing\popen_spawn_win32.py", line 109, in wait
```

**Comment by ngosang** [comment]
Fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.1
