### ISSUE TITLE
Can't run new release 3.2.2

### ISSUE THREAD

**Issue by uponatime2019** [FlareSolverr/FlareSolverr#821]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.2
- Last working FlareSolverr version: 3.2.1
- Operating system: Windows 10
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

When run program this error occurred

### Logged Error Messages

```text
\Downloads\flaresolverr>flaresolverr.exe
[7340] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 22, in <module>
  File "pathlib.py", line 14, in <module>
  File "urllib\parse.py", line 40, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[7340] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1637214058
