### ISSUE TITLE
undetected_chromedriver patcher is broken with Chrome >= 115

### ISSUE THREAD

**Issue by Hyperz** [FlareSolverr/FlareSolverr#827]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.2
- Last working FlareSolverr version: 3.2.2
- Operating system: Windows 10 Pro
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): N/A because it crashes
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: any
```

### Description

It looks like Google has deprecated https://chromedriver.storage.googleapis.com/ for Chrome versions over 114. As a result the undetected_chromedriver patcher is throwing a 404 HTTPError with the latest Chrome update because https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115 doesn't exist. There's a new API at https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json which replaces the old one.

Related Google announcement: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE/m/5NxzS_SRAgAJ

### Logged Error Messages

```text
2023-07-19 21:58:31 INFO     Testing web browser installation...
2023-07-19 21:58:31 INFO     Platform: Windows-10-10.0.19044-SP0
2023-07-19 21:58:31 INFO     Chrome / Chromium path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
2023-07-19 21:58:31 INFO     Chrome / Chromium major version: 115
2023-07-19 21:58:31 INFO     Launching web browser...
Traceback (most recent call last):
  File "c:\Software\Flaresolverr\source_v3\src\utils.py", line 210, in get_user_agent
    driver = get_webdriver()
  File "c:\Software\Flaresolverr\source_v3\src\utils.py", line 96, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
  File "c:\Software\Flaresolverr\source_v3\src\undetected_chromedriver\__init__.py", line 247, in __init__
    self.patcher.auto()
  File "c:\Software\Flaresolverr\source_v3\src\undetected_chromedriver\patcher.py", line 124, in auto
    release = self.fetch_release_number()
  File "c:\Software\Flaresolverr\source_v3\src\undetected_chromedriver\patcher.py", line 145, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\Development\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Development\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Development\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Development\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Development\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Development\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Software\Flaresolverr\source_v3\src\flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "c:\Software\Flaresolverr\source_v3\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "c:\Software\Flaresolverr\source_v3\src\utils.py", line 214, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

**Comment by ilike2burnthing** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1259#issuecomment-1546736798
