### ISSUE TITLE
Bizarre error when starting up (shutil.SameFileError)

### ISSUE THREAD

**Issue by Yankees4life** [FlareSolverr/FlareSolverr#831]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: FlareSolverr 3.2.2
- Last working FlareSolverr version: FlareSolverr 3.2.1
- Operating system: Windows
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Not too sure whats happening here. I even cleared the cache and cookies on chrome so it can't be that

### Logged Error Messages

```text
2023-07-25 23:34:01 INFO     FlareSolverr 3.2.2
2023-07-25 23:34:01 INFO     Testing web browser installation...
2023-07-25 23:34:02 INFO     Platform: Windows-10-10.0.19044-SP0
2023-07-25 23:34:02 INFO     Chrome / Chromium path: C:\Program Files\Google\Chrome\Application\chrome.exe
2023-07-25 23:34:02 INFO     Chrome / Chromium major version: 113
2023-07-25 23:34:02 INFO     Launching web browser...
Traceback (most recent call last):
  File "C:\Users\Jean\Documents\Projects\FlareSolverr\src\utils.py", line 218, in get_user_agent
    driver = get_webdriver()
  File "C:\Users\Jean\Documents\Projects\FlareSolverr\src\utils.py", line 104, in get_webdriver
    shutil.copy(driver.patcher.executable_path, PATCHED_DRIVER_PATH)
  File "C:\Program Files\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python310\lib\shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'C:\\Users\\Jean\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' and 'C:\\Users\\Jean\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' are the same file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jean\Documents\Projects\FlareSolverr\src\flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "C:\Users\Jean\Documents\Projects\FlareSolverr\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "C:\Users\Jean\Documents\Projects\FlareSolverr\src\utils.py", line 222, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. 'C:\\Users\\Jean\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' and 'C:\\Users\\Jean\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' are the same file
```

**Comment by ilike2burnthing** [comment]
Delete the `C:\Users\Jean\appdata\roaming\undetected_chromedriver` folder.
