### ISSUE TITLE
Docker not working for v3.3.0

### ISSUE THREAD

**Issue by waynerobinson** [FlareSolverr/FlareSolverr#853]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.0
- Last working FlareSolverr version: n/a
- Operating system: Linux
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): n/a
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue: n/a
```

### Description

Docker version of FlareSolverr 3.3.0 not working with command (see logs):

```bash
docker run \
  --name=flaresolverr \
  -p 8191:8191 \
  -e LOG_LEVEL=debug \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:v3.3.0
```

### Logged Error Messages

```text
2023-08-03 02:32:09 INFO     ReqId 140231755312000 FlareSolverr 3.3.0
2023-08-03 02:32:09 DEBUG    ReqId 140231755312000 Debug log enabled
2023-08-03 02:32:09 INFO     ReqId 140231755312000 Testing web browser installation...
2023-08-03 02:32:09 INFO     ReqId 140231755312000 Platform: Linux-5.15.0-1020-aws-x86_64-with-glibc2.36
2023-08-03 02:32:09 INFO     ReqId 140231755312000 Chrome / Chromium path: /bin/chromium
2023-08-03 02:32:09 INFO     ReqId 140231755312000 Chrome / Chromium major version: 115
2023-08-03 02:32:09 INFO     ReqId 140231755312000 Launching web browser...
2023-08-03 02:32:09 DEBUG    ReqId 140231755312000 Launching web browser...
2023-08-03 02:32:09 DEBUG    ReqId 140231755312000 Started executable: `/app/chromedriver` in a child process with pid: 31
Traceback (most recent call last):
  File "/app/utils.py", line 296, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 177, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 461, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 122, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /app/chromedriver unexpectedly exited. Status code was: -5


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 99, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 300, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: Service /app/chromedriver unexpectedly exited. Status code was: -5
```

**Comment by InterN0te** [comment]
You're not the only one with this issue, a pull request is already there : #850

**Comment by waynerobinson** [comment]
Sorry about that! Didn't put two-and-two together based on my quick search of titles. 😅

**Comment by ngosang** [comment]
Fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.1

**Comment by InterN0te** [comment]
Still got this error with v3.3.2 :

![image](https://github.com/FlareSolverr/FlareSolverr/assets/10882916/7abe27e0-9e61-46df-b89a-c7e9ddd677e6)

**Comment by Redirts** [comment]
The error is still present with 3.3.2....
