### ISSUE TITLE
The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by harry4152** [FlareSolverr/FlareSolverr#89]
### Environment

**FlareSolverr Version**: 1.2.3

**Docker**: yes

**OS**: Debian GNU/Linux 10 (buster) arm64

**Last Working FlareSolverr Version**: Unknown

**Are you using a proxy or VPN?** No

**Using Captcha Solver:** No

### Description

Hello ! 

Based on the advice of @ilike2burnthing  i'm openning an issue here ! You can also see the issue that was open on Jackett here #https://github.com/Jackett/Jackett/issues/11127

My setup is the following : 
  - Jackett running on my host ;
  - FlareSolverr running within in a docker with the standard settings on the same host.
 
At the moment all the indexers which are protected by CloudFlare would fail (yggtorrent,torrent7) even tho FlareSolverr show a successful response in the logs.

"The cookies provided by FlareSolverr are not valid".

I'll gladly accept some help on this and i'm available if some more logs/debugging/whatever are needed.

Thank you for your work and your time !

### Logged Error Messages

The logs did not provide any error , in fact they show a success : 
```
2021-02-18T21:44:14.019Z INFO REQ-20 Cloudflare detected
2021-02-18T21:44:23.035Z INFO REQ-20 Successful response in 11.077 s
2021-02-18T22:52:08.422Z INFO REQ-21 Incoming request: GET /
2021-02-18T22:52:08.422Z INFO REQ-21 Successful response in 0 s
2021-02-18T22:52:08.422Z INFO REQ-21 FlareSolverr is ready!
2021-02-18T22:53:02.780Z INFO REQ-22 Incoming request: POST /v1
2021-02-18T22:53:02.781Z INFO REQ-22 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-02-18T22:53:04.859Z INFO REQ-22 Cloudflare detected
2021-02-18T22:53:11.741Z INFO REQ-22 Successful response in 8.961 s
2021-02-18T22:53:42.122Z INFO REQ-23 Incoming request: POST /v1
2021-02-18T22:53:42.123Z INFO REQ-23 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-02-18T22:53:43.274Z INFO REQ-23 Cloudflare detected
2021-02-18T22:53:50.029Z INFO REQ-23 Successful response in 7.907 s
2021-02-18T22:53:54.541Z INFO REQ-24 Incoming request: GET /
2021-02-18T22:53:54.541Z INFO REQ-24 Successful response in 0 s
2021-02-18T22:53:54.542Z INFO REQ-24 FlareSolverr is ready!
```
The Jackett error is the following : 
```
Jackett.Common.IndexerException: Exception (yggcookie): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1271
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```
### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/79253378/108476971-f10ec200-7292-11eb-8eb8-b19c4280789f.png)

**Comment by ilike2burnthing** [comment]
@ngosang see https://github.com/Jackett/Jackett/issues/11127#issuecomment-782598822 for suspected cause.

**Comment by HpNoTiQ56** [comment]
Hi,
I've got same issues on other sites like 7torrents for example. I've tried YggTorrent, Yggcookie and 7torrents and they all get this error.
It was working fine 5 days ago.

**Comment by ilike2burnthing** [comment]
Unless you're adding additional information, don't post 'same here' comments, just use a thumbs up reaction on the initial post to show that you're also affected, and subscribe for notifications if you want to keep track of it.

**Comment by HpNoTiQ56** [comment]
> Unless you're adding additional information, don't post 'same here' comments, just use a thumbs up reaction on the initial post to show that you're also affected, and subscribe for notifications if you want to keep track of it.

I'm just adding it's not working for 3 indexers.

**Comment by ilike2burnthing** [comment]
Already mentioned in OP. It's a general issue, not specific to any indexers.

**Comment by havocked** [comment]
> @ngosang see [Jackett/Jackett#11127 (comment)](https://github.com/Jackett/Jackett/issues/11127#issuecomment-782598822) for suspected cause.

To complete the previous comment, this place is more suspicious:
https://github.com/Jackett/Jackett/blob/bf8cae6a48839f9fb42c2e30a9f5832667b072c5/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs#L59

 When init `ClearanceHandler` (handler communicating with Flaresolverr), we set `BrowserUtil.ChromeUserAgent`. It's probably this User Agent that's going to be used for Flaresolverr, right? I'm not an expert in C# but the parts of the code I mentioned are suspicious :)

**Comment by Only1Jake** [comment]
Hi there, I am getting this issue currently and can't seem to get past any cloudflare sites. I've tried this on different pcs and still getting this error. I'm using the flaresolverr.exe on localhost with no proxy and using https://github.com/ngosang/FlareSolverrSharp in Microsoft Visual studio from here. Any help appreciated!!


![zt (2)](https://user-images.githubusercontent.com/6633128/116643535-626e9d80-a9c5-11eb-863d-a0ddf4cf4fef.PNG)

**Comment by Only1Jake** [comment]
Can someone please help me with this as I am not using any kind of proxy. thanks.

**Comment by QuentinJ54** [comment]
Hello, I found a solution at the moment. I forced the DNS of my Synologi and deactivated the IPv6 on my box and it worked directly.

**Comment by jeff15110168** [comment]
hello - im having this same issue after having setup Flaresolverr + jackett using docker (on Unraid). Any idea how to fix this error?

`Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid`

Logs in Flaresolver itself show that it seems to be working?

```
2021-07-27T22:49:27-04:00 INFO FlareSolverr v1.2.8
2021-07-27T22:49:27-04:00 INFO Listening on http://0.0.0.0:8191
2021-07-27T22:49:36-04:00 INFO REQ-1 Incoming request: POST /v1
2021-07-27T22:49:36-04:00 INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.1337x.to/cat/Movies/time/desc/1/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-07-27T22:49:39-04:00 INFO REQ-1 Cloudflare detected
2021-07-27T22:49:40-04:00 INFO REQ-1 Challenge solved.
2021-07-27T22:49:40-04:00 INFO REQ-1 Response in 3.81 s
```

**Comment by ngosang** [comment]
Related #161

**Comment by Kwinnieprince** [comment]
I have the same issue, both Jackett and Flaresolver are running in docker containers and I've disabled IPv6 on those docker containers. They are also both in the same network.
The FlareSolverr logs look fine, they handle the request successfully but then in Jacket, it goes wrong

**Comment by flynn-buc** [comment]
> Fixed in [FlareSolverr v2.0.0](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.0.0)
> If you are using Jackett, version v0.18.1041 or higher is required to bypass Cloudflare.

Using jackett Version v0.20.195 and flaresolverr v2.1.0, issue is still present for me. Running flaresolverr on docker, same machine as jackett, on windows 10 pro.

**Comment by ilike2burnthing** [comment]
Could you access the site in browser from the same device at that time? Or if you can access it now, does it work in Jackett?

**Comment by flynn-buc** [comment]
I can access the site directly on a browser, but it fails tests from jackett. Without flaresolverr, I get an error stating that a challenge is detected but flaresolverr is not configured.

**Comment by ilike2burnthing** [comment]
Using the URL https://1337x.to/ you can access it in browser at the moment? Because it's returning `Error 503 Service Unavailable` for me and has been for most of the day.

The official mirrors are working fine though, try them.

**Comment by flynn-buc** [comment]
Yup! I even just clicked on your link and the site loaded with no issues for me.  https://imgur.com/Sm7OeWm

**Comment by ilike2burnthing** [comment]
Weird, it's refusing to load for me.

Do any of the mirror sites work for you?

**Comment by flynn-buc** [comment]
Tried a couple earlier today, everything seems fine for me

**Comment by SmartBoy84** [comment]
I have the same issue "The cookies provided by FlareSolverr are not valid"
I've even turned off IPV6 for the Flaresolerr container. Oddly enough, when hosting flaresoleverr on other computer it works perfectly.

**Comment by ilike2burnthing** [comment]
IPv6 needs to be disabled for both FlareSolverr and Jackett.

**Comment by SmartBoy84** [comment]
How do I disable IPV6 for Jackett when it's not running in a docker container and `curl 'https://api.ipify.org?format=json'` returns the IPV4 IP on the host

**Comment by ilike2burnthing** [comment]
Either disable it for your system as a whole or switch to using a Jackett container.

See the top of this troubleshooting section - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by SmartBoy84** [comment]
> Either disable it for your system as a whole or switch to using a Jackett container.
> 
> See the top of this troubleshooting section - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

Yep, can confirm; turning IPV6 off system-wide works.

**Comment by Nuke142** [comment]
> hello - im having this same issue after having setup Flaresolverr + jackett using docker (on Unraid). Any idea how to fix this error?
> 
> `Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid`
> ```

Hey. Solved on Unraid?

**Comment by Nuke142** [comment]
> hello - im having this same issue after having setup Flaresolverr + jackett using docker (on Unraid). Any idea how to fix this error?
> `Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid`
> ```

@jeff15110168 Hey. Solved on Unraid?

**Comment by vinchi007** [comment]
not working for me either. disabled all ipv6 on docker host and related containers (flaresolverr and jackett)

**Comment by Alphachoups** [comment]
Still not working after years.. So frustrating a solution with problems every weeks/months..

**Comment by ngosang** [comment]
Jackett v0.20.2495 + FlareSolverr 3.0.0 fix most issues

**Comment by EnfantDup** [comment]
It still have this issue with the latest version. I believe it is related to IPv6 as I cannot disable it (used by other services)

**Comment by ilike2burnthing** [comment]
@EnfantDup if you're using (or able to use) Docker, you can disable IPv6 for just the Jackett and FlareSolverr containers.

**Comment by inverimus** [comment]
IPV6 disabled for both, stopped working for me recently after working fine for months.

**Comment by ilike2burnthing** [comment]
Open a new issue rather than commenting on a 2.5yr old post.

**Comment by tuyennn** [comment]
Issue was still persistent

**Comment by majc18** [comment]
I'm using raspberry pi 5 with raspberry pi os that uses NetworkManager and this solution worked for me:

 ## **Step 1: Configure DNS with NetworkManager**

nmcli connection show
sudo nmcli connection modify "Wired connection 1" ipv4.dns "8.8.8.8 1.1.1.1"
sudo nmcli connection modify "Wired connection 1" ipv6.dns ""
sudo nmcli connection up "Wired connection 1"


## **Step 2: Disable IPv6 via NetworkManager**


# Disable IPv6 on your connection
sudo nmcli connection modify "Wired connection 1" ipv6.method "disabled"
sudo nmcli connection up "Wired connection 1"

## **Step 3: Configure Docker DNS & Disable IPv6**

# Create/edit Docker config
sudo nano /etc/docker/daemon.json

```bash
{
  "dns": ["8.8.8.8", "1.1.1.1"],
  "ipv6": false,
  "experimental": false
}

Save and restart Docker:

sudo systemctl restart docker

## **Step 4: Recreate FlareSolverr Container**

# Stop and remove old container
sudo docker stop flaresolverr && sudo docker rm flaresolverr

# Create new container
docker run -d \
  --name=flaresolverr \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest


## **Step 5: Verify Settings**


# Check DNS
nmcli connection show "Wired connection 1" | grep ipv4.dns

# Check IPv6 status
nmcli connection show "Wired connection 1" | grep ipv6.method
# Should show "disabled"

# Check Docker DNS
sudo docker run --rm alpine cat /etc/resolv.conf
# Should show 8.8.8.8 and 1.1.1.1

# Test FlareSolverr
curl -X POST "http://localhost:8191/v1" \
  -H "Content-Type: application/json" \
  -d '{"cmd": "request.get", "url":"https://google.com", "maxTimeout": 60000}'
