### ISSUE TITLE
Memory overflow & Unable to process browser request.

### ISSUE THREAD

**Issue by libid0nes** [FlareSolverr/FlareSolverr#90]
### Environment

**FlareSolverr Version**: 1.2.3

**Docker**: no

**OS**: Windows 21H1

**Last Working FlareSolverr Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] no

**Using Captcha Solver:** no

**If using captcha solver, which one:** none

### Description

For some reason, at runtime, the Chromium instance literally gobbles up memory, reaching 2GB consumption in 15-20 seconds.
https://imgur.com/WmKxJDM
I think this is related to the inability to process the request.

### Logged Error Messages

```
2021-02-20T19:42:00.150Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
2021-02-20T19:42:00.153Z DEBUG REQ-0 Debug log enabled
2021-02-20T19:42:07.815Z INFO REQ-1 Incoming request: POST /v1
2021-02-20T19:42:07.819Z INFO REQ-1 Params: {"cmd":"request.get","url":"http://www.javlibrary.com/en/"}
2021-02-20T19:42:07.820Z DEBUG REQ-1 Launching headless browser...
2021-02-20T19:42:08.160Z DEBUG REQ-1 Adding custom headers: {}
2021-02-20T19:42:08.160Z DEBUG REQ-1 { headers: [Function (anonymous)] }
2021-02-20T19:42:08.166Z DEBUG REQ-1 Navigating to... http://www.javlibrary.com/en/
2021-02-20T19:42:08.207Z DEBUG REQ-1 {
  headers: {
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'
  }
}
2021-02-20T19:42:08.531Z DEBUG REQ-1 <!DOCTYPE html><html lang="en-US"><head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="robots" content="noindex, nofollow">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="12">
  <script type="text/javascript">
    //<![CDATA[
    (function(){

      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "27265",
        cRay: "624ab57fad50fa5c",
        cHash: "3b761cf5646df51",
        cFPWv: "b",
        cTTimeMs: "4000",
        cRq: {
          ru: "aHR0cDovL3d3dy5qYXZsaWJyYXJ5LmNvbS9lbi8=",
          ra: "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgxLjAuNDA0NC4xMzggU2FmYXJpLzUzNy4zNg==",
          rm: "R0VU",
          d: "XQnAHSWxrd2hRxEeS/flZPSe5fLit3SXXzF3cZrEGWUWR2gAygAJ3AAuHVxVVCLbxvyRNyKdjav4c7+olq1LoinZrKhhs6Kcq48qwVWU0HNXwLE/NQfH3DTANvBuyGlnnR3soDQXPosOPJu8nnZ0+fQ8kFMfKqNg8unD151esBghomwVqGmUaPpWWITYnNzcNklK28IzVxr7dqnc+CMRdQA0w11KAwpHlwLs8DdW6PJ24b12dbSBl1I5Vj32vV/CGmv4GD+IKKsvc6T4r+NA+5dI1Mk9V8qXskxz08AOhSeDVIIfY5odcPvKlYwyy9a8pfl98yq9jKcNTlQgnbqtal+53bIV32EMWpjfXuZ8vIKezVdVLPVUMllfHdUdiQp4SCAZzDmMo1hJGY7B5t/haddBSKYlN0MW03DSNU0flo3A5GEfUEiHNwNZAHTanwTZQjL4yhVzo11Stg86pTN4qd1e1oSfD+r08kXVsSKruj2WuHbJLZfin08BoaX593cctAffZ5VnwfdHX9IQ12go1pjtbq29BpOMKPoasT+V3kzMe8TB62wzhiEd9m1DHopeI0txKFSmNGO9pq1MKtFNZ3PbPCvErilrRttsl5/KrwRtZR7r2UxWoFwkblfX8RxJ3tmMj19GrPvtcoNtm3hhHvmh6CrSRHYjpAn5K5ox6CDS5Zq46FLdxlp16BoWza0zJRpJz7ZsSdSpB9+au3Dlue/Jaxy/JSWc4u4/9Z0hvOy05y5jVuRsUqcP2mIc7YdUnguyQTWwHd1dHXvllR7hOzyp/IwVNyi6tNqYNm5S0zo=",
          t: "MTYxMzg1MDEyNy4zMTAwMDA=",
          m: "+K7uzr33gcr2xYL1HaqUyMDvs9E4AcyUhDPFoyA1jvY=",
          i1: "rhIPj3ZlY76zvAsKO3TYdg==",
          i2: "U7dgZY0EMEFuDhzVB+lu4w==",
          uh: "/vg0YoWth6t5UzuVRO519gE7bwQx2xZe1ioR4ueuS4c=",
          hh: "3htzUBXaqug0moZaVaRPWNYG1rRQQxdDndKhxQafs0M=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};

    })();
    //]]>
  </script>


<script type="text/javascript" src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1"></script></head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tbody><tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display: block;">

    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> javlibrary.com.</h1>

    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs">Please allow up to 5 seconds…</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting…</p>
  </div>
   <!-- <a href="http://bt50.org/nonalignedfrequent.php?pl=0">table</a> -->
  <form class="challenge-form" id="challenge-form" action="/en/?__cf_chl_jschl_tk__=f1d232f6df6061fe8cd9f9115d95628a647d6393-1613850127-0-ARCnDJKCfRgQHe2ZlADeEpocF0pnljswm4rOgraWwCGUCQ_V3t0rFAuwojcaJGVAscqC-5fg0U8h_9_Se1VcOvQDDq_ULcD-NgYMmETLCdK7CzbzuOi-1pXX6MzKkfBl3_ngwYFSq4xPXVcmDHXpILQE9wqvXbyA0K9j0KWrX_Z7AtrL_Nhn5ikxFo8BI1w1buUFz6agXcpVDQIlfkb3Z-833YHjy-bXoIsXx4Miv32gv9LW7lX9HRvnocEsfaOEI5QTAGXehbkZevDdl09HCz5NAEy96wPvbdMCl8wNa9IqqbOG7kcXjuOBiwHvBkXVngRt0NAPjdew8zHxJ0EdbNw" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="r" value="c1ce54e061a53cd4bde27467d81da484140ecc9a-1613850127-0-AZwjDs15TFOXIGobIaiXAQ8XjUyyf3kAxRg5kFg9JhT1GSUsgPprTaysgxPkfQXiAww7tMvdkSd/0DMFlIZ54XwYDZhpemThaxoEyO/hX9y4Flz24bg4jEh7r81/k8fqgoa4fp3nsryRxJ/aIcMd/kGBUatxOXfOwjCQmf7qGY/KBbIxV0Ky0PgE4j/3tJJmWsXJyMIgz5R9fQR1+GsVO7TV6jkva0NJ4tZN9oLNi4txJ6LjlzovALSVNU0y8nst+h5ER/pXTY4igWEMf3e4n9wk7JBx1eH8lJyzkGheCZdc+g2wBP+8dsDu+voaGVvqufjAklsGUXfSbfCSazGPCi6iWvj6nd0aMfd24N7B+hwlmBaY+lS+VUFjNRSSh98mVYIY0ue8E2ju+CxmSPYc62cHhYfwzY8O0+uic05gKoPBpWOeuB6kddpr647ascR9kSoA12zdAof5INRxBSzh9hATUuWCdOfYq6vlFJD0CqV4MmN8C6RLICMxcas/rSdmBIYGe249+2IJKihJqxYLKVTMPo3jAI7AAY4OAVZC/suCiBvTAOa2A0zU2HRrBBPNMbdTEWZdBTOvM4L2lfGoytwGYkvGgE3CROyLq5wy/aOnP0mOmnZqATUBFKM+MDSHpkB7XYoAm212fXiOEAxRtuJIxHwzBtB7Mrw0uGaPcuOA+xQDLpw3ZoyptLEZSvtPpQ==">
    <input type="hidden" value="e987ea0ddedb7c30d73258ba77e2356e" id="jschl-vc" name="jschl_vc">
    <!-- <input type="hidden" value="" id="jschl-vc" name="jschl_vc"/> -->
    <input type="hidden" name="pass" value="1613850131.31-GGUQ15d+xt">
    <input type="hidden" id="jschl-answer" name="jschl_answer">
  </form>

    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=624ab57fad50fa5c");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1";
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>



  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=624ab57fad50fa5c')"> </div>
</div>


          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br>
            <span class="ray_id">Ray ID: <code>624ab57fad50fa5c</code></span>
          </div>
      </td>

    </tr>
  </tbody></table><img src="/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=624ab57fad50fa5c" id="trk_jschal_js" alt="">


</body></html>
2021-02-20T19:42:08.539Z INFO REQ-1 Cloudflare detected
2021-02-20T19:42:08.546Z DEBUG REQ-1 Javascript challenge element '#trk_jschal_js' detected.
2021-02-20T19:42:08.547Z DEBUG REQ-1 Waiting for Cloudflare challenge...
2021-02-20T19:43:08.175Z ERROR REQ-1 Error: Maximum timeout reached. maxTimeout=60000 (ms)
    at C:\snapshot\FlareSolverr\node_modules\await-timeout\src\utils.js:20:38
    at Timeout.<anonymous> (C:\snapshot\FlareSolverr\node_modules\await-timeout\src\index.js:32:46)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
2021-02-20T19:43:08.177Z ERROR REQ-1 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)
```

### Screenshots

https://imgur.com/WmKxJDM

**Comment by ngosang** [comment]
Sorry for the late response. The site you were testing has disabled CloudFlare protection and I can't test it.
Anyway, I can't control the memory used by Chrome. The timeout is to kill Chrome after few seconds if this happens.
It's a shame I can't reproduce the issue. If you find the same issue in other page let me know.
