### ISSUE TITLE
utils.get_user_agent() / TypeError: '<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by illnesse** [FlareSolverr/FlareSolverr#911]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- Are you using Docker: no
- Are you using Captcha Solver: no
```

### Description

won't start, previous version was fine

### Logged Error Messages

```text
root@CT9552:/opt/flaresolverr/FlareSolverr/src# /opt/.venv/flaresolverr/bin/python3.11 /opt/flaresolverr/FlareSolverr/src/flaresolverr.py
2023-09-21 18:25:32 INFO     FlareSolverr 3.3.6
2023-09-21 18:25:32 INFO     Testing web browser installation...
2023-09-21 18:25:32 INFO     Platform: Linux-5.4.203-1-pve-x86_64-with-glibc2.31
2023-09-21 18:25:32 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-09-21 18:25:38 INFO     Chrome / Chromium major version: 90
2023-09-21 18:25:38 INFO     Launching web browser...
Traceback (most recent call last):
  File "/opt/flaresolverr/FlareSolverr/src/utils.py", line 296, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/opt/flaresolverr/FlareSolverr/src/utils.py", line 177, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/flaresolverr/FlareSolverr/src/undetected_chromedriver/__init__.py", line 252, in __init__
    self.patcher = Patcher(
                   ^^^^^^^^
  File "/opt/flaresolverr/FlareSolverr/src/undetected_chromedriver/patcher.py", line 65, in __init__
    self.is_old_chromedriver = version_main and version_main <= 114
                                                ^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flaresolverr/FlareSolverr/src/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/opt/flaresolverr/FlareSolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/flaresolverr/FlareSolverr/src/utils.py", line 300, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. '<=' not supported between instances of 'str' and 'int'
```

**Comment by ilike2burnthing** [comment]
Have you tried updating Chromium? v90 is fairly ancient.

**Comment by mews-se** [comment]
I noticed a similar problem, however updating Chromium on Ubuntu is not that straight forward...
