### ISSUE TITLE
[yggtorrent] (updating) Error connecting to FlareSolverr server

### ISSUE THREAD

**Issue by DaGreenX** [FlareSolverr/FlareSolverr#926]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.6
- Last working FlareSolverr version: 3.3.6
- Operating system: DSM 7
- Are you using Docker: [yes/no] YES
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] NO
- Are you using a Proxy: [yes/no] NO
- Are you using Captcha Solver: [yes/no] YES
- If using captcha solver, which one: Harvester
- URL to test this issue:
Jackett : v0.21.1051
```

### Description

Indexer down in radarr/sonarr
trying to edit and save in Jackett : ko

### Logged Error Messages

```text
FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (192.168.1.44:8191)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()

[v0.21.1056.0] FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (192.168.1.44:8191)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 593
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by Gauvino** [comment]
Same problem here with prowlarr

**Comment by ilike2burnthing** [comment]
@DaGreenX, can you access `http://192.168.1.44:8191` in browser on the same local network as Jackett?

@Gauvino not the same issue. See https://github.com/FlareSolverr/FlareSolverr/issues/880 instead.

**Comment by DaGreenX** [comment]
No I can't

**Comment by DaGreenX** [comment]
OK, so I forced the local port in the Docker configuration to 8191 and rebooted the NAS. I restarted the indexer tests in Jackett. everything's ok.

**Comment by c4x6d** [comment]
Same issue here on YGGTorrent tracker:

Jackett error: 

`ackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x5618e7959023 <unknown>\n#1 0x5618e76756ec <unknown>\n#2 0x5618e765e1ce <unknown>\n#3 0x5618e765ccdb <unknown>\n#4 0x5618e765d2fd <unknown>\n#5 0x5618e7671a53 <unknown>\n#6 0x5618e7672a32 <unknown>\n#7 0x5618e767ffaf <unknown>\n#8 0x5618e7683f31 <unknown>\n#9 0x5618e765d8c7 <unknown>\n#10 0x5618e767fc64 <unknown>\n#11 0x5618e76f59bb <unknown>\n#12 0x5618e76ddbb3 <unknown>\n#13 0x5618e76a89de <unknown>\n#14 0x5618e76a9d72 <unknown>\n#15 0x5618e7927fb6 <unknown>\n#16 0x5618e792b02d <unknown>\n#17 0x5618e792aac6 <unknown>\n#18 0x5618e792b4d5 <unknown>\n#19 0x5618e793190b <unknown>\n#20 0x5618e792b856 <unknown>\n#21 0x5618e7904b0d <unknown>\n#22 0x5618e7944265 <unknown>\n#23 0x5618e794445f <unknown>\n#24 0x5618e795204f <unknown>\n#25 0x7fd494f2cea7 start_thread\n

[v0.21.1073.0] Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x5618e7959023 <unknown>\n#1 0x5618e76756ec <unknown>\n#2 0x5618e765e1ce <unknown>\n#3 0x5618e765ccdb <unknown>\n#4 0x5618e765d2fd <unknown>\n#5 0x5618e7671a53 <unknown>\n#6 0x5618e7672a32 <unknown>\n#7 0x5618e767ffaf <unknown>\n#8 0x5618e7683f31 <unknown>\n#9 0x5618e765d8c7 <unknown>\n#10 0x5618e767fc64 <unknown>\n#11 0x5618e76f59bb <unknown>\n#12 0x5618e76ddbb3 <unknown>\n#13 0x5618e76a89de <unknown>\n#14 0x5618e76a9d72 <unknown>\n#15 0x5618e7927fb6 <unknown>\n#16 0x5618e792b02d <unknown>\n#17 0x5618e792aac6 <unknown>\n#18 0x5618e792b4d5 <unknown>\n#19 0x5618e793190b <unknown>\n#20 0x5618e792b856 <unknown>\n#21 0x5618e7904b0d <unknown>\n#22 0x5618e7944265 <unknown>\n#23 0x5618e794445f <unknown>\n#24 0x5618e795204f <unknown>\n#25 0x7fd494f2cea7 start_thread\n
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x5618e7959023 <unknown>\n#1 0x5618e76756ec <unknown>\n#2 0x5618e765e1ce <unknown>\n#3 0x5618e765ccdb <unknown>\n#4 0x5618e765d2fd <unknown>\n#5 0x5618e7671a53 <unknown>\n#6 0x5618e7672a32 <unknown>\n#7 0x5618e767ffaf <unknown>\n#8 0x5618e7683f31 <unknown>\n#9 0x5618e765d8c7 <unknown>\n#10 0x5618e767fc64 <unknown>\n#11 0x5618e76f59bb <unknown>\n#12 0x5618e76ddbb3 <unknown>\n#13 0x5618e76a89de <unknown>\n#14 0x5618e76a9d72 <unknown>\n#15 0x5618e7927fb6 <unknown>\n#16 0x5618e792b02d <unknown>\n#17 0x5618e792aac6 <unknown>\n#18 0x5618e792b4d5 <unknown>\n#19 0x5618e793190b <unknown>\n#20 0x5618e792b856 <unknown>\n#21 0x5618e7904b0d <unknown>\n#22 0x5618e7944265 <unknown>\n#23 0x5618e794445f <unknown>\n#24 0x5618e795204f <unknown>\n#25 0x7fd494f2cea7 start_thread\n
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
`

Flaresolverr container logs:

`2023-10-22 23:58:29 INFO     Incoming request => POST /v1 body: {'maxTimeout': 75000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=all'}
2023-10-22 23:58:29 INFO     Challenge detected. Title found: Just a moment...
2023-10-22 23:58:34 INFO     Challenge solved!
2023-10-22 23:58:34 ERROR    Error: Error solving the challenge. Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=116.0.5845.180)\nStacktrace:\n#0 0x5619e2785023 <unknown>\n#1 0x5619e24a16ec <unknown>\n#2 0x5619e248a1ce <unknown>\n#3 0x5619e2488cdb <unknown>\n#4 0x5619e24892fd <unknown>\n#5 0x5619e249da53 <unknown>\n#6 0x5619e249ea32 <unknown>\n#7 0x5619e24abfaf <unknown>\n#8 0x5619e24aff31 <unknown>\n#9 0x5619e24898c7 <unknown>\n#10 0x5619e24abc64 <unknown>\n#11 0x5619e25219bb <unknown>\n#12 0x5619e2509bb3 <unknown>\n#13 0x5619e24d49de <unknown>\n#14 0x5619e24d5d72 <unknown>\n#15 0x5619e2753fb6 <unknown>\n#16 0x5619e275702d <unknown>\n#17 0x5619e2756ac6 <unknown>\n#18 0x5619e27574d5 <unknown>\n#19 0x5619e275d90b <unknown>\n#20 0x5619e2757856 <unknown>\n#21 0x5619e2730b0d <unknown>\n#22 0x5619e2770265 <unknown>\n#23 0x5619e277045f <unknown>\n#24 0x5619e277e04f <unknown>\n#25 0x7fdf0a316ea7 start_thread\n
2023-10-22 23:58:34 INFO     Response in 5.256 s
2023-10-22 23:58:34 INFO     172.18.0.1 POST http://192.168.1.106:8191/v1 500 Internal Server Error`

Result of uname -a on host machine : 

`Linux <hostname> 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

(hostname being purposefully obfuscated)

Content of docker-compose :

`  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - CAPTCHA_SOLVER=harvester
      - HARVESTER_ENDPOINT=https://127.0.0.1:5000/token
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    restart: unless-stopped`

**Comment by SadE54** [comment]
Same here : 
2024-02-19 21:14:22.8|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://xxx.xxx.xxx.xxx:15211/v1: 500.InternalServerError (190 bytes)
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1708373601334, "endTimestamp": 1708373662891, "version": "3.3.14-hotfix2"}
2024-02-19 21:14:22.9|Warn|Cardigann|Unable to connect to indexer

[v1.13.3.4273] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://xxx.xxx.xxx.xxx:15211/v1]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 57
   at NzbDrone.Core.Indexers.IndexerHttpClient.PostResponse(HttpResponse response, IIndexerProxy selectedProxy) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 86
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 41
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 573
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 491
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1708373601334, "endTimestamp": 1708373662891, "version": "3.3.14-hotfix2"}
