### ISSUE TITLE
Something is wrong with the get_user_agent function

### ISSUE THREAD

**Issue by kyle-kw** [FlareSolverr/FlareSolverr#935]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

An error occurs when I get `driver.page_source`(src/flaresolverr_service.py: 399) in multiprocessing and multithreading. I examined the above code and found that `driver.quit()` appears in `utils.get_user_agent(driver)`(src/flaresolverr_service.py: 395). Strangely, it works fine when I don't use multiprocessing and multithreading. Is this a bug?

### Logged Error Messages

```text
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109e060d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6a5ecea2442ebe03ab466ea137e9c4ff/source
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109e06cd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6a5ecea2442ebe03ab466ea137e9c4ff/source
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109e06b20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6a5ecea2442ebe03ab466ea137e9c4ff/source
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/kewei/PycharmProjects/Learn/FlareSolverr/src/flaresolverr_service.py", line 241, in _resolve_challenge
    return func_timeout(timeout, _evil_logic, (req, driver, method))
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/Users/kewei/PycharmProjects/Learn/FlareSolverr/src/flaresolverr_service.py", line 399, in _evil_logic
    challenge_res.response = driver.page_source
  File "/Users/kewei/PycharmProjects/Learn/FlareSolverr/src/undetected_chromedriver/__init__.py", line 824, in __getattribute__
    return super().__getattribute__(item)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 446, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)["value"]
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 343, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 291, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 312, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/Users/kewei/opt/anaconda3/envs/flare-env/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=60601): Max retries exceeded with url: /session/6a5ecea2442ebe03ab466ea137e9c4ff/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109e06ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by ilike2burnthing** [comment]
Resolved by https://github.com/FlareSolverr/FlareSolverr/pull/921?
