### ISSUE TITLE
Cannot start a Chrome session

### ISSUE THREAD

**Issue by toverux** [FlareSolverr/FlareSolverr#945]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.7
- Last working FlareSolverr version: 3.3.4
- Operating system: Ubuntu 23.10
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): unknown
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
```

### Description

So I tried updating my FlareSolverr installation today, and now it crashes at start with the following stack trace.
I tried downgrading to the previous working version but the same issue is occurring.

It might be because I upgraded Chrome alongside, now on 119.

I tried starting Chrome manually and it works.

### Logged Error Messages

```text
Nov 05 15:58:49 saphir systemd[1]: Started flaresolverr.service - FlareSolverr.
Nov 05 15:58:50 saphir flaresolverr[17513]: 2023-11-05 15:58:50 INFO     FlareSolverr 3.3.7
Nov 05 15:58:50 saphir flaresolverr[17513]: 2023-11-05 15:58:50 INFO     Testing web browser installation...
Nov 05 15:58:50 saphir flaresolverr[17513]: 2023-11-05 15:58:50 INFO     Platform: Linux-6.5.0-10-generic-x86_64-with-glibc2.38
Nov 05 15:58:50 saphir flaresolverr[17513]: 2023-11-05 15:58:50 INFO     Chrome / Chromium path: /usr/bin/google-chrome-stable
Nov 05 15:58:50 saphir flaresolverr[17513]: 2023-11-05 15:58:50 INFO     Chrome / Chromium major version: 119
Nov 05 15:58:50 saphir flaresolverr[17513]: 2023-11-05 15:58:50 INFO     Launching web browser...
Nov 05 15:58:52 saphir flaresolverr[17513]: Traceback (most recent call last):
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/utils.py", line 296, in get_user_agent
Nov 05 15:58:52 saphir flaresolverr[17513]:     driver = get_webdriver()
Nov 05 15:58:52 saphir flaresolverr[17513]:              ^^^^^^^^^^^^^^^
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/utils.py", line 177, in get_webdriver
Nov 05 15:58:52 saphir flaresolverr[17513]:     driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
Nov 05 15:58:52 saphir flaresolverr[17513]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/undetected_chromedriver/__init__.py", line 474, in __init__
Nov 05 15:58:52 saphir flaresolverr[17513]:     super(Chrome, self).__init__(
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
Nov 05 15:58:52 saphir flaresolverr[17513]:     super().__init__(
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
Nov 05 15:58:52 saphir flaresolverr[17513]:     super().__init__(
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
Nov 05 15:58:52 saphir flaresolverr[17513]:     self.start_session(capabilities)
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/undetected_chromedriver/__init__.py", line 732, in start_session
Nov 05 15:58:52 saphir flaresolverr[17513]:     super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
Nov 05 15:58:52 saphir flaresolverr[17513]:     response = self.execute(Command.NEW_SESSION, caps)["value"]
Nov 05 15:58:52 saphir flaresolverr[17513]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
Nov 05 15:58:52 saphir flaresolverr[17513]:     self.error_handler.check_response(response)
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
Nov 05 15:58:52 saphir flaresolverr[17513]:     raise exception_class(message, screen, stacktrace)
Nov 05 15:58:52 saphir flaresolverr[17513]: selenium.common.exceptions.SessionNotCreatedException: Message: session not created
Nov 05 15:58:52 saphir flaresolverr[17513]: from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
Nov 05 15:58:52 saphir flaresolverr[17513]:   (Session info: chrome=119.0.6045.105)
Nov 05 15:58:52 saphir flaresolverr[17513]: Stacktrace:
Nov 05 15:58:52 saphir flaresolverr[17513]: #0 0x55bfa455b4e3 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #1 0x55bfa428ac76 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #2 0x55bfa428ed50 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #3 0x55bfa429097e <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #4 0x55bfa4290a4c <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #5 0x55bfa42eff77 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #6 0x55bfa42ee47f <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #7 0x55bfa42e5de3 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #8 0x55bfa42bb2dd <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #9 0x55bfa42bc34e <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #10 0x55bfa451b3e4 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #11 0x55bfa451f3d7 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #12 0x55bfa4529b20 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #13 0x55bfa4520023 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #14 0x55bfa44ee1aa <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #15 0x55bfa45446b8 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #16 0x55bfa4544847 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #17 0x55bfa4554243 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #18 0x7f36e6497ada <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: During handling of the above exception, another exception occurred:
Nov 05 15:58:52 saphir flaresolverr[17513]: Traceback (most recent call last):
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/flaresolverr.py", line 105, in <module>
Nov 05 15:58:52 saphir flaresolverr[17513]:     flaresolverr_service.test_browser_installation()
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
Nov 05 15:58:52 saphir flaresolverr[17513]:     user_agent = utils.get_user_agent()
Nov 05 15:58:52 saphir flaresolverr[17513]:                  ^^^^^^^^^^^^^^^^^^^^^^
Nov 05 15:58:52 saphir flaresolverr[17513]:   File "/home/morgan/flaresolverr/src/utils.py", line 300, in get_user_agent
Nov 05 15:58:52 saphir flaresolverr[17513]:     raise Exception("Error getting browser User-Agent. " + str(e))
Nov 05 15:58:52 saphir flaresolverr[17513]: Exception: Error getting browser User-Agent. Message: session not created
Nov 05 15:58:52 saphir flaresolverr[17513]: from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
Nov 05 15:58:52 saphir flaresolverr[17513]:   (Session info: chrome=119.0.6045.105)
Nov 05 15:58:52 saphir flaresolverr[17513]: Stacktrace:
Nov 05 15:58:52 saphir flaresolverr[17513]: #0 0x55bfa455b4e3 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #1 0x55bfa428ac76 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #2 0x55bfa428ed50 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #3 0x55bfa429097e <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #4 0x55bfa4290a4c <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #5 0x55bfa42eff77 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #6 0x55bfa42ee47f <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #7 0x55bfa42e5de3 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #8 0x55bfa42bb2dd <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #9 0x55bfa42bc34e <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #10 0x55bfa451b3e4 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #11 0x55bfa451f3d7 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #12 0x55bfa4529b20 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #13 0x55bfa4520023 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #14 0x55bfa44ee1aa <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #15 0x55bfa45446b8 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #16 0x55bfa4544847 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #17 0x55bfa4554243 <unknown>
Nov 05 15:58:52 saphir flaresolverr[17513]: #18 0x7f36e6497ada <unknown>
```

**Comment by andtoliom** [comment]
Same error here, started since updated Chrome to 119, it was working well on Chrome 118 and FlareSolverr 3.3.6

**Comment by Brokeos** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/880#issuecomment-1793593576

**Comment by andtoliom** [comment]
> [#880 (comment)](https://github.com/FlareSolverr/FlareSolverr/issues/880#issuecomment-1793593576)

Is there any solution for who use Python build?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/928#issuecomment-1784000384

**Comment by toverux** [comment]
I'm sorry, I'm not able to make it work.
I use a venv-based solution and requirements.txt as per the current version on Git specifies `selenium==4.11.2`.
In any case my global Ubuntu package version is `4.11.2+dfsg-1`.

I'm not very familiar with Python so I might be missing something?

So both are inferior to the recommended 4.12.0... and I still get the error.

**Comment by NabiKAZ** [comment]
This problem happened to me too.
It was not a problem before, but recently it has become a problem. With Windows 10 and 11 and Chrome:
Version 119.0.6045.124 (Official Build) (64-bit)

```
C:\Nabi\FlareSolverr>python src\flaresolverr.py
2023-11-08 18:11:39 INFO     ReqId 11316 FlareSolverr 3.3.7
2023-11-08 18:11:39 DEBUG    ReqId 11316 Debug log enabled
2023-11-08 18:11:39 INFO     ReqId 11316 Testing web browser installation...
2023-11-08 18:11:39 INFO     ReqId 11316 Platform: Windows-10-10.0.22000-SP0
2023-11-08 18:11:39 INFO     ReqId 11316 Chrome / Chromium path: C:\Program Files\Google\Chrome\Application\chrome.exe
2023-11-08 18:11:39 INFO     ReqId 11316 Chrome / Chromium major version: 119
2023-11-08 18:11:39 INFO     ReqId 11316 Launching web browser...
2023-11-08 18:11:39 DEBUG    ReqId 11316 Launching web browser...
2023-11-08 18:13:04 DEBUG    ReqId 11316 Started executable: `C:\Users\Nabi\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe` in a child process with pid: 19268
Traceback (most recent call last):
  File "C:\Nabi\FlareSolverr\src\utils.py", line 300, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "C:\Nabi\FlareSolverr\src\utils.py", line 181, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Nabi\FlareSolverr\src\undetected_chromedriver\__init__.py", line 474, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Nabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Nabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Nabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Nabi\FlareSolverr\src\undetected_chromedriver\__init__.py", line 732, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Nabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.123)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x010FA813+48355]
        (No symbol) [0x0108C4B1]
        (No symbol) [0x00F95358]
        (No symbol) [0x00F985B5]
        (No symbol) [0x00F999E1]
        (No symbol) [0x00F99A80]
        (No symbol) [0x00FE1F1B]
        (No symbol) [0x00FE093C]
        (No symbol) [0x00FDA536]
        (No symbol) [0x00FB82DC]
        (No symbol) [0x00FB93DD]
        GetHandleVerifier [0x0135AABD+2539405]
        GetHandleVerifier [0x0139A78F+2800735]
        GetHandleVerifier [0x0139456C+2775612]
        GetHandleVerifier [0x011851E0+616112]
        (No symbol) [0x01095F8C]
        (No symbol) [0x01092328]
        (No symbol) [0x0109240B]
        (No symbol) [0x01084FF7]
        BaseThreadInitThunk [0x76E86839+25]
        RtlGetFullPathName_UEx [0x779B906F+1215]
        RtlGetFullPathName_UEx [0x779B903D+1165]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nabi\FlareSolverr\src\flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "C:\Nabi\FlareSolverr\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Nabi\FlareSolverr\src\utils.py", line 306, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: session not created
from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.123)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x010FA813+48355]
        (No symbol) [0x0108C4B1]
        (No symbol) [0x00F95358]
        (No symbol) [0x00F985B5]
        (No symbol) [0x00F999E1]
        (No symbol) [0x00F99A80]
        (No symbol) [0x00FE1F1B]
        (No symbol) [0x00FE093C]
        (No symbol) [0x00FDA536]
        (No symbol) [0x00FB82DC]
        (No symbol) [0x00FB93DD]
        GetHandleVerifier [0x0135AABD+2539405]
        GetHandleVerifier [0x0139A78F+2800735]
        GetHandleVerifier [0x0139456C+2775612]
        GetHandleVerifier [0x011851E0+616112]
        (No symbol) [0x01095F8C]
        (No symbol) [0x01092328]
        (No symbol) [0x0109240B]
        (No symbol) [0x01084FF7]
        BaseThreadInitThunk [0x76E86839+25]
        RtlGetFullPathName_UEx [0x779B906F+1215]
        RtlGetFullPathName_UEx [0x779B903D+1165]

Exception ignored in: <function Chrome.__del__ at 0x000002080F7C4D60>
Traceback (most recent call last):
  File "C:\Nabi\FlareSolverr\src\undetected_chromedriver\__init__.py", line 861, in __del__
  File "C:\Nabi\FlareSolverr\src\undetected_chromedriver\__init__.py", line 816, in quit
OSError: [WinError 6] The handle is invalid
```

**Comment by RileyXX** [comment]
```bash
2023-11-10 04:17:02 INFO     FlareSolverr 3.3.7
2023-11-10 04:17:02 INFO     Testing web browser installation...
2023-11-10 04:17:02 INFO     Platform: Windows-10-10.0.19045-SP0
2023-11-10 04:17:02 INFO     Chrome / Chromium path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
2023-11-10 04:17:02 INFO     Chrome / Chromium major version: 119
2023-11-10 04:17:02 INFO     Launching web browser...
Traceback (most recent call last):
  File "C:\Program Files\flaresolverr\FlareSolverr\src\utils.py", line 296, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\flaresolverr\FlareSolverr\src\utils.py", line 177, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\flaresolverr\FlareSolverr\src\undetected_chromedriver\__init__.py", line 474, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Program Files\flaresolverr\FlareSolverr\src\undetected_chromedriver\__init__.py", line 732, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Riley\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x007DA813+48355]
        (No symbol) [0x0076C4B1]
        (No symbol) [0x00675358]
        (No symbol) [0x006785B5]
        (No symbol) [0x006799E1]
        (No symbol) [0x00679A80]
        (No symbol) [0x006C1F1B]
        (No symbol) [0x006C093C]
        (No symbol) [0x006BA536]
        (No symbol) [0x006982DC]
        (No symbol) [0x006993DD]
        GetHandleVerifier [0x00A3AABD+2539405]
        GetHandleVerifier [0x00A7A78F+2800735]
        GetHandleVerifier [0x00A7456C+2775612]
        GetHandleVerifier [0x008651E0+616112]
        (No symbol) [0x00775F8C]
        (No symbol) [0x00772328]
        (No symbol) [0x0077240B]
        (No symbol) [0x00764FF7]
        BaseThreadInitThunk [0x760CFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x76FA7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x76FA7C3E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\flaresolverr\FlareSolverr\src\flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "C:\Program Files\flaresolverr\FlareSolverr\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\flaresolverr\FlareSolverr\src\utils.py", line 300, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: session not created
from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x007DA813+48355]
        (No symbol) [0x0076C4B1]
        (No symbol) [0x00675358]
        (No symbol) [0x006785B5]
        (No symbol) [0x006799E1]
        (No symbol) [0x00679A80]
        (No symbol) [0x006C1F1B]
        (No symbol) [0x006C093C]
        (No symbol) [0x006BA536]
        (No symbol) [0x006982DC]
        (No symbol) [0x006993DD]
        GetHandleVerifier [0x00A3AABD+2539405]
        GetHandleVerifier [0x00A7A78F+2800735]
        GetHandleVerifier [0x00A7456C+2775612]
        GetHandleVerifier [0x008651E0+616112]
        (No symbol) [0x00775F8C]
        (No symbol) [0x00772328]
        (No symbol) [0x0077240B]
        (No symbol) [0x00764FF7]
        BaseThreadInitThunk [0x760CFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x76FA7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x76FA7C3E+238]

Exception ignored in: <function Chrome.__del__ at 0x000002E8735ACF40>
Traceback (most recent call last):
  File "C:\Program Files\flaresolverr\FlareSolverr\src\undetected_chromedriver\__init__.py", line 861, in __del__
  File "C:\Program Files\flaresolverr\FlareSolverr\src\undetected_chromedriver\__init__.py", line 816, in quit
OSError: [WinError 6] The handle is invalid
```
See this portion of the error: 
```python
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)
```
There is an issue creating a new session with Chrome browser, specifically chrome version (119) - `119.0.6045.124`.

**Comment by ilike2burnthing** [comment]
[v3.3.8](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.8)
