### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by alexisgonnon** [FlareSolverr/FlareSolverr#959]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 0.21.1189
- Last working FlareSolverr version: 0.21.1189
- Operating system: Debian GNU/Linux 11 
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): {"msg": "FlareSolverr is ready!", "version": "3.3.2", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"}
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one: 
- URL to test this issue:
```

### Description

when I try to test yggtorent it doesn't work 

### Logged Error Messages

```text
FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

[v0.21.1189.0] FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 562
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 593
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

Try increasing the timeout to 100000.

If you still have issues, does this also affect the indexers for iDope, TorrentQQ, and Torrent[CORE]?

**Comment by alexisgonnon** [comment]
where is the parameter to change the time limit?

**Comment by ilike2burnthing** [comment]
In Jackett's settings.

**Comment by adri1m64** [comment]
Hello, I've the same problem, I have change to 120s of timeout.
The prompt of FlareSolverr said that: "Challenge detected. Selector found: #challenge-spinner"
And no more

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/959#issuecomment-1806919261

**Comment by martfta** [comment]
if we do a HEADLESS browser and we open another tab for the same site, it get everything completed... this is log after I have open another tab;

2023-11-11 18:05:04 DEBUG    ReqId 17392 Timeout waiting for selector
2023-11-11 18:05:04 DEBUG    ReqId 17392 Try to find the Cloudflare verify checkbox...
2023-11-11 18:05:04 DEBUG    ReqId 17392 Cloudflare verify checkbox not found on the page.
2023-11-11 18:05:04 DEBUG    ReqId 17392 Try to find the Cloudflare 'Verify you are human' button...
2023-11-11 18:05:04 DEBUG    ReqId 17392 The Cloudflare 'Verify you are human' button not found on the page.
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for title (attempt 4): Just a moment...
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for title (attempt 4): DDoS-Guard
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): #cf-challenge-running
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): .ray_id
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): .attack-box
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): #cf-please-wait
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): #challenge-spinner
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): #trk_jschal_js
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): td.info #js_info
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for selector (attempt 4): div.vc div.text-box h2
2023-11-11 18:05:07 DEBUG    ReqId 17392 Waiting for redirect
2023-11-11 18:05:08 DEBUG    ReqId 17392 Timeout waiting for redirect
2023-11-11 18:05:08 INFO     ReqId 17392 Challenge solved!
2023-11-11 18:05:08 DEBUG    ReqId 26692 A used instance of webdriver has been destroyed
2023-11-11 18:05:08 DEBUG    ReqId 26692 Response => POST /v1 body: {'status': 'ok', 'message':

**Comment by Akashi2020** [comment]
The problem would not be due to the chromium version?

**Comment by pokemaster974** [comment]
> if we do a HEADLESS browser and we open another tab for the same site, it get everything completed... this is log after I have open another tab;
> 
> 2023-11-11 18:05:04 DEBUG ReqId 17392 Timeout waiting for selector 2023-11-11 18:05:04 DEBUG ReqId 17392 Try to find the Cloudflare verify checkbox... 2023-11-11 18:05:04 DEBUG ReqId 17392 Cloudflare verify checkbox not found on the page. 2023-11-11 18:05:04 DEBUG ReqId 17392 Try to find the Cloudflare 'Verify you are human' button... 2023-11-11 18:05:04 DEBUG ReqId 17392 The Cloudflare 'Verify you are human' button not found on the page. 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for title (attempt 4): Just a moment... 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for title (attempt 4): DDoS-Guard 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): #cf-challenge-running 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): .ray_id 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): .attack-box 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): #cf-please-wait 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): #challenge-spinner 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): #trk_jschal_js 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): td.info #js_info 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for selector (attempt 4): div.vc div.text-box h2 2023-11-11 18:05:07 DEBUG ReqId 17392 Waiting for redirect 2023-11-11 18:05:08 DEBUG ReqId 17392 Timeout waiting for redirect 2023-11-11 18:05:08 INFO ReqId 17392 Challenge solved! 2023-11-11 18:05:08 DEBUG ReqId 26692 A used instance of webdriver has been destroyed 2023-11-11 18:05:08 DEBUG ReqId 26692 Response => POST /v1 body: {'status': 'ok', 'message':

Yes, it's because chromedriver is detected by Cloudflare.
We are many of ygg to fail the protection. See #951

**Comment by Fabbbou** [comment]
I had the same issue. I double the latency in Flaresolverr from Jacket gui `FlareSolverr Max Timeout (ms)`
From 55000 to 110000 and it fixed it.

**Comment by ilike2burnthing** [comment]
Try with [v3.3.8](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.8).

For those not using Docker, if the new version doesn't work, try running from source with the latest version of Chrome - https://github.com/FlareSolverr/FlareSolverr#from-source-code.

**Comment by alexisgonnon** [comment]
when I change the a value from 55,000 to 100,000 I get this error 

Exception in GetConfigurationForSetup (yggtorrent): System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 688
   at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies, Int32 maxRedirects) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 625
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1036
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 950

**Comment by ilike2burnthing** [comment]
Have you tried running from source?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/951
