### ISSUE TITLE
Exception: Error getting browser User-Agent. int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by rxrw** [FlareSolverr/FlareSolverr#962]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.8
- Last working FlareSolverr version: v3.3.7
- Operating system: ubuntu
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Linux-5.15.0-88-generic-x86_64-with-glibc2.31
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I'm running FlareSolverr on my k8s cluster as a container of prowlarr which may be not important.

Because there's an error on started after updated the image version from v3.3.7 to v3.3.8.

### Logged Error Messages

```text
> kubectl logs -f prowlarr-5b684dd575-f2pw7 -n media-center -c

flaresolverr
2023-11-13 06:04:29 INFO     FlareSolverr 3.3.8
2023-11-13 06:04:29 INFO     Testing web browser installation...
2023-11-13 06:04:29 INFO     Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
2023-11-13 06:04:29 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-11-13 06:04:29 INFO     Chrome / Chromium major version: 119
2023-11-13 06:04:29 INFO     Launching web browser...
Traceback (most recent call last):
  File "/app/utils.py", line 296, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 177, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 252, in __init__
    self.patcher = Patcher(
                   ^^^^^^^^
  File "/app/undetected_chromedriver/patcher.py", line 67, in __init__
    version_main_int = int(version_main)
                       ^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 302, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by ilike2burnthing** [comment]
Yea, revert to v3.3.7 for now. Working fine on Windows, but not on Docker - the change to patcher.py in https://github.com/FlareSolverr/FlareSolverr/commit/04858c22fd1b84d04b1af992dfdbb3a4f07c1dd0 is at fault.

**Comment by ilike2burnthing** [comment]
[v3.3.9](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.9)
