### ISSUE TITLE
Keep restarting 

### ISSUE THREAD

**Issue by hstorey219** [FlareSolverr/FlareSolverr#965]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]no
- Are you using a Proxy: [yes/no]no
- Are you using Captcha Solver: [yes/no]no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Keeps restarting on Docker for windows

### Logged Error Messages

```text
023-11-13 07:47:02   File "/app/utils.py", line 296, in get_user_agent
2023-11-13 07:47:02     driver = get_webdriver()
2023-11-13 07:47:02              ^^^^^^^^^^^^^^^
2023-11-13 07:47:02   File "/app/utils.py", line 177, in get_webdriver
2023-11-13 07:47:02     driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
2023-11-13 07:47:02              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-13 07:47:02   File "/app/undetected_chromedriver/__init__.py", line 252, in __init__
2023-11-13 07:47:02     self.patcher = Patcher(
2023-11-13 07:47:02                    ^^^^^^^^
2023-11-13 07:47:02   File "/app/undetected_chromedriver/patcher.py", line 67, in __init__
2023-11-13 07:47:02     version_main_int = int(version_main)
2023-11-13 07:47:02                        ^^^^^^^^^^^^^^^^^
2023-11-13 07:47:02 TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2023-11-13 07:47:02 
2023-11-13 07:47:02 During handling of the above exception, another exception occurred:
2023-11-13 07:47:02 
2023-11-13 07:47:02 Traceback (most recent call last):
2023-11-13 07:47:02   File "/app/flaresolverr.py", line 105, in <module>
2023-11-13 07:47:02     flaresolverr_service.test_browser_installation()
2023-11-13 07:47:02   File "/app/flaresolverr_service.py", line 72, in test_browser_installation
2023-11-13 07:47:02     user_agent = utils.get_user_agent()
2023-11-13 07:47:02                  ^^^^^^^^^^^^^^^^^^^^^^
2023-11-13 07:47:02   File "/app/utils.py", line 302, in get_user_agent
2023-11-13 07:47:02     raise Exception("Error getting browser User-Agent. " + str(e))
2023-11-13 07:47:02 Exception: Error getting browser User-Agent. int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2023-11-13 07:48:02 2023-11-13 12:48:02 INFO     FlareSolverr 3.3.8
2023-11-13 07:48:02 2023-11-13 12:48:02 INFO     Testing web browser installation...
2023-11-13 07:48:02 2023-11-13 12:48:02 INFO     Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
2023-11-13 07:48:02 2023-11-13 12:48:02 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-11-13 07:48:02 2023-11-13 12:48:02 INFO     Chrome / Chromium major version: 119
2023-11-13 07:48:02 2023-11-13 12:48:02 INFO     Launching web browser...
2023-11-13 07:48:03 Traceback (most recent call last):
2023-11-13 07:48:03   File "/app/utils.py", line 296, in get_user_agent
2023-11-13 07:48:03     driver = get_webdriver()
2023-11-13 07:48:03              ^^^^^^^^^^^^^^^
2023-11-13 07:48:03   File "/app/utils.py", line 177, in get_webdriver
2023-11-13 07:48:03     driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
2023-11-13 07:48:03              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-13 07:48:03   File "/app/undetected_chromedriver/__init__.py", line 252, in __init__
2023-11-13 07:48:03     self.patcher = Patcher(
2023-11-13 07:48:03                    ^^^^^^^^
2023-11-13 07:48:03   File "/app/undetected_chromedriver/patcher.py", line 67, in __init__
2023-11-13 07:48:03     version_main_int = int(version_main)
2023-11-13 07:48:03                        ^^^^^^^^^^^^^^^^^
2023-11-13 07:48:03 TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2023-11-13 07:48:03 
2023-11-13 07:48:03 During handling of the above exception, another exception occurred:
2023-11-13 07:48:03 
2023-11-13 07:48:03 Traceback (most recent call last):
2023-11-13 07:48:03   File "/app/flaresolverr.py", line 105, in <module>
2023-11-13 07:48:03     flaresolverr_service.test_browser_installation()
2023-11-13 07:48:03   File "/app/flaresolverr_service.py", line 72, in test_browser_installation
2023-11-13 07:48:03     user_agent = utils.get_user_agent()
2023-11-13 07:48:03                  ^^^^^^^^^^^^^^^^^^^^^^
2023-11-13 07:48:03   File "/app/utils.py", line 302, in get_user_agent
2023-11-13 07:48:03     raise Exception("Error getting browser User-Agent. " + str(e))
2023-11-13 07:48:03 Exception: Error getting browser User-Agent. int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by screamjojo** [comment]
Same issue
