### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by Jewem** [FlareSolverr/FlareSolverr#968]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.9
- Last working FlareSolverr version:
- Operating system: Debian 5.10.197-1 (2023-09-29) x86_64
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [yes/no] i don't know
- If using captcha solver, which one:
- URL to test this issue:  https://www3.yggtorrent.wtf/
```

### Description

Hello,
I'v juste install FlareSolverr on my server.
Jackett Version v0.21.1207

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid

[v0.21.1207.0] Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 558
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 339
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 357
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 733
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by Jewem** [comment]
![Capture d'écran 2023-11-13 224841](https://github.com/FlareSolverr/FlareSolverr/assets/150742202/aece9956-5c48-46a7-b30d-7fd8f7fae5b5)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

**Comment by Jewem** [comment]
Hello, thank you for the wiki.
-FlareSolverr is running on the same device and using the same IP. (seedbox on Debian, FlareSolverr on Docker in the same machine)

-I'have no proxy or VPN.

I have to check my Docker configuration for IPV6, how can i check it ?

**Comment by ilike2burnthing** [comment]
> I have to check my Docker configuration for IPV6, how can i check it ?

You don't need to check, just disable it, for both containers.

**Comment by ilike2burnthing** [comment]
> Could the Cloudflare authentication page be the issue? What do you think?

If you're using v3.3.10, then no. Follow the troubleshooting steps linked above.

**Comment by kyuuk** [comment]
i have the same issue, and it is actually not a problem with captcha solving
for the context i'm using [Jackett](https://github.com/Jackett/Jackett) Version v0.21.1212
here are the debug logs for FlareSolverr
```
2023-11-15 00:12:54 INFO     ReqId 139648868628224 Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=all'}
2023-11-15 00:12:54 DEBUG    ReqId 139648868628224 Launching web browser...
version_main cannot be converted to an integer
2023-11-15 00:12:54 DEBUG    ReqId 139648868628224 Started executable: `/app/chromedriver` in a child process with pid: 567
2023-11-15 00:12:55 DEBUG    ReqId 139648868628224 New instance of webdriver has been created to perform the request
2023-11-15 00:12:55 DEBUG    ReqId 139648860235520 Navigating to... https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=all
2023-11-15 00:12:56 INFO     ReqId 139648860235520 Challenge detected. Title found: Just a moment...
2023-11-15 00:12:56 DEBUG    ReqId 139648860235520 Waiting for title (attempt 1): Just a moment...
2023-11-15 00:12:57 DEBUG    ReqId 139648860235520 Timeout waiting for selector
2023-11-15 00:12:57 DEBUG    ReqId 139648860235520 Try to find the Cloudflare verify checkbox...
2023-11-15 00:12:57 DEBUG    ReqId 139648860235520 Cloudflare verify checkbox not found on the page.
2023-11-15 00:12:57 DEBUG    ReqId 139648860235520 Try to find the Cloudflare 'Verify you are human' button...
2023-11-15 00:12:57 DEBUG    ReqId 139648860235520 The Cloudflare 'Verify you are human' button not found on the page.
2023-11-15 00:12:59 DEBUG    ReqId 139648860235520 Waiting for title (attempt 2): Just a moment...
2023-11-15 00:13:00 DEBUG    ReqId 139648860235520 Timeout waiting for selector
2023-11-15 00:13:00 DEBUG    ReqId 139648860235520 Try to find the Cloudflare verify checkbox...
2023-11-15 00:13:01 DEBUG    ReqId 139648860235520 Cloudflare verify checkbox found and clicked!
2023-11-15 00:13:01 DEBUG    ReqId 139648860235520 Try to find the Cloudflare 'Verify you are human' button...
2023-11-15 00:13:01 DEBUG    ReqId 139648860235520 The Cloudflare 'Verify you are human' button not found on the page.
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for title (attempt 3): Just a moment...
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for title (attempt 3): DDoS-Guard
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): #cf-challenge-running
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): .ray_id
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): .attack-box
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): #cf-please-wait
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): #challenge-spinner
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): #trk_jschal_js
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): td.info #js_info
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for selector (attempt 3): div.vc div.text-box h2
2023-11-15 00:13:03 DEBUG    ReqId 139648860235520 Waiting for redirect
2023-11-15 00:13:04 DEBUG    ReqId 139648860235520 Timeout waiting for redirect
2023-11-15 00:13:04 INFO     ReqId 139648860235520 Challenge solved!
2023-11-15 00:13:04 DEBUG    ReqId 139648868628224 A used instance of webdriver has been destroyed
2023-11-15 00:13:04 DEBUG    ReqId 139648868628224 Response => POST /v1 body: {'status': 'ok', 'message': 'Challenge solved!', 'solution': {'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=all', 'status': 200, 'cookies': [{'domain': '.yggtorrent.wtf', 'expiry': 1700439182, 'httpOnly': False, 'name': 'v14_promo_details', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'XXXXXXXXXX='}, {'domain': '.yggtorrent.wtf', 'expiry': 1700014382, 'httpOnly': True, 'name': 'ygg_', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'XXXXXXXXXXXXXXXX'}, {'domain': '.yggtorrent.wtf', 'expiry': 1731543181, 'httpOnly': True, 'name': 'cf_clearance', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'XXXXXXXXXXXXXXXXXXXXXXXXXX'}, {'domain': 'www3.yggtorrent.wtf', 'expiry': 1700010776, 'httpOnly': False, 'name': 'cf_chl_2', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'XXXXXXX'}], 'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36', 'headers': {}, 'response': '<html>........</html>'}, 'startTimestamp': 1700007174649, 'endTimestamp': 1700007184549, 'version': '3.3.10'}
2023-11-15 00:13:04 INFO     ReqId 139648868628224 Response in 9.9 s
```

could it be more of a Jackett problem ?

**Comment by ilike2burnthing** [comment]
Again, follow the troubleshooting steps above.

**Comment by Jewem** [comment]
I'm trying to disable IPV6 for my Docker.
Do you know the command ?

**Comment by Jewem** [comment]
`debian@nsxxx:~$ sudo docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS          PORTS                                                 NAMES
   ghcr.io/flaresolverr/flaresolverr:latest   "/usr/bin/dumb-init …"   30 minutes ago   Up 30 minutes   0.0.0.0:8191->8191/tcp, :::8191->8191/tcp, 8192/tcp   flaresolverr
`

**Comment by Jewem** [comment]
I've just trying this but it doesn't work :

debian@nsxx:~$ sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6 = 1
debian@nsxx:~$ service docker restart

After restart, the docker ps result is the same : 

CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS         PORTS          NAMES
443d91   ghcr.io/flaresolverr/flaresolverr:latest   "/usr/bin/dumb-init …"   45 minutes ago   Up 6 minutes   0.0.0.0:8191->8191/tcp, :::8191->8191/tcp, 8192/tcp   flaresolverr

**Comment by Jewem** [comment]
debian@ns:~ sudo ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        **inet6 fe80::42:f3ff:fe02:b0cd**  prefixlen 64  scopeid 0x20<link>
        ether 02:42:f3:02:b0:cd  txqueuelen 0  (Ethernet)

**Comment by Jewem** [comment]
```
sysctl net.ipv6.conf.all.disable_ipv6=1
sysctl net.ipv6.conf.default.disable_ipv6=1
```

**Comment by Jewem** [comment]
it works !!!!!

**Comment by gagy2** [comment]
Hi guys, running into the issue trying to add ygg as well.. I'm using Mulvad as my VPN with transmission _OpenVPN in docker.... my issue is Mulvad requires IPV6 to work :( Any one have an idea if we can leave it enabled for my VPN to work but get flaresolverr not to use it maybe?

# ipv6 must be enabled for Mullvad to work
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"

**Comment by ilike2burnthing** [comment]
Disable it for the Jackett/Prowlarr and FlareSolverr containers, don't disable it for your Transmission container.

**Comment by gagy2** [comment]
Thanks might do the trick..
 I'm new to docker..
I did a docker compose including all containers: transmission, jackett, sonar and radarr and attached them all behind the transmission/Openvpn so all traffic is behind vpn. 

Will try if O can disable ipv6 for the 2 container and leaving it for openvpn.

If not I might have to exclude them from the vpn probably... 
thanks a lot
