### ISSUE TITLE
macOS requires Xvfb to run with root privileges

### ISSUE THREAD

**Issue by 101Dude** [FlareSolverr/FlareSolverr#982]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: before Xvfb
- Operating system: macOS
- Are you using Docker: No
- FlareSolverr User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
- Are you using a VPN: Yes
- Are you using a Proxy: Yes
- Are you using Captcha Solver: No
- If using captcha solver, which one: n/a
- URL to test this issue: n/a
```

### Description

macOS requires Xvfb to be run as root in order to create a directory in `/private/tmp/`. Flaresolverr fails when `xvfb` is called without root privileges. **Can this be done or do I gave to create this directory before running `flaresolverr.py`?**

`sudo  mkdir -m 1777 /tmp/.X11-unix` works to pre-create this required directory.

commands and results:
--
```
16:37:16.623 at iMacEth FlareSolverr on  master pip list
Package            Version
------------------ -----------
attrs              23.1.0
bottle             0.12.25
certifi            2023.7.22
charset-normalizer 3.3.2
func-timeout       4.3.5
h11                0.14.0
idna               3.4
outcome            1.3.0.post0
pefile             2023.2.7
pip                23.3.1
prometheus-client  0.17.1
PySocks            1.7.1
requests           2.31.0
selenium           4.11.2
setuptools         68.2.2
sniffio            1.3.0
sortedcontainers   2.4.0
trio               0.23.1
trio-websocket     0.11.1
urllib3            2.1.0
waitress           2.1.2
websockets         11.0.3
wsproto            1.2.0
xvfbwrapper        0.2.9


16:37:28.366 at iMacEth FlareSolverr on  master python src/flaresolverr.py                          
2023-11-19 16:37:47 INFO     FlareSolverr 3.3.10
2023-11-19 16:37:47 INFO     Testing web browser installation...
2023-11-19 16:37:47 INFO     Platform: macOS-14.1.1-x86_64-i386-64bit
2023-11-19 16:37:47 INFO     Chrome / Chromium path: /usr/local/bin/chromium
2023-11-19 16:37:47 INFO     Chrome / Chromium major version: 117
2023-11-19 16:37:47 INFO     Launching web browser...
Traceback (most recent call last):
  File "/Users/john/GitHub/FlareSolverr/src/utils.py", line 300, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/Users/john/GitHub/FlareSolverr/src/utils.py", line 163, in get_webdriver
    start_xvfb_display()
  File "/Users/john/GitHub/FlareSolverr/src/utils.py", line 317, in start_xvfb_display
    XVFB_DISPLAY.start()
  File "/Users/john/.pyenv/versions/flaresolverr-proj/lib/python3.12/site-packages/xvfbwrapper.py", line 79, in start
    raise RuntimeError('Xvfb did not start')
RuntimeError: Xvfb did not start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/GitHub/FlareSolverr/src/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/Users/john/GitHub/FlareSolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/john/GitHub/FlareSolverr/src/utils.py", line 306, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Xvfb did not start

16:37:47.572 at iMacEth FlareSolverr on  master sudo /opt/X11/bin/Xvfb 
Password:
^C%      

16:37:57.572 at iMacEth ~ cd /private/tmp/.X11-unix                        

16:38:08.953 at iMacEth /private/tmp/.X11-unix ls -aleod@
drwxrwxrwt  3 root  96 Nov 19 16:38 .   

16:38:21.115 at iMacEth /private/tmp/.X11-unix cd /Users/john/GitHub/FlareSolverr
                                                                                                                                                                              
16:38:28.485 at iMacEth FlareSolverr on  master python src/flaresolverr.py 
2023-11-19 16:38:32 INFO     FlareSolverr 3.3.10
2023-11-19 16:38:32 INFO     Testing web browser installation...
2023-11-19 16:38:32 INFO     Platform: macOS-14.1.1-x86_64-i386-64bit
2023-11-19 16:38:32 INFO     Chrome / Chromium path: /usr/local/bin/chromium
2023-11-19 16:38:32 INFO     Chrome / Chromium major version: 117
2023-11-19 16:38:32 INFO     Launching web browser...
2023-11-19 16:38:39 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2023-11-19 16:38:39 INFO     Test successful!
2023-11-19 16:38:39 INFO     Serving on http://0.0.0.0:8191
```

### Logged Error Messages

```text
included above
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/discussions/981

**Comment by 101Dude** [comment]
I suppose I am missing something simple, would you Please offer a suggestion on how to get around this. Thank you
