### ISSUE TITLE
Impossible Raspberry Pie : unknown error: cannot connect to chrome

### ISSUE THREAD

**Issue by Tpsw242** [FlareSolverr/FlareSolverr#986]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version: none
- Operating system: Linux, Raspberry pi 3
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no 
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I've tried to install FlareSolver on my raspbery via docker but I can't get it to work. I've tried everything but nothing works

### Logged Error Messages

```text
version_main cannot be converted to an integer
Traceback (most recent call last):
  File "/app/utils.py", line 300, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
```

**Comment by ilike2burnthing** [comment]
The `version_main` line has nothing to do with the issue. Provide the full log.

**Comment by Tpsw242** [comment]
Thansk you, 
This is all the log i can see

2023-11-28 19:08:31 INFO     ReqId 548467989824 FlareSolverr 3.3.10
2023-11-28 19:08:31 DEBUG    ReqId 548467989824 Debug log enabled
2023-11-28 19:08:31 INFO     ReqId 548467989824 Testing web browser installation...
2023-11-28 19:08:31 INFO     ReqId 548467989824 Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
2023-11-28 19:08:31 INFO     ReqId 548467989824 Chrome / Chromium path: /usr/bin/chromium
2023-11-28 19:08:39 INFO     ReqId 548467989824 Chrome / Chromium major version: 119
2023-11-28 19:08:39 INFO     ReqId 548467989824 Launching web browser...
2023-11-28 19:08:39 DEBUG    ReqId 548467989824 Launching web browser...
version_main cannot be converted to an integer
2023-11-28 19:08:41 DEBUG    ReqId 548467989824 Started executable: `/app/chromedriver` in a child process with pid: 31
Traceback (most recent call last):
  File "/app/utils.py", line 300, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 181, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 472, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/app/undetected_chromedriver/__init__.py", line 730, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:37807
from chrome not reachable
Stacktrace:
#0 0x00559063bb58 <unknown>
#1 0x005590345e60 <unknown>
#2 0x005590335eb4 <unknown>
#3 0x005590377f8c <unknown>
#4 0x005590371290 <unknown>
#5 0x0055903b47d0 <unknown>
#6 0x0055903b3f28 <unknown>
#7 0x00559037b728 <unknown>
#8 0x00559037c9d0 <unknown>
#9 0x00559061084c <unknown>
#10 0x005590613660 <unknown>
#11 0x00559061322c <unknown>
#12 0x005590603404 <unknown>
#13 0x005590613d6c <unknown>
#14 0x0055905eec24 <unknown>
#15 0x00559062c788 <unknown>
#16 0x00559062c98c <unknown>
#17 0x00559063b0bc <unknown>
#18 0x007faec7a648 start_thread
#19 0x007fae4b8fdc <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 306, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:37807
from chrome not reachable
Stacktrace:
#0 0x00559063bb58 <unknown>
#1 0x005590345e60 <unknown>
#2 0x005590335eb4 <unknown>
#3 0x005590377f8c <unknown>
#4 0x005590371290 <unknown>
#5 0x0055903b47d0 <unknown>
#6 0x0055903b3f28 <unknown>
#7 0x00559037b728 <unknown>
#8 0x00559037c9d0 <unknown>
#9 0x00559061084c <unknown>
#10 0x005590613660 <unknown>
#11 0x00559061322c <unknown>
#12 0x005590603404 <unknown>
#13 0x005590613d6c <unknown>
#14 0x0055905eec24 <unknown>
#15 0x00559062c788 <unknown>
#16 0x00559062c98c <unknown>
#17 0x00559063b0bc <unknown>
#18 0x007faec7a648 start_thread
#19 0x007fae4b8fdc <unknown>

2023-11-28 19:09:56 INFO     ReqId 548049100096 FlareSolverr 3.3.10
2023-11-28 19:09:56 DEBUG    ReqId 548049100096 Debug log enabled
2023-11-28 19:09:56 INFO     ReqId 548049100096 Testing web browser installation...
2023-11-28 19:09:56 INFO     ReqId 548049100096 Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
2023-11-28 19:09:56 INFO     ReqId 548049100096 Chrome / Chromium path: /usr/bin/chromium

**Comment by Tpsw242** [comment]
I’m on Rasoberry Pie 3 so I’ve 1gb of memory.
As far as I now I don’t have any limit on the container.

I’ve tried multiple version and found that the 3.3.7 is working. All the newer version doesn’t work.

**Comment by ilike2burnthing** [comment]
It could be a memory issue, but then I don't know why an earlier version would work.

Please provide the response for `uname -a` on the host device. I'll leave this open as needing help.

**Comment by Tpsw242** [comment]
`Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
`

**Comment by ilike2burnthing** [comment]
Add the ENV `BROWSER_TIMEOUT` with the value of `200000`, see if that helps. If not, does it at least take longer to crash?

**Comment by nusiloot** [comment]
seems got the same issue here on raspberry pi 2

uname -a:

	Linux Server2 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux

error:
	

docker logs flaresolverr_test

	2023-12-04 22:24:28 INFO     FlareSolverr 3.3.10
	2023-12-04 22:24:28 INFO     Testing web browser installation...
	2023-12-04 22:24:28 INFO     Platform: Linux-5.10.103-v7+-armv7l-with-glibc2.31
	2023-12-04 22:24:28 INFO     Chrome / Chromium path: /usr/bin/chromium
	2023-12-04 22:24:28 INFO     Chrome / Chromium major version: 119
	2023-12-04 22:24:28 INFO     Launching web browser...
	Traceback (most recent call last):
	  File "/app/utils.py", line 300, in get_user_agent
	    driver = get_webdriver()
	             ^^^^^^^^^^^^^^^
	  File "/app/utils.py", line 163, in get_webdriver
	    start_xvfb_display()
	  File "/app/utils.py", line 317, in start_xvfb_display
	    XVFB_DISPLAY.start()
	  File "/usr/local/lib/python3.11/site-packages/xvfbwrapper.py", line 73, in start
	    time.sleep(self.__class__.SLEEP_TIME_BEFORE_START)
	PermissionError: [Errno 1] Operation not permitted

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/app/flaresolverr.py", line 105, in <module>
	    flaresolverr_service.test_browser_installation()
	  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
	    user_agent = utils.get_user_agent()
	                 ^^^^^^^^^^^^^^^^^^^^^^
	  File "/app/utils.py", line 306, in get_user_agent
	    raise Exception("Error getting browser User-Agent. " + str(e))
	Exception: Error getting browser User-Agent. [Errno 1] Operation not permitted

**Comment by ilike2burnthing** [comment]
See if [v3.3.11](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.11) makes a difference.

**Comment by Tpsw242** [comment]
Thanks, but unfortunately it still doesn't work

The logs

````2023-12-11 21:43:43 INFO     ReqId 547702652224 FlareSolverr 3.3.10
2023-12-11 21:43:43 DEBUG    ReqId 547702652224 Debug log enabled
2023-12-11 21:43:43 INFO     ReqId 547702652224 Testing web browser installation...
2023-12-11 21:43:43 INFO     ReqId 547702652224 Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
2023-12-11 21:43:43 INFO     ReqId 547702652224 Chrome / Chromium path: /usr/bin/chromium
2023-12-11 21:44:13 INFO     ReqId 547702652224 Chrome / Chromium major version: 119
2023-12-11 21:44:13 INFO     ReqId 547702652224 Launching web browser...
2023-12-11 21:44:13 DEBUG    ReqId 547702652224 Launching web browser...
version_main cannot be converted to an integer
2023-12-11 21:44:19 DEBUG    ReqId 547702652224 Started executable: `/app/chromedriver` in a child process with pid: 32
Traceback (most recent call last):
  File "/app/utils.py", line 300, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 181, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/undetected_chromedriver/__init__.py", line 472, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/app/undetected_chromedriver/__init__.py", line 730, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:45097
from chrome not reachable
Stacktrace:
#0 0x0055879bbb58 <unknown>
#1 0x0055876c5e60 <unknown>
#2 0x0055876b5eb4 <unknown>
#3 0x0055876f7f8c <unknown>
#4 0x0055876f1290 <unknown>
#5 0x0055877347d0 <unknown>
#6 0x005587733f28 <unknown>
#7 0x0055876fb728 <unknown>
#8 0x0055876fc9d0 <unknown>
#9 0x00558799084c <unknown>
#10 0x005587993660 <unknown>
#11 0x00558799322c <unknown>
#12 0x005587983404 <unknown>
#13 0x005587993d6c <unknown>
#14 0x00558796ec24 <unknown>
#15 0x0055879ac788 <unknown>
#16 0x0055879ac98c <unknown>
#17 0x0055879bb0bc <unknown>
#18 0x007fbd139648 start_thread
#19 0x007fbc977fdc <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 306, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:45097
from chrome not reachable
Stacktrace:
#0 0x0055879bbb58 <unknown>
#1 0x0055876c5e60 <unknown>
#2 0x0055876b5eb4 <unknown>
#3 0x0055876f7f8c <unknown>
#4 0x0055876f1290 <unknown>
#5 0x0055877347d0 <unknown>
#6 0x005587733f28 <unknown>
#7 0x0055876fb728 <unknown>
#8 0x0055876fc9d0 <unknown>
#9 0x00558799084c <unknown>
#10 0x005587993660 <unknown>
#11 0x00558799322c <unknown>
#12 0x005587983404 <unknown>
#13 0x005587993d6c <unknown>
#14 0x00558796ec24 <unknown>
#15 0x0055879ac788 <unknown>
#16 0x0055879ac98c <unknown>
#17 0x0055879bb0bc <unknown>
#18 0x007fbd139648 start_thread
#19 0x007fbc977fdc <unknown>

**Comment by Tpsw242** [comment]
Small update, Flaresolverr seems to be working with the latest version. I tried to use it in jackett and it return me an error 

`[yggtorrent] (updating) Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException (125): Operation canceled   --- End of inner exception stack trace ---   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   --- End of inner exception stack trace ---   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)   --- End of inner exception`

The Logs from Flaresolverr 

```
2023-12-16 18:35:14 INFO     ReqId 547839216960 FlareSolverr 3.3.12
2023-12-16 18:35:14 DEBUG    ReqId 547839216960 Debug log enabled
2023-12-16 18:35:14 INFO     ReqId 547839216960 Testing web browser installation...
2023-12-16 18:35:14 INFO     ReqId 547839216960 Platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
2023-12-16 18:35:14 INFO     ReqId 547839216960 Chrome / Chromium path: /usr/bin/chromium
2023-12-16 18:35:22 INFO     ReqId 547839216960 Chrome / Chromium major version: 120
2023-12-16 18:35:22 INFO     ReqId 547839216960 Launching web browser...
2023-12-16 18:35:22 DEBUG    ReqId 547839216960 Launching web browser...
version_main cannot be converted to an integer
2023-12-16 18:35:25 DEBUG    ReqId 547839216960 Started executable: `/app/chromedriver` in a child process with pid: 31
2023-12-16 18:35:48 INFO     ReqId 547839216960 FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2023-12-16 18:35:48 INFO     ReqId 547839216960 Test successful!
2023-12-16 18:35:48 INFO     ReqId 547839216960 Serving on http://0.0.0.0:8191
2023-12-16 18:35:56 INFO     ReqId 547796140512 192.168.1.134 GET http://192.168.1.139:8191/ 200 OK
2023-12-16 18:36:10 INFO     ReqId 547787747808 192.168.1.134 GET http://192.168.1.139:8191/ 200 OK
2023-12-16 18:36:27 INFO     ReqId 547779355104 Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/'}
2023-12-16 18:36:27 DEBUG    ReqId 547779355104 Launching web browser...
version_main cannot be converted to an integer
2023-12-16 18:36:28 DEBUG    ReqId 547779355104 Started executable: `/app/chromedriver` in a child process with pid: 165
2023-12-16 18:36:58 DEBUG    ReqId 547779355104 New instance of webdriver has been created to perform the request
2023-12-16 18:36:58 DEBUG    ReqId 547762569696 Navigating to... https://www3.yggtorrent.qa/
2023-12-16 18:37:56 DEBUG    ReqId 547779355104 A used instance of webdriver has been destroyed
2023-12-16 18:37:56 ERROR    ReqId 547779355104 Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-12-16 18:37:56 DEBUG    ReqId 547779355104 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 55.0 seconds.', 'startTimestamp': 1702751787561, 'endTimestamp': 1702751876031, 'version': '3.3.12'}
2023-12-16 18:37:56 INFO     ReqId 547779355104 Response in 88.47 s
2023-12-16 18:37:56 INFO     ReqId 547779355104 172.18.0.1 POST http://192.168.1.139:8191/v1 500 Internal Server Error
2023-12-16 18:38:26 INFO     ReqId 547770962400 Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/'}
2023-12-16 18:38:26 DEBUG    ReqId 547770962400 Launching web browser...
version_main cannot be converted to an integer
2023-12-16 18:38:27 DEBUG    ReqId 547770962400 Started executable: `/app/chromedriver` in a child process with pid: 309
2023-12-16 18:38:53 DEBUG    ReqId 547770962400 New instance of webdriver has been created to perform the request
2023-12-16 18:38:53 DEBUG    ReqId 547754176992 Navigating to... https://www3.yggtorrent.qa/
2023-12-16 18:39:52 DEBUG    ReqId 547770962400 A used instance of webdriver has been destroyed
2023-12-16 18:39:52 ERROR    ReqId 547770962400 Error: Error solving the challenge. Timeout after 55.0 seconds.
2023-12-16 18:39:52 DEBUG    ReqId 547770962400 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 55.0 seconds.', 'startTimestamp': 1702751906977, 'endTimestamp': 1702751992043, 'version': '3.3.12'}
2023-12-16 18:39:52 INFO     ReqId 547770962400 Response in 85.066 s
2023-12-16 18:39:52 INFO     ReqId 547770962400 172.18.0.1 POST http://192.168.1.139:8191/v1 500 Internal Server Error

```

**Comment by ilike2burnthing** [comment]
Odd, that shouldn't have changed anything, but I'll take it!

Test with the public indexers `iDope`, `TorrentQQ`, and `Torrent[CORE]`.

If they work, and your system language isn't English, set the ENV `LANG` to an English language code as per the example - https://github.com/FlareSolverr/FlareSolverr#environment-variables.

If none work though, try increasing the timeout and follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting.
